### ISSUE TITLE
Bidirectional LSTM example cannot be trained

### ISSUE THREAD

**Issue by ygoncharov** [fchollet/keras#1020]
The error message:

Traceback (most recent call last):
  File "/Users/yaroslav/Projects/liqres/keras/examples/imdb_bidirectional_lstm.py", line 59, in <module>
    nb_epoch=4)
  File "build/bdist.macosx-10.6-x86_64/egg/keras/models.py", line 682, in fit
  File "build/bdist.macosx-10.6-x86_64/egg/keras/models.py", line 215, in _fit
  File "/Users/yaroslav/Projects/liqres/velq/lib/python2.7/site-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/Users/yaroslav/Projects/liqres/velq/lib/python2.7/site-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()

ValueError: Input dimension mis-match. (input[1].shape[1] = 128, input[2].shape[1] = 64)
Apply node that caused the error: Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 2.0}, Join.0, Elemwise{Composite{Cast{float64}(LT(i0, i1))}}[(0, 0)].0)
Inputs types: [TensorType(float64, (True, True)), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(1, 1), (32, 128), (32, 64)]
Inputs strides: [(8, 8), (1024, 8), (512, 8)]
Inputs values: [array([[ 2.]]), 'not shown', 'not shown']

**Comment by dbonadiman** [comment]
I created the example and just checked if it works. it works just fine for me. Here is the usual recommendation (update to the latest version of Keras/Theano). 

If it does work let me know if you performed some modification on the code (Dataset, or network parameters).

**Comment by ygoncharov** [comment]
Upgrading Theano to the latest version (pip install --upgrade git+git://github.com/Theano/Theano.git) fixed the issue. Thanks!

**Comment by dbonadiman** [comment]
@ygoncharov no problem it is because they frequently change they internals in the development version and we try to keep our codebase up to date with their most recent version.
