### ISSUE TITLE
GRU breaking on incompatible shapes

### ISSUE THREAD

**Issue by Tomtomgo** [fchollet/keras#1055]
I tried to do something similar to the [GRU image caption learning example](http://keras.io/examples/#architecture-for-learning-image-captions-with-a-convnet-and-a-gated-recurrent-unit) when I ran into an issue. To verify that it's not an issue in my code I've tried the same as in the example:

```python
from keras.models import Sequential
language_model = Sequential()
language_model.add(Embedding(10000, 256, input_length=16))
language_model.add(GRU(output_dim=128, return_sequences=True))
language_model.add(Dense(128))
```

When I run that I get the following error:

```bash
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    language_model.add(Dense(128))
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/containers.py", line 37, in add
    self.layers[-1].set_previous(self.layers[-2])
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/core.py", line 33, in set_previous
    str(self.input_ndim) + " but previous layer has output_shape " + str(layer.output_shape)
AssertionError: Incompatible shapes: layer expected input with ndim=2 but previous layer has output_shape (None, 16, 128)
```

Version info via [pipdeptree](https://pypi.python.org/pypi/pipdeptree/):

```bash
Keras==0.2.0
  - theano [installed: 0.7.0]
    - numpy [required: >=1.7.1, installed: 1.10.1]
    - scipy [required: >=0.11, installed: 0.16.1]
    - six [required: >=1.9.0, installed: 1.10.0]
  - pyyaml [installed: 3.11]
```

**Comment by fchollet** [comment]
Output of a RNN layer with `return_sequences=True` is 3D, input to a `Dense` layer must be 2D. All of this is covered in this docs.
