### ISSUE TITLE
imdb bidirectional example bug

### ISSUE THREAD

**Issue by nawarhalabi** [fchollet/keras#1107]
The imdb bidirectional example "imdb_bidirectional_lstm.py" is returning an error:

```
ValueError: Input dimension mis-match. (input[1].shape[1] = 128, input[2].shape[1] = 64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "imdb_bidirectional_lstm.py", line 80, in <module>
    nb_epoch=4)
  File "/home/nawarhalabi/deepnet/keras/keras/models.py", line 684, in fit
    shuffle=shuffle, metrics=metrics)
  File "/home/nawarhalabi/deepnet/keras/keras/models.py", line 216, in _fit
    outs = f(*ins_batch)
  File "/usr/local/lib/python3.2/dist-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python3.2/dist-packages/theano/gof/link.py", line 206, in raise_with_op
    raise exc_type(exc_value).with_traceback(exc_trace)
  File "/usr/local/lib/python3.2/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[1].shape[1] = 128, input[2].shape[1] = 64)
Apply node that caused the error: Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 2.0}, Join.0, Elemwise{Composite{Cast{float64}(LT(i0, i1))}}[(0, 0)].0)
Inputs types: [TensorType(float64, (True, True)), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(1, 1), (32, 128), (32, 64)]
Inputs strides: [(8, 8), (1024, 8), (512, 8)]
Inputs values: [array([[ 2.]]), 'not shown', 'not shown']
```

When I set the dropout layer probability to 0 it works (not sure if this is right though)

**Comment by NanditaDamaraju** [comment]
Same here. I removed the dropout layer entirely and merged the inputs into the dense layer. That seemed to work for me.

**Comment by mbotumbo** [comment]
I'm not working with the IMDB example, but I was seeing a similar error. Updating Theano addressed this particular issue for me. pip install --upgrade git+git://github.com/Theano/Theano.git

**Comment by jakebian** [comment]
Can confirm, got same issue, updating Theano fixed it.
