### ISSUE TITLE
"ImportError: cannot import name dnn" Using slurm to run Keras on gpu

### ISSUE THREAD

**Issue by mbchang** [fchollet/keras#1121]
I am using slurm to run a bidirectional lstm on a gpu. My code runs fine on the CPU but I get an import error when I run on the gpu. Any suggestions? Below is my command:

`srun -N 1 -c 1 -p gpu --gres=gpu:1 --mem=10000 python bidirectional_lstm.py`
Below is my output: 

```
Using Theano backend.
Using gpu device 0: GeForce GTX TITAN Black
Traceback (most recent call last):
  File "bidirectional_lstm.py", line 8, in <module>
    from keras.models import Graph
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/keras/backend/__init__.py", line 34, in <module>

  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 25, in <module>
ImportError: cannot import name dnn
srun: error: node019: task 0: Exited with exit code 1
```

**Comment by mittaluday** [comment]
Having the same problem

**Comment by mbchang** [comment]
It was able to fix it; I needed to install cudnn (http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html) and update theano.

**Comment by pgrinaway** [comment]
Has anyone been able to resolve this without installing `cuDNN`?
