### ISSUE TITLE
ZeroPadding2D bug with TensorFlow?

### ISSUE THREAD

**Issue by Zebreu** [fchollet/keras#1135]
Hello,

I'm getting that kind of error when I use ZeroPadding2D layers with TensorFlow (it works well when Theano is the backend). 

```
Traceback (most recent call last):
  File "vgg_net.py", line 1345, in <module>
    custom_convnet()
  File "vgg_net.py", line 1235, in custom_convnet
    model = build_custom3()
  File "vgg_net.py", line 1226, in build_custom3
    model.compile(loss='categorical_crossentropy',optimizer=optimizer)
  File "//anaconda/lib/python2.7/site-packages/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 686, in get_output
    X = self.get_input(train)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 107, in get_input
    return self.previous.get_output(train=train)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 686, in get_output
    X = self.get_input(train)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 107, in get_input
    return self.previous.get_output(train=train)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 686, in get_output
    X = self.get_input(train)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 107, in get_input
    return self.previous.get_output(train=train)
  File "//anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 597, in get_output
    return K.flatten(X)
  File "//anaconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 258, in flatten
    x = tf.reshape(x, [-1, np.prod(x.get_shape()[1:].as_list())])
  File "//anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2349, in prod
    out=out, keepdims=keepdims)
  File "//anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

**Comment by fchollet** [comment]
> K.flatten(X)
> 'NoneType'

It means the initial shape of your input is not defined. What's your code?

**Comment by Zebreu** [comment]
This model:
```
model = Sequential()
    model.add(ZeroPadding2D((1,1),input_shape=(3,224,224)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dense(512, activation='relu'))
    model.add(Dense(2, activation='softmax'))

    optimizer = keras.optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(loss='categorical_crossentropy',optimizer=optimizer)
```

**Comment by fchollet** [comment]
I'll look into it. A quick fix would be for you not to start with padding as first layer.

**Comment by Zebreu** [comment]
Yes, thanks. I changed the first conv layer to border_mode = 'same', which I think (in this case) should give something identical to the first zero-padding layer (unless I misunderstood something).

**Comment by duschendestroyer** [comment]
I get the exact same error with MaxPooling2D. It only happens with the tensorflow backend.
To reproduce take the mnist_cnn example and change nb_pool to something greater than 12.
The feature map is 24x24x32 and thus should accept pooling kernels up to 24x24.
So it looks like the reshape fails when the pooling reduces the feature map to 1x1x32.

**Comment by discomethod** [comment]
I encountered this same error message when compiling a similar model with the tensorflow backend.
```python
    model = Sequential()
    model.add(ZeroPadding2D((1,1),input_shape=(3,224,224)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(256, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(256, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(256, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(Flatten())
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(classes, activation='softmax'))
```
I tried adding in layers one by one. The error appears when the first ```model.add(Flatten())``` layer is added.
In the end, I got the model to compile by removing the first padding layer and moving the ```input_shape``` parameter to the ```Convolution2D``` layer.

**Comment by DelightRun** [comment]
+1, same problem.
It hasn't been fixed yet?

**Comment by atique81** [comment]
same here. waiting for a solution...

**Comment by mdda** [comment]
This appears to have been fixed by a combination of the commits : "Remove dummy inputs in layers" and "Fix variable-size shape inference in padding layer".  

After quite a lot of digging, I found the 'surplus placeholder initialisation' issue myself, and then checked the fix against GitHub...  Closing this issue would have saved me a lot of time.  

Current fix : use keras from git, rather than from PyPI.  (i.e. the TensorFlow VGG16 model loading works now).  Next issue : switching from theano to tensorflow gives different results (and the theano ones look more correct for the given images)...

**Comment by atique81** [comment]
Hi @mdda,
I have just installed keras from the git using "sudo pip install git+git://github.com/fchollet/keras.git. I have also set the backend as "tensorflow" in the keras.json file located at ~/.keras. But, when I try to load the vgg16 model with the pretrained weights as available [here](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3). While the same code runs in theano backend, it throws the following errors while tried with tensorflow backend. 

Could you please point me what exactly causing this error to occur?
-----------------------------------------------------------------------------------------
........
W tensorflow/core/kernels/constant_op.cc:38] Internal: Dst tensor is not initialized.
E tensorflow/core/common_runtime/executor.cc:275] Executor failed to create kernel. Internal: Dst tensor is not initialized.
	 [[Node: Assign_26/value = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [25088,4096] values: 1.9745843e-05 0.00035308721 -0.0018327669...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Traceback (most recent call last):
  File "imagenet_cnn_call_ipython.py", line 54, in <module>
    model = vgg_16_keras.load_VGG_16(model_weights_path)
  File "/home/atique/2hat/scripts/vgg_16_keras.py", line 53, in load_VGG_16
    model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 909, in load_weights
    self.layers[k].set_weights(weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 300, in set_weights
    K.set_value(p, w)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 381, in set_value
    tf.assign(x, np.asarray(value)).op.run(session=get_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1377, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3132, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 315, in run
    return self._run(None, fetches, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 511, in _run
    feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _do_run
    target_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 586, in _do_call
    e.code)
tensorflow.python.framework.errors.InternalError: Dst tensor is not initialized.
	 [[Node: Assign_26/value = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [25088,4096] values: 1.9745843e-05 0.00035308721 -0.0018327669...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Caused by op u'Assign_26/value', defined at:
  File "imagenet_cnn_call_ipython.py", line 54, in <module>
    model = vgg_16_keras.load_VGG_16(model_weights_path)
  File "/home/atique/2hat/scripts/vgg_16_keras.py", line 53, in load_VGG_16
    model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 909, in load_weights
    self.layers[k].set_weights(weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 300, in set_weights
    K.set_value(p, w)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 381, in set_value
    tf.assign(x, np.asarray(value)).op.run(session=get_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 40, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 411, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 529, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 178, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 165, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2040, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1087, in __init__
    self._traceback = _extract_stack()

**Comment by Cospel** [comment]
Get very similar error from tensorflow for vgg, when running on cpu it works but on gpu fails.

**Comment by gyan-garcia** [comment]
I get  "**name 'ZeroPadding2D' is not defined**" when running this model with TensorFlow-cpu backend on a Windows machine.

**Comment by Samuel-Ranjith** [comment]
+1 have the same issue

**Comment by ajeyaajeya** [comment]
I have the same problem with ZeroPadding2D
---------------------------------------------------------------------------
```
NameError                                 Traceback (most recent call last)
<ipython-input-38-2b22a1dcacc7> in <module>
----> 1 model.add(ZeroPadding2D((0, 2)))
      2 model.add(Convolution2D(256, 1, 3, border_mode='valid', activation="relu", name="conv1", init='glorot_uniform'))
      3 model.add(Dropout(dr))
      4 model.add(ZeroPadding2D((0, 2)))
      5 model.add(Convolution2D(80, 2, 3, border_mode="valid", activation="relu", name="conv2", init='glorot_uniform'))

NameError: name 'ZeroPadding2D' is not defined
```
