### ISSUE TITLE
babi_memnn.py Error

### ISSUE THREAD

**Issue by farizrahman4u** [fchollet/keras#1136]
When running babi_memnn.py, I  get  the following error:
```
Compiling...
C:\Python27\lib\site-packages\theano\scan_module\scan_perform_ext.py:133: Runtim
eWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
Train on 10000 samples, validate on 1000 samples
Epoch 1/70
Traceback (most recent call last):
  File "babi_memnn.py", line 202, in <module>
    validation_data=([inputs_test, queries_test, inputs_test], answers_test))
  File "build\bdist.win32\egg\keras\models.py", line 507, in fit
  File "build\bdist.win32\egg\keras\models.py", line 226, in _fit
  File "build\bdist.win32\egg\keras\backend\theano_backend.py", line 357, in __c
all__
  File "C:\Python27\lib\site-packages\theano\compile\function_module.py", line 6
06, in __call__
    storage_map=self.fn.storage_map)
  File "C:\Python27\lib\site-packages\theano\compile\function_module.py", line 5
95, in __call__
    outputs = self.fn()
  File "C:\Python27\lib\site-packages\theano\gof\op.py", line 768, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\Python27\lib\site-packages\theano\tensor\blas.py", line 1612, in perf
orm
    z[0] = numpy.asarray(numpy.dot(x, y))
ValueError: ('shapes (32,68) and (132,64) not aligned: 68 (dim 1) != 132 (dim 0)
', (32, 68), (132, 64))
Apply node that caused the error: Dot22(Alloc.0, <TensorType(float32, matrix)>)
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(32, 68), (132, 64)]
Inputs strides: [(272, 4), (256, 4)]
Inputs values: ['not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-tr
ace of when this node was created. This can be done with by setting the Theano f
lag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be
 disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storag
e map footprint of this apply node.
```

**Comment by fchollet** [comment]
Could you update the unit tests to get full coverage (and correctness) on the `dot`, `cos` merge modes, as well as Lambda and LambdaMerge layers (which have several untested methods)?

**Comment by farizrahman4u** [comment]
This error is not due to dot merge mode.

**Comment by farizrahman4u** [comment]
This error is not related to dot merge mode.
