### ISSUE TITLE
I'm building a Convolutional GRU, I need help to update to this backend

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#1183]
To build a convolutional RNN, we need to run convolutions inside a for loop. It was working in the hand coded Theano, but now I'm getting an error I couldn't figure out. Can anybody help? It crashes under both backends with different messages.

The code is here: https://github.com/EderSantana/seya/blob/master/seya/layers/conv_rnn.py
Unit test is here: https://github.com/EderSantana/seya/blob/master/tests/test_conv_rnn.py

Here is the error message under Theano backend:

```
======================================================================
ERROR: test_basic (__main__.TestConvGRU)
Just check that the ConvGRU layer can compile and run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_conv_rnn.py", line 25, in test_basic
    model.compile('sgd', 'mse')
  File "/home/eders/python/keras/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/home/eders/python/keras/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/home/eders/python/keras/keras/layers/recurrent.py", line 80, in get_output
    masking=masking)
  File "/home/eders/python/keras/keras/backend/theano_backend.py", line 431, in rnn
    go_backwards=go_backwards)
  File "/home/eders/python/Theano/theano/scan_module/scan.py", line 745, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/home/eders/python/keras/keras/backend/theano_backend.py", line 414, in _step
    output, new_states = step_function(input, states)
  File "/home/eders/python/seya/seya/sandbox/conv_rnn.py", line 96, in step
    z = self.inner_activation(xz_t + apply_layer(self.conv_z, h_tm1))
  File "/home/eders/python/seya/seya/utils.py", line 18, in apply_layer
    Y = layer.get_output(train=train)
  File "/home/eders/python/keras/keras/layers/convolutional.py", line 218, in get_output
    filter_shape=self.W_shape)
  File "/home/eders/python/keras/keras/backend/theano_backend.py", line 551, in conv2d
    border_mode=(pad_x, pad_y))
  File "/home/eders/python/Theano/theano/sandbox/cuda/dnn.py", line 1196, in dnn_conv
    out = gpu_alloc_empty(*out_shp)
  File "/home/eders/python/Theano/theano/gof/op.py", line 600, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/eders/python/Theano/theano/sandbox/cuda/basic_ops.py", line 3630, in make_node
    shape, output = self.validate_shape(shape)
  File "/home/eders/python/Theano/theano/sandbox/cuda/basic_ops.py", line 3621, in validate_shape
    const_shp = tensor.get_scalar_constant_value(s)
  File "/home/eders/python/Theano/theano/tensor/basic.py", line 660, in get_scalar_constant_value
    for i in v.owner.inputs]
  File "/home/eders/python/Theano/theano/tensor/basic.py", line 660, in get_scalar_constant_value
    for i in v.owner.inputs]
  File "/home/eders/python/Theano/theano/tensor/basic.py", line 660, in get_scalar_constant_value
    for i in v.owner.inputs]
  File "/home/eders/python/Theano/theano/tensor/basic.py", line 660, in get_scalar_constant_value
    for i in v.owner.inputs]
  File "/home/eders/python/Theano/theano/tensor/basic.py", line 772, in get_scalar_constant_value
    raise ValueError(msg)
ValueError: get_scalar_constant_value detected deterministic IndexError: x.shape[2] when x.ndim=2.x=Subtensor{int64}.0

----------------------------------------------------------------------
Ran 1 test in 3.011s
```

**Comment by fchollet** [comment]
What's the TensorFlow error message?

**Comment by EderSantana** [comment]
I fixed the Theano part, I just needed to reshape the hidden state to an image.

Here is the new TensorFlow error:
```
======================================================================
ERROR: test_basic (__main__.TestConvGRU)
Just check that the ConvGRU layer can compile and run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_conv_rnn.py", line 25, in test_basic
    model.compile('sgd', 'mse')
  File "/home/eders/python/keras/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/home/eders/python/keras/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/home/eders/python/keras/keras/layers/recurrent.py", line 80, in get_output
    masking=masking)
  File "/home/eders/python/keras/keras/backend/tensorflow_backend.py", line 378, in rnn
    input_list = tf.unpack(inputs)
  File "/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 238, in unpack
    raise ValueError("Cannot infer num from shape %s" % shape)
ValueError: Cannot infer num from shape TensorShape([Dimension(None), Dimension(None), Dimension(None)])

----------------------------------------------------------------------
Ran 1 test in 0.245s
```

There is a point where I reshape (-1, n_channels, dim, dim). Is this -1 the problem?

**Comment by fchollet** [comment]
Replace
```python
self.input = K.placeholder(ndim=3)
```

with
```python
self.input = K.placeholder(shape=explicit_input_shape)
```

And you'll be set.

**Comment by fchollet** [comment]
> There is a point where I reshape (-1, n_channels, dim, dim). Is this -1 the problem?

It might also be a (different) problem. I don't know. To be verified.

**Comment by EderSantana** [comment]
@fchollet I think you are in the right track here the message did improve. I'll search for that last dimension:

```
======================================================================
ERROR: test_basic (__main__.TestConvGRU)
Just check that the ConvGRU layer can compile and run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_conv_rnn.py", line 27, in test_basic
    model.compile('sgd', 'mse')
  File "/home/eders/python/keras/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/home/eders/python/keras/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/home/eders/python/keras/keras/layers/recurrent.py", line 80, in get_output
    masking=masking)
  File "/home/eders/python/keras/keras/backend/tensorflow_backend.py", line 378, in rnn
    input_list = tf.unpack(inputs)
  File "/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 238, in unpack
    raise ValueError("Cannot infer num from shape %s" % shape)
ValueError: Cannot infer num from shape TensorShape([Dimension(None), Dimension(5), Dimension(10)])

----------------------------------------------------------------------
Ran 1 test in 0.251s
```

I'm already defining batch size explicitly too...

**Comment by EderSantana** [comment]
nvm I found the problem, working under TensforFlow as well, tkx for the help :+1: 

One thing, all the layers with internal reshaping need to get a predefined batch size.
Do you know if TF devs are interested in dynamic dimension inference?

**Comment by fchollet** [comment]
> I'm already defining batch size explicitly too...

It looks like the batch size isn't defined. Are you sure about that? 

There are no operations in the Keras backend that introduce shape indeterminism, so if all variables / placeholder shapes are explicitly defined you'll never see 'None' is a shape downstream.

**Comment by EderSantana** [comment]
@fchollet I updated the working code

**Comment by fchollet** [comment]
Ok, cool if it's working now!

**Comment by EderSantana** [comment]
Do you find it worth PRing it here?

**Comment by fchollet** [comment]
What are the implications for the codebase and feature scope? What would be the relationship to a possible `Recurrent` container?

**Comment by EderSantana** [comment]
Conv RNNs hold the current record on image processing http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Liang_Recurrent_Convolutional_Neural_2015_CVPR_paper.pdf

They are basically distributed RNNs just like regular convolutions are distributed MLPs. I believe that will be important for Deep Learning in general. But I can maintain it over Seya while the field matures. I just wanted to ask if you thought it would be better suited here.

The reshaping and things like that happen inside the layer. Out side, everything are vectors like for a regular RNN. Recurrent container wouldn't need to handle them in a different way.

**Comment by kracwarlock** [comment]
@EderSantana I am getting the same error with tensorflow backend. What was the reason behind this and how did you fix this? Seems like reshaping with a `-1` breaks tensorflow shape inference.

**Comment by EderSantana** [comment]
yeah it does break everything if one of your dimensions is unknown. need to use batch_input_shape I think

**Comment by kracwarlock** [comment]
yeah I wanted to keep batch dimension unknown
keeping it fixed for now then
