### ISSUE TITLE
missing some files which caused two examples failed!

### ISSUE THREAD

**Issue by andyyuan78** [fchollet/keras#119]
ubgpu@ubgpu:~/github/keras/examples$ 
ubgpu@ubgpu:~/github/keras/examples$ python skipgram_word_embeddings.py 
Using gpu device 0: GeForce GTX 970
Fit tokenizer...
Traceback (most recent call last):
  File "skipgram_word_embeddings.py", line 93, in <module>
    tokenizer.fit_on_texts(text_generator())
  File "build/bdist.linux-x86_64/egg/keras/preprocessing/text.py", line 55, in fit_on_texts
  File "skipgram_word_embeddings.py", line 76, in text_generator
    f = open(path)
IOError: [Errno 2] No such file or directory: '/home/ubgpu/HNCommentsAll.1perline.json'
ubgpu@ubgpu:~/github/keras/examples$ 
ubgpu@ubgpu:~/github/keras/examples$ 

ubgpu@ubgpu:~/github/keras/examples$ python kaggle_otto_nn.py 
Using gpu device 0: GeForce GTX 970
Loading data...
Traceback (most recent call last):
  File "kaggle_otto_nn.py", line 78, in <module>
    X, labels = load_data('train.csv', train=True)
  File "kaggle_otto_nn.py", line 39, in load_data
    df = pd.read_csv(path)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 420, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 218, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 502, in __init__
    self._make_engine(self.engine)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 610, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/lib/python2.7/dist-packages/pandas/io/parsers.py", line 972, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "parser.pyx", line 330, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3200)
  File "parser.pyx", line 557, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:5559)
IOError: File train.csv does not exist
ubgpu@ubgpu:~/github/keras/examples$

**Comment by fchollet** [comment]
You will have to download that particular dataset yourself. We are not hosting the download as part of the Keras datasets because the file is quite large. 

The header comments on this particular examples have instructions on how to download the dataset.
