### ISSUE TITLE
'mode' in max_pool_2d() 

### ISSUE THREAD

**Issue by ivy94419** [fchollet/keras#1192]
Hi,I am getting such problem:

def cnn():
    data, label = load_data()
    print(data.shape[0], ' samples')

    label = np_utils.to_categorical(label, 10)

    model = Sequential()

    model.add(Convolution2D(4, 5, 5, border_mode='valid', input_shape=(1, 28, 28)))
    model.add(Activation('tanh'))

    model.add(Convolution2D(8, 3, 3, border_mode='valid'))
    model.add(Activation('tanh'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Convolution2D(16, 3, 3, border_mode='valid'))
    model.add(Activation('tanh'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Flatten())
    model.add(Dense(256))
    model.add(Activation('tanh'))

    model.add(Dense(10))
    model.add(Activation('softmax'))

    sgd = SGD(l2=0.0,lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

    model.compile(loss='categorical_crossentropy', optimizer=sgd, class_mode="categorical")

    model.fit(data, label, batch_size=100, nb_epoch=100, show_accuracy=True)

    json_string = model.to_json()

    json_file = open('/Users/chenyoake/Desktop/json_model','w')

    json_file.write(json_string)

    model.save_weights('/Users/chenyoake/Desktop/model_weight.h5')

--------------------------------------------------------------------------------------------------------------------------------
Using Theano backend.
42000  samples
Traceback (most recent call last):
  File "cnn.py", line 94, in <module>
    main()
  File "cnn.py", line 91, in main
    cnn()
  File "cnn.py", line 62, in cnn
    model.compile(loss='categorical_crossentropy', optimizer=sgd, class_mode="categorical")
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 681, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 681, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 591, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 323, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 212, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 327, in get_output
    dim_ordering=self.dim_ordering)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 594, in maxpool2d
    mode='average_exc_pad')
TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

How can I solve this problem? Thank you!

**Comment by rpinsler** [comment]
`max_pool_2d()` is a Theano function, which _does_ expect a keyword argument `mode`. Can you run:
```
from theano.tensor.signal.downsample import max_pool_2d
import theano.tensor as T
import numpy as np
X = T.matrix()
X_in = np.asarray(np.random.rand(10, 10), dtype="float32")
max_pool_2d(X, (2, 2), ignore_border=True, mode="average_exc_pad").eval({X: X_in})
```
without an error?

**Comment by fchollet** [comment]
Update Theano (see the FAQ, also CONTRIBUTING.md)

**Comment by dxiaosa** [comment]
do you solve the problem?
