### ISSUE TITLE
AttributeError: 'Dense' object has no attribute 'W'

### ISSUE THREAD

**Issue by m09** [fchollet/keras#1247]
Hello, while trying to run the code of [skip-thoughts](https://github.com/ryankiros/skip-thoughts), I ran into this error. [The script that uses keras](https://github.com/ryankiros/skip-thoughts/blob/master/eval_sick.py) defines the following (simple) model for logistic regression:

    lrmodel = Sequential()
    lrmodel.add(Dense(ninputs, nclass))
    lrmodel.add(Activation('softmax'))
    lrmodel.compile(loss='categorical_crossentropy', optimizer='adam')

The stack trace:
```
Traceback (most recent call last):
  File "./eval_sick.py", line 158, in <module>
    evaluate(model, evaltest=True)
  File "./eval_sick.py", line 45, in evaluate
    lrmodel = prepare_model(ninputs=trainF.shape[1])
  File "./eval_sick.py", line 78, in prepare_model
    lrmodel.compile(loss='categorical_crossentropy', optimizer='adam')
  File "/home/mougard/.virtualenvs/skip-thoughts/local/lib/python2.7/site-packages/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/home/mougard/.virtualenvs/skip-thoughts/local/lib/python2.7/site-packages/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/home/mougard/.virtualenvs/skip-thoughts/local/lib/python2.7/site-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/home/mougard/.virtualenvs/skip-thoughts/local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/home/mougard/.virtualenvs/skip-thoughts/local/lib/python2.7/site-packages/keras/layers/core.py", line 682, in get_output
    output = self.activation(K.dot(X, self.W) + self.b)
AttributeError: 'Dense' object has no attribute 'W'
```

`pip freeze`:
```
boto==2.38.0
bz2file==0.98
gensim==0.12.3
httpretty==0.8.6
Keras==0.3.0
nltk==3.1
numpy==1.10.1
PyYAML==3.11
requests==2.8.1
scikit-learn==0.17
scipy==0.16.1
six==1.10.0
sklearn==0.0
smart-open==1.3.0
Theano==0.7.0
wheel==0.24.0
```

Any idea what the problem is? Thanks for the awesome library :)

**Comment by fchollet** [comment]
Change this line: `lrmodel.add(Dense(ninputs, nclass))`
to: `lrmodel.add(Dense(nclass, input_dim=ninputs))`

And update Keras to its latest version (Theano as well). You're all set.
