### ISSUE TITLE
model.fit(shuffle=False) gives TypeError

### ISSUE THREAD

**Issue by jmmcd** [fchollet/keras#131]
```
Traceback (most recent call last):
  File "toy_mlp.py", line 24, in <module>
    model.fit(X, y, validation_split=0.5, shuffle=False, nb_epoch=50, verbose=2)
  File "build/bdist.macosx-10.5-x86_64/egg/keras/models.py", line 189, in fit
TypeError: object of type 'slice' has no len()
```

Fix is probably just change `slice()` to `range()` in `models.py` line 188.

**Comment by fchollet** [comment]
Good catch : ) This is fixed now.
