### ISSUE TITLE
Bug in /theano/sandbox/cuda/dnn.py

### ISSUE THREAD

**Issue by meank** [fchollet/keras#1315]
/usr/bin/python2.7 /home/dell/DLTest/cifar_test/Residul/cifar_residul_net.py
Using Theano backend.
Using gpu device 1: GeForce GTX TITAN X (CNMeM is disabled)
('X_train shape:', (50000, 3, 32, 32))
(50000, 'train samples')
(10000, 'test samples')
Traceback (most recent call last):
  File "/home/dell/DLTest/cifar_test/Residul/cifar_residul_net.py", line 87, in <module>
    model.compile(loss='categorical_crossentropy', optimizer=sgd)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 681, in get_output
    X = self.get_input(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 591, in get_output
    X = self.get_input(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/containers.py", line 216, in get_output
    return self.outputs[self.output_order[0]].get_output(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 389, in get_output
    s = self.layers[0].get_output(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 212, in get_output
    X = self.get_input(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 98, in get_output
    return self.get_input(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/containers.py", line 216, in get_output
    return self.outputs[self.output_order[0]].get_output(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/core.py", line 389, in get_output
    s = self.layers[0].get_output(train)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 215, in get_output
    dim_ordering=self.dim_ordering)
  File "/home/dell/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 543, in conv2d
    border_mode=(pad_x, pad_y))
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 1191, in dnn_conv
    conv_mode=conv_mode)(img.shape, kerns.shape)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 251, in **init**
    border_mode = tuple(map(int, border_mode))
TypeError: int() argument must be a string or a number, not 'TensorVariable'

I got a bug after i delete /usr/local/cuda/lib64/libcudnn\*  and /usr/local/cuda/include/cudnn.h

Then add the same files of cudnn7-5v3 into the same path

**Comment by meanmee** [comment]
I sovled it by re-installing keras

**Comment by solipsy** [comment]
I have the same problem after installing cuDNN 3 into CUDA7.5 directories.  If I rename usr/local/cuda/include/cudnn.h to some other name, it runs (CUDA works). 
I reinstalled Keras (v 0.3.0), but the problem persists. I know that CUDA is quirky to set up, so after copying the files I  tried this again: sudo ldconfig /usr/local/cuda-7.5/lib64, but no luck.

My theanorc file contains:
[global]
floatX = float32
device = gpu0
optimizer = fast_run
optimizer_including=cudnn

[nvcc]
fastmath = True

[cuda]
root = /usr/local/cuda-7.5

[lib]
cnmem = 0.9

I'd be grateful for any advice.
Thanks!

/usr/bin/python2.7 /home/virostatiq/PycharmProjects/imdb/net/cifar.py
Using Theano backend.
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is enabled)
X_train shape: (50000, 3, 32, 32)
50000 train samples
10000 test samples
Traceback (most recent call last):
  File "/home/virostatiq/PycharmProjects/imdb/net/cifar.py", line 70, in <module>
    model.compile(loss='categorical_crossentropy', optimizer=sgd)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 681, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 488, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 681, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 591, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 488, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 323, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 212, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 212, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 488, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 323, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 212, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 215, in get_output
    dim_ordering=self.dim_ordering)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 543, in conv2d
    border_mode=(pad_x, pad_y))
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 1192, in dnn_conv
    conv_mode=conv_mode, precision=precision)(img.shape,
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.py", line 260, in __init__
    border_mode = tuple(map(int, border_mode))
TypeError: int() argument must be a string or a number, not 'TensorVariable'

Process finished with exit code 1

**Comment by nouiz** [comment]
The way to fix this is to find in that line why border_mode isn't an int.

Updating Theano could help.

Otherwise, I would need a way to reproduce it, I got such report outside of
Keras about this, but I don't have a use case to investigate.

Also, check that this line in keras have pad_x and pad_y as an int. If not,
then the problem is in Keras as it should be an int.

File
"/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py",
line 543, in conv2d
border_mode=(pad_x, pad_y))

**Comment by nouiz** [comment]
I think this was fixed in keras. Can someone confirm and close this issue if so?

**Comment by solipsy** [comment]
Hi,

i updated Keras from master and the issue is indeed fixed. At least it worked for me. Thanks!

Marko

**Comment by tboquet** [comment]
@nouiz, @solipsy and @meank, yes it has been fixed and tested with CUDA 7.5 and cuDNN v3 and v4 (#1383, 13379da and #1414).
