### ISSUE TITLE
The 30 seconds to Keras introduction is broken

### ISSUE THREAD

**Issue by kallewoof** [fchollet/keras#1326]
Looks broken anyway, unless I've managed to install Keras incorrectly.

```python
>>> from keras.models import Sequential
Using Theano backend.
Using gpu device 0: Tesla K20c
>>> model = Sequential()
>>> from keras.layers.core import Dense, Activation
>>> model.add(Dense(output_dim=64, input_dim=100, init="glorot_uniform"))
>>> model.add(Activation("relu"))
>>> model.add(Dense(output_dim=10, init="glorot_uniform"))
>>> model.add(Activation("softmax"))
>>> model.compile(loss='categorical_crossentropy', optimizer='sgd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)
  File "/usr/lib/python2.7/site-packages/keras/layers/containers.py", line 73, in get_output
    return self.layers[-1].get_output(train)
  File "/usr/lib/python2.7/site-packages/keras/layers/core.py", line 512, in get_output
    X = self.get_input(train)
  File "/usr/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/lib/python2.7/site-packages/keras/layers/core.py", line 681, in get_output
    X = self.get_input(train)
  File "/usr/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/lib/python2.7/site-packages/keras/layers/core.py", line 513, in get_output
    return self.activation(X)
  File "/usr/lib/python2.7/site-packages/keras/activations.py", line 25, in relu
    return K.relu(x, alpha=alpha, max_value=max_value)
  File "/usr/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 458, in relu
    x = T.nnet.relu(x, alpha)
AttributeError: 'module' object has no attribute 'relu'
>>>
```

**Comment by fchollet** [comment]
We do our best to post clear installation instructions, answer common questions in a FAQ, etc. The info is out there.
