### ISSUE TITLE
imdb_bidirectional_lstm.py error

### ISSUE THREAD

**Issue by dadatawajue** [fchollet/keras#1380]
Hi, I'm trying to run： “imdb_bidirectional_lstm.py”， but I receive this error:

```
Using Theano backend.
Loading data...
20000 train sequences
5000 test sequences
Pad sequences (samples x time)
X_train shape: (20000L, 100L)
X_test shape: (5000L, 100L)
Build model...

Warning (from warnings module):
  File "C:\SciSoft\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\theano\scan_module\scan_perform_ext.py", line 133
    from scan_perform.scan_perform import *
RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
INFO (theano.gof.compilelock): Refreshing lock C:\Users\Michael\AppData\Local\Theano\compiledir_Windows-8-6.2.9200-AMD64_Family_16_Model_4_Stepping_3_AuthenticAMD-2.7.10-64\lock_dir\lock
Train...
Epoch 1/4

Traceback (most recent call last):
  File "C:\SciSoft\keras-0.3.0\examples\imdb_bidirectional_lstm.py", line 59, in <module>
    nb_epoch=4)
  File "build\bdist.win-amd64\egg\keras\models.py", line 692, in fit
    shuffle=shuffle, metrics=metrics)
  File "build\bdist.win-amd64\egg\keras\models.py", line 226, in _fit
    outs = f(ins_batch)
  File "build\bdist.win-amd64\egg\keras\backend\theano_backend.py", line 357, in __call__
    return self.function(*inputs)
  File "C:\SciSoft\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\theano\compile\function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "C:\SciSoft\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\theano\compile\function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[1].shape[1] = 128, input[2].shape[1] = 64)
Apply node that caused the error: Elemwise{mul,no_inplace}(TensorConstant{(1L, 1L) of 2.0}, Join.0, Elemwise{Composite{Cast{float32}(LT(i0, i1))}}.0)
Inputs types: [TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(1L, 1L), (32L, 128L), (32L, 64L)]
Inputs strides: [(4L, 4L), (512L, 4L), (256L, 4L)]
Inputs values: [array([[ 2.]], dtype=float32), 'not shown', 'not shown']
```

I'm using:
- Python 2.7.10
- Theano 0.7
- numpy 1.9.3
- scipy 0.16.1
- pyyaml 3.11

For keras I've tried to use the latest master branch as well as the 0.3.0 release, but both result in the same error. Any help would be much appreciated :)

**Comment by fchollet** [comment]
You need to update Theano to its latest version from the Github repo.

**Comment by dadatawajue** [comment]
Great, it worked, thanks a lot :)
