### ISSUE TITLE
error when running deep_dream.py

### ISSUE THREAD

**Issue by willard-yuan** [fchollet/keras#1464]
When I run the `deep_dream.py`, it throws the error:

```sh
python deep_dream.py ~/Pictures/Lenna.png results/dream
Using Theano backend.
Traceback (most recent call last):
  File "deep_dream.py", line 83, in <module>
    model.add(Convolution2D(64, 3, 3, activation='relu', name='conv1_1'))
  File "/Users/willard/anaconda/lib/python2.7/site-packages/keras/layers/convolutional.py", line 254, in __init__
    super(Convolution2D, self).__init__(**kwargs)
  File "/Users/willard/anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 41, in __init__
    assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' + kwarg
AssertionError: Keyword argument not understood: name
```
In `convolutional.py` in line [L192](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L192), there is indeed no argument of **name**. 

The version of Keras I use is 0.3.1, and my system is OS X.

Anyone has the problem?

**Comment by fchollet** [comment]
Update Keras. Names were introduced a couple weeks earlier.
