### ISSUE TITLE
Stacked Denoising Autoencoder theano.gradient.DisconnectedInputError

### ISSUE THREAD

**Issue by pyben** [fchollet/keras#1482]
Hi. I'm implementing an SDA, this is base on this [pull request](https://github.com/fchollet/keras/pull/371/files). I tweak it a little bit to become an SDA.
But I got this error when I fine tune the model.

```
Traceback (most recent call last):
  File "imdb_sda.py", line 66, in <module>
    model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
  File "/home/vagrant/.virtualenvs/spam/lib/python3.4/site-packages/keras/models.py", line 465, in compile
    train_loss)
  File "/home/vagrant/.virtualenvs/spam/lib/python3.4/site-packages/keras/optimizers.py", line 125, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/vagrant/.virtualenvs/spam/lib/python3.4/site-packages/keras/optimizers.py", line 47, in get_gradients
    grads = K.gradients(loss, params)
  File "/home/vagrant/.virtualenvs/spam/lib/python3.4/site-packages/keras/backend/theano_backend.py", line 398, in gradients
    return T.grad(loss, variables)
  File "/home/vagrant/.virtualenvs/spam/lib/python3.4/site-packages/theano/gradient.py", line 545, in grad
    handle_disconnected(elem)
  File "/home/vagrant/.virtualenvs/spam/lib/python3.4/site-packages/theano/gradient.py", line 532, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: <TensorType(float32, matrix)>
Backtrace when the node is created:
  File "/home/vagrant/.virtualenvs/spam/lib/python3.4/site-packages/keras/backend/theano_backend.py", line 34, in variable
    return theano.shared(value=value, name=name, strict=False)
```

As of now I got the latest version of Keras and Theano from the repository.
Here's the [code](https://gist.github.com/pyben/41d12f33c9a4717e3adf). Thanks.

**Comment by HristoBuyukliev** [comment]
Hey, I had the same exact issue. The thing is, you have copied 
`trained_encoders.append(ae.layers[0].encoder)`
but as the encoder is 2 layers it should be 
`trained_encoders.append((ae.layers[0].encoder.layers[1]))`

**Comment by benigls** [comment]
Thanks HristoBuyukliev the error is resolve.
How did you optimize your SDA?

**Comment by pyben** [comment]
Thanks HristoBuyukliev. The error is resolve.
How did you optimize your SDA?

**Comment by HristoBuyukliev** [comment]
Mostly the same way as you. Btw, close the issue.

**Comment by pyben** [comment]
If it's okay with you, can I get a copy of your code?
I just want to experiment.
