### ISSUE TITLE
[CUSTOM Layer Error] TypeError: 'TensorVariable' object is not callable

### ISSUE THREAD

**Issue by lireagan** [fchollet/keras#1485]
Hey guys! I want to implement a custom layer but got some error.

here is my codes:

``` python
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import division

import numpy as np

import marshal
import types
import sys
from theano import tensor as T
import keras.layers.core as core

class Dense2BinaryLLX(core.Layer):
    '''
        get 0-1 dense output.

    '''
    def __init__(self, **kwargs):
        super(Dense2BinaryLLX, self).__init__(**kwargs)

    @property

    def get_output(self, train=False):
        X = self.get_input(train)
    pdb.set_trace()
    return T.round(X)

    def get_config(self):
        config = {"name": self.__class__.__name__}
        base_config = super(Dense2BinaryLLX, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

And Then I want to use this layer in my model:

``` python
vgg_model.add(Flatten())
vgg_model.add(Dense(4096, activation='relu'))
vgg_model.add(Dropout(0.5))
vgg_model.add(Dense(4096, activation='relu'))
vgg_model.add(Dropout(0.5))
vgg_model.add(Dense(100, activation='sigmoid'))


######

# add Dense2BinaryLLX layer
vgg_model.add(Dense2BinaryLLX())

# finetune the classification layer
vgg_model.add(Dropout(0.5))
vgg_model.add(Dense(nb_classes, activation='softmax'))

vgg_model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
```

Then the error happend:
```
Traceback (most recent call last):
  File "weibo_img_cnn_vgg_emo_top100_finetune_lastlayer_binarydense_senti.py", line 115, in <module>
    vgg_model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 400, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 103, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 873, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 139, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 601, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 139, in get_input
TypeError: 'TensorVariable' object is not callable
```
Any body can help me? Thank you a lot for your attention!

**Comment by farizrahman4u** [comment]
Remove the `@property` on  top  of `get_output`. Its supposed to be a function.

**Comment by lireagan** [comment]
@farizrahman4u Thank you!
