### ISSUE TITLE
Using "external" functions in LambdaMerge

### ISSUE THREAD

**Issue by pminervini** [fchollet/keras#1487]
Hello everyone, the Lambda and LambdaMerge layers are really useful!
However, I was trying to modularize my functions a little bit, by storing them in a separate package, adding some arguments and so forth. This is where I started having this small issue.

I'm adding a snippet for reproducing it: the following is main.py

```python
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from keras.layers.core import LambdaMerge

import ns.b as b

encoder_a = Sequential()
encoder_a.add(Embedding(input_dim=2, output_dim=3, input_length=1))

encoder_b = Sequential()
encoder_b.add(Embedding(input_dim=2, output_dim=3, input_length=1))

def func(args):
    return b.combiner(args)

model = Sequential()
model.add(LambdaMerge(layers=[encoder_a, encoder_b], function=func))

model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
```

The LambdaMerge layer applies func() on the two input layers. func() is defined using a simple function stored in ns/b.py (on a side note: ns/__init__.py exists and is empty):

```python
def combiner(args):
    return args[0] + args[1]
```

Summing up:

```bash
$ find
./main.py
./ns
./ns/b.py
./ns/__init__.py
```

This is the error I am getting:

```bash
$ PYTHONPATH=. python3 -uB main.py 
Using Theano backend.
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 433, in compile
    self.y_train = self.get_output(train=True)
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/containers.py", line 128, in get_output
    return self.layers[-1].get_output(train)
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/core.py", line 1481, in get_output
    return func(inputs)
  File "main.py", line 14, in func
    return b.combiner(args)
NameError: name 'b' is not defined
```
What's the best way of dealing with such cases? If I simply move the code from ns/b.py to main.py everything works like a charm, but I was trying to avoid bloating my main.py.

Thank you guys in advance for your time and help!

**Comment by pminervini** [comment]
I've temporarily "solved" by removing all code related to marshalling in Lambda and LambdaMerge:

```python
from keras.layers.core import Layer

import sys


class Lambda(Layer):
    def __init__(self, function, output_shape=None, **kwargs):
        super(Lambda, self).__init__(**kwargs)
        py3 = sys.version_info[0] == 3
        self.function = function
        if output_shape is None:
            self._output_shape = None
        elif type(output_shape) in {tuple, list}:
            self._output_shape = tuple(output_shape)
        else:
            self._output_shape = output_shape
        super(Lambda, self).__init__()

    @property
    def output_shape(self):
        if self._output_shape is None:
            return self.input_shape
        elif type(self._output_shape) == tuple:
            return (self.input_shape[0], ) + self._output_shape
        else:
            output_shape_func = self._output_shape
            shape = output_shape_func(self.input_shape)
            if type(shape) not in {list, tuple}:
                raise Exception('output_shape function must return a tuple')
            return tuple(shape)

    def get_output(self, train=False):
        X = self.get_input(train)
        func = self.function
        return func(X)


class LambdaMerge(Lambda):
    def __init__(self, layers, function, output_shape=None):
        if len(layers) < 2:
            raise Exception('Please specify two or more input layers '
                            '(or containers) to merge.')
        self.layers = layers
        self.params = []
        self.regularizers = []
        self.constraints = []
        self.updates = []
        for l in self.layers:
            params, regs, consts, updates = l.get_params()
            self.regularizers += regs
            self.updates += updates
            # params and constraints have the same size
            for p, c in zip(params, consts):
                if p not in self.params:
                    self.params.append(p)
                    self.constraints.append(c)
        py3 = sys.version_info[0] == 3
        self.function = function
        if output_shape is None:
            self._output_shape = None
        elif type(output_shape) in {tuple, list}:
            self._output_shape = tuple(output_shape)
        else:
            self._output_shape = output_shape
        super(Lambda, self).__init__()

    @property
    def output_shape(self):
        input_shapes = [layer.output_shape for layer in self.layers]
        if self._output_shape is None:
            return input_shapes[0]
        elif type(self._output_shape) == tuple:
            return (input_shapes[0][0], ) + self._output_shape
        else:
            output_shape_func = self._output_shape
            shape = output_shape_func(input_shapes)
            if type(shape) not in {list, tuple}:
                raise Exception('output_shape function must return a tuple.')
            return tuple(shape)

    def get_params(self):
        return self.params, self.regularizers, self.constraints, self.updates

    def get_output(self, train=False):
        func = self.function
        inputs = [layer.get_output(train) for layer in self.layers]
        return func(inputs)

    def get_input(self, train=False):
        res = []
        for i in range(len(self.layers)):
            o = self.layers[i].get_input(train)
            if not type(o) == list:
                o = [o]
            for output in o:
                if output not in res:
                    res.append(output)
        return res

    @property
    def input(self):
        return self.get_input()

    def supports_masked_input(self):
        return False

    def get_output_mask(self, train=None):
        return None

    def get_weights(self):
        weights = []
        for l in self.layers:
            weights += l.get_weights()
        return weights

    def set_weights(self, weights):
        for i in range(len(self.layers)):
            nb_param = len(self.layers[i].params)
            self.layers[i].set_weights(weights[:nb_param])
            weights = weights[nb_param:]

    def get_config(self):
        config = {'name': self.__class__.__name__,
                  'layers': [l.get_config() for l in self.layers],
                  'function': self.function,
                  'output_shape': self._output_shape}
        base_config = super(LambdaMerge, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

**Comment by farizrahman4u** [comment]
Try this:
```
def func(args):
    return self.b.combiner(args)
```

```
lm=LambdaMerge(layers=[encoder_a, encoder_b], function=func)
setattr(lm,'b',b)
```

```
encoder_a = Sequential()
encoder_a.add(Embedding(input_dim=2, output_dim=3, input_length=1))

encoder_b = Sequential()
encoder_b.add(Embedding(input_dim=2, output_dim=3, input_length=1))

model = Sequential()
model.add(lm)

model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
```

**Comment by pminervini** [comment]
here you go - main.py:

```python
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from keras.layers.core import LambdaMerge

import ns.b as b

def func(args):
    return self.b.combiner(args)

encoder_a = Sequential()
encoder_a.add(Embedding(input_dim=2, output_dim=3, input_length=1))

encoder_b = Sequential()
encoder_b.add(Embedding(input_dim=2, output_dim=3, input_length=1))

lm = LambdaMerge(layers=[encoder_a, encoder_b], function=func)
setattr(lm, 'b', b)

model = Sequential()
model.add(lm)

model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
```

ns/b.py:

```python
def combiner(args):
    return args[0] + args[1]
```

running:

```bash
$ PYTHONPATH=. python3 -uB main.py 
Using Theano backend.
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 433, in compile
    self.y_train = self.get_output(train=True)
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/containers.py", line 128, in get_output
    return self.layers[-1].get_output(train)
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/core.py", line 1481, in get_output
    return func(inputs)
  File "main.py", line 8, in func
    return self.b.combiner(args)
NameError: name 'self' is not defined
```

**Comment by farizrahman4u** [comment]
Oops!. Then give this a try:

```
def func(args):
    import ns.b  as  b
    return b.combiner(args)
```

**Comment by pminervini** [comment]
The following seems to work like a charm, thank you :) I'm going to restore the original Lambda and LambdaMerge layers, and I'll let  you know if your solution raises any issues.

Thank you!

```python
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from keras.layers.core import LambdaMerge

def func(args):
    import ns.b as b
    return b.combiner(args)

encoder_a = Sequential()
encoder_a.add(Embedding(input_dim=2, output_dim=3, input_length=1))

encoder_b = Sequential()
encoder_b.add(Embedding(input_dim=2, output_dim=3, input_length=1))

lm = LambdaMerge(layers=[encoder_a, encoder_b], function=func)

model = Sequential()
model.add(lm)

model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
```

**Comment by pminervini** [comment]
What do you think it's the best way to pass some arguments to func() ?

**Comment by farizrahman4u** [comment]
I usually keep my `Lambda` layers simple, and write custom classes for more complex stuff. You can pass arguments in the form of a dictionary to a `LambdaMerge` layer. Suppose you need a `LambdaMerge` layer that does `y = a*x1 + b*x2` where `x1` and `x2` are the layers being merged and `a` , `b` are the values that you need to seed as arguments.

Arguments holder:
```python
class Args(Layer):
    def __init__(self, dic):
          self.dic = dic
          self._input_shape = (None,)
          super(Args, self).__init__()
     def get_output(self, train=False):
           return self.dic
```

Add values of `a`  and `b` to  dictionary.
```python
args = Args({'a':3, 'b':2})
```
Lambda function:

```python
def f(x):
      x1=x[0]
      x2=x[1]
      args=x[2] #retrieve back the  arguments
      a=args['a']
      b=args['b']
      y=a*x1 + b*x2
      return y
```
And dont' forget to merge the arguments with your layers:

```python
#
#
#
lm = LambdaMerge(layers=[encoder_a, encoder_b, args], function=f)
model = Sequential()
model.add(lm)
```

**Comment by pminervini** [comment]
The custom layer handling the parameters is a totally elegant solution.

However, how are you using it? I keep getting "Exception: Layer is not connectedand is not an input layer." Do you need a snippet for reproducing the issue ?

**Comment by farizrahman4u** [comment]
I have updated my code above. Try again.

**Comment by pminervini** [comment]
It works like a charm, thank you :)
