### ISSUE TITLE
Error when using validation_data for a Graph model

### ISSUE THREAD

**Issue by entron** [fchollet/keras#1497]
The fit function of my graph model is:

```
model.fit({'input': X_train, 'output': y_train},
          batch_size=batch_size,
          nb_epoch=nb_epoch,
         validation_data=(X_test, y_test))
```

I got an error

```
Traceback (most recent call last):
  File "imdb_cnn.py", line 79, in <module>
    validation_data=(X_test, y_test))
  File "/usr/local/lib/python3.4/site-packages/keras/models.py", line 1129, in fit
    y_val = [standardize_y(validation_data[name]) for name in self.output_order]
  File "/usr/local/lib/python3.4/site-packages/keras/models.py", line 1129, in <listcomp>
    y_val = [standardize_y(validation_data[name]) for name in self.output_order]
TypeError: tuple indices must be integers, not str
```

Could someone tell me where is the problem? 

By the way, I also noticed that `show_accuracy ` argument is not supported in Graph. Will it be added?

**Comment by entron** [comment]
It works now after I made this change:

```
model.fit({'input': X_train, 'output': y_train},
          batch_size=batch_size,
          nb_epoch=nb_epoch,
          validation_data={'input': X_test, 'output': y_test})
```

**Comment by anjishnu** [comment]
The documentation is outdated, maybe someone should submit a PR.
