### ISSUE TITLE
Issue when using Embedding layer with Tensorflow backend

### ISSUE THREAD

**Issue by jfsantos** [fchollet/keras#1509]
My model has an `Embedding` layer as its first layer, followed by a `Dropout` and `LSTM` layers, like this:

```
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=vocab_size))
model.add(Dropout(input_dropout))
model.add(LSTM(n_hidden, return_sequences=True))
<remainder of the model here, which includes a few more LSTM layers>
```

If I try to use it like this, I'll get a warning message from Keras telling me that I need to specify `batch_input_shape` when using Tensorflow. However, even if I specify `batch_input_shape` up to the first LSTM layer, I still get the same error message.

**Comment by fchollet** [comment]
What's the complete model?

**Comment by farizrahman4u** [comment]
There might be some  2D layer in between Your first and LSTM layers. Post the whole thing.

**Comment by jfsantos** [comment]
This is what it looks like:

```
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=vocab_size))
model.add(Dropout(input_dropout))
model.add(LSTM(n_hidden, return_sequences=True))

for layer in range(n_layers-1):
    model.add(Dropout(hidden_dropout))
    model.add(LSTM(n_hidden, return_sequences=True))

model.add(Dropout(hidden_dropout))
model.add(TimeDistributedDense(vocab_size))
model.add(Activation('softplus'))
```

No 2D things, only a TimeDistributedDense layer (which should work). By the way, the exact same model works with Theano.

**Comment by fchollet** [comment]
> However, even if I specify batch_input_shape up to the first LSTM layer, I still get the same error message.

It only makes sense to specify it in the very first layer.

> I'll get a warning message from Keras telling me that I need to specify batch_input_shape when using Tensorflow. 

This should only occur when using stateful RNNs. What's the exact error message?

**Comment by jfsantos** [comment]
The traceback is a bit long, but here it goes:

```
Traceback (most recent call last):
  File "train_keras.py", line 85, in <module>
    model.compile(loss='categorical_crossentropy', optimizer=opt)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/models.py", line 408, in compile
    self.y_train = self.get_output(train=True)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/containers.py", line 128, in get_output
    return self.layers[-1].get_output(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 658, in get_output
    X = self.get_input(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 159, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 1101, in get_output
    X = self.get_input(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 159, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 624, in get_output
    X = self.get_input(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 159, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/recurrent.py", line 127, in get_output
    X = self.get_input(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 159, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 624, in get_output
    X = self.get_input(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 159, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/recurrent.py", line 127, in get_output
    X = self.get_input(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 159, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 624, in get_output
    X = self.get_input(train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 159, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/home/jfsantos/tensorflow/lib/python3.4/site-packages/keras/layers/recurrent.py", line 135, in get_output
    'including the samples axis.')
Exception: When using TensorFlow, you should define explicitly the number of timesteps of your sequences. Make sure the first layer has a "batch_input_shape" argument including the samples axis.
```

**Comment by fchollet** [comment]
I see. The solution might not be obvious. Basically the error is that your input shape has "None" in the time axis. There are two things you could do:

- `input_length` argument
```python
model.add(Embedding(input_dim=vocab_size, output_dim=vocab_size, input_length=10))
```

- `input_shape` argument
```python
model.add(Embedding(input_dim=vocab_size, output_dim=vocab_size, input_shape=(10, 32)))
```

What error message would you have expected?

> By the way, the exact same model works with Theano.

Sure it does, this is specifically a TensorFlow limitations.

**Comment by jfsantos** [comment]
This is definitely the part of the error message which led me the wrong way: `Make sure the first layer has a "batch_input_shape" argument including the samples axis.`, since none of the solutions involve specifying the batch size. However, at least intuitively, passing `input_batch_shape` should have worked since it has all the needed information. Maybe fixing the error message is not the problem, and we should instead make sure that specifying the input with `batch_input_shape` always works.

**Comment by fchollet** [comment]
Both should be fixed.

So if you use `input_shape` it works, but if you use `batch_input_shape` it doesn't?

**Comment by jfsantos** [comment]
Exactly. I apologize for the poor quality of the first report :(

I only started adding `batch_input_shape` to other layers when adding it to
the `Embedding` layer did not work.

--
João Felipe Santos

**Comment by fchollet** [comment]
Wait a minute. This doesn't make sense.

I made a mistake in my previous reply. It does not make sense to pass an
`input_shape` or `batch_input_shape` to an Embedding layer. The correct
solution is to use the `input_length` argument.

Indeed, the batch input shape of an Embedding layer is always 2D and *does
not include the time dimension*! Since the time dimension is implicit in
the integer indices of the embedding.

I will update the error message to reflect this.

**Comment by jfsantos** [comment]
Great. With this and the recent work on getting masking to work with Tensorflow, I got my monophonic music generation models to work with Keras on both backends. I just need to adapt the generation code and also make a dataset converter/generator, so we can use MIDI as input instead of ABC.

**Comment by fchollet** [comment]
Sounds great!
