### ISSUE TITLE
Stuck in compiling examples/addition_rnn.py

### ISSUE THREAD

**Issue by sunil-at-gh** [fchollet/keras#1600]
examples/addition_rnn.py seems to get stuck in the compile phase, when using Theano backend, current dev version, and THEANO_FLAGS = 'mode=FAST_RUN,device=cpu,floatX=float32'. Changing the mode to FAST_COMPILE works.

Using CTL-C to interrupt gives following trace:

^CTraceback (most recent call last):
  File "examples/addition_rnn.py", line 149, in <module>
    model.compile(loss='categorical_crossentropy', optimizer='adam')
  File "KERAS_HOME/keras/models.py", line 480, in compile
    self._train = K.function(train_ins, [train_loss], updates=updates)
  File "KERAS_HOME/keras/backend/theano_backend.py", line 407, in function
    return Function(inputs, outputs, updates=updates)
  File "KERAS_HOME/keras/backend/theano_backend.py", line 399, in __init__
    allow_input_downcast=True, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/compile/pfunc.py", line 461, in pfunc
    output_keys=output_keys)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/compile/function_module.py", line 1771, in orig_function
    output_keys=output_keys).create(
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/compile/function_module.py", line 1451, in **init**
    optimizer_profile = optimizer(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/opt.py", line 101, in **call**
    return self.optimize(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/opt.py", line 2203, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/opt.py", line 1779, in process_node
    replacements = lopt.transform(node)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/opt.py", line 4696, in local_useless_elemwise_comparison
    T.extract_constant(node.inputs[0]) == 0 and \
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/basic.py", line 3349, in extract_constant
    x = get_scalar_constant_value(x, elemwise=elemwise)

.... the following is repeated many times ...

  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/basic.py", line 660, in get_scalar_constant_value
    for i in v.owner.inputs]
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/basic.py", line 660, in <listcomp>
    for i in v.owner.inputs]
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/basic.py", line 660, in get_scalar_constant_value
    for i in v.owner.inputs]
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/basic.py", line 660, in <listcomp>
    for i in v.owner.inputs]
.... repeated many times ...

**Comment by sunil-at-gh** [comment]
**Proposed fix:**

It seems that changing the definition of **K.repeat** to the following fixes the problem:

```
def repeat(x, n):
    '''Repeat a 2D tensor.

    If x has shape (samples, dim) and n=2,
    the output will have shape (samples, 2, dim).
    '''
    x3d = x.reshape([-1, 1, x.shape[1]])
    return T.tile(x3d, [1, n, 1])
```
