### ISSUE TITLE
error while reading weights in .h5 format in a graphical model

### ISSUE THREAD

**Issue by wadhwasahil** [fchollet/keras#1737]
The error which I get is show below: - 
` g = f['graph']
   KeyError: "Unable to open object (Object 'core' doesn't exist)"
`

**Comment by tboquet** [comment]
Could you please include a working code snippet so we can understand what you are trying to do? Tx!

**Comment by wadhwasahil** [comment]
I am changing the VGG network to graphical. Here is the link to the code.
[code](http://ideone.com/Xwclqpl)

**Comment by tboquet** [comment]
Not working, you could include it directly in your comment.  Please use only one issue, #1720 that @pasky pointed out is basically the same.

**Comment by wadhwasahil** [comment]
Please see the updated link above. And suggest changes.

**Comment by tboquet** [comment]
Do you have the full traceback of the error too?

**Comment by wadhwasahil** [comment]
Yes.
`
Using Theano backend.
/home/darkfantasy/Theano/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    model = VGG_16('/home/darkfantasy/Desktop/Sahil/Video Classification/vgg16_weights.h5')
  File "main.py", line 53, in VGG_16
    model.load_weights(weights_path)
  File "/home/darkfantasy/anaconda2/lib/python2.7/site-packages/keras/models.py", line 1331, in load_weights
    g = f['graph']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "/home/darkfantasy/anaconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 164, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/home/ilan/minonda/conda-bld/work/h5py/h5o.c:3551)
KeyError: "Unable to open object (Object 'graph' doesn't exist)"
`

**Comment by pasky** [comment]
How did you create the h5 file you are trying to open?

**Comment by wadhwasahil** [comment]
I downloaded it from here.
[https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3l)

**Comment by tboquet** [comment]
Ok sure did you try the solution I mentionned in #1728?

**Comment by tboquet** [comment]
By the way, if you see that a similar issue is already open, continue the discussion on it, I suggest you close this one and we continue on #1728, it will be easier for other users to follow.

**Comment by wadhwasahil** [comment]
Yes. The same error is displayed. Ok sure, Closing it,
