### ISSUE TITLE
Sequence to Sequence LSTM prediction

### ISSUE THREAD

**Issue by mininaNik** [fchollet/keras#1785]
I want to have sequence to sequence training. I have five sequences. I considered the length of the history 100 to predict 10 steps ahead for each input sequence. I transformed the data to following format:
As an input X I have array of n matrices, each with 100 rows and 5 columns (technically, X is a tensor with dimensions n x 100 x 5). The target y will be matrix n x10 x 5 - for each input X_i (matrix 100 x 5) I want one corresponding y (10 x 5). So my input data (X) is a numpy array n x 100 x 5 and output (y) is n x10 x 5. I solved this problem when I wanted to predict only one step ahead (when X is a numpy array n x 100 x 5 and output (y) is n x 5 ), here #1727. Now I want to predict more and I guess only changing the output structure and training the network again is enough? Am I right?
 My model is as follows:

```
in_out_neurons = 5
hidden_neurons = 20
n_nxt = 10
n_prev = 100
future_history = n_nxt*hidden_neurons
model = Sequential()  
model.add(LSTM(output_dim=future_history, return_sequences=True, forget_bias_init = 'one', input_shape=(n_prev,in_out_neurons)))
model.add(Dropout(0.2))    
model.add(LSTM(future_history, return_sequences=False, forget_bias_init = 'one'))
model.add(Dropout(0.2))
model.add(Dense(n_nxt*in_out_neurons))
model.add(Activation("linear"))
model.compile(loss="mse", optimizer="rmsprop")
model.fit(X_train, y_train, batch_size=100, nb_epoch=1)
```

I got the following error, can anybody help me to solve the problem:

```
 Traceback (most recent call last):
 File "/home/mina/Documents/research/five cores (LSTM) seq2seq changing structure 8/KerasLSTM.py", line 217, in <module>
main()
 File "/home/mina/Documents/research/five cores (LSTM) seq2seq changing structure 8/KerasLSTM.py", line 184, in main
model.fit(X_train, y_train, batch_size=100, nb_epoch=1)
 File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 581, in fit
shuffle=shuffle, metrics=metrics)
 File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 239, in _fit
outs = f(ins_batch)
 File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 365, in __call__
   return self.function(*inputs)
 File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 513, in __call__
allow_downcast=s.allow_downcast)
 File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 169, in filter
data.shape))
 TypeError: ('Bad input argument to theano function with name "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py:362"  
at index 1(0-based)', 'Wrong number of dimensions: expected 2, got 3 with shape (100, 5, 5).')
```

**Comment by tboquet** [comment]
You should return sequences in your decoder and use a `TimeDistributedDense` layer to keep the time dimension. Try with this:

```python
in_out_neurons = 5
hidden_neurons = 20
n_nxt = 10
n_prev = 100
future_history = n_nxt*hidden_neurons
model = Sequential()  
model.add(LSTM(output_dim=future_history, return_sequences=True, forget_bias_init = 'one', input_shape=(n_prev,in_out_neurons)))
model.add(Dropout(0.2))    
model.add(LSTM(future_history, return_sequences=True, forget_bias_init = 'one'))
model.add(Dropout(0.2))
model.add(TimeDistributedDense(n_nxt, in_out_neurons))
model.add(Activation("linear"))
model.compile(loss="mse", optimizer="rmsprop")
model.fit(X_train, y_train, batch_size=100, nb_epoch=1)
```

**Comment by mininaNik** [comment]
@tboquet , thank you. Now I get this error: 

    Traceback (most recent call last):
     File "/home/mina/Documents/research/five cores (LSTM) seq2seq changing structure 8/KerasLSTM.py", line 228, in <module>
    main()
      File "/home/mina/Documents/research/five cores (LSTM) seq2seq changing structure 8/KerasLSTM.py", line 190, in main
        model.add(TimeDistributedDense(n_nxt, in_out_neurons))
     File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 68, in add    
        self.layers[-1].set_previous(self.layers[-2])
      File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 89, in set_previous
        self.build()
      File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 1073, in build
        self.W = self.init((input_dim, self.output_dim))
    TypeError: 'int' object is not callable

**Comment by tboquet** [comment]
Sorry I forgot the parenthesis the input shape should be a tuple:
```python
model.add(TimeDistributedDense((n_nxt, in_out_neurons)))
```

**Comment by mininaNik** [comment]
@tboquet , thanks a lot for your fast response :) It seems that the problem is not only related to the parenthesis, I get the following error now:

    Traceback (most recent call last):
      File "/home/mina/Documents/research/five cores (LSTM) seq2seq changing structure 8/KerasLSTM.py", line 229, in <module>
    main()
      File "/home/mina/Documents/research/five cores (LSTM) seq2seq changing structure 8/KerasLSTM.py", line 191, in main
        model.add(TimeDistributedDense((n_nxt, in_out_neurons)))
      File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 68, in add
        self.layers[-1].set_previous(self.layers[-2])
      File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 89, in set_previous
        self.build()
      File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 1073, in build
    self.W = self.init((input_dim, self.output_dim))
      File "/usr/local/lib/python2.7/dist-packages/keras/initializations.py", line 39, in glorot_uniform
        s = np.sqrt(6. / (fan_in + fan_out))
    TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

**Comment by tboquet** [comment]
Sorry, I have the monday morning productivity curse! You should input an `int`:
```python
model.add(TimeDistributedDense(in_out_neurons))
```
But the `TimeDistributedDense` won't give you the right time dimension, giving you an output of (n, 100, 5).
I'm not sure at this point if you could use a `Flatten` and a `Reshape` layer to achieve what you want.

**Comment by mininaNik** [comment]
@tboquet Thank you

**Comment by LuKaa** [comment]
@mininaNik Do you have a working example of the code you have posted above?
