### ISSUE TITLE
Input dimension mis-match

### ISSUE THREAD

**Issue by lifeng1989** [fchollet/keras#1830]
when I run exampel/imdb_bidirectional_lstm.py i have this trouble:
ValueError: Input dimension mis-match. (input[1].shape[1] = 128, input[2].shape[1] = 64)
I find this is because the backward layer have influence on forward layer，but I don't kown how to fix it.
Can you help me ? Thanks.

Log is as follows:
Traceback (most recent call last):
  File "imdb_bidirectional_lstm.py", line 57, in <module>
    batch_size=batch_size,nb_epoch=4)
  File "/home/rank_intern/share/python/anaconda2/lib/python2.7/site-packages/keras/models.py", line 1127, in fit
    shuffle=shuffle, metrics=metrics)
  File "/home/rank_intern/share/python/anaconda2/lib/python2.7/site-packages/keras/models.py", line 239, in _fit
    outs = f(ins_batch)
  File "/home/rank_intern/share/python/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 365, in __call__
    return self.function(*inputs)
  File "/home/rank_intern/share/python/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 606, in **call**
    storage_map=self.fn.storage_map)
  File "/home/rank_intern/share/python/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 595, in **call**
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[1].shape[1] = 72, input[2].shape[1] = 64)
Apply node that caused the error: Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 2.0}, Join.0, Elemwise{Composite{Cast{float32}(LT(i0, i1))}}.0)
Inputs types: [TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(1, 1), (32, 72), (32, 64)]
Inputs strides: [(4, 4), (288, 4), (256, 4)]
Inputs values: [array([[ 2.]], dtype=float32), 'not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by dongfangyixi** [comment]
hi , maybe you could add 'concat_axis' in line: model.add_node(Dropout(0.5), ........) or use merge_mode='sum' instead of the defaulted 'concat'.
here is the document for reference:
add_node(layer, name, input=None, inputs=[], merge_mode='concat', concat_axis=-1, dot_axes=-1, create_output=False)

**Comment by lifeng1989** [comment]
@dongfangyixi  It's useful. Thanks
