### ISSUE TITLE
Layer shape not compatible with weight shape when evaluating.

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#1831]
Whenever I attempt to load my best model (using ModelCheckpoints), it returns an error.

```
Traceback (most recent call last):
  File "LCRN.py", line 181, in <module>
    train_model(model, data[train], labels[train])
  File "LCRN.py", line 110, in train_model
    model.load_weights("best_model.h5")
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 584, in load_weights
    self.layers[k].set_weights(weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 136, in set_weights
    raise Exception("Layer shape %s not compatible with weight shape %s." % (K.get_value(p).shape, w.shape))
Exception: Layer shape (4, 1, 16, 16) not compatible with weight shape (5, 1, 16, 16).
```

For some strange reason, it seems to assume testing is done over 5 samples. Any idea as to why?

**Comment by fchollet** [comment]
Hard to tell what is going on in this context. Can you share the code?

**Comment by KeironO** [comment]
Yeah, no problem.

```python
def create_lcrn(number_of_timesteps, height, width):
    print "Creating the LRCN:"
    model = Sequential()

    # Convolutional Layers
    model.add(TimeDistributedConvolution2D(8,4,4, border_mode="valid",
                            input_shape=(number_of_timesteps,1,height,width)))
    # For visualisation purposes
    convout1 = Activation('relu')
    model.add(convout1)
    model.add(TimeDistributedMaxPooling2D(pool_size=(4, 4)))
    model.add(Dropout(0.25))
    
    model.add(TimeDistributedFlatten())

    model.add(GRU(100, return_sequences=True))
    model.add(GRU(50, return_sequences=False))

    model.add(Dense(1))
    model.add(Activation("sigmoid"))

    o = RMSprop()
    model.compile(loss="mse", optimizer=o, class_mode="binary")
    print "\t Model Created!"
    return model, convout1


def calculate_class_weights(train_label):
    list = train_label.tolist()

    num_neg = list.count(0)
    num_pos = list.count(1)

    duplicate = num_pos / num_neg

    class_weights={0 : (num_neg * (duplicate)) , 1: num_pos }
    return class_weights

def train_model(model, train_data, train_label):
    class_weights = calculate_class_weights(train_label)
    history = History()
    best_model = ModelCheckpoint("best_model.h5", monitor="loss", save_best_only=True)
    early_stopper = EarlyStopping(monitor="val_loss", patience=100)

    model.fit(train_data, train_label,
              batch_size=16,
              nb_epoch=1000,
              verbose=1,
              shuffle=True,
              validation_split=0.1,
              class_weight=class_weights,
              callbacks=[best_model, early_stopper])

    model.load_weights("best_model.h5")


    return model

def evaluate_model(test_data):
    prediction_probabilities = model.predict_proba(test_data, verbose=0).tolist()
    predictions = model.predict_classes(test_data, verbose=0).tolist()

    return prediction_probabilities, predictions

if __name__ == "__main__":
    # Details for training
    number_of_folds = 10

    # Details for data
    number_of_timesteps, height, width = 53, 28, 28

    all_test_labels = []
    all_prediction_probabilities = []
    all_predictions = []
    
    data, labels = load_data(height, width, number_of_timesteps)
    number_of_samples = data.shape[0]
    print "\tVideo loaded in shape of:", data.shape
    print "\t\tNumber of samples:", number_of_samples, ", Number of timesteps:", number_of_timesteps
    stratified_k_fold = StratifiedKFold(labels, n_folds=number_of_folds, shuffle=True)
    model = None
    for i, (train, test) in enumerate(stratified_k_fold):
        model, convout1 = create_lcrn(number_of_timesteps, height, width)
        train_model(model, data[train], labels[train])
        prediction_probabilities, predictions = evaluate_model(data[test])
```

**Comment by KeironO** [comment]
I've still not been able to fix this.

**Comment by munichong** [comment]
@KeironO Have you fixed the problem? I have the same issue now.
