### ISSUE TITLE
Shape Mismatch Error when training Attention Model

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#1837]
I am running [this](https://gist.github.com/shyamupa/7eccbea7e8f576e39714) code which implements a simple attention based similarity model, where training is done by negative sampling. Here are the shapes of my inputs, (`X` and `y` are sequences and `z` is the desired score (1 for similar, 0 for not))
```
X_train shape: (210600, 110) y_train shape: (210600, 32) z_train shape: (210600,)
X_dev shape: (54756, 110) y_dev shape: (54756, 32) z_dev shape: (54756,)
X_test shape: (57213, 110) y_test shape: (57213, 32) z_test shape: (57213,)
```

I suspect that I am doing something wrong in `get_R` layer of the code.
**UPDATE**: I realized that `get_R` is wrong, but do not have a [clue](https://groups.google.com/forum/#!topic/keras-users/3t6KIxs3J7g) how to fix it. I have a tensor with shape `(BatchSize, SeqLen, dim)` and another with shape `(BatchSize, SeqLen)` and want to get a tensor of shape `(BatchSize, dim)`. How to do this with the primitive operations?

I can compile the model, but when I train I get the following error, does anyone know what am I doing wrong?

```
Train on 210600 samples, validate on 54756 samples
Epoch 1/10
Traceback (most recent call last):
  File "my_model.py", line 252, in <module>
    mode='auto')]
  File "/Users/Shyam/anaconda/lib/python2.7/site-packages/keras/models.py", line 1316, in fit
    shuffle=shuffle, metrics=metrics)
  File "/Users/Shyam/anaconda/lib/python2.7/site-packages/keras/models.py", line 314, in _fit
    outs = f(ins_batch)
  File "/Users/Shyam/anaconda/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 443, in __call__
    return self.function(*inputs)
  File "/Users/Shyam/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Users/Shyam/anaconda/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Users/Shyam/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Shape mismatch: x has 32 rows but z has 12100 rows
Apply node that caused the error: Gemm{inplace}(Dot22.0, TensorConstant{1.0}, Subtensor{::, int64}.0, <TensorType(float32, matrix)>, TensorConstant{1.0})
Toposort index: 697
Inputs types: [TensorType(float32, matrix), TensorType(float32, scalar), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, scalar)]
Inputs shapes: [(12100, 200), (), (32, 200), (200, 200), ()]
Inputs strides: [(800, 4), (), (113600, 4), (800, 4), ()]
Inputs values: ['not shown', array(1.0, dtype=float32), 'not shown', 'not shown', array(1.0, dtype=float32)]
Outputs clients: [[Elemwise{Add}[(0, 2)](InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0, Gemm{inplace}.0)]]
```

In case its useful, here is the output of `model.summary()`,

```
--------------------------------------------------------------------------------
Layer (name)                  Output Shape                  Param #
--------------------------------------------------------------------------------
Layer (inputx)                (None, 110)                   0
Layer (inputy)                (None, 32)                    0
Embedding (x_emb)             (None, 110, 256)              2560000
Embedding (y_emb)             (None, 32, 256)               2560000
LSTM (forward)                (None, 142, 100)              142800
LSTM (backward)               (None, 142, 100)              142800
Dropout (dropout)             (None, 142, 200)              0
Lambda (h_n)                  (None, 200)                   0
Lambda (Y)                    (None, 110, 200)              0
RepeatVector (H_n_cross_e)    (None, 110, 200)              0
TimeDistributedDense (WY)     (None, 110, 200)              40200
TimeDistributedDense (Whn)    (None, 110, 200)              40200
TimeDistributedDense (M)      (None, 110, 200)              80200
TimeDistributedDense (_alpha) (None, 110, 1)                201
Reshape (alpha)               (None, 110)                   0
Lambda (_r)                   (None, 200, 1)                0
Reshape (r)                   (None, 200)                   0
Dense (Wr)                    (None, 200)                   40200
Dense (Wh)                    (None, 200)                   40200
Dense (h_star)                (None, 200)                   40200
Dense (out)                   (None, 1)                     201
--------------------------------------------------------------------------------
Total params: 5687202
```

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by shyamupa** [comment]
So I solved the problem using `batched_tensordot` in Theano, like so,

```
def get_R(X):
    Y, alpha = X.values()  # Y should be (None,L,k) and alpha should be (None,L,1) and ans should be (None, k,1)
    tmp=K.permute_dimensions(Y,(0,)+(2,1))
    ans=K.T.batched_dot(tmp,alpha)
    return ans
```

**Comment by Imorton-zd** [comment]
Hi, @shyamupa, which research field are you engaged in? Would you shared  the code of the attention model with us? Many thanks!

**Comment by shyamupa** [comment]
@lmorton-zd I am working in natural language processing. I have released the code. Check-it out [here](https://github.com/shyamupa/snli-entailment)!

**Comment by Imorton-zd** [comment]
Thank you very much!
