### ISSUE TITLE
ImportError: cannot import name pool

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#1899]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "D:/zhangdong/ACL/Task2/D-LSTM.py", line 15, in <module>
    from keras.optimizers import SGD, RMSprop, Adagrad
  File "build\bdist.win-amd64\egg\keras\optimizers.py", line 2, in <module>
  File "build\bdist.win-amd64\egg\keras\backend\__init__.py", line 46, in <module>
  File "build\bdist.win-amd64\egg\keras\backend\theano_backend.py", line 4, in <module>
ImportError: cannot import name pool
```
I just plan to update keras, but generating this error. It's terrible! Would someone help me solve this problem? Many thanks.

**Comment by farizrahman4u** [comment]
Update theano, update keras.

**Comment by fchollet** [comment]
To post this message, you had to deleted the following template: 

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

**Comment by shriramnandakumar** [comment]
Same problem. Had to use BLSTM and tried updating Keras and Theano, but  didn't work!

**Comment by Imorton-zd** [comment]
@farizrahman4u Reset your compiler.

**Comment by zeleizhang** [comment]
check out your filename is multiprocessing.py,from multiprocessing import Pool will import your multiprocessing.py,so can not import name Pool.:)
