### ISSUE TITLE
The input shape of keras based on Tensorflow

### ISSUE THREAD

**Issue by gklee2014** [fchollet/keras#1933]
Now, I have a question about the 4D tensor on keras about Convolution2D Layers.
Keras doc says :"4D tensor with shape: (samples, channels, rows, cols) if dim_ordering='th' or 4D tensor with shape: (samples, rows, cols, channels) if dim_ordering='tf'."
I use 'tf',how about my input?when I use (samples, channels, rows, cols),it is ok, but when I use (samples, rows, cols, channels) as input,it has some problems.

**Comment by fchollet** [comment]
The `dim_ordering` argument refers to dimension ordering conventions in the data you are using. It is not related to your choice of backend.

If your data looks like `(batch, width, height, channels)`, then use `dim_ordering='tf'`. If it looks like `(batch, channels, width, height)`, then use `dim_ordering='th'`.

**Comment by gklee2014** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/wzu/ljcode/cas2_test/cnn_cas2.py", line 139, in <module>
    model = VGG_16('vgg16_weights.h5')
  File "/home/wzu/ljcode/cas2_test/cnn_cas2.py", line 122, in VGG_16
    model.add(Dense(256))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 68, in add
    self.layers[-1].set_previous(self.layers[-2])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 98, in set_previous
    assert self.input_ndim == len(layer.output_shape), ('Incompatible shapes: layer expected input with ndim=' +
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 835, in output_shape
    '(got ' + str(input_shape[1:]) + '. '
Exception: The shape of the input to "Flatten" is not fully defined (got (128, 7, 0). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.

A part of my code:
model = Sequential()
model.add(Convolution2D(16,3,3,border_mode='valid',init='glorot_uniform',dim_ordering='tf',input_shape=(10,226,226)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
