### ISSUE TITLE
error while using save_weights()

### ISSUE THREAD

**Issue by TrueWord** [fchollet/keras#201]
I ran into an error while using model.save_weights()
````
Traceback (most recent call last):
  File "cnn2.py", line 160, in <module>
    model.save_weights('model_weight.hdf5')
  File "/home/cy/.local/lib/python2.6/site-packages/keras/models.py", line 379, in save_weights
    g = f.create_group('layer_{}'.format(k))
ValueError: zero length field name in format
```
Could anyone help ?

Besides, the HDF5 libraries dependance is not automatically checked while installing. 

Thanks

**Comment by tdhd** [comment]
Could you please show us how you created the model?

**Comment by TrueWord** [comment]
The model is created by:
```python
model = Sequential()

model.add(Convolution2D(32, 3, 3, 3, border_mode='full')) 
model.add(Activation('relu'))
model.add(Convolution2D(32, 32, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(poolsize=(2, 2)))
model.add(Dropout(0.25))

model.add(Convolution2D(64, 32, 3, 3, border_mode='full')) 
model.add(Activation('relu'))
model.add(Convolution2D(64, 64, 3, 3)) 
model.add(Activation('relu'))
model.add(MaxPooling2D(poolsize=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(64*16*16, 2048, init='normal'))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(2048, nb_classes, init='normal'))
model.add(Activation('softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)
```
which is almost identical to the model in `keras/example/cifar10_cnn.py `

Then, after training and testing, I want to save it with
```Python
model.save_weights('model_weight.hdf5')
```
where came in the error.
```
Traceback (most recent call last):
  File "cnn2.py", line 164, in <module>
    model.save_weights('model_weight.hdf5')
  File "/home/cy/.local/lib/python2.6/site-packages/keras/models.py", line 379, in save_weights
    g = f.create_group('layer_{}'.format(k))
ValueError: zero length field name in format
```
Another minor matter is that it does not allow saving weights to an existing file, which seems quite inconvenient to users.
```
Traceback (most recent call last):
  File "cnn2.py", line 164, in <module>
    model.save_weights('model_weight.hdf5')
  File "/home/cy/.local/lib/python2.6/site-packages/keras/models.py", line 375, in save_weights
    raise IOError('%s already exists' % (filepath))
IOError: model_weight.hdf5 already exists
```
Thanks for your attention :)

**Comment by tdhd** [comment]
I just ran your example and could not reproduce your error. Please be sure that you have the latest version.

Be aware that in the latest version there is an issue with `save_weights` if you use python `2.x` (#205). The best way to avoid this is to specify `overwrite=True` in `save_weights` at the moment.

**Comment by TrueWord** [comment]
Thank you.

I will try to upgrade my package and specify `overwrite=True`.
