### ISSUE TITLE
"AssertionError" in new version.

### ISSUE THREAD

**Issue by lji72** [fchollet/keras#2219]
Traceback (most recent call last):
  File "maxout_96_64_cnn.py", line 210, in <module>
    model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.008, decay=1e-6,  momentum=0.9, nesterov=True)) #optimizer='adadelta')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 420, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 128, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 673, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 964, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 639, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 1327, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 639, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/advanced_activations.py", line 70, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 964, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 836, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 639, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/advanced_activations.py", line 70, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 311, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 495, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 762, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/advanced_activations.py", line 70, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 311, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 762, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 495, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 639, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/advanced_activations.py", line 70, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 311, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 495, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/advanced_activations.py", line 70, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 173, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 316, in get_output
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 582, in conv2d
AssertionError

I  come cross above question， I run this code in old version very well . But when in new version, I get this question. I 'm very appreciated that you can give me some advises.

**Comment by lji72** [comment]
model = Sequential()

model.add(Convolution2D(32, 6, 6,
						init = 'uniform',
                        border_mode='same', 
		  	            subsample=(2, 2),
                        input_shape=(1, img_rows, img_cols)))
#model.add(Activation('relu'))
model.add(PReLU(init='zero', weights=None))
model.add(MaxPooling2D(pool_size=(4, 4), strides=(2,2)))


model.add(Convolution2D(81, 4, 4, init = 'uniform'))
#model.add(Activation('relu'))
model.add(PReLU(init='zero', weights=None))

model.add(Dropout(0.10))
model.add(MaxPooling2D(pool_size=(3, 3), strides=(1,1)))
#model.add(Dropout(0.25))
model.add(ZeroPadding2D(padding=(1,1), dim_ordering='th'))


model.add(Convolution2D(210, 3, 3, init = 'uniform'))
#model.add(Activation('relu'))
model.add(PReLU(init='zero', weights=None))
model.add(ZeroPadding2D(padding=(2,2), dim_ordering='th'))
model.add(MaxPooling2D(pool_size=(3, 3), strides=(2,2)))

model.add(Convolution2D(360, 3, 3, init = 'uniform'))
#model.add(Activation('relu'))
model.add(PReLU(init='zero', weights=None))
model.add(Dropout(0.20))

#model.add(ZeroPadding2D(2,2), dim_ordering='th')
#model.add(MaxPooling2D(pool_size=(3, 3), stride(2,2)))


model.add(Flatten())

model.add(Dense(500, init = 'uniform'))
#model.add(Activation('relu'))
#model.add(MaxoutDense(500, nb_feature=4, init='glorot_uniform', weights=None, W_regularizer=None, b_regularizer=None, activity_regularizer=None, W_constraint=None, b_constraint=None, input_dim=None))
model.add(PReLU(init='zero', weights=None))
model.add(Dropout(0.5))

#model.add(Dense(250))
#model.add(Activation('relu'))
model.add(MaxoutDense(250, nb_feature=4, init='uniform', weights=None, W_regularizer=None, b_regularizer=None, activity_regularizer=None, W_constraint=None, b_constraint=None, input_dim=None))
#model.add(PReLU(init='zero', weights=None))
model.add(Dropout(0.5))

model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.008, decay=1e-6,  momentum=0.9, nesterov=True)) #optimizer='adadelta')

**Comment by philipperemy** [comment]
Did you update theano or TF accordingly?

**Comment by philipperemy** [comment]
You may have a look at this link as well:

http://www.johnwittenauer.net/configuring-theano-for-high-performance-deep-learning/

**Comment by lji72** [comment]
@philipperemy  Thanks, I would have a try.

**Comment by fchollet** [comment]
What version of Keras is this?

import keras
print keras.__version__

**Comment by philipperemy** [comment]
@lji72 if it's solved, please close this issue
