### ISSUE TITLE
Queries regarding sequence length and predict function

### ISSUE THREAD

**Issue by shashankg7** [fchollet/keras#2261]
I am trying to perform sentiment analysis using the same model as specified in keras examples (imdb_lstm). I have doubt related to 'pad_sequences' function. 

For shorter sentences it makes sense to pad them to specified length, but this function also trims sentences with length > maxlen to maxlen. Aren't we losing information with this truncation? Is there any other alternative to still keep the sentence and train LSTM?

Also I am unable to use predict function to predict the sentiment of a sentence provided by user. 
I am taking a sentence from user and mapping it to integer sequence using the dictionary learned from dataset. I am trying following code, 

input = raw_input()
 mapping input to integer sequence (list) to X
pred = model.predict(X, batch_size=1)

It is giving following error:

Traceback (most recent call last):
  File "train_lstm.py", line 74, in <module>
    clf.find_sentiment()
  File "train_lstm.py", line 67, in find_sentiment
    X = sequence.pad_sequences(X, maxlen=self.maxlen)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/sequence.py", line 32, in pad_sequences
    lengths = [len(s) for s in sequences]
TypeError: object of type 'int' has no len()

**Comment by shashankg7** [comment]
The issue is solved. I didn't use pad_sequences on test sample (for second query). Regarding first query I think it is necessary to limit the sequence length to some fix (possibly small size), due to gradient issues with RNN's. Though LSTM and GRU solves this issue to some extend, I think it is still better to trim the sequence to small length.
