### ISSUE TITLE
Loading model after upgrading to keras1 error : 'NoneType' object has no attribute 'predict' 

### ISSUE THREAD

**Issue by Belbola** [fchollet/keras#2311]
After upgrading keras the model fails to predict anything after loading it 

```
# imports
import numpy as np 
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.optimizers import SGD
from keras.layers.recurrent import LSTM
from keras.models import model_from_json

# load it 
model = model_from_json(open('architecture.json').read())
model.load_weights('weights.h5')

 # predict 
predicted = model.predict(X_test[i].reshape((1, 168, 1)))
```

with error : 

```
Traceback (most recent call last):

  File "<ipython-input-6-c878daace714>", line 4, in <module>
    predicted = model.predict(X_test[i].reshape((1, 168, 1)))

  File "/home/akram/anaconda2/lib/python2.7/site-packages/keras/models.py", line 444, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)

AttributeError: 'NoneType' object has no attribute 'predict'
```
```
model.get_config()
Out[9]: 
[{'class_name': 'LSTM',
  'config': {'U_regularizer': None,
   'W_regularizer': None,
   'activation': 'tanh',
   'b_regularizer': None,
   'batch_input_shape': (None, None, 1),
   'consume_less': u'cpu',
   'dropout_U': 0.0,
   'dropout_W': 0.0,
   'forget_bias_init': 'one',
   'go_backwards': False,
   'init': 'glorot_uniform',
   'inner_activation': 'hard_sigmoid',
   'inner_init': 'orthogonal',
   'input_dim': 1,
   'input_dtype': u'float32',
   'input_length': None,
   'name': u'lstm_1',
   'output_dim': 50,
   'return_sequences': False,
   'stateful': False,
   'trainable': True,
   'unroll': False}},
 {'class_name': 'Dense',
  'config': {'W_constraint': None,
   'W_regularizer': None,
   'activation': 'linear',
   'activity_regularizer': None,
   'b_constraint': None,
   'b_regularizer': None,
   'init': 'glorot_uniform',
   'input_dim': None,
   'name': u'dense_1',
   'output_dim': 50,
   'trainable': True}},
 {'class_name': 'Activation',
  'config': {'activation': 'relu',
   'name': u'activation_1',
   'trainable': True}},
 {'class_name': 'RepeatVector',
  'config': {'n': 186, 'name': u'repeatvector_1', 'trainable': True}},
 {'class_name': 'LSTM',
  'config': {'U_regularizer': None,
   'W_regularizer': None,
   'activation': 'tanh',
   'b_regularizer': None,
   'batch_input_shape': (None, None, 50),
   'consume_less': u'cpu',
   'dropout_U': 0.0,
   'dropout_W': 0.0,
   'forget_bias_init': 'one',
   'go_backwards': False,
   'init': 'glorot_uniform',
   'inner_activation': 'hard_sigmoid',
   'inner_init': 'orthogonal',
   'input_dim': 50,
   'input_dtype': 'float32',
   'input_length': None,
   'name': u'lstm_2',
   'output_dim': 50,
   'return_sequences': True,
   'stateful': False,
   'trainable': True,
   'unroll': False}},
 {'class_name': 'TimeDistributedDense',
  'config': {'W_constraint': None,
   'W_regularizer': None,
   'activation': 'linear',
   'activity_regularizer': None,
   'b_constraint': None,
   'b_regularizer': None,
   'init': 'glorot_uniform',
   'input_dim': None,
   'input_length': None,
   'name': u'timedistributeddense_1',
   'output_dim': 1,
   'trainable': True}}]
```

Any hint ?

**Comment by nomicflux** [comment]
I was running into the same problem - did you figure out what the issue was?

**Comment by fchollet** [comment]
You need to compile your model after loading it, the loading step will no
longer compile the model automatically.

**Comment by Chanukaa** [comment]
I am also having the same error. Compiling the model after loading also gives the same error. did anyone figure out the reason for the issue?

**Comment by tharshi92** [comment]
I am having this same problem
