### ISSUE TITLE
ERROR (theano.gof.cmodule): [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by dsy412610** [fchollet/keras#2318]
When I ran my code with the new version of Keras, I encountered an error as following:
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=core-avx2 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=core-avx2 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/theano/gof -fvisibility=hidden -o /home/dsy/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpYLSNLS/d677916e618411b78d3c26b1c886bb3d.so /home/dsy/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpYLSNLS/mod.cpp -L/usr/lib -lpython2.7
ERROR (theano.gof.cmodule): [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "Alexnet.py", line 96, in <module>
    result = model.fit(X_train, Y_train, batch_size=batch_size, validation_split = 0.2, nb_epoch=nb_epoch)#, callbacks = [early_stopping])
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 402, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 964, in fit
    self._make_train_function()
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 640, in _make_train_function
    *_self._function_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 498, in function
    return Function(inputs, outputs, updates=updates, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 484, in __init__
    *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 322, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1779, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1643, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 1005, in make_all
    no_recycling))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 978, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 881, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1143, in **compile**
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2182, in compile_str
    p_out = output_subprocess_Popen(cmd)
  File "/usr/local/lib/python2.7/dist-packages/theano/misc/windows.py", line 76, in output_subprocess_Popen
    p = subprocess_Popen(command, *_params)
  File "/usr/local/lib/python2.7/dist-packages/theano/misc/windows.py", line 37, in subprocess_Popen
    proc = subprocess.Popen(command, startupinfo=startupinfo, **params)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

 I don't know how to solve this problem. Who can tell me why this error appear? Thank you!

**Comment by dsy412610** [comment]
It's weird that my code can run normally after I reduced input data and recovered the data again. Why?

**Comment by dsy412610** [comment]
`model = `

**Comment by dsy412610** [comment]
I used the model as following:
`model = Sequential()
model.add(Convolution2D(96, 11, 11, border_mode = 'valid', input_shape = (3, 227, 227), subsample = (4, 4)))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(ZeroPadding2D(padding = (2, 2)))
model.add(Convolution2D(256, 5, 5, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(ZeroPadding2D(padding = (1, 1)))
model.add(Convolution2D(384, 3, 3, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))`
