### ISSUE TITLE
Comaptibility with TensorFlow 0.8.

### ISSUE THREAD

**Issue by JoelKronander** [fchollet/keras#2327]
I get errors trying keras 1.0 with new tensorflow 0.8 on mac os.

**Comment by fchollet** [comment]
It would help if you were to specify which errors.

**Comment by JoelKronander** [comment]
Hi, this is the error I get, 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joel/Research/Misc/UdacityTensorflow/as3keras.py", line 44, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python3.5/site-packages/keras/models.py", line 5, in <module>
    from . import backend as K
  File "/usr/local/lib/python3.5/site-packages/keras/backend/__init__.py", line 54, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 55, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by JoelKronander** [comment]
i upgraded tensorflow using sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0rc0-py3-none-any.whl

**Comment by fchollet** [comment]
You need to uninstall protobuf, uninstall TF, and reinstall TF via pip. This is a common TF installation issue, not a Keras issue.

**Comment by JoelKronander** [comment]
Thank you!
