### ISSUE TITLE
theano backend / cnn faliure for ubuntu?

### ISSUE THREAD

**Issue by sjhddh** [fchollet/keras#2339]
found a issue, not sure why.

was using Mac before, no issue happens. 

but when switch to ubuntu, something happends..

I am running python 3.5 on ubuntu 14.04 TLS

I found some weird errors on my own code.

Then, I just tried running **keras example** _mnist_cnn.py_

the same thing happend:

``` python
image  [None, None, None, None]  filters  [32, 32, 3, 3]
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv_gradweight_gemm,local_conv2d_cpu,local_conv2d_gradinputs_cpu,local_conv2d_gradweight_cpu)
ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(32, 32, 3, 3)}(Elemwise{mul,no_inplace}.0, convolution2d_2_W)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 1223, in transform
    repl = opt.transform(node)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/tensor/nnet/opt.py", line 153, in local_conv2d_cpu
    subsample=node.op.subsample)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/tensor/nnet/conv.py", line 132, in conv2d
    assert image_shape[1] == filter_shape[1]
AssertionError

Traceback (most recent call last):
  File "mnist_cnn.py", line 71, in <module>
    verbose=1, validation_data=(X_test, Y_test))
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/keras/models.py", line 402, in fit
    sample_weight=sample_weight)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/keras/engine/training.py", line 986, in fit
    self._make_test_function()
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/keras/engine/training.py", line 666, in _make_test_function
    **self._function_kwargs)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 498, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 484, in __init__
    **kwargs)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/compile/function.py", line 322, in function
    output_keys=output_keys)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/compile/function_module.py", line 1778, in orig_function
    output_keys=output_keys).create(
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/compile/function_module.py", line 1458, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 2196, in apply
    lopt_change = self.process_node(fgraph, node, lopt)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 1777, in process_node
    lopt, node)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 1673, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 1659, in warn
    raise exc
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/gof/opt.py", line 1223, in transform
    repl = opt.transform(node)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/tensor/nnet/opt.py", line 153, in local_conv2d_cpu
    subsample=node.op.subsample)
  File "/home/aaron/Git/.virtualenvs/ts/local/lib/python3.5/site-packages/theano/tensor/nnet/conv.py", line 132, in conv2d
    assert image_shape[1] == filter_shape[1]
AssertionError
```

Not sure what it is.

help......

**Comment by nouiz** [comment]
The Theano error should be removed by: https://github.com/Theano/Theano/pull/4370

But this probably indicate that now image_shape isn't passed anymore by Keras to theano. So fixing this in Keras would be ideal, but itsn't very used anymore.

**Comment by nouiz** [comment]
Also, Keras still use the old Theano interface. Instead of calling theano.tensor.nnet.conv.conv2d, it should call theano.nnet.conv2d.

This will result in faster code. There is a parameter name change, that will result in warning if you don't do it.

**Comment by tboquet** [comment]
I think it has been integrated [here](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L811-L815).

**Comment by sjhddh** [comment]
@tboquet Ahh, thank you very much. But, it does not really solve the problem, updating to Keras 1.0.1 throws even more weird errors. I might need to roll back to Keras 0.3.3 for a long while in order to keep the dev environment stable.

**Comment by nouiz** [comment]
Update to Theano dev version:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

to fix the original problem.
