### ISSUE TITLE
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup...

### ISSUE THREAD

**Issue by githubzhanglei** [fchollet/keras#2345]
I am running python and keras on windows,
I use anaconda2 with"pip install keras" to install the keras. The installed keras version is 1.0.0, and the installed theano version is 0.8.1. Then I run the keras example "mnist_cnn.py" step by step, the errors come out when it run the 70 line" model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1, validation_data=(X_test, Y_test))". 
The ERRORs are as follows:

Using Theano backend.
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
X_train shape: (60000L, 1L, 28L, 28L)
60000 train samples
10000 test samples
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv_gradweight_gemm,local_conv2d_cpu,local_conv2d_gradinputs_cpu,local_conv2d_gradweight_cpu)
ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='valid', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(32, 32, 3, 3)}(Elemwise{mul,no_inplace}.0, convolution2d_2_W)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1223, in transform
    repl = opt.transform(node)
  File "C:\Anaconda2\lib\site-packages\theano\tensor\nnet\opt.py", line 153, in local_conv2d_cpu
    subsample=node.op.subsample)
  File "C:\Anaconda2\lib\site-packages\theano\tensor\nnet\conv.py", line 132, in conv2d
    assert image_shape[1] == filter_shape[1]
AssertionError

image  [None, None, None, None]  filters  [32, 32, 3, 3]
Traceback (most recent call last):

  File "<ipython-input-1-129f2e24a4ae>", line 1, in <module>
    runfile('E:/DeepLearning/kerasProject/kerasMnistExample.py', wdir='E:/DeepLearning/kerasProject')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "E:/DeepLearning/kerasProject/kerasMnistExample.py", line 77, in <module>
    verbose=1, validation_data=(X_test, Y_test))

  File "C:\Anaconda2\lib\site-packages\keras-1.0.0-py2.7.egg\keras\models.py", line 402, in fit
    sample_weight=sample_weight)

  File "C:\Anaconda2\lib\site-packages\keras-1.0.0-py2.7.egg\keras\engine\training.py", line 986, in fit
    self._make_test_function()

  File "C:\Anaconda2\lib\site-packages\keras-1.0.0-py2.7.egg\keras\engine\training.py", line 666, in _make_test_function
    **self._function_kwargs)

  File "C:\Anaconda2\lib\site-packages\keras-1.0.0-py2.7.egg\keras\backend\theano_backend.py", line 498, in function
    return Function(inputs, outputs, updates=updates, **kwargs)

  File "C:\Anaconda2\lib\site-packages\keras-1.0.0-py2.7.egg\keras\backend\theano_backend.py", line 484, in **init**
    **kwargs)

  File "C:\Anaconda2\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)

  File "C:\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)

  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(

  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1456, in **init**
    optimizer_profile = optimizer(fgraph)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 101, in **call**
    return self.optimize(fgraph)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 89, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 89, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 2196, in apply
    lopt_change = self.process_node(fgraph, node, lopt)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1777, in process_node
    lopt, node)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1673, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)

  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1659, in warn
    raise exc

AssertionError

**Comment by githubzhanglei** [comment]
Run the same code on MacOS 10.11.3, No Error reported. The version of Keras and Theano are the same as on windows.
Anybody knows why?
Thanks

**Comment by rpinsler** [comment]
Seems to be a duplicate of #2339.

**Comment by sjhddh** [comment]
Hey there,
Yeah, we encountered the same error.

After diving into Keras community for a while,
I think it might be aroused by the following factors:

1. Keras just upgraded from 0.3.3 to 10.0.0
I updated keras on my mac and then it has some errors as well.
So, I think might be a problem of the version difference.
Maybe you can have a try rolling your keras back to 0.3.3

2. CUDA and cm package conflicts.
e, basically, for ubuntu, try different package/driver combinations, something magic might happen.
if you try THEANO_FLAG to use cpu only? if it works, then, it might be a problem on GPU things.

Looking forward to see more real solutions.

**Comment by nouiz** [comment]
Theano will be super slow as you don't have a g++ compiler. There was this
warning in the output you gave:

WARNING (theano.configdefaults): g++ not detected ! Theano will be unable
to execute optimized C-implementations (for both CPU and GPU) and will
default to Python implementations. Performance will be severely degraded.
To remove this warning, set Theano flags cxx to an empty string.

Otherwise, the optimization failure is just a warning. You can ignore it.
But yes, it would be great to fix it.

I added the Theano fix to remove that in this PR:

https://github.com/Theano/Theano/pull/4370

But the problem is that Keras don't pass the image_shape, only the
filter_shape with that Keras version. Maybe the image_shape was lost during
the big update. This should be looked into by other people from Keras.

**Comment by rilut** [comment]
@nouiz I've also encountered an error with Theano 0.8.x + Keras 1.0 (installed both from master branch yesterday). I'm running it on CPU and Windows 10 x64

```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Elemwise{Cast{float32}}(TensorConstant{(1L, 1L) of 0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "C:\Anaconda2\lib\site-packages\theano\tensor\opt.py", line 5863, in constant_folding
    no_recycling=[])
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 978, in make_thunk
    no_recycling)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 881, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 2213, in compile_str
    return dlimport(lib_filename)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 299, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('DLL load failed: The specified procedure could not be found.', '[Elemwise{Cast{float32}}(TensorConstant{(1L, 1L) of 0})]')
.......
ImportError: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(Dot22.0, InplaceDimShuffle{x,0}.0), '\n', 'DLL load failed: The specified procedure could not be found.', '[Elemwise{add,no_inplace}(<TensorType(float32, matrix)>, <TensorType(float32, row)>)]')

```
Is my error related to this issue?
I'm looking forward on your PR merge, to see if it solves my error too.

**Comment by nouiz** [comment]
I don't know, I googled rapidly the error message:

DLL load failed: The specified procedure could not be found.

ANd they point to a few different option. Maybe you mix 32bit and 64
bit software stack. Maybe a dependency isn't well install ...

Google for that and check those options.

**Comment by rilut** [comment]
@nouiz I think those are related to OpenCV rather than Theano :)

**Comment by knguyen0105** [comment]
I'm also having the same problem. I upgraded both keras and theano to the latest version. keras 1.0.1 and theano 0.8.1.

I installed opencv using this command "conda install -c https://conda.binstar.org/menpo opencv"

**Comment by nouiz** [comment]
You can update Theano to the development version:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by knguyen0105** [comment]
Thank you. It works wonder!

**Comment by githubzhanglei** [comment]
Thank you. The errors are fixed when the  theano are upgraded from 0.8.1 to 0.9.0.dev0.

**Comment by rilut** [comment]
@nouiz

> I don't know, I googled rapidly the error message:

> DLL load failed: The specified procedure could not be found.

> And they point to a few different option. Maybe you mix 32bit and 64
bit software stack. Maybe a dependency isn't well install ...

> Google for that and check those options.

Mostly those are related to OpenCV. Unfortunately, I still have no idea what the cause of this error is :confused:. My checklist:

- [x] Reinstalled Anaconda 64-bit
- [x] `conda install mingw libpython`
- [x] Have no other g++ such as TDM-GCC
- [x] Installed Theano and Keras from today master branch
- [x] Minimal .THEANORC (eg. without any openblas settings)

Maybe I'll just use my lab PC instead. Cheers

**Comment by nouiz** [comment]
If you don't need opencv anymore, you could remove them... Not the best
solution for sure.

**Comment by rilut** [comment]
@nouiz no, I don't use OpenCV at all. What I meant was those error messages mostly related to people who mix 32-bit & 64-bit library of OpenCV, while I haven't found any case related to Theano (like me), which is strange (because I follow the installation instruction from Theano website)

**Comment by Hazarapet** [comment]
I've got an error and can't find a solution

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Elemwise{sub,no_inplace}(TensorConstant{[[ 0.  1. ..  1.  0.]]}, TensorConstant{[[ 0.  1. ..  1.  0.]]})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1996, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6473, in constant_folding
    required = thunk()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 859, in rval
    fill_storage()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1710, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "<string>", line 2, in reraise
ValueError: Input dimension mis-match. (input[0].shape[0] = %lli, input[%i].shape[%i] = %lli)

theano cache clear and purge didn't help.is there any idea how I can solve this?
