### ISSUE TITLE
Importing old network from json throws KeyError

### ISSUE THREAD

**Issue by Brabantis** [fchollet/keras#2352]
I have just upgraded Keras, and trying to import a network I had saved as json (architecture) + h5 (weights). However, model_from_json throws a KeyError exception referring to class_name.

``` python
Python 2.7.11 |Anaconda custom (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from keras.models import model_from_json
Using Theano backend.
>>> model = model_from_json(open('models/complete2/architecture.json').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/migliorini/anaconda2/lib/python2.7/site-packages/keras/models.py", line 30, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/home/migliorini/anaconda2/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 24, in layer_from_config
    class_name = config['class_name']
KeyError: 'class_name'
```
Keras and Theano are updated to the latest version. I was hoping not to have to train again the net.
Thanks in advance for the help,
Enrico

**Comment by fchollet** [comment]
Old JSON files are not compatible with the latest version. Rebuild your model from its source code (which is compatible), then save it again.

**Comment by Brabantis** [comment]
Ok, thank you. The weights saved in h5 will still be compatible?

**Comment by fchollet** [comment]
Yes.
