### ISSUE TITLE
ImportError: cannot import name gof

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#2414]
Just now, keras and theano were well-balanced on my code, but after next running, it yielded the error.
```
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "E:/EMNLP/experiment/user_detection_KT.py", line 32, in <module>
    from keras.layers import Input, LSTM, Dense, merge,Embedding
  File "C:\Anaconda2\lib\site-packages\keras\layers\__init__.py", line 2, in <module>
    from ..engine import Layer, Input, InputLayer, Merge, merge, InputSpec
  File "C:\Anaconda2\lib\site-packages\keras\engine\__init__.py", line 3, in <module>
    from .topology import InputSpec
  File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 15, in <module>
    from keras import backend as K
  File "C:\Anaconda2\lib\site-packages\keras\backend\__init__.py", line 51, in <module>
    from .theano_backend import *
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 1, in <module>
    import theano
  File "C:\Anaconda2\lib\site-packages\theano\__init__.py", line 74, in <module>
    from theano.printing import pprint, pp
  File "C:\Anaconda2\lib\site-packages\theano\printing.py", line 35, in <module>
    if pd.find_graphviz():
  File "C:\Anaconda2\lib\site-packages\pydot.py", line 409, in find_graphviz
    "SOFTWARE\ATT\Graphviz", 0, win32con.KEY_QUERY_VALUE )
pywintypes.error: (2, 'RegOpenKeyEx', '\xcf\xb5\xcd\xb3\xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xce\xc4\xbc\xfe\xa1\xa3')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "E:/EMNLP/experiment/user_detection_KT.py", line 32, in <module>
    from keras.layers import Input, LSTM, Dense, merge,Embedding
  File "C:\Anaconda2\lib\site-packages\keras\layers\__init__.py", line 2, in <module>
    from ..engine import Layer, Input, InputLayer, Merge, merge, InputSpec
  File "C:\Anaconda2\lib\site-packages\keras\engine\__init__.py", line 3, in <module>
    from .topology import InputSpec
  File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 15, in <module>
    from keras import backend as K
  File "C:\Anaconda2\lib\site-packages\keras\backend\__init__.py", line 51, in <module>
    from .theano_backend import *
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 1, in <module>
    import theano
  File "C:\Anaconda2\lib\site-packages\theano\__init__.py", line 74, in <module>
    from theano.printing import pprint, pp
  File "C:\Anaconda2\lib\site-packages\theano\printing.py", line 19, in <module>
    from theano import gof
ImportError: cannot import name gof
```

**Comment by nouiz** [comment]
Your version of pydot is troublesome. Can you uninstall it and install
pydot_ng instead?

**Comment by Imorton-zd** [comment]
@nouiz Thanks for your replay! I have solved this error!

**Comment by Imorton-zd** [comment]
@nouiz However, I have install pydot_ng, when I use the code below, yield other errors!
```
from keras.utils.visualize_util import model_to_dot
from keras.utils.visualize_util import plot
```
```
RuntimeError: Failed to import pydot. You must install pydot and graphviz for `p
ydotprint` to work.
```

**Comment by nouiz** [comment]
Theano support pydot and pydot_ng. You can check how we support both
version in the Theano file theano/printing.py. Check the import at the top.
You can do the same in Keras to have it support pydot_ng. This is easy to
do. If it work, can you make a PR to keras? pydot isn't supported anymore
and pydot_ng is.

Otherwise, maybe reinstalling pydot will work this time.

**Comment by Imorton-zd** [comment]
@nouiz I have read the file printing.py. The code could support pydot_ng. But why get the `RuntimeError`?
```
try:
    # pydot-ng is a fork of pydot that is better maintained
    import pydot_ng as pd
    if pd.find_graphviz():
        pydot_imported = True
except ImportError:
    try:
        # fall back on pydot if necessary
        import pydot as pd
        if pd.find_graphviz():
            pydot_imported = True
    except ImportError:
        pass
```

**Comment by nouiz** [comment]
I don't use keras. I develop Theano. I don't know run keras raise a runtime
error when it don't find pydot. Just do the same in your modified code.

We prefer to let the file be imported and raise an error when it get used.
Maybe the author of keras prefer to raise the error when the file is
imported.

**Comment by braingineer** [comment]
you could just install graphviz.. 

`pip install graphviz`

I use anaconda, so

`conda install graphviz`
