### ISSUE TITLE
Exception: Invalid merge mode: join

### ISSUE THREAD

**Issue by BinbinBian** [fchollet/keras#2424]
the shape of Y is kxL,and alpha is Lx1.

Here is my code:
model.add_node(Lambda(get_R, output_shape=(k,1)), name='_r', inputs=['Y','alpha'],merge_mode='join')

def get_R(X):
    Y, alpha = X.values()  # Y should be (None,L,k) and alpha should be (None,L,1) and ans should be (None, k,1)
    tmp=K.permute_dimensions(Y,(0,)+(2,1))  # copied from permute layer, Now Y is (None,k,L) and alpha is always (None,L,1)
    ans=K.T.batched_dot(tmp,alpha)
    return ans

Traceback (most recent call last):
  File "amodel.py", line 267, in <module>
    model = build_model(options)
  File "amodel.py", line 140, in build_model
    model.add_node(Lambda(get_R, output_shape=(k,1)), name='_r', inputs=['Y','alpha'],merge_mode='join')
  File "/home/bbbian/anaconda/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/legacy/models.py", line 183, in add_node
    name='merge_inputs_for_' + name)
  File "/home/bbbian/anaconda/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 1116, in __init__
    node_indices, tensor_indices)
  File "/home/bbbian/anaconda/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 1129, in _arguments_validation
    raise Exception('Invalid merge mode: ' + str(mode))
Exception: Invalid merge mode: join

**Comment by fchollet** [comment]
Maybe because... there is no such merge mode? The list of valid merge modes can be found in the docs.
