### ISSUE TITLE
Merge Layer example fails on fit()

### ISSUE THREAD

**Issue by atnelson** [fchollet/keras#2427]
The [Merge Layer example](http://keras.io/getting-started/sequential-model-guide/#the-merge-layer) in the documentation fails when calling final_model.fit()
```
left_branch = Sequential()
left_branch.add(Dense(32, input_dim=784))

right_branch = Sequential()
right_branch.add(Dense(32, input_dim=784))

merged = Merge([left_branch, right_branch], mode='concat')

final_model = Sequential()
final_model.add(merged)
final_model.add(Dense(10, activation='softmax'))

input1 = np.random.random((100,784))
target1 = np.random.random((100,10))

final_model.compile('rmsprop','categorical_crossentropy')

final_model.fit(x=input1,y=target1,
             batch_size=32,
             nb_epoch=10)
```

The error is as follows:
```
Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 402, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 971, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 898, in _standardize_user_data
    exception_prefix='model input')
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 73, in standardize_input_data
    array = arrays[i]
IndexError: list index out of range
Total params: 50890
```

Looking at training.py, it appears there are more input_names than arrays.

**Comment by fchollet** [comment]
The example in the docs works fine. You have to notice that such a model has two inputs, and therefore you need to pass it two input arrays rather than one.

**Comment by atnelson** [comment]
Thanks! I had just figured that out by (successfully) training the last example of http://keras.io/getting-started/sequential-model-guide/#examples

It might be worth adding a few extra lines to the simple example I struggled with. I imagine I won't be the only one to have this confusion:

```
final_model.compile('rmsprop','categorical_crossentropy')
input = np.random.random((100,784))
target = np.random.random((100,10))
final_model.fit(x=[input,input],y=target,
             batch_size=32,
             nb_epoch=10)
```
