### ISSUE TITLE
sparse_categorical_crossentropy doesn't seem to be working

### ISSUE THREAD

**Issue by hr0nix** [fchollet/keras#2444]
[Here](https://gist.github.com/hr0nix/c7d56944e14b7a26349aa4113a879be3) is an example language model, that doesn't work with sparse_categorical_crossentropy. If one uncomments lines 25-26, running the script will result in the following error:

`Traceback (most recent call last):
  File "./sparse_softmax_example.py", line 34, in <module>
    main()
  File "./sparse_softmax_example.py", line 26, in main
    model.fit(input, output, batch_size=1, nb_epoch=1)
  File "/place/home/hr0nix/src/text_features/env2/lib/python2.7/site-packages/keras/models.py", line 402, in fit
    sample_weight=sample_weight)
  File "/place/home/hr0nix/src/text_features/env2/lib/python2.7/site-packages/keras/engine/training.py", line 1036, in fit
    callback_metrics=callback_metrics)
  File "/place/home/hr0nix/src/text_features/env2/lib/python2.7/site-packages/keras/engine/training.py", line 774, in _fit_loop
    outs = f(ins_batch)
  File "/place/home/hr0nix/src/text_features/env2/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 499, in __call__
    return self.function(*inputs)
  File "/place/home/hr0nix/src/text_features/env2/lib/python2.7/site-packages/theano/compile/function_module.py", line 815, in __call__
    allow_downcast=s.allow_downcast)
  File "/place/home/hr0nix/src/text_features/env2/lib/python2.7/site-packages/theano/tensor/type.py", line 178, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/place/home/hr0nix/src/text_features/env2/lib/python2.7/site-packages/keras/backend/theano_backend.py:495"  at index 1(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (1, 2).')`

Lines 28-30 work just fine. Am I doing something wrong or is it a bug in keras codebase?

**Comment by cmyr** [comment]
If you're using that objective you manually have to add an extra dimension, e.g. `np.expand_dims(y, -1)` on your inputs.

I think this was documented somewhere in keras 0.3, it may have been lost in the shuffle. 

This was a work around for some stuff where keras was inferring some things about temporal outputs based on shape. 

Let me know if that works or does not work.
