### ISSUE TITLE
Building the documentation with Python 3.5

### ISSUE THREAD

**Issue by roryhr** [fchollet/keras#2454]
```
/keras/docs$ python -c "import keras
print(keras.__version__)"
1.0.1
/keras/docs$ python -V
Python 3.5.1 :: Continuum Analytics, Inc.
/keras/docs$ python autogen.py 
Using TensorFlow backend.
Cleaning up existing sources directory.
Populating sources directory with templates.
Starting autogeneration.
Traceback (most recent call last):
  File "autogen.py", line 390, in <module>
    signature = get_function_signature(function, method=False)
  File "autogen.py", line 253, in get_function_signature
    elif type(v) == unicode:
NameError: name 'unicode' is not defined
/keras/docs$ 
```

**Comment by grahamannett** [comment]
needs to have 
from __future__ import unicode_literals 
added and if statements changed probably
