### ISSUE TITLE
TimeDistributed Embedding Error: Index must be Integers

### ISSUE THREAD

**Issue by siddk** [fchollet/keras#2458]
I am having an issue where I can't build a model in which I use a TimeDistributed wrapper on an Embedding layer. The code is as follows:

``` python
def build_model(self):
        """
        Build Keras Model
        """
        model = Sequential()
        # Input Shape: (_, STORY_SIZE, SENTENCE_SIZE)
        model.add(TimeDistributed(Embedding(input_dim=self.V, output_dim=self.EMBEDDING_SIZE,
                                            input_length=self.SENTENCE_SIZE),
                                  input_shape=(self.STORY_SIZE, self.SENTENCE_SIZE)))
        # Shape: (_, STORY_SIZE, SENTENCE_SIZE, EMBEDDING_SIZE)
        model.add(TimeDistributed(Flatten()))
        # Shape: (_, STORY_SIZE, SENTENCE_SIZE * EMBEDDING_SIZE)
        model.add(LSTM(self.MEMORY_SIZE, return_sequences=True))
        # Shape: (_, STORY_SIZE, MEMORY_SIZE)
        model.add(TimeDistributed(Dense(self.V, activation='softmax')))
        # Shape: (_, STORY_SIZE, VOCAB_SIZE) --> Softmax

        return model
```

When I try and build this model, I get the following traceback:

```
Traceback (most recent call last):
  File "/Users/sidd/Projects/memory/naive_rnn/model/memrnn.py", line 35, in build_model
    input_shape=(self.STORY_SIZE, self.SENTENCE_SIZE)))
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/models.py", line 107, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/topology.py", line 341, in create_input_layer
    self(x)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/layers/wrappers.py", line 125, in call
    y = self.layer.call(X)  # (nb_samples * timesteps, ...)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/layers/embeddings.py", line 133, in call
    out = K.gather(W, x)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 156, in gather
    return reference[indices]
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/tensor/var.py", line 503, in __getitem__
    return self.take(args[axis], axis)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/tensor/var.py", line 535, in take
    return theano.tensor.subtensor.take(self, indices, axis, mode)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 2387, in take
    return take(a, indices.flatten(), axis, mode).reshape(shape, ndim)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 2365, in take
    return advanced_subtensor1(a, indices)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 1687, in make_node
    raise TypeError('index must be integers')
TypeError: index must be integers
```

This seems to be an issue with the dimension of the tensor passed to the Embedding layer. I'm not sure if I'm using TimeDistributed properly in this context, or how I might fix this. Any help resolving this would be much appreciated, thanks!

**Comment by siddk** [comment]
Ok, I managed to fix it by editing the TimeDistibuted wrapper class as follows:

In call(self, X, mask=None):

```pythonX = K.reshape(X, (-1, ) + input_shape[2:])  # (nb_samples * timesteps, ...)
            if isinstance(self.layer, Embedding):
                y = self.layer.call(X.astype('int32'))
            else:
                y = self.layer.call(X)  # (nb_samples * timesteps, ...)

**Comment by braingineer** [comment]
You don't have to Distribute the Embeddings. 

```python
import theano
A = theano.shared(np.arange(15).reshape(5,3))
B = theano.shared(np.random.randint(0,4,(2,2,2)))
print(A[B].eval().shape) ### will print (2,2,2,3)
```

see #2442 for discussion of embedding tensors

also, I think maybe you didn't set your inputs as ints. 

```python
B = theano.shared(np.random.randint(0,4,(2,2,2)))
print(B.eval().dtype)  
# > dtype('int64')
print(theano.tensor.reshape(B, (4,2)).eval().dtype) 
# > dtype('int64')
```

I typically use an Input layer `Input(shape=(x,y), dtype='int32')`.

**Comment by siddk** [comment]
Hey @braingineer 

Thanks! I looked at #2442, and I think it's just doing the same thing as the Time Distribution, but I'll definitely use that tip in the future.

I couldn't find any documentation for Input layers, have they been deprecated?

**Comment by braingineer** [comment]
> doing the same thing

no. it's doing indexing. distributed embedding is reshaping and then embedding. that's a couple wasted operations. 

> input layers

It's part of the new API. you're best bet is to check the examples and the code: 
https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L976

or to read the functional how-to
http://keras.io/getting-started/functional-api-guide/

It's just a temporary variable placement holder.  It allows you to get a symbolic handle on the input and define properties like shape and type.

**Comment by siddk** [comment]
Hmm, so I tried getting rid of the TimeDistributed wrapper for the Embeddings layer, but now I'm getting the following error:

```
/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight)
    969                                                            class_weight=class_weight,
    970                                                            check_batch_dim=False,
--> 971                                                            batch_size=batch_size)
    972         # prepare validation data
    973         if validation_data:

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/training.pyc in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_dim, batch_size)
    909                           in zip(y, sample_weights, class_weights, self.sample_weight_modes)]
    910         check_array_lengths(x, y, sample_weights)
--> 911         check_loss_and_target_compatibility(y, self.loss_functions, self.internal_output_shapes)
    912         if self.stateful and batch_size:
    913             if x[0].shape[0] % batch_size != 0:

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/training.pyc in check_loss_and_target_compatibility(targets, losses, output_shapes)
    199                 raise Exception('A target array with shape ' + str(y.shape) +
    200                                 ' was passed for an output of shape ' + str(shape) +
--> 201                                 ' while using as loss `' + loss.__name__ + '`. '
    202                                 'This loss expects '
    203                                 'targets to have the same shape '

Exception: A target array with shape (1000, 10, 22) was passed for an output of shape (None, 14, 22) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.
```

It seems that the shape at the end of the model is now different than it was before.

This is the new model code I'm using:

```python
model = Sequential()
model.add(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_SIZE,
                    input_length=SENTENCE_MAX, mask_zero=True,
                    input_shape=(STORY_MAX, SENTENCE_MAX)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(MEMORY_SIZE, return_sequences=True))
model.add(TimeDistributed(Dense(VOCAB_SIZE, activation='softmax')))
```

Input tensor is 3D -> (Num_Samples, Story_Max, Sentence_Max), and Output Tensor is 3D -> (Num_Samples, Story_Max, Vocab_Size)

**Comment by braingineer** [comment]
So, I'm not sure how you got that output shape.  

```python
model = Sequential()
# input is (batch, story, sentence)
model.add(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_SIZE,
                    input_length=SENTENCE_MAX, mask_zero=True,
                    input_shape=(STORY_MAX, SENTENCE_MAX)))
# size is now (batch, story, sentence, embedding)

# batch flattens over time dim; result is (batch, story, sentence * embedding)
model.add(TimeDistributed(Flatten()))
# iterates over story, returns (batch, story, memory)
model.add(LSTM(MEMORY_SIZE, return_sequences=True))
# softmax over memory, results in (batch, story, vocab)
model.add(TimeDistributed(Dense(VOCAB_SIZE, activation='softmax'))
```

this is what I'm guessing you were aiming for. 

Your usage of the shape parameters in the embedding confuse me. 

Since you're using the model version of Keras, you'd have to add an InputLayer I think rather than use input.  But you should do, at the beginning:

```python
model.add(InputLayer(batch_input_shape=(BATCH_SIZE, STORY_MAX, SENTENCE_MAX), dtype='int32'))
```
now, keras isn't trying to guess what shape you have. 

If you altered the embedding as I had mentioned so that it doesn't use the `input_length` variable, you can just do 

```python
model.add(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_SIZE,   
                                     mask_zero=True))
```

Because the input shape is specified in the InputLayer, Embedding's `get_output_shape_for` function (which is how the shape information gets passed through your network) will output 

```python
batch_input_shape + (self.output_dim,)
```

**Comment by siddk** [comment]
Ok, I did as you suggested, and I'm getting the weirdest error. Here's the current model code:

```python
STORY_MAX, SENTENCE_MAX = 10, 14
EMBEDDING_SIZE, MEMORY_SIZE = 128, 100
VOCAB_SIZE = 22
BATCH_SIZE = 32

# Build Keras Model
model = Sequential()
model.add(InputLayer(batch_input_shape=(BATCH_SIZE, STORY_MAX, SENTENCE_MAX), input_dtype='int32'))
model.add(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_SIZE, mask_zero=True))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(MEMORY_SIZE, return_sequences=True))
model.add(TimeDistributed(Dense(VOCAB_SIZE, activation='softmax')))

# Fit the model
model.compile(optimizer='Adam', loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=BATCH_SIZE, nb_epoch=50,
          validation_split=0.05)
```

And here's the (long) stacktrace:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/sidd/Projects/memory/naive_rnn/sandbox.py in <module>()
     32               metrics=['accuracy'])
     33 model.fit(train_x, train_y, batch_size=BATCH_SIZE, nb_epoch=50,
---> 34           validation_split=0.05)

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/models.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, **kwargs)
    400                               shuffle=shuffle,
    401                               class_weight=class_weight,
--> 402                               sample_weight=sample_weight)
    403 
    404     def evaluate(self, x, y, batch_size=32, verbose=1,

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight)
   1028                               verbose=verbose, callbacks=callbacks,
   1029                               val_f=val_f, val_ins=val_ins, shuffle=shuffle,
-> 1030                               callback_metrics=callback_metrics)
   1031 
   1032     def evaluate(self, x, y, batch_size=32, verbose=1, sample_weight=None):

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/training.pyc in _fit_loop(self, f, ins, out_labels, batch_size, nb_epoch, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics)
    766                 batch_logs['size'] = len(batch_ids)
    767                 callbacks.on_batch_begin(batch_index, batch_logs)
--> 768                 outs = f(ins_batch)
    769                 if type(outs) != list:
    770                     outs = [outs]

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/backend/theano_backend.pyc in __call__(self, inputs)
    491     def __call__(self, inputs):
    492         assert type(inputs) in {list, tuple}
--> 493         return self.function(*inputs)
    494 
    495 

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/gof/link.pyc in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/scan_module/scan_op.pyc in rval(p, i, o, n, allow_gc)
    949         def rval(p=p, i=node_input_storage, o=node_output_storage, n=node,
    950                  allow_gc=allow_gc):
--> 951             r = p(n, [x[0] for x in i], o)
    952             for o in node.outputs:
    953                 compute_map[o][0] = True

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/scan_module/scan_op.pyc in <lambda>(node, args, outs)
    938                         args,
    939                         outs,
--> 940                         self, node)
    941         except (ImportError, theano.gof.cmodule.MissingGXX):
    942             p = self.execute

/Users/sidd/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/scan_perform.so in theano.scan_module.scan_perform.perform (/Users/sidd/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/mod.cpp:4316)()

/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/gof/link.pyc in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

/Users/sidd/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/scan_perform.so in theano.scan_module.scan_perform.perform (/Users/sidd/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/mod.cpp:4193)()

ValueError: Input dimension mis-match. (input[0].shape[1] = 14, input[1].shape[1] = 100)
Apply node that caused the error: Elemwise{switch,no_inplace}(<TensorType(int8, matrix)>, Elemwise{Composite{(clip((i0 + i1), i2, i3) * tanh(i4))}}[(0, 1)].0, <TensorType(float32, matrix)>)
Toposort index: 12
Inputs types: [TensorType(int8, matrix), TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(32, 14), (32, 100), (32, 100)]
Inputs strides: [(140, 1), (400, 4), (400, 4)]
Inputs values: ['not shown', 'not shown', 'not shown']
Outputs clients: [['output']]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/models.py", line 139, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/layers/recurrent.py", line 227, in call
    input_length=input_shape[1])
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 619, in rnn
    go_backwards=go_backwards)
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/theano/scan_module/scan.py", line 745, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/Users/sidd/Projects/virtualenv/nltk/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 608, in _step
    output = T.switch(mask, output, output_tm1)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,cpu,scan_fn}(Elemwise{minimum,no_inplace}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, lstm_1_U_o, lstm_1_U_f, lstm_1_U_i, lstm_1_U_c)
Toposort index: 373
Inputs types: [TensorType(int64, scalar), TensorType(float32, 3D), TensorType(int8, 3D), TensorType(float32, 3D), TensorType(float32, 3D), TensorType(float32, 3D), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(), (10, 32, 400), (10, 32, 14), (10, 32, 100), (11, 32, 100), (11, 32, 100), (100, 100), (100, 100), (100, 100), (100, 100)]
Inputs strides: [(), (1600, 16000, 4), (14, 140, 1), (12800, 400, 4), (12800, 400, 4), (12800, 400, 4), (400, 4), (400, 4), (400, 4), (400, 4)]
Inputs values: [array(10), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Subtensor{int64:int64:int8}(forall_inplace,cpu,scan_fn}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1})], [Subtensor{int64:int64:int64}(forall_inplace,cpu,scan_fn}.1, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1})], [Subtensor{int64:int64:int64}(forall_inplace,cpu,scan_fn}.2, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

Any idea why this is happening?

**Comment by fchollet** [comment]
You version of Keras must be outdated. This is the error you should be getting:

`Exception: Input 0 is incompatible with layer timedistributed_1: expected ndim=3, found ndim=4`

The TL;DR is this: `Embedding` is for sequences, with output ndim=3 (as specified in the docs), not for sequences of sequences. `TimeDistributed(Embedding())` is what you are looking for. As pointed out previously, it will do a couple operations that you don't actually need; if you care about this you should implement your own Embedding layer based on the original one.

Your model should be:

```
model = Sequential()
model.add(InputLayer(batch_input_shape=(BATCH_SIZE, STORY_MAX, SENTENCE_MAX), input_dtype='int32'))
model.add(TimeDistributed(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_SIZE, mask_zero=True)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(MEMORY_SIZE, return_sequences=True))
model.add(TimeDistributed(Dense(VOCAB_SIZE, activation='softmax')))

model.compile(optimizer='Adam', loss='categorical_crossentropy',
              metrics=['accuracy'])
```

This compiles and does what you expect. 

Also: update your Keras install to the master branch of the repo.

**Comment by fchollet** [comment]
PS: you don't actually the `InputLayer` layer; it isn't documented and isn't really meant as a user-facing layer. You can specify the batch size and input dtype via keyword arguments:

````python
model = Sequential()
model.add(TimeDistributed(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_SIZE, mask_zero=True), batch_input_shape=(BATCH_SIZE, STORY_MAX, SENTENCE_MAX), input_dtype='int32'))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(MEMORY_SIZE, return_sequences=True))
model.add(TimeDistributed(Dense(VOCAB_SIZE, activation='softmax')))
```

**Comment by braingineer** [comment]
@fchollet  thanks for the corrections!  

as a side note, would it be worthwhile to have an extra flag inside embedding, or another embedding class that does this style of ndim>2 embedding? This is the second github issue I've commented on that's been related to this.   Or, at the very least, maybe some documentation or a write-up describing the expected use case and adapting to additional use cases.  I could write either of these up later today.

**Comment by siddk** [comment]
Thanks a ton @fchollet - Everything works as expected.
