### ISSUE TITLE
Wrong documentation or regression found

### ISSUE THREAD

**Issue by inferrna** [fchollet/keras#2528]
master at c9f7d970e97d5af3f92a96cac75554aaf4261337
http://keras.io/layers/core/#dense

```python3
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras.models import Sequential
Using Theano backend.
>>> from keras.layers.core import Dense
>>> model = Sequential(Dense(32, input_dim=16))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Keras-1.0.1-py3.5.egg/keras/models.py", line 88, in __init__
    for layer in layers:
TypeError: 'Dense' object is not iterable
```

**Comment by joelthchao** [comment]
You can summit a pull request to correct document or make it more general.
```python
def __init__(self, layers=None, name=None):
    self.layers = []  # stack of layers
    self.model = None  # internal Model instance
    self.inputs = []  # tensors
    self.outputs = []  # tensors (length 1)

    # omit...
    
    # do some type check
    if layers is None:
        layers = []
    elif not isinstance(layers, list):
        layers = [layers]
    for layer in layers:
        self.add(layer)
```

**Comment by fchollet** [comment]
I fixed the docstring.
