### ISSUE TITLE
LookupError: No gradient defined for operation 'ResizeNearestNeighbor_2 When reproducing keras.blog.io autoencoder example

### ISSUE THREAD

**Issue by GPistre** [fchollet/keras#2747]
I was trying to run the example convolutional autoencoder showed here: http://blog.keras.io/ but the code, copied verbatim, seems to produce an error.
Both keras and tensorflow are up to date.
```
from keras.layers import Input, Convolution2D, MaxPooling2D, UpSampling2D
from keras.models import Model

input_img = Input(shape=(1, 28, 28))

x = Convolution2D(16, 3, 3, activation='relu', border_mode='same')(input_img)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
encoded = MaxPooling2D((2, 2), border_mode='same')(x)

# at this point the representation is (8, 4, 4) i.e. 128-dimensional

x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(encoded)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(16, 3, 3, activation='relu')(x)
x = UpSampling2D((2, 2))(x)
decoded = Convolution2D(1, 3, 3, activation='sigmoid', border_mode='same')(x)

autoencoder = Model(input_img, decoded)
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

from keras.datasets import mnist
import numpy as np

(x_train, _), (x_test, _) = mnist.load_data()

x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = np.reshape(x_train, (len(x_train), 1, 28, 28))
x_test = np.reshape(x_test, (len(x_test), 1, 28, 28))

autoencoder.fit(x_train, x_train,
                nb_epoch=50,
                batch_size=128,
                shuffle=True,
                validation_data=(x_test, x_test))
```

Results in : 

```
Traceback (most recent call last):
  File "", line 42, in <module>
    validation_data=(x_test, x_test))
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1037, in fit
    self._make_train_function()
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 663, in _make_train_function
    training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)
  File "/usr/local/lib/python2.7/site-packages/keras/optimizers.py", line 264, in get_updates
    grads = self.get_gradients(loss, params)
  File "/usr/local/lib/python2.7/site-packages/keras/optimizers.py", line 53, in get_gradients
    grads = K.gradients(loss, params)
  File "/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 684, in gradients
    return tf.gradients(loss, variables)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 395, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'ResizeNearestNeighbor_2' (op type: ResizeNearestNeighbor)
```

**Comment by fchollet** [comment]
Most likely you are just using an outdated version of TensorFlow. By the way you are not providing nearly enough information for us to be able to help you.
