### ISSUE TITLE
TensorBoard fails with latest version of Keras

### ISSUE THREAD

**Issue by paipai880429** [fchollet/keras#2749]
I am going through "[Building Autoencoders in Keras](http://blog.keras.io/index.html)" provided by @fchollet . When I want to reproduce the code of ``` Convolutional autoencoder ```, I get the following error:

```
Traceback (most recent call last):
  File "disturb_label.py", line 192, in <module>
    TensorBoard(log_dir='/tmp/disturb', histogram_freq=1)])
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 651, in fit_generator
    max_q_size=max_q_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1312, in fit_generator
    callbacks._set_model(callback_model)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 28, in _set_model
    callback._set_model(model)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 465, in _set_model
    tf_version = tuple(int(i) for i in tf.__version__.split('.'))
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 465, in <genexpr>
    tf_version = tuple(int(i) for i in tf.__version__.split('.'))
ValueError: invalid literal for int() with base 10: '0rc0'
```
It looks like ```callbacks.py``` is failing to parse the version of tensorflow?

My version of Keras and TensorFlow is 1.0.3 and 0.8.0rc0, respectively.

**Comment by paipai880429** [comment]
It is fixed by update TensorFlow ```pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl ```.
However, the version is still 0.8.0rc0, wondering.
