### ISSUE TITLE
ValueError when calling save_weights

### ISSUE THREAD

**Issue by markberger** [fchollet/keras#2817]
I am receiving an error when I'm trying to save a simple CNN. I updated to the master version of Keras and Theano, and that did not solve my problem.

Here is my code: https://gist.github.com/markberger/5b272dccc81e25e2ef87184b822ac5b0

Here is the traceback:

```
Traceback (most recent call last):
  File "conv.py", line 66, in <module>
    train()
  File "conv.py", line 63, in train
    save_model(model)
  File "conv.py", line 22, in save_model
    model.save_weights('model.h5', overwrite=True)
  File "...venv/lib/python2.7/site-packages/keras/engine/topology.py", line 2287, in save_weights
    g.attrs['weight_names'] = weight_names
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2536)
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/attrs.py", line 93, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/attrs.py", line 175, in create
    space = h5s.create_simple(shape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2536)
  File "h5py/h5s.pyx", line 101, in h5py.h5s.create_simple (/tmp/pip_build_root/h5py/h5py/h5s.c:1436)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)
```

**Comment by jbajor** [comment]
The issue was reported before: https://github.com/fchollet/keras/issues/2306

However, I do not agree with @fchollet 's solution. I have the latest stable hdf5 - 1.8.17 and newest h5py - 2.6.0. The problem occurs only on keras>=1.0.0, but does not on 0.3.3.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-014cab1fc01f> in <module>()
----> 1 model.save_weights("models/"+MODEL+".h5", overwrite=True)

/home/bajorjm/.pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/engine/topology.py in save_weights(self, filepath, overwrite)
   2303                     name = 'param_' + str(i)
   2304                 weight_names.append(name.encode('utf8'))
-> 2305             g.attrs['weight_names'] = weight_names
   2306             for name, val in zip(weight_names, weight_values):
   2307                 param_dset = g.create_dataset(name, val.shape,

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/gpfs22/home/bajorjm/h5py-2.6.0/h5py/_objects.c:2577)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/gpfs22/home/bajorjm/h5py-2.6.0/h5py/_objects.c:2536)()

/home/bajorjm/.pyenv/versions/3.5.1/lib/python3.5/site-packages/h5py-2.6.0-py3.5-linux-x86_64.egg/h5py/_hl/attrs.py in __setitem__(self, name, value)
     91         use the methods create() and modify().
     92         """
---> 93         self.create(name, data=value, dtype=base.guess_dtype(value))
     94
     95     @with_phil

/home/bajorjm/.pyenv/versions/3.5.1/lib/python3.5/site-packages/h5py-2.6.0-py3.5-linux-x86_64.egg/h5py/_hl/attrs.py in create(self, name, data, shape, dtype)
    173                 htype2 = None
    174
--> 175             space = h5s.create_simple(shape)
    176
    177             # This mess exists because you can't overwrite attributes in HDF5.

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/gpfs22/home/bajorjm/h5py-2.6.0/h5py/_objects.c:2577)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/gpfs22/home/bajorjm/h5py-2.6.0/h5py/_objects.c:2536)()

h5py/h5s.pyx in h5py.h5s.create_simple (/gpfs22/home/bajorjm/h5py-2.6.0/h5py/h5s.c:1436)()
```

**Comment by Vatshank** [comment]
hey @jbajor, were you able to resolve the issue?

**Comment by jbajor** [comment]
@Vatshank Unfortunately not. I am still using keras 0.3.3 because of this.

**Comment by Vatshank** [comment]
The code in #2306 in comment https://github.com/fchollet/keras/issues/2306#issuecomment-209646606 is working after upgrading to hdf5 1.8.12 and h5py 2.6.0 for keras 1.0 .
Maybe it is some other issue?
