### ISSUE TITLE
crash in standardize_input_data (with sparse_categorical_crossentropy) [regression]

### ISSUE THREAD

**Issue by cmyr** [fchollet/keras#2852]
as of 32b10a8,  `standardize_input_data` fails a shape check when using `sparse_categorical_crossentropy` and `TimeDistributed(Dense())`. 

```
Traceback (most recent call last):
  File "somewhere/keras/keras/models.py", line 496, in train_on_batch
    class_weight=class_weight)
  File "somewhere/keras/keras/engine/training.py", line 1162, in train_on_batch
    check_batch_dim=True)
  File "somewhere/keras/keras/engine/training.py", line 925, in _standardize_user_data
    exception_prefix='model target')
  File "somewhere/keras/keras/engine/training.py", line 104, in standardize_input_data
    str(array.shape))
Exception: Error when checking model target: expected activation_1 to have shape (None, 20, 100) but got array with shape (128, 20, 1)
```

I'll poke around when I get a chance, but I'm not very familiar with this area of the codebase.

**Comment by paul-felt** [comment]
I'm seeing this as well. I'm using the functional API with two discrete (sparse) outputs, fwiw.
