### ISSUE TITLE
Can't load weights

### ISSUE THREAD

**Issue by mlakhal** [fchollet/keras#2936]
I have a pretrained model, the code works fine. But, suddenly I couldn't load the weights and I am getting and error. I've checked around to figure out what was going on, and it seems that the file is open elsewhere, the problem is that it is actually not open before the call.  
Here's what I am getting:
`model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2318, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-T2GP4U/h5py/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-T2GP4U/h5py/h5py/_objects.c:2536)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-build-T2GP4U/h5py/h5py/h5f.c:1811)
IOError: Unable to open file (Unable to find a valid file signature)`

**Comment by DaveRichmond-** [comment]
Hi mlakhal,

I'm having the same problem that you described above.  I see that you closed the issue.  Could you let me know how you resolved this?

Thanks!
Dave

**Comment by fchollet** [comment]
This appears to be a file corruption issue. You should probably save the model again to a new file.

**Comment by DaveRichmond-** [comment]
Hi Francois,

Thanks so much for your response.  Unfortunately, re-downloading the weights file (YOLO_small.ckpt) doesn't seem to help.  I don't think that the file is corrupted because I have some tensorflow code that will initialize a model from these weights with no problem.

I'm in the process of trying a different work around (I found the trained weights in a different format that I can read and then write into my keras model (hopefully) without too much work).  But just so that I'm clear, should the following command:

model.load_weights('weights.ckpt'), 

work for reading weights from a tensorflow checkpoint file into a keras model?

Thanks again for your help!

Best,
Dave

**Comment by mrgloom** [comment]
Trying to load vgg16 pretrained model: https://keras.io/applications/#vgg16
But getting error:

```
    vgg16= keras.applications.vgg16.VGG16(include_top=False, weights='imagenet', input_shape=(224,224,3))
  File "/usr/local/lib/python2.7/dist-packages/keras/applications/vgg16.py", line 169, in VGG16
    model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2532, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-nCYoKW-build/h5py/h5f.c:2117)
IOError: Unable to open file (File signature not found)
```

```
pip show keras
Name: Keras
Version: 2.0.4
Summary: Deep Learning for Python
Home-page: https://github.com/fchollet/keras
Author: Francois Chollet
Author-email: francois.chollet@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: theano, pyyaml, six
```

```
pip show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.1.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: werkzeug, six, wheel, numpy, mock, protobuf
```

```
pip show h5py
Name: h5py
Version: 2.7.0
Summary: Read and write HDF5 files from Python
Home-page: http://www.h5py.org
Author: Andrew Collette
Author-email: andrew.collette@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: numpy, six
```

**Comment by mrgloom** [comment]
Problem was that for some reason it can't download models and they were just 11kb, so I downloaded them manually from https://github.com/fchollet/deep-learning-models/releases and put into /home/myuser/.keras/models

**Comment by amelie711** [comment]
same problem，I cleared the cache, but the problem still persists
`    def _define_model(output_layer=-1):
        '''Define a pre-trained MobileNet model.

        Args:
            output_layer: the number of layer that output.

        Returns:
            Class of keras model with weights.
        '''
        base_model = MobileNet(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
        output = base_model.layers[output_layer].output
        output = GlobalAveragePooling2D()(output)
        model = Model(inputs=base_model.input, outputs=output)
        return model`

the result
`Traceback (most recent call last):
  File "run.py", line 50, in <module>
    result = similarity.extract_feature_multi(xiaozhu)
  File "/home/ec2-user/image_feature/main_image.py", line 182, in extract_feature_multi
    self._model = DeepModel()
  File "/home/ec2-user/image_feature/model_util.py", line 16, in __init__
    self._model = self._define_model()
  File "/home/ec2-user/image_feature/model_util.py", line 31, in _define_model
    base_model = MobileNet(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
  File "/usr/lib/python3.6/site-packages/tensorflow/python/keras/applications/__init__.py", line 70, in wrapper
    return base_fun(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/keras/applications/mobilenet.py", line 32, in MobileNet
    return mobilenet.MobileNet(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/keras_applications/mobilenet.py", line 320, in MobileNet
    model.load_weights(weights_path)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1510, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/lib64/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/usr/lib64/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`
