### ISSUE TITLE
Error saving the model keras.__version__=1.0.3

### ISSUE THREAD

**Issue by akmahaja** [fchollet/keras#2946]
```
Traceback (most recent call last):
 File "trainer.py", line 61, in <module>
 create_training_features(input_file, en_parse_file)
 File "trainer.py", line 49, in create_training_features
 json_string =model.to_json()
 File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2373, in to_json
 return json.dumps(model_config, default=get_json_type, **kwargs)
 File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
 sort_keys=sort_keys, **kw).encode(obj)
 File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
 chunks = self.iterencode(o, _one_shot=True)
 File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
 return _iterencode(o, 0)
 UnicodeDecodeError: 'utf8' codec can't decode byte 0x8f in position 169: invalid start byte
```

I upgraded the keras to 1.0.3 and since then it has started giving me this error. Earlier was 0.3.3, however it is running fine on another system with keras 1.0.3 version. Unable to figure out the issue.

**Comment by cWren0110** [comment]
I am getting a similar error, was there ever a resolution to this? Are you by chance running on windows and creating at least one layer using a lambda function?
