### ISSUE TITLE
Error loading the models with custom layers

### ISSUE THREAD

**Issue by akmahaja** [fchollet/keras#2952]
Keras throw the following issue when I try to add the custom layer information while loading the model. 

I am using the following code to add the custom layers, where DropoutMask and Denser are the name of the classes. What here is causing the issue?
    
    model = model_from_json(open(util.model).read(),custom_objects={'DropoutMask': DropoutMask,'Denser':Denser})

    Traceback (most recent call last):
    File "denser_classifier.py", line 305, in <module>
     predict(relations_file, en_parse_file, outfile)
    File "denser_classifier.py", line 251, in predict
     model = model_from_json(open(util.model).read(),custom_objects={'DropoutMask':   DropoutMask,'Denser':Denser})
    File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 37, in model_from_json
     return layer_from_config(config, custom_objects=custom_objects)
    File "/usr/local/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
     return layer_class.from_config(config['config'])
    File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2199, in from_config
     custom_objects=custom_objects)
    File "/usr/local/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
     return layer_class.from_config(config['config'])
    File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 898, in from_config
     return cls(**config)
     TypeError: __init__() takes at least 2 arguments (11 given)

**Comment by akmahaja** [comment]
I figured out the issue. It was the get_config function missing the newly added configuration items.

**Comment by scatterbrain333** [comment]
I am experiencing the same problem. how did you solve it?

**Comment by akmahaja** [comment]
It has been a long time since I have touched this piece of code, but I think I have already answered the solution to this issue that I was facing. However the errors in KERAS are not very informative, so you might be getting this issue because of some other issue. Try checking for the  **get_config** function in the **newly added configuration items in your model**
