### ISSUE TITLE
Can't load a batch normalization layer twice

### ISSUE THREAD

**Issue by henry0312** [fchollet/keras#2954]
It's strange that somewhere in global keep the status of BatchNormalization🤔

## Error

```
» python bn2.py
Using Theano backend.
1.0.4
1st loading
2nd loading
Traceback (most recent call last):
  File "bn2.py", line 31, in <module>
    b = model_from_json(json_string)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/models.py", line 36, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/utils/layer_utils.py", line 35, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/models.py", line 784, in from_config
    model.add(layer)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/models.py", line 145, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/layers/normalization.py", line 116, in call
    raise Exception('You are attempting to share a '
Exception: You are attempting to share a same `BatchNormalization` layer across different data flows. This is not possible. You should use `mode=2` in `BatchNormalization`, which has a similar behavior but is shareable (see docs for a description of the behavior).
```

## Sample code
https://gist.github.com/henry0312/f379dc2e2d2c02258405d0bc5dfb192a

**Comment by fchollet** [comment]
When you are doing, you are creating models where layers have identical names, and subsequently where variables have the same name. Variables belong in a global state where they are addressed by name, so reusing a name means reusing the same variable.

This is not managed by Keras, this is managed by TensorFlow and Theano (which have the same behavior).

So what you are doing is building two identical models with shared weights. I agree this might be counter-intuitive. There should probably be an option to override the names and make them unique.

**Comment by fchollet** [comment]
You're right, that's an issue. Working on it.

**Comment by fchollet** [comment]
This is fixed. Thank you for the bug report.

**Comment by henry0312** [comment]
works fine. thank you.

**Comment by alyato** [comment]
@henry0312 ,i meet the same error in the latest version. MY keras is 1.1.1 and i want to implemetn the ResNet,refer to resnet_cifar10.py.
