### ISSUE TITLE
unrolling recurrent networks causes theano optimization error

### ISSUE THREAD

**Issue by ReallyCoolName** [fchollet/keras#2976]
Just reinstalled theano+keras to make sure. I've tried a few things and it seems the problem only happens when the RNN being unrolled is before a `RepeatVector` layer (unrolling a network after the `RepeatVector` doesn't cause any problem).

My code:
```
embedding_models =[]
for _ in xrange(n_simultaneous):
    embedding_models += [Sequential()]
    embedding_models[-1].add(Embedding(28,2,batch_input_shape=(b_sz,50 )))

model.add(Merge(embedding_models,mode='concat'))
model.add(GRU(10,stateful=True,unroll=True,return_sequences=True))
model.add(Flatten())
model.add(RepeatVector(10))
model.add(GRU(10,stateful=True,unroll=False,return_sequences=True))
model.add(TimeDistributedDense(180,activation='softmax'))'''
model.compile(loss=categorial_ce, optimizer='rmsprop',metrics=['accuracy'])
X_train,Y_train = get_batch()
model.fit(X_train, Y_train, batch_size=b_sz, nb_epoch=4, verbose=1,validation_split=v_splt)```


The error: (50 times `TensorConstant{10}` if anyone's wondering. probably number of timesteps. And no, `config.mode` is not `FAST_COMPILE`, is `Mode`, which is equivalent to `FAST_RUN`):


```ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10}, TensorConstant{10})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/tensor/opt.py", line 5827, in constant_folding
    required = thunk()
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 912, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 839, in perform
    super(Elemwise, self).perform(node, inputs, output_storage)
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 769, in perform
    "Did you used Theano flags mode=FAST_COMPILE?"
MethodNotDefined: ('perform', <class 'theano.tensor.elemwise.Elemwise'>, 'Elemwise', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')

ERROR (theano.gof.opt): Optimization failure due to: local_mul_zero
ERROR (theano.gof.opt): node: Elemwise{mul,no_inplace}(TensorConstant{50}, Elemwise{switch,no_inplace}.0, Elemwise{switch,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/tensor/opt.py", line 5193, in local_mul_zero
    value = get_scalar_constant_value(i)
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/tensor/basic.py", line 660, in get_scalar_constant_value
    for i in v.owner.inputs]
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/tensor/basic.py", line 662, in get_scalar_constant_value
    v.owner.op.perform(v.owner, const, ret)
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 839, in perform
    super(Elemwise, self).perform(node, inputs, output_storage)
  File "/home/azureuser/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 769, in perform
    "Did you used Theano flags mode=FAST_COMPILE?"
MethodNotDefined: ('perform', <class 'theano.tensor.elemwise.Elemwise'>, 'Elemwise', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')```

I'd try to help, but I spent all my sanity during the weekend trying to debug my implementation of a neural tensor network.

**Comment by nouiz** [comment]
Could this be caused by the python stack limit:

Do this before importing theano:
import sys
sys.setrecursionlimit(10000)

see: https://github.com/fchollet/keras/issues/2489

Maybe the error is the wrong one. I don't understand why this error would appear if it run with scan but give this error in the unrolled version.

**Comment by fchollet** [comment]
> I've tried a few things and it seems the problem only happens when the RNN being unrolled is before a RepeatVector layer (unrolling a network after the RepeatVector doesn't cause any problem).

I somehow doubt this could have anything to do with the following op. If you have managed to unroll the RNN, what you get is a 2D tensor, and the next ops are independent from the series of ops that resulted in that tensor.

Issues with unrolling Theano RNNs are something I've seen before. I don't know the exact cause and I don't know a good workaround. You should either:
- use scan (`unroll`=False)
- use TF (which is pretty good at unrolling RNNs on arbitrarily long sequences albeit pretty slow at runtime)
- reduce the length of the sequences until Theano unrolling works

**Comment by ReallyCoolName** [comment]
@nouiz  Not a recursion limit problem - I already had that problem (gave me a different error), and I increased the recursion limit.

@fchollet length isn't that big, though I guess it was pretty dumb of me to assume `RepeatVector` has anything to do with the problem (though lately I haven't had much time to think)

guess I should close this for now, since you're aware of the problem and it's not that important
