### ISSUE TITLE
AssertionError When I stack Autoencoder with TimeDistributed Layer

### ISSUE THREAD

**Issue by chbrian** [fchollet/keras#2984]
I'm using an autoencoder followed by a timedistributed layer. However, I met with an AssertionError.

```
Traceback (most recent call last):
  File "test3.py", line 115, in <module>
    model.fit(x_train, y_train, batch_size=batch_size, validation_split=0.05, nb_epoch=1, shuffle=True)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/keras/engine/training.py", line 1022, in fit
    self._make_test_function()
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/keras/engine/training.py", line 686, in _make_test_function
    **self._function_kwargs)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 528, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 514, in __init__
    **kwargs)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/compile/function.py", line 322, in function
    output_keys=output_keys)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1827, in orig_function
    output_keys=output_keys).create(
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1507, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/gof/opt.py", line 102, in __call__
    return self.optimize(fgraph)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/gof/opt.py", line 90, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/gof/opt.py", line 233, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/gof/opt.py", line 86, in optimize
    self.add_requirements(fgraph)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1434, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/gof/fg.py", line 566, in attach_feature
    attach(self)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1261, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1314, in on_import
    self.set_shape(r, s)
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1113, in set_shape
    shape_vars.append(self.unpack(s[i]))
  File "/home/xiaoyong/xiaoyong/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 1035, in unpack
    assert s_i >= 0
AssertionError
```

My model:

```
activation = LeakyReLU(alpha=0.3)

input_model = Input(shape=(timestamp, gene_classes,))
model0 = BatchNormalization()(input_model)
model1 = Convolution1D(512, 3, activation='relu', border_mode='same', W_regularizer=l2(0.01))(model0)
encoded = MaxPooling1D(pool_length=2, border_mode='same')(model1)
model2 = Convolution1D(512, 3, activation='relu', border_mode='same', W_regularizer=l2(0.01))(encoded)
decoded = UpSampling1D(length=2)(model2)
model3 = TimeDistributed(Dense(64, activation='relu'))(decoded)
model3 = BatchNormalization()(model3)
model3 = Dropout(0.5)(model3)
model3 = TimeDistributed(Dense(30, activation='softmax'))(model3)
model = Model(input_model, model3)
sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True, clipvalue=2)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=["accuracy"])
```

Thank you.

**Comment by bizso09** [comment]
getting same error, tried a few variations of the model, with Sequential, Functional API, Reshapes, Inputs ... 

```
    self.mod.fit([self.texts, self.meta], self.tar)
  File "C:\Python27\lib\site-packages\keras\engine\training.py", line 1037, in fit
    self._make_train_function()
  File "C:\Python27\lib\site-packages\keras\engine\training.py", line 670, in _make_train_function
    **self._function_kwargs)
  File "C:\Python27\lib\site-packages\keras\backend\theano_backend.py", line 528, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Python27\lib\site-packages\keras\backend\theano_backend.py", line 514, in __init__
    **kwargs)
  File "C:\Python27\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Python27\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\Python27\lib\site-packages\theano\compile\function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "C:\Python27\lib\site-packages\theano\compile\function_module.py", line 1456, in __init__
    optimizer_profile = optimizer(fgraph)
  File "C:\Python27\lib\site-packages\theano\gof\opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "C:\Python27\lib\site-packages\theano\gof\opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Python27\lib\site-packages\theano\gof\opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Python27\lib\site-packages\theano\gof\opt.py", line 85, in optimize
    self.add_requirements(fgraph)
  File "C:\Python27\lib\site-packages\theano\tensor\opt.py", line 1438, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\Python27\lib\site-packages\theano\gof\fg.py", line 621, in attach_feature
    attach(self)
  File "C:\Python27\lib\site-packages\theano\tensor\opt.py", line 1262, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\Python27\lib\site-packages\theano\tensor\opt.py", line 1315, in on_import
    self.set_shape(r, s)
  File "C:\Python27\lib\site-packages\theano\tensor\opt.py", line 1114, in set_shape
    shape_vars.append(self.unpack(s[i]))
  File "C:\Python27\lib\site-packages\theano\tensor\opt.py", line 1036, in unpack
    assert s_i >= 0
AssertionError
```
```

        inp1 = Input(shape=(3, 3), dtype='int32')
        m1 = Flatten()(inp1)
        m1 = Embedding(input_dim=25, 
                                 output_dim=25,
                                 mask_zero=False,
                                 input_length=3*3)(m1)
        m1 = Convolution1D(nb_filter=25, 
                                     filter_length=3, 
                                     activation="relu",
                                     border_mode="same")(m1)
        m1 = MaxPooling1D(pool_length=3, border_mode="same")(m1)

        inp2 = Input(shape=(3, 1))
        mod = merge([m1, inp2], mode = "concat", concat_axis=2)
        mod = LSTM(output_dim=25, return_sequences=False)(mod)
        mod = Dense(1, activation="sigmoid")(mod)
        
        mod = Model(input=[inp1, inp2], output=mod)
        mod.compile(optimizer="rmsprop", loss='binary_crossentropy', metrics=['accuracy'])
```

**Comment by bizso09** [comment]
Tried a different architecture yet again, this time I'm getting a different error
```

Traceback (most recent call last):
    conv = TimeDistributed(conv)(timed_text_input)
  File "C:\Python27\lib\site-packages\keras\layers\wrappers.py", line 84, in __init__
    super(TimeDistributed, self).__init__(layer, **kwargs)
  File "C:\Python27\lib\site-packages\keras\layers\wrappers.py", line 9, in __init__
    self.uses_learning_phase = layer.uses_learning_phase
AttributeError: 'TensorVariable' object has no attribute 'uses_learning_phase'

```

**Comment by nouiz** [comment]
The first error is from Theano. Can you update to Theano dev vesrion?

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

The second one is from keras.

**Comment by Grzego** [comment]
I had the same error. Removing `border_mode='same'` from `MaxPooling1D` solved it for me.
