### ISSUE TITLE
word2vec model 'merge' layer error

### ISSUE THREAD

**Issue by shashankg7** [fchollet/keras#3006]
I am trying to train a word2vec skipgram model. I have written the following model for the same:

```
    model1 = Sequential()
    model1.add(Embedding(90000, 100))
    #model1.add(Reshape(100,))

    model2 = Sequential()
    model2.add(Embedding(90000, 100))
    #model2.add(Reshape(100,))

    model = Sequential()
    model.add(Merge([model1, model2], mode='dot'))
    model.add(Activation('sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    X = np.array(self.skg[0])
    y = np.array(self.skg[1])
    pdb.set_trace()
    Xc = X[:, 0]
    Xw = X[:, 1]
    Xc = map(lambda x:x[0], Xc)
    Xw = map(lambda x:x[0], Xw)
    model.fit([Xc, Xw], y, batch_size=32, nb_epoch=10, shuffle='batch')
```

Xc is list of indices for main word and Xw is list of indices for context word. When I run this model I am getting the following error :

File "preprocess.py", line 69, in word2vec
    model.add(Merge([model1, model2], mode='dot'))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1119, in **init**
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 155, in create_node
    output_shapes = to_list(outbound_layer.get_output_shape_for(input_shapes))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1308, in get_output_shape_for
    tensordot_output = np.tensordot(np.zeros(tuple(shape1[1:])),
TypeError: an integer is required

Now I am not sure what this means.

**Comment by maxbry** [comment]
What is represented by `y` in your case? In my eyes, `word2vec` is an unsupervised method. What is your target?

**Comment by shashankg7** [comment]
y is label for word pairs. It is 1 if the pair is within same context and 0 if a pair does not belongs to same context window.

**Comment by nzw0301** [comment]
In my experiment for skip-gram and negative-samping, I wrote below.

```
model1 = Sequential()
model1.add(Embedding(90000, 100, input_length=1))


model2 = Sequential()
model2.add(Embedding(90000, 100, input_length=1))

model = Sequential()
model.add(Merge([model1, model2], mode='dot', dot_axes=2))
model.add(Reshape((1,), input_shape=(1,1)))
model.add(Activation('sigmoid'))
```

[full code](https://github.com/nzw0301/keras-examples/blob/master/Skip-gram-with-NG.ipynb)

**Comment by tokestermw** [comment]
I have the same issue with the Functional API.

Here is my code:

```
from keras.layers import Input, Dense, merge, Flatten, Layer, Reshape
from keras.layers.embeddings import Embedding
from keras.models import Model

maxlen = 1
embedding_size = 100
vocab_size = 40000

# -- 
context_input = Input(shape=(maxlen, ), dtype='int32', name='context')
embedding_layer_context = Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=(maxlen, ))(context_input)

target_input = Input(shape=(maxlen, ), dtype='int32', name='target')
embedding_layer_target = Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=(maxlen, ))(target_input)

merge_layer = merge([embedding_layer_context, embedding_layer_target], mode='dot', dot_axes=(1, 1))
```

and then the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-6311c4e3085c> in <module>()
     14 embedding_layer_target = Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=(maxlen, ))(target_input)
     15 
---> 16 merge_layer = merge([embedding_layer_context, embedding_layer_target], mode='dot', dot_axes=(1, 1))

/usr/local/lib/python2.7/site-packages/keras/engine/topology.pyc in merge(inputs, mode, concat_axis, dot_axes, output_shape, output_mask, name)
   1462                             node_indices=node_indices,
   1463                             tensor_indices=tensor_indices,
-> 1464                             name=name)
   1465         return merge_layer.inbound_nodes[0].output_tensors[0]
   1466     else:

/usr/local/lib/python2.7/site-packages/keras/engine/topology.pyc in __init__(self, layers, mode, concat_axis, dot_axes, output_shape, output_mask, node_indices, tensor_indices, name)
   1121                                        node_indices, tensor_indices)
   1122             self.built = True
-> 1123             self.add_inbound_node(layers, node_indices, tensor_indices)
   1124         else:
   1125             self.built = False

/usr/local/lib/python2.7/site-packages/keras/engine/topology.pyc in add_inbound_node(self, inbound_layers, node_indices, tensor_indices)
    541         # creating the node automatically updates self.inbound_nodes
    542         # as well as outbound_nodes on inbound layers.
--> 543         Node.create_node(self, inbound_layers, node_indices, tensor_indices)
    544 
    545     def get_output_shape_for(self, input_shape):

/usr/local/lib/python2.7/site-packages/keras/engine/topology.pyc in create_node(cls, outbound_layer, inbound_layers, node_indices, tensor_indices)
    153             output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
    154             output_masks = to_list(outbound_layer.compute_mask(input_tensors, input_masks))
--> 155             output_shapes = to_list(outbound_layer.get_output_shape_for(input_shapes))
    156 
    157         if not output_tensors or output_tensors[0] is None:

/usr/local/lib/python2.7/site-packages/keras/engine/topology.pyc in get_output_shape_for(self, input_shape)
   1310             shape2 = list(input_shapes[1])
   1311             dot_axes = [a - 1 for a in self.dot_axes]
-> 1312             tensordot_output = np.tensordot(np.zeros(tuple(shape1[1:])),
   1313                                             np.zeros(tuple(shape2[1:])),
   1314                                             axes=dot_axes)

TypeError: an integer is required
```

I had this issue before with the previous Graph API. Something to do with multiple Embedding layers in a multiple input network.
https://github.com/fchollet/keras/issues/1409#issuecomment-169790026
