### ISSUE TITLE
no histogram in tensorboard, keras 1.0.4, tensorflow 0.8

### ISSUE THREAD

**Issue by benwu232** [fchollet/keras#3026]
Hi,

I'm now using keras 1.0.4 + tensorflow 0.8. In my tensorboard, I can see accuracy, loss in 'events' tab, but the 'histograms' tab is always empty. 

I'm using fit_generator, here is the code:

tensorboard = keras.callbacks.TensorBoard(log_dir=mydir.tb_log, histogram_freq=1, write_graph=True)
history = self.model.fit_generator(train_generator, samples_per_epoch=samples_per_epoch,
                                          nb_epoch=pars['nb_epoch'],
                                          verbose=2,
                                          callbacks=[tensorboard],
                                          validation_data=validate_generator, nb_val_samples=nb_val_samples,
                                          class_weight=pars['class_weight'])

I debugged into _set_model in callbacks.py, at about line 455, I get variables like below:
layer: <keras.layers.core.Dense object at 0x7f668c8a74d0>
'{}_W'.format(layer): '<keras.layers.core.Dense object at 0x7f668c8a74d0>_W'
'{}_b'.format(layer): '<keras.layers.core.Dense object at 0x7f668c8a74d0>_b'
'{}_out'.format(layer): '<keras.layers.core.Dense object at 0x7f668c8a74d0>_out'

Are these right? I think 'layer' should be a string, but here it is an object. I saw fig_generator has some issues with tensorboard, are them solved?

Thanks a lot!

**Comment by benwu232** [comment]
I just try tensorboard on the mnist_mlp.py

I changed the code like this:

tensorboard = keras.callbacks.TensorBoard(log_dir='./tb_log', histogram_freq=1, write_graph=True)
history = model.fit(X_train, Y_train,
                    batch_size=batch_size, nb_epoch=nb_epoch,
                    verbose=1, validation_data=(X_test, Y_test), callbacks=[tensorboard])

When I run it. There is something wrong. Here are the messages:

Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
60000 train samples
10000 test samples
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 870M
major: 3 minor: 0 memoryClockRate (GHz) 0.967
pciBusID 0000:01:00.0
Total memory: 3.00GiB
Free memory: 2.84GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 870M, pci bus id: 0000:01:00.0)
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
dense_1 (Dense)                  (None, 512)           401920      dense_input_1[0][0]              
____________________________________________________________________________________________________
activation_1 (Activation)        (None, 512)           0           dense_1[0][0]                    
____________________________________________________________________________________________________
dropout_1 (Dropout)              (None, 512)           0           activation_1[0][0]               
____________________________________________________________________________________________________
dense_2 (Dense)                  (None, 512)           262656      dropout_1[0][0]                  
____________________________________________________________________________________________________
activation_2 (Activation)        (None, 512)           0           dense_2[0][0]                    
____________________________________________________________________________________________________
dropout_2 (Dropout)              (None, 512)           0           activation_2[0][0]               
____________________________________________________________________________________________________
dense_3 (Dense)                  (None, 10)            5130        dropout_2[0][0]                  
____________________________________________________________________________________________________
activation_3 (Activation)        (None, 10)            0           dense_3[0][0]                    
====================================================================================================
Total params: 669706
____________________________________________________________________________________________________
Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 4s - loss: 0.2426 - acc: 0.9247 - val_loss: 0.1035 - val_acc: 0.9691
Epoch 2/20
60000/60000 [==============================] - 3s - loss: 0.1005 - acc: 0.9696 - val_loss: 0.0927 - val_acc: 0.9721
Epoch 3/20
59776/60000 [============================>.] - ETA: 0s - loss: nan - acc: 0.9528Traceback (most recent call last):
  File "/home/wb/study/qute/prj/qute/src/experimental/keras_minst_mlp.py", line 58, in <module>
    verbose=1, validation_data=(X_test, Y_test), callbacks=[tensorboard])
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/models.py", line 408, in fit
    sample_weight=sample_weight)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/engine/training.py", line 1053, in fit
    callback_metrics=callback_metrics)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/engine/training.py", line 812, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/callbacks.py", line 39, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/callbacks.py", line 489, in on_epoch_end
    result = self.sess.run([self.merged], feed_dict=feed_dict)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Nan in summary histogram for: HistogramSummary
	 [[Node: HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](HistogramSummary/tag, dense_1_W/read/_676)]]
Caused by op u'HistogramSummary', defined at:
  File "/home/wb/study/qute/prj/qute/src/experimental/keras_minst_mlp.py", line 58, in <module>
    verbose=1, validation_data=(X_test, Y_test), callbacks=[tensorboard])
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/models.py", line 408, in fit
    sample_weight=sample_weight)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/engine/training.py", line 1053, in fit
    callback_metrics=callback_metrics)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/engine/training.py", line 754, in _fit_loop
    callbacks._set_model(callback_model)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/callbacks.py", line 28, in _set_model
    callback._set_model(model)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/keras/callbacks.py", line 457, in _set_model
    tf.histogram_summary('{}_W'.format(layer), layer.W)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/ops/logging_ops.py", line 113, in histogram_summary
    tag=tag, values=values, name=scope)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 55, in _histogram_summary
    name=name)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

Process finished with exit code 1

**Comment by bbitmaster** [comment]
I am also encountering this issue. It seems TensorBoard isn't working with fit_generator. I believe the reason for the failure is on [line 475 of callbacks.py] (https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L475), self.model.validation_data is None when this executes with fit_generator.

I think the only way to fix this is to rewrite the code to work with a generator for validation data. I'm confused though, because looking at old issues and even the unit tests for tensorboard, I get the impression that it was working with fit_generator at some point in the past.

Anyway, hope this helps anyone who wants to take a crack at fixing this issue.

**Comment by benwu232** [comment]
https://github.com/fchollet/keras/issues/3100

just open another issue about this problem.
@bbitmaster
