### ISSUE TITLE
ValueError: 'this shared variable already has an update expression' with babi_memnn.py

### ISSUE THREAD

**Issue by StevenLOL** [fchollet/keras#3082]
```
python ./babi_memnn.py 

Using Theano backend.
Using gpu device 0: GeForce GTX 960M (CNMeM is disabled, cuDNN 4007)
Extracting stories for the challenge: single_supporting_fact_10k
-
Vocab size: 22 unique words
Story max length: 68 words
Query max length: 4 words
Number of training stories: 10000
Number of test stories: 1000
-
Here's what a "story" tuple looks like (input, query, answer):
([u'Mary', u'moved', u'to', u'the', u'bathroom', u'.', u'John', u'went', u'to', u'the', u'hallway', u'.'], [u'Where', u'is', u'Mary', u'?'], u'bathroom')
-
Vectorizing the word sequences...
-
inputs: integer tensor of shape (samples, max_length)
inputs_train shape: (10000, 68)
inputs_test shape: (1000, 68)
-
queries: integer tensor of shape (samples, max_length)
queries_train shape: (10000, 4)
queries_test shape: (1000, 4)
-
answers: binary (1 or 0) tensor of shape (samples, vocab_size)
answers_train shape: (10000, 22)
answers_test shape: (1000, 22)
-
Compiling...
Traceback (most recent call last):
  File "./babi_memnn.py", line 209, in <module>
    validation_data=([inputs_test, queries_test, inputs_test], answers_test))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.4-py2.7.egg/keras/models.py", line 408, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.4-py2.7.egg/keras/engine/training.py", line 1052, in fit
    self._make_train_function()
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.4-py2.7.egg/keras/engine/training.py", line 677, in _make_train_function
    **self._function_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.4-py2.7.egg/keras/backend/theano_backend.py", line 541, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.4-py2.7.egg/keras/backend/theano_backend.py", line 527, in __init__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 322, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 443, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 188, in rebuild_collect_shared
    (store_into, update_d[store_into]))
ValueError: ('this shared variable already has an update expression', (embedding_2_W, GpuFromHost.0))

```

I got this error on my desktop (GT960 2GB) as well on my labptop GTX 960m 4GB.

**There is no problem when running babi_rnn.py**

keras 1.0.4
nvcc 7.5
theano  0.7.0 / 0.8.0

**Comment by fchollet** [comment]
Fixed it; thanks for the report.

**Comment by samevers** [comment]
so what is the solution finally? O_O
