### ISSUE TITLE
Error runing mnist_siamese_graph example

### ISSUE THREAD

**Issue by logaritmisk** [fchollet/keras#3131]
Hi,

Tried to run the `mnist_siamese_graph.py` examle but got an error. Found this issue #2677, but it seems that was fixed in this commit 8327b37a0bd84290a6646692e2e75f45fba646e5 so I guess this is different problem.

```shell
$ python mnist_siamese_graph.py                
Using Theano backend.
Traceback (most recent call last):
  File "mnist_siamese_graph.py", line 111, in <module>
    distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([processed_a, processed_b])
  File "/path/to/project/.venv/lib/python3.4/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/path/to/project/.venv/lib/python3.4/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/path/to/project/.venv/lib/python3.4/site-packages/keras/engine/topology.py", line 173, in create_node
    str(output_masks))
Exception: The `compute_mask` method of layer "lambda_1" should return one mask tensor per output tensor of the layer. Found: [None, None]
```

```shell
$ pip list
Keras (1.0.5)
numpy (1.11.1)
pip (8.1.2)
protobuf (3.0.0b2)
PyYAML (3.11)
scipy (0.17.1)
setuptools (24.0.0)
six (1.10.0)
tensorflow (0.9.0)
Theano (0.9.0.dev1)
wheel (0.29.0)
```

**Comment by fchollet** [comment]
Right. I fixed it, thanks for the report.

**Comment by ttthhh** [comment]
Still getting same error...
