### ISSUE TITLE
LocallyConnected layer only working on cpu

### ISSUE THREAD

**Issue by Simoncarbo** [fchollet/keras#3137]
Hi,

I'm trying to use the recently added local layers (keras/keras/layers/local.py). Training the exact same network with the same script works on cpu but not on gpu (CUDA, with or without CuDNN). I'm using Theano backend. I had no problems with gpu before. I suppose the problem lies in the local layers implementation.

Issue script:
```
import numpy.random as random

from keras.models import Sequential
import keras.layers as layers
from keras.optimizers import SGD


model = Sequential()
   
model.add(layers.ZeroPadding2D(padding=(1, 1),input_shape = (1,10,14))) 
model.add(layers.LocallyConnected2D(2,3,3,activation = 'relu',border_mode = 'valid'))

model.add(layers.Flatten())
model.add(layers.Dense(1, activation = 'sigmoid'))

model.compile(optimizer = SGD(lr = 0.001, momentum = 0.1, decay = 0.0), loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

model.fit(random.rand(10,1,10,14),random.rand(10,1), batch_size = 1,nb_epoch = 5)
```

**with cpu:**
```
Using Theano backend.
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
zeropadding2d_1 (ZeroPadding2D)  (None, 1, 12, 16)     0           zeropadding2d_input_1[0][0]      
____________________________________________________________________________________________________
locallyconnected2d_1 (LocallyConn(None, 2, 10, 14)     2800        zeropadding2d_1[0][0]            
____________________________________________________________________________________________________
flatten_1 (Flatten)              (None, 280)           0           locallyconnected2d_1[0][0]       
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 1)             281         flatten_1[0][0]                  
====================================================================================================
Total params: 3081
____________________________________________________________________________________________________
Epoch 1/5
10/10 [==============================] - 0s - loss: 0.6649 - acc: 0.0000e+00     
Epoch 2/5
10/10 [==============================] - 0s - loss: 0.6631 - acc: 0.0000e+00     
Epoch 3/5
10/10 [==============================] - 0s - loss: 0.6613 - acc: 0.0000e+00     
Epoch 4/5
10/10 [==============================] - 0s - loss: 0.6598 - acc: 0.0000e+00     
Epoch 5/5
10/10 [==============================] - 0s - loss: 0.6582 - acc: 0.0000e+00  
```
**with gpu:**
```
Traceback (most recent call last):

  File "<ipython-input-3-da4ca203c2ba>", line 1, in <module>
    runfile('*/test_issue.py', wdir='*')

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Simon/Documents/Projets Data Science/Ultrasound Nerve Segmentation- Kaggle/test_issue.py", line 25, in <module>
    model.fit(random.rand(10,1,10,14),random.rand(10,1), batch_size = 1,nb_epoch = 5)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\keras\models.py", line 413, in fit
    sample_weight=sample_weight)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\keras\engine\training.py", line 1081, in fit
    self._make_train_function()

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\keras\engine\training.py", line 705, in _make_train_function
    **self._function_kwargs)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\keras\backend\theano_backend.py", line 541, in function
    return Function(inputs, outputs, updates=updates, **kwargs)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\keras\backend\theano_backend.py", line 527, in __init__
    **kwargs)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\compile\function.py", line 322, in function
    output_keys=output_keys)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\compile\pfunc.py", line 480, in pfunc
    output_keys=output_keys)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\compile\function_module.py", line 1784, in orig_function
    defaults)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\compile\function_module.py", line 1648, in create
    input_storage=input_storage_lists, storage_map=storage_map)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\vm.py", line 1042, in make_all
    no_recycling))

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\sandbox\cuda\__init__.py", line 256, in make_thunk
    compute_map, no_recycling)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\op.py", line 975, in make_thunk
    no_recycling)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\op.py", line 875, in make_c_thunk
    output_storage=node_output_storage)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\cc.py", line 1189, in make_thunk
    keep_lock=keep_lock)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\cc.py", line 1130, in __compile__
    keep_lock=keep_lock)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\cc.py", line 1585, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\cmodule.py", line 1145, in module_from_key
    module = lnk.compile_cmodule(location)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\gof\cc.py", line 1491, in compile_cmodule
    preargs=preargs)

  File "C:\Users\sicarbonnell\AppData\Local\Continuum\Anaconda3\envs\python34\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py", line 403, in compile_str
    'for cmd', ' '.join(cmd))

Exception: ('The following error happened while compiling the node', GpuJoin(TensorConstant{0}, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0, Rebroadcast{1}.0), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -arch=sm_50 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=m18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\\Users\\sicarbonnell\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.4.4-64\\cuda_ndarray -IC:\\Users\\sicarbonnell\\AppData\\Local\\Continuum\\Anaconda3\\envs\\python34\\lib\\site-packages\\numpy\\core\\include -IC:\\Users\\sicarbonnell\\AppData\\Local\\Continuum\\Anaconda3\\envs\\python34\\include -IC:\\Users\\sicarbonnell\\AppData\\Local\\Continuum\\Anaconda3\\envs\\python34\\lib\\site-packages\\theano\\gof -IC:\\Users\\sicarbonnell\\AppData\\Local\\Continuum\\Anaconda3\\envs\\python34\\lib\\site-packages\\theano\\sandbox\\cuda -o C:\\Users\\sicarbonnell\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.4.4-64\\tmpkc7vegoz\\mac87adaa1b92aafdf1d5bd49bc08bc35.pyd mod.cu -LC:\\Users\\sicarbonnell\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_61_Stepping_4_GenuineIntel-3.4.4-64\\cuda_ndarray -LC:\\Users\\sicarbonnell\\AppData\\Local\\Continuum\\Anaconda3\\envs\\python34\\libs -LC:\\Users\\sicarbonnell\\AppData\\Local\\Continuum\\Anaconda3\\envs\\python34 -lcudart -lcublas -lcuda_ndarray -lpython34', '[GpuJoin(TensorConstant{0}, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>, <CudaNdarrayType(float32, (True, False, False))>)]')
```

Looking forward for your help.

Simon

**Comment by joelthchao** [comment]
```python
theano.__version__ # '0.8.2'
keras.__version__ #'1.0.5'
```
My computer can run your code. What is your theano version?

**Comment by Simoncarbo** [comment]
Thanks for your reply! Good to see that the code should work.

I've the latest theano version: 
theano.__version__: '0.9.0dev1.dev-375ab0bde13bdb002a0f2001bc2a9a0ba2b45994'
keras.__version__: '1.0.5'

The problem could lie in my CUDA installation... But if it is, it's strange that other convolutional layers are working fine.

**Comment by Simoncarbo** [comment]
Just tried by getting back to theano 0.8.2, same problem: working with cpu but not with gpu

I think I'm going to reinstall CUDA.

**Comment by Simoncarbo** [comment]
After exploring more into the error and local.py code, the error lies probably in K.concatenate(). I think GpuJoin (in the error message) refers to this call. Also, K.concatenate() is the only backend call that does not appear in standard convolutional layers code (which are working fine).

Any comments about this? I just started with Keras, don't know much about Theano... Can K.concatenate() be replaced by something else?

**Comment by Simoncarbo** [comment]
Still working on it and updating...

The same code with a smaller input image (from 10x14 to 5x7) is working!
```
import numpy.random as random

from keras.models import Sequential
import keras.layers as layers
from keras.optimizers import SGD

# change values here to 100 and 140
nb_rows = 5  
nb_columns = 7

model = Sequential()

model.add(layers.ZeroPadding2D(padding=(1, 1),input_shape = (1,nb_rows,nb_columns))) 
model.add(layers.LocallyConnected2D(2,3,3,activation = 'relu',border_mode = 'valid'))

model.add(layers.Flatten())
model.add(layers.Dense(1, activation = 'sigmoid'))

model.compile(optimizer = SGD(lr = 0.001, momentum = 0.1, decay = 0.0), loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

model.fit(random.rand(10,1,nb_rows,nb_columns),random.rand(10,1), batch_size = 1,nb_epoch = 5)
```

I suppose it is a performance issue. @joelthchao could you run the code (using gpu) with input size 100x140 or even bigger to see if it works?

**Comment by Simoncarbo** [comment]
Another note: the theano compilation of concatenate is really slow.
```
import theano
import theano.tensor as T

x = T.dmatrix()
y = T.dmatrix()
z = T.concatenate([x,y]*10000)
f = theano.function([x,y],z)
```

**Comment by Simoncarbo** [comment]
I am now certain that the error was caused by the fact that too many objects were concatenated. Concatenation is very slow in theano and maybe keras is not liking this.

I've developped a solution that works for my needs, and doesn't need any concatenation. It makes the assumption that filter shape and subsampling strides are equal, and that the filter is valid for the image shape.

With this assumption, the filters cover all the image without overlapping. The result can then be computed by element-wise product with a weight matrix of same shape and summing over input filters and pools (if subsampling is used). Thanks to broadcasting, the resulting code is quite short and doesn't need concatenation:

Weight shape:
`self.W_shape = (nb_filter,input_filter,input_shape[2],input_shape[3])`

Call:
```
def call(self, x, mask=None):
        stride_row, stride_col = self.subsample
        nb_filter,_,_,_ = self.W_shape

        if self.dim_ordering == 'th':
            if K._backend == 'theano':
                x = x.reshape([x.shape[0],1,x.shape[1],x.shape[2],x.shape[3]])
                # x has shape (batchsize,1,input_nbfilter,input_rows,input_cols)
                # W has shape (nb_filter , input_nbfilter,input_rows,input_cols)
                output = K.sum(x*self.W,axis = 2) # uses broadcasting, sums over input filters
                if stride_row>1 or stride_col >1:
                    # sum pooling isn't working -> avg pooling multiplied by number of elements/pool
                    output = (stride_row*stride_col)*K.pool2d(output,(stride_row, stride_col),(stride_row, stride_col),pool_mode = 'avg')
```

My fork is working correctly and is fast even for large filterbanks/inputs:
https://github.com/Simoncarbo/keras

The result can not be used for all types of locally connected layers, but I hope it can be helpful to others anyway.

**Comment by joelthchao** [comment]
Thanks for your great efforts! Do you take care of TensorFlow backend?

**Comment by Simoncarbo** [comment]
Thanks. I can take care of this, but I can't test it since I don't have TensorFlow (and I'm on Windows...)

But first, two questions:
1) Do you encounter the same problem as me when you use keras' LocallyConnected2D layer with big inputs? (ex. 100x140)
2) Do you think my version is worth to generalize to TensorFlow and push to keras? The input restrictions (filter shape = subsampling strides, border valid) seem quite  strict to me. Not sure it will be helpful. 

The idea can maybe be generalized to the case filter shape != subsampling strides, by using shifted versions of the input. It would take some time to think about it and to implement.

**Comment by joelthchao** [comment]
1) I can't run on big input, would get an maximum recursion depth exceed error. I think my implement doesn't do well in theano. 
2) Once your implement have passed extensive test on both backend, you can propose a PR for it.

**Comment by Simoncarbo** [comment]
Got it. I would be very happy to contribute, but I will be quite busy (or on holiday) until 19th of August. I hope to find some time anyway. Cheers!

**Comment by kevinwu23** [comment]
Just wondering if there is an update to this code -- would greatly appreciate if there'a any new work done on this as I'm running into the max. recursion error as well.

**Comment by Simoncarbo** [comment]
Hi Kevin. I haven't made any PR with updated code. Are you sure the proposed solution fits your needs? It has quite heavy restrictions concerning the convolution parameters (no spatial overlap).
