### ISSUE TITLE
cropping/trimming out layer

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras#3162]
As far as I know there's no cropping layer in Keras.
If it's true, is it just because not many people need this? I'm curious.
I might need one and wondering if it's just me who want this sort of thing.
In detail, it's just the opposite of zero-padding, i.e. can cut off some of the data in arbitrary dimension.

**Comment by oeway** [comment]
+1, would be great if someone can add cropping layer.

**Comment by keunwoochoi** [comment]
It should be similar to `ZeroPadding2D` layers. So..
```

class Cropping2D(Layer):
    '''Cropping layer for 2D input (e.g. picture).

    # Input shape
        4D tensor with shape:
        (samples, depth, first_axis_to_crop, second_axis_to_crop)

    # Output shape
        4D tensor with shape:
        (samples, depth, first_cropped_axis, second_cropped_axis)

    # Arguments
        padding: tuple of tuple of int (length 2)
            How many should be trimmed off at the beginning and end of
            the 2 padding dimensions (axis 3 and 4).
    '''
    input_ndim = 4

    def __init__(self, cropping=((1,1),(1,1)), dim_ordering='th', **kwargs):
        super(ZeroPadding2D, self).__init__(**kwargs)
        assert len(cropping) == 2, 'cropping mus be two tuples, e.g. ((1,1),(1,1))'
        assert len(cropping[0]) == 2, 'cropping[0] should be a tuple'
        assert len(cropping[1]) == 2, 'cropping[1] should be a tuple'
        self.cropping = tuple(cropping)
        self.input = K.placeholder(ndim=4)
        assert dim_ordering in {'tf', 'th'}, 'dim_ordering must be in {tf, th}'
        self.dim_ordering = dim_ordering

    @property
    def output_shape(self):
        input_shape = self.input_shape
        if self.dim_ordering == 'th':
            return (input_shape[0],
                    input_shape[1],
                    input_shape[2] - self.cropping[0][0] - self.cropping[0][1],
                    input_shape[3] - self.cropping[1][0] - self.cropping[1][1])
        elif self.dim_ordering == 'tf':
            return (input_shape[0],
                    input_shape[1] - self.cropping[0][0] - self.cropping[0][1],
                    input_shape[2] - self.cropping[1][0] - self.cropping[1][1],
                    input_shape[3])
        else:
            raise Exception('Invalid dim_ordering: ' + self.dim_ordering)

    def get_output(self, train=False):
        X = self.get_input(train)
         # TODO
        return K.spatial_2d_padding(X, padding=self.padding, 
                                    dim_ordering=self.dim_ordering)

    def get_config(self):
        config = {'name': self.__class__.__name__,
                  'cropping': self.padding}
        base_config = super(Cropping2D, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

        
```

, which seems alright except the very cropping part - `get_output()`. I'm not sure it could be done with the current backend.

**Comment by keunwoochoi** [comment]
@fchollet, is cropping can be done by 

```
    def get_output(self, train=False):
        X = self.get_input(train)
        width, height = self.output_shape()[2], self.output_shape()[3]
        width_crop_left = self.cropping[0][0]
        height_crop_top = self.cropping[1][0]

        return X[:, :, width_crop_left:width+width_crop_left, height_crop_top:height+height_crop_top]
```

? I think it may work in Theano but not sure in tensorflow, for which we might need `array_ops.slice(value, offset, size, name=name)` as [this code](https://github.com/tensorflow/tensorflow/blob/0ef4620a7d39c793457b7a338a1e1494b49e0f94/tensorflow/python/ops/random_ops.py#L326).

**Comment by keunwoochoi** [comment]
Tried this code, no working with an exception as below:
the cropping layer code: (written based on ZeroPadding2D)
```
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from keras import backend as K
from keras.engine import Layer, InputSpec

# imports for backwards namespace compatibility

class Cropping2D(Layer):
    '''Cropping layer for 2D input (e.g. picture).

    # Input shape
        4D tensor with shape:
        (samples, depth, first_axis_to_crop, second_axis_to_crop)

    # Output shape
        4D tensor with shape:
        (samples, depth, first_cropped_axis, second_cropped_axis)

    # Arguments
        padding: tuple of tuple of int (length 2)
            How many should be trimmed off at the beginning and end of
            the 2 padding dimensions (axis 3 and 4).
    '''
    input_ndim = 4

    def __init__(self, cropping=((1,1),(1,1)), dim_ordering=K.image_dim_ordering(), **kwargs):
        super(Cropping2D, self).__init__(**kwargs)
        assert len(cropping) == 2, 'cropping mus be two tuples, e.g. ((1,1),(1,1))'
        assert len(cropping[0]) == 2, 'cropping[0] should be a tuple'
        assert len(cropping[1]) == 2, 'cropping[1] should be a tuple'
        self.cropping = tuple(cropping)
        assert dim_ordering in {'tf', 'th'}, 'dim_ordering must be in {tf, th}'
        self.dim_ordering = dim_ordering
        self.input_spec = [InputSpec(ndim=4)]        

    def get_output_shape_for(self, input_shape):
        if self.dim_ordering == 'th':
            
            return (input_shape[0],
                    input_shape[1],
                    input_shape[2] - self.cropping[0][0] - self.cropping[0][1],
                    input_shape[3] - self.cropping[1][0] - self.cropping[1][1])
        elif self.dim_ordering == 'tf':
            return (input_shape[0],
                    input_shape[1] - self.cropping[0][0] - self.cropping[0][1],
                    input_shape[2] - self.cropping[1][0] - self.cropping[1][1],
                    input_shape[3])
        else:
            raise Exception('Invalid dim_ordering: ' + self.dim_ordering)

    def call(self, x, mask=None):
        width, height = self.output_shape()[2], self.output_shape()[3]
        width_crop_left = self.cropping[0][0]
        height_crop_top = self.cropping[1][0]

        return x[:, :, width_crop_left:width+width_crop_left, height_crop_top:height+height_crop_top]

    def get_config(self):
        config = {'cropping': self.padding}
        base_config = super(Cropping2D, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```
and used like
```

model = Sequential()
model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='same',
                        input_shape=(1, img_rows, img_cols)))

model.add(cropping.Cropping2D(cropping=((2,2),(2,2)) ))
```
error is:
```
Traceback (most recent call last):
  File "cnn_cropping.py", line 57, in <module>
    model.add(cropping.Cropping2D(cropping=((2,2),(2,2)) ))
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/models.py", line 146, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/gnu/Gnubox/keras_playground/cropping.py", line 54, in call
    width, height = self.output_shape()[2], self.output_shape()[3]
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 815, in output_shape
    'and thus has no defined output shape.')
Exception: The layer has never been called and thus has no defined output shape.
```

Does anyone know what's the problem here?

**Comment by viksitkumarnigam** [comment]
Did you find a solution to your cropping problem. I have the same issue.

**Comment by keunwoochoi** [comment]
sadly not.

**Comment by ironbar** [comment]
Hi, 
I have made a little modification in the call function and it works.

```
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from keras import backend as K
from keras.engine import Layer, InputSpec

# imports for backwards namespace compatibility

class Cropping2D(Layer):
    '''Cropping layer for 2D input (e.g. picture).

    # Input shape
        4D tensor with shape:
        (samples, depth, first_axis_to_crop, second_axis_to_crop)

    # Output shape
        4D tensor with shape:
        (samples, depth, first_cropped_axis, second_cropped_axis)

    # Arguments
        padding: tuple of tuple of int (length 2)
            How many should be trimmed off at the beginning and end of
            the 2 padding dimensions (axis 3 and 4).
    '''
    input_ndim = 4

    def __init__(self, cropping=((1,1),(1,1)), dim_ordering=K.image_dim_ordering(), **kwargs):
        super(Cropping2D, self).__init__(**kwargs)
        assert len(cropping) == 2, 'cropping mus be two tuples, e.g. ((1,1),(1,1))'
        assert len(cropping[0]) == 2, 'cropping[0] should be a tuple'
        assert len(cropping[1]) == 2, 'cropping[1] should be a tuple'
        self.cropping = tuple(cropping)
        assert dim_ordering in {'tf', 'th'}, 'dim_ordering must be in {tf, th}'
        self.dim_ordering = dim_ordering
        self.input_spec = [InputSpec(ndim=4)]        

    def get_output_shape_for(self, input_shape):
        if self.dim_ordering == 'th':

            return (input_shape[0],
                    input_shape[1],
                    input_shape[2] - self.cropping[0][0] - self.cropping[0][1],
                    input_shape[3] - self.cropping[1][0] - self.cropping[1][1])
        elif self.dim_ordering == 'tf':
            return (input_shape[0],
                    input_shape[1] - self.cropping[0][0] - self.cropping[0][1],
                    input_shape[2] - self.cropping[1][0] - self.cropping[1][1],
                    input_shape[3])
        else:
            raise Exception('Invalid dim_ordering: ' + self.dim_ordering)

    def call(self, x, mask=None):
        """
        width, height = self.output_shape()[2], self.output_shape()[3]
        width_crop_left = self.cropping[0][0]
        height_crop_top = self.cropping[1][0]

        return x[:, :, width_crop_left:width+width_crop_left, height_crop_top:height+height_crop_top]
        """
        return x[:, :, self.cropping[0][0]:-self.cropping[0][1], self.cropping[1][0]:-self.cropping[1][1]]

    def get_config(self):
        config = {'cropping': self.padding}
        base_config = super(Cropping2D, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

I have tested it with this lines
```
model = Sequential()
model.add(Cropping2D(cropping=((2,2),(20,20)) ,input_shape=(1,200,200)))

input_data = np.ones((10,1,200,200))
print input_data.shape
print model.predict(input_data).shape
```
This should output 

> (10, 1, 200, 200)
> (10, 1, 196, 160)

**Comment by keunwoochoi** [comment]
@ironbar, I also tested it and works very well. For me they seem the same so I still don't understand why though. (Do you know?)
My test code is a simplified version of mnist_cnn example.
~~~python
'''Trains a simple convnet on the MNIST dataset.

Gets to 99.25% test accuracy after 12 epochs
(there is still a lot of margin for parameter tuning).
16 seconds per epoch on a GRID K520 GPU.
'''

from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.utils import np_utils

import cropping	
import pdb

batch_size = 128
nb_classes = 10
nb_epoch = 4

# input image dimensions
img_rows, img_cols = 28, 28
# number of convolutional filters to use
nb_filters = 1
# size of pooling area for max pooling
nb_pool = 2
# convolution kernel size
nb_conv = 3

# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

model = Sequential()
model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='same',
                        input_shape=(1, img_rows, img_cols)))

model.add(cropping.Cropping2D(cropping=((2,2),(2,2)) ))
# model.add(ZeroPadding2D(padding=(-1, -1)))
model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(img_rows/2, img_cols/2)))

model.add(Flatten())
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adadelta',
              metrics=['accuracy'])
model.summary()
# fit
model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
          verbose=1, validation_data=(X_test, Y_test))

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

~~~

With Theano backend it works fine as below. Can anyone test it on TF?
~~~bash
$ python cnn_cropping.py
Using Theano backend.
Couldn't import dot_parser, loading of dot files will not be possible.
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to
====================================================================================================
convolution2d_1 (Convolution2D)  (None, 1, 28, 28)     10          convolution2d_input_1[0][0]
____________________________________________________________________________________________________
cropping2d_1 (Cropping2D)        (None, 1, 24, 24)     0           convolution2d_1[0][0]
____________________________________________________________________________________________________
convolution2d_2 (Convolution2D)  (None, 1, 24, 24)     10          cropping2d_1[0][0]
____________________________________________________________________________________________________
activation_1 (Activation)        (None, 1, 24, 24)     0           convolution2d_2[0][0]
____________________________________________________________________________________________________
maxpooling2d_1 (MaxPooling2D)    (None, 1, 1, 1)       0           activation_1[0][0]
____________________________________________________________________________________________________
flatten_1 (Flatten)              (None, 1)             0           maxpooling2d_1[0][0]
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 10)            20          flatten_1[0][0]
____________________________________________________________________________________________________
activation_2 (Activation)        (None, 10)            0           dense_1[0][0]
====================================================================================================
Total params: 40
____________________________________________________________________________________________________
Train on 60000 samples, validate on 10000 samples
Epoch 1/4
60000/60000 [==============================] - 6s - loss: 2.3120 - acc: 0.1088 - val_loss: 2.3031 - val_acc: 0.1144
Epoch 2/4
60000/60000 [==============================] - 4s - loss: 2.2946 - acc: 0.1278 - val_loss: 2.2758 - val_acc: 0.1918
Epoch 3/4
60000/60000 [==============================] - 3s - loss: 2.2423 - acc: 0.1833 - val_loss: 2.1945 - val_acc: 0.1857
Epoch 4/4
60000/60000 [==============================] - 3s - loss: 2.1588 - acc: 0.1910 - val_loss: 2.1191 - val_acc: 0.1900
Test score: 2.11912097359
Test accuracy: 0.19
~~~

**Comment by keunwoochoi** [comment]
@fchollet, I am not sure if I should PR it. What do you think?

**Comment by ruslanagit** [comment]
Hi!
I need the cropping layer in 2D as well.
Any updates on adding this to Keras? 
Thanks!

**Comment by keunwoochoi** [comment]
@ruslanagit, please check out my repo https://github.com/keunwoochoi/keras_cropping_layer
If there are more demands, I will ask @fchollet again. So if you think you would need it. pleast comment here!

**Comment by ruslanagit** [comment]
@keunwoochoi, thanks. I will take your code.
I believe you should send your PR even if you don't get approval in this thread. It seems like people do need it.
The only thing, if I can comment, I would make the usage of the layer similar to zero padding. i.e. instead of _cropping=((2,2),(2,2))_ I would make it just _cropping=(2,2)_, similar to  _padding=(1,1)_ in ZeroPadding2D layer. I think, chances someone would ever need to have non-symmetric cropping are low. So it's better to keep the syntax simple and clean. IMHO.
Otherwise, great job. And **thanks for sharing**!!!

**Comment by keunwoochoi** [comment]
@ruslanagit Yep, I agree as API that's better - but actually I wanted a non-symmetric cropping ;) 
If you're using TF, I'd appreciate if you confirm it's working well on it! Then I'll clean the code and PR.

**Comment by ruslanagit** [comment]
I afraid I cannot be very useful here. 
I use theano backend.

**Comment by keunwoochoi** [comment]
https://github.com/keunwoochoi/keras_cropping_layer/commit/444c032f742eb5ba1611130a9b63b74b4b226391
Now it's working on TF as well.

**Comment by keunwoochoi** [comment]
It is PRed: https://github.com/fchollet/keras/pull/3509, Let's talk!

**Comment by keunwoochoi** [comment]
#3509 merged.
