### ISSUE TITLE
What is the correct data format for recurrent networks? TypeError: Cannot convert Type TensorType(float32, 3D) to TensorType(float32, (False, False, True))

### ISSUE THREAD

**Issue by Jonksar** [fchollet/keras#3254]
I am trying to build a recurrent network which classifies sequences (multidimensional data streams). I must be missing something, since while running my code:

    from keras.models import Sequential
    from keras.layers import LSTM, Dropout, Activation
    import numpy as np
    
    ils = 10            # input layer size
    ilt = 11            # input layer time steps
    hls = 12            # hidden layer size
    nhl = 2             # number of hidden layers
    ols = 1             # output layer size
    p = 0.2             # dropout probability
    f_a = 'relu'        # activation function
    opt = 'rmsprop'     # optimizing function
    
    #
    # Building the model
    #
    model = Sequential()
    
    # The input layer
    model.add(LSTM(hls, input_shape=(ilt, ils), return_sequences=True))
    model.add(Activation(f_a))
    model.add(Dropout(p))
    
    # Hidden layers
    for i in range(nhl - 1):
        model.add(LSTM(hls, return_sequences=True))
        model.add(Activation(f_a))
        model.add(Dropout(p))
    
    # Output layer
    model.add(LSTM(ols, return_sequences=False))
    model.add(Activation('softmax'))
    
    model.compile(optimizer=opt, loss='binary_crossentropy')
    
    #
    # Making test data and fitting the model
    #
    
    m_train, n_class = 1000, 2
    data = np.array(np.random.random((m_train, ilt, ils)))
    labels = np.random.randint(n_class, size=(m_train, 1))
    
    
    model.fit(data, labels, nb_epoch=10, batch_size=32)

I get output (full):

```
/usr/bin/python2.7 /home/koala/repos/ml_practice/models.py
Using Theano backend.
Traceback (most recent call last):
  File "/home/koala/repos/ml_practice/models.py", line 45, in <module>
    model.fit(data, labels, nb_epoch=10, batch_size=32)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/models.py", line 429, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/engine/training.py", line 1081, in fit
    self._make_train_function()
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/engine/training.py", line 698, in _make_train_function
    training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/optimizers.py", line 125, in get_updates
    grads = self.get_gradients(loss, params)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/optimizers.py", line 53, in get_gradients
    grads = K.gradients(loss, params)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/backend/theano_backend.py", line 587, in gradients
    return T.grad(loss, variables)
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 561, in grad
    grad_dict, wrt, cost_name)
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1324, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gradient.py", line 1113, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/home/koala/.local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 2523, in grad
    outputs = local_op(*outer_inputs)
  File "/home/koala/.local/lib/python2.7/site-packages/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/koala/.local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 430, in make_node
    new_inputs.append(format(outer_seq, as_var=inner_seq))
  File "/home/koala/.local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 422, in format
    rval = tmp.filter_variable(rval)
  File "/home/koala/.local/lib/python2.7/site-packages/theano/tensor/type.py", line 233, in filter_variable
    self=self))
TypeError: Cannot convert Type TensorType(float32, 3D) (of Variable Subtensor{:int64:}.0) into Type TensorType(float32, (False, False, True)). You can try to manually convert Subtensor{:int64:}.0 into a TensorType(float32, (False, False, True)).


```
Is this a problem with the data format at all?

I posted this to [stackoverflow](http://stackoverflow.com/questions/38420363/keras-what-is-the-correct-data-format-for-recurrent-networks) and the for someone this code worked. 

```
koala@Koala:~/repos/ml_practice$ pip list | grep Theano && pip list | grep Keras
Theano (0.8.2)
Keras (1.0.6)

```

**Comment by Jonksar** [comment]
I got my code working with more than one label. If I only had one label I would have to hack by having two output nodes from which one is always negative? 

Seems like a bug. But problem solved.
