### ISSUE TITLE
TypeError: unsupported operand type(s) in building Bidirectional LSTM

### ISSUE THREAD

**Issue by yingShen-Skye** [fchollet/keras#3341]
Hi,
I new to Keras and I am trying to build a sequential labeling model using LSTM in Keras.
And I have got the error **TypeError: unsupported operand type(s) for +: 'int' and 'dict'**

```Console
Traceback (most recent call last):
  File "/Users/shenying/PycharmProjects/Prosody/SBiLstm.py", line 165, in <module>
    output = TimeDistributed(Dense(labels_index, activation='softmax'))(after_dp)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/engine/topology.py", line 458, in __call__
    self.build(input_shapes[0])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/layers/wrappers.py", line 102, in build
    self.layer.build(child_input_shape)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/layers/core.py", line 597, in build
    name='{}_W'.format(self.name))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/initializations.py", line 60, in glorot_uniform
    s = np.sqrt(6. / (fan_in + fan_out))
TypeError: unsupported operand type(s) for +: 'int' and 'dict'
```

The main code is:
```python
# Shape of data tensor: (19997, 1000)
# Shape of label tensor: (19997, 20)

sequence = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
embedded = Embedding(input_dim=nb_words+1, output_dim=EMBEDDING_DIM,
                     mask_zero=True, weights=[embedding_matrix], input_length=MAX_SEQUENCE_LENGTH)(sequence)

lstm = LSTM(EMBEDDING_DIM, return_sequences=True)(embedded)

after_dp = Dropout(0.5)(lstm)
output = TimeDistributed(Dense(labels_index, activation='softmax'))(after_dp) # the error line

model = Model(input=sequence, output=output)
model.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])

print('Train...')
model.fit(x_train, y_train,
          batch_size=batch_size,
          nb_epoch=4,
          validation_data=(x_val, y_val))
```

**Comment by zhaopku** [comment]
Of course 'int' and 'dict' can not be added to each other
