### ISSUE TITLE
load_weights fails because 'layer_names' is missing

### ISSUE THREAD

**Issue by fvisin** [fchollet/keras#3359]
`load_weights` is broken.
"Can't open attribute (Can't locate attribute: 'layer_names')"

```
Traceback (most recent call last):
  File "/u/visin/.local/lib/python2.7/site-packages/ipdb/__main__.py", line 168, in main
    pdb._runscript(mainpyfile)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "eval_camvid2.MD10_relu.py", line 1, in <module>
    from keras.optimizers import RMSprop as Optimizer
  File "rec_conv_deconv.py", line 318, in run
    model.load_weights('./tmp/tmp_' + save_name + "_latest.w")
  File "/u/visin/exp/keras/keras/engine/topology.py", line 2414, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/u/visin/exp/keras/keras/engine/topology.py", line 2451, in load_weights_from_hdf5_group
    layer_names = [n.decode('utf8') for n in f.attrs['layer_names']]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 52, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open (/home/ilan/minonda/conda-bld/work/h5py/h5a.c:2088)
KeyError: "Can't open attribute (Can't locate attribute: 'layer_names')"
Uncaught exception. Entering post mortem debugging
```

**Comment by titu1994** [comment]
@fvisin I've had this same problem. It's caused because ModelCheckpoint has a new attribute save_only_weights which is default false. 

Unknowingly, if you fit a model then it will save the entire model instead of just the weights. 

As a fix for now, use the keras.model.load_model function to load the entire model from the h5 file. That worked for me. This needs to be fixed though or at least mentioned somewhere.

**Comment by fchollet** [comment]
The documentation clearly states the behavior of `ModelCheckpoint`. Maybe check that first. https://keras.io/callbacks/#modelcheckpoint

**Comment by marcj** [comment]
This change came in 5 days ago https://github.com/fchollet/keras/commit/ea561ba6d87879b9a67a7454e1d29777fb59132d#diff-ca6be3eb60c04bc5fcd73355b7f99d0d. When some BC breaks in a patch or minor version happen (I guess it will be released not as a new major version as usual with Keras), then nobody goes through the documentation looking for changes.

To avoid such confusion bigger projects have usually a changelog file, so people can track changes. Or add alpha|beta version if you just don't care about backwards compatibility. Or even write some sentences at your [tags](https://github.com/fchollet/keras/releases). "New PyPI release. " is really not an appropriate tag description, especially not if you consider the popularity of this library. 
IMHO the current state with that rolling releases with no changelog at all and bc breaks is just frustrating. You should probably think about a real release system.

**Comment by titu1994** [comment]
@fchollet Sorry. That was my mistake.

**Comment by fvisin** [comment]
Thank you @titu1994 @marcj 

> The documentation clearly states the behavior of ModelCheckpoint. Maybe check that first. https://keras.io/callbacks/#modelcheckpoint

The behavior changed, breaking the API. Maybe try not to break the API when introducing new features.

Anyway, the problem is not `ModelCheckpoint` but rather [this line](https://github.com/fchollet/keras/blob/a9fc2bed49c7988ccd6d365c1542818172b64ffe/keras/engine/topology.py#L2416) which can be changed into:
```python
try:
    self.load_weights_from_hdf5_group(f)
except KeyError:
    self.load_weights_from_hdf5_group(f['model_weights'])
```
to cope with the new model's weights structure keeping the old behavior.

>  "New PyPI release. " is really not an appropriate tag description, especially not if you consider the popularity of this library. 
> IMHO the current state with that rolling releases with no changelog at all and bc breaks is just frustrating. What do you think about a more robust release system? I guess many users will be happy about it :)

I most definitely agree.

**Comment by ktlim86** [comment]
I have encountered a problem running the example in https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html.

I am using the code from this [link](https://gist.github.com/fchollet/7eb39b44eb9e16e59632d25fb3119975).

I have made some changes to the code from the above link as shown below.
Here is the full code

```
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dropout, Flatten, Dense

# path to the model weights files.
# weights_path = '../keras/examples/vgg16_weights.h5'
# top_model_weights_path = 'fc_model.h5'
top_model_weights_path = '/path_to/vgg16_weights.h5'
# dimensions of our images.
img_width, img_height = 150, 150

train_data_dir = '/path_to/data/train'
validation_data_dir = '/path_to/data/validation'
nb_train_samples = 2000
nb_validation_samples = 800
epochs = 50
batch_size = 16

# build the VGG16 network
# model = applications.VGG16(weights='imagenet', include_top=False)
# I have added input_shape in applications.VGG16 as I have encountered an error. Exception: The shape of the input to "Flatten" is not fully defined
model = applications.VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3)) 
print('Model loaded.')

# build a classifier model to put on top of the convolutional model
top_model = Sequential()
top_model.add(Flatten(input_shape=model.output_shape[1:]))
top_model.add(Dense(256, activation='relu'))
top_model.add(Dropout(0.5))
top_model.add(Dense(1, activation='sigmoid'))

# note that it is necessary to start with a fully-trained
# classifier, including the top classifier,
# in order to successfully do fine-tuning
top_model.load_weights(top_model_weights_path)

# add the model on top of the convolutional base
model.add(top_model)

# set the first 25 layers (up to the last conv block)
# to non-trainable (weights will not be updated)
for layer in model.layers[:25]:
    layer.trainable = False

# compile the model with a SGD/momentum optimizer
# and a very slow learning rate.
model.compile(loss='binary_crossentropy',
              optimizer=optimizers.SGD(lr=1e-4, momentum=0.9),
              metrics=['accuracy'])

# prepare data augmentation configuration
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1. / 255)

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='binary')

validation_generator = test_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='binary')

# fine-tune the model
model.fit_generator(
    train_generator,
    samples_per_epoch=nb_train_samples,
    epochs=epochs,
    validation_data=validation_generator,
    nb_val_samples=nb_validation_samples)

model.save_weights('second_try.h5')
```


My problem is as shown below:
```
Using TensorFlow backend.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Model loaded.
Traceback (most recent call last):
  File "examples/classifier_from_little_data_script_3.py", line 74, in <module>
    top_model.load_weights(top_model_weights_path)
  File "/home/imerino/keras/venv/local/lib/python2.7/site-packages/keras/models.py", line 706, in load_weights
    topology.load_weights_from_hdf5_group(f, layers)
  File "/home/imerino/keras/venv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2865, in load_weights_from_hdf5_group
    layer_names = [n.decode('utf8') for n in f.attrs['layer_names']]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "/home/imerino/keras/venv/local/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 58, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open (/tmp/pip-nCYoKW-build/h5py/h5a.c:2337)
KeyError: "Can't open attribute (Can't locate attribute: 'layer_names')"
```

I am running keras version 2.0.1. Please advise. Thanks.

**Comment by agulli** [comment]
Is this also creating an issue with https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3?

**Comment by extrospective** [comment]
Yes, I have encountered a similar issue, and I assume one has to find the correct version of the weights files to match the version of Keras.  (Running Theano, Keras 2.02)
