### ISSUE TITLE
error in "conv_filter_visualization.py" when loading h5 file.

### ISSUE THREAD

**Issue by boozyguo** [fchollet/keras#3410]
when running the example "conv_filter_visualization.py". There are some errors reported:

C:\Anaconda2\python.exe D:/x230/working/AI/keras/snn/examples/conv_filter_visualization.py
Using Theano backend.
Traceback (most recent call last):
  File "D:/x230/working/AI/keras/snn/examples/conv_filter_visualization.py", line 98, in <module>
    for k in range(f.attrs['nb_layers']):
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2584)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2543)
  File "C:\Anaconda2\lib\site-packages\h5py\_hl\attrs.py", line 52, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2584)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2543)
  File "h5py\h5a.pyx", line 77, in h5py.h5a.open (C:\aroot\work\h5py\h5a.c:2093)
KeyError: "Can't open attribute (Can't locate attribute: 'nb_layers')"

Process finished with exit code 1

It looks like the hd5 file can not be loaded correctly.

**Comment by boozyguo** [comment]
The issue had been closed.  The h5 file includes some layer name that do not defined in network.

**Comment by Jose-Chang** [comment]
Could you explain how did you fixed this error please? I am having the exact same problem. Thanks in advanced.
