### ISSUE TITLE
Build model  error after replacing Embedding with Dense

### ISSUE THREAD

**Issue by camcamc** [fchollet/keras#350]
I took the IMDB example and replace the input with Dense, since my input is a dense matrix with variable length and 61 features, but then got the errors:

       model = Sequential()
	model.add(Dense(61, 16,init='uniform',activation='sigmoid'))
	model.add(LSTM(16, 16)) # try using a GRU instead, for fun
	model.add(Dropout(0.5))
	model.add(Dense(16, 1))
	model.add(Activation('sigmoid'))

Build model...
Traceback (most recent call last):
  File "lstm.py", line 58, in <module>
    model.compile(loss='binary_crossentropy', optimizer='adam', class_mode="binary")
  File "build/bdist.linux-i686/egg/keras/models.py", line 246, in compile
  File "build/bdist.linux-i686/egg/keras/layers/containers.py", line 51, in get_output
  File "build/bdist.linux-i686/egg/keras/layers/core.py", line 224, in get_output
  File "build/bdist.linux-i686/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-i686/egg/keras/layers/core.py", line 334, in get_output
  File "build/bdist.linux-i686/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-i686/egg/keras/layers/core.py", line 199, in get_output
  File "build/bdist.linux-i686/egg/keras/layers/core.py", line 32, in get_input
  File "build/bdist.linux-i686/egg/keras/layers/recurrent.py", line 384, in get_output
  File "build/bdist.linux-i686/egg/keras/layers/recurrent.py", line 27, in get_padded_shuffled_mask
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/var.py", line 341, in dimshuffle
    pattern)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.py", line 141, in __init__
    (i, j, len(input_broadcastable)))
ValueError: new_order[2] is 2, but the input only has 2 axes.

**Comment by camcamc** [comment]
It was something else in the code, not the embedding layer itself. I'm closing this issue.

**Comment by NancyZxll** [comment]
Hello Camcamc, 
    I am meeting the same error as you.  I added a dense before my LSTM.
    Like this:
model.add(Flatten())
#use one convolution layer, 1980, 54, work!
#input: 1980=100*(500-5+1)
#output: 54 is the number of your defined output=peptidemaxLen
model.add(Dense(49600,peptidemaxLen, init='normal')) 
model.add(Activation('softmax'))


model.add(LSTM(peptidemaxLen, peptidemaxLen, return_sequences=True))
model.add(Dropout(0.2))


    Could you tell me how you solved the problem?
    Many thanks!

**Comment by sanyecunfu** [comment]
I also find the same error?
Why the first hidden layer must be embedding layer?
thanks
