### ISSUE TITLE
Graph model cannot compile with adagrad & adadelta

### ISSUE THREAD

**Issue by pcyin** [fchollet/keras#354]
Minimum working example from documentation (http://keras.io/models/#graph)

    # graph model with two inputs and one output
    graph = Graph()
    graph.add_input(name='input1', ndim=2)
    graph.add_input(name='input2', ndim=2)
    graph.add_node(Dense(32, 16), name='dense1', input='input1')
    graph.add_node(Dense(32, 4), name='dense2', input='input2')
    graph.add_node(Dense(16, 4), name='dense3', input='dense1')
    graph.add_output(name='output', inputs=['dense2', 'dense3'], merge_mode='sum')
    graph.compile('adadelta', {'output':'mse'})

```
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x105e6dad0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/tensor/opt.py", line 5338, in local_fuse
    tmp.tag.test_value = gof.op.get_test_value(ii).flatten()[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by fchollet** [comment]
All optimizers work fine with all types of Graphs as far as I can tell. Try updating your version of Theano.

**Comment by pcyin** [comment]
I found it's somehow related to IDE (PyCharm)... will debug it and close the issue
