### ISSUE TITLE
Generator Race Condition in master

### ISSUE THREAD

**Issue by kuza55** [fchollet/keras#3601]
I don't really know what's causing this atm, but there is some sort of multithreading issue with generators in the master branch causing me to get exceptions in my generator.

Reverting to what is currently in pip solves the issue, so it's probably something that has changed wrt generators since a release.

```
Traceback (most recent call last):                                                                                                              
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                                                                        
    self.run()                                                                                                                                  
  File "/usr/lib/python2.7/threading.py", line 763, in run                                                                                      
    self.__target(*self.__args, **self.__kwargs)                                                                                                
  File "/home/ubuntu/virtualenv/local/lib/python2.7/site-packages/keras/engine/training.py", line 425, in data_generator_task                   
    generator_output = next(generator)                                                                                                          
ValueError: generator already executing                                                                                                         

Traceback (most recent call last):                                                                                                              
  File "run.py", line 18, in <module>                                                                                                           
    validation_data=vgen, nb_val_samples=5120)                                                                                                  
  File "/home/ubuntu/virtualenv/local/lib/python2.7/site-packages/keras/engine/training.py", line 1469, in fit_generator                        
    max_q_size=max_q_size)                                                                                                                      
  File "/home/ubuntu/virtualenv/local/lib/python2.7/site-packages/keras/engine/training.py", line 1539, in evaluate_generator                   
    'or (x, y). Found: ' + str(generator_output))                                                                                               
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None                                                   
Exception in thread Thread-36:                                                                                                                  
Traceback (most recent call last):                                                                                                              
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                                                                        
    self.run()                                                                                                                                  
  File "/usr/lib/python2.7/threading.py", line 763, in run                                                                                      
    self.__target(*self.__args, **self.__kwargs)                                                                                                
  File "/home/ubuntu/virtualenv/local/lib/python2.7/site-packages/keras/engine/training.py", line 425, in data_generator_task                   
    generator_output = next(generator)                                                                                                          
  File "/mnt/bosch/data.py", line 135, in generate_batch                                                                                        
    (x_arr, y_arr) = next(gen)                                                                                                                  
  File "/mnt/bosch/data.py", line 206, in new_gen                                                                                               
    yield ([np.array(num_arr).reshape((968)), np.array(num_mask).reshape((968)),                                                                
AttributeError: 'NoneType' object has no attribute 'array'                                                                                      

Exception in thread Thread-37:                                                                                                                  
Traceback (most recent call last):                                                                                                              
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                                                                        
    self.run()                                                                                                                                  
  File "/usr/lib/python2.7/threading.py", line 763, in run                                                                                      
    self.__target(*self.__args, **self.__kwargs)                                                                                                
  File "/home/ubuntu/virtualenv/local/lib/python2.7/site-packages/keras/engine/training.py", line 425, in data_generator_task                   
    generator_output = next(generator)                                                                                                          
  File "/mnt/bosch/data.py", line 135, in generate_batch                                                                                        
    (x_arr, y_arr) = next(gen)                                                                                                                  
  File "/mnt/bosch/data.py", line 206, in new_gen                                                                                               
    yield ([np.array(num_arr).reshape((968)), np.array(num_mask).reshape((968)),                                                                
AttributeError: 'NoneType' object has no attribute 'array'                              
```

**Comment by sergeyf** [comment]
I am having this issue as well.

**Comment by oeway** [comment]
Same here, but there seems a new commit to solve this problem: https://github.com/fchollet/keras/commit/1c6db0815853f7c5421b8057e9167f19b5b94812
I am testing that.

**Comment by oeway** [comment]
No, it doesn't fix my problem, can anyone else check that? @sergeyf @kuza55

**Comment by kuza55** [comment]
Any chance you have a repro you can post? Might make it easier to track down.

**Comment by oeway** [comment]
@kuza55 Thanks for you response.
For the code, it's complicated to make a repo, but the error now occurs when I use a generator for the validation dataset.
Now, a fixed validation dataset seems fixed my problem.
