### ISSUE TITLE
TimeDistributed Wrapper Fails w/ Exception

### ISSUE THREAD

**Issue by alexmarkley** [fchollet/keras#3621]
When I use the TimeDistributed wrapper after an LSTM layer, I get the following exception:

```
Exception: Error when checking model target: expected timedistributed_1 to have 3 dimensions, but got array with shape (100, 1)
```

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). (Script below...)

```
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.layers.wrappers import TimeDistributed
import numpy

samples = 100
timesteps = 32
inputs = 3
outputs = 1

Xt = numpy.random.random((samples, timesteps, inputs))
Yt = numpy.random.random((samples, outputs))

print("Building model...")
model = Sequential()
model.add(LSTM(output_dim=128, input_shape=(timesteps, inputs), activation='tanh', return_sequences=True))
#model.add(BatchNormalization())
model.add(LSTM(output_dim=128, activation='tanh', return_sequences=True))
#model.add(BatchNormalization())
model.add(TimeDistributed(Dense(outputs, init='uniform', activation='linear')))

model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics=['accuracy'])

model.summary()

print("Fitting model...")

model.fit(Xt, Yt)
```

Full script output:

```
(env)[alex@annie annie]$ THEANO_FLAGS=mode=FAST_RUN,device=gpu,force_device=true,floatX=float32 python keras/kerasBug.py
Using Theano backend.
Using gpu device 0: GeForce GTX 1070 (CNMeM is disabled, cuDNN 5005)
Building model...
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to
====================================================================================================
lstm_1 (LSTM)                    (None, 32, 128)       67584       lstm_input_1[0][0]
____________________________________________________________________________________________________
lstm_2 (LSTM)                    (None, 32, 128)       131584      lstm_1[0][0]
____________________________________________________________________________________________________
timedistributed_1 (TimeDistribute(None, 32, 1)         129         lstm_2[0][0]
====================================================================================================
Total params: 199297
____________________________________________________________________________________________________
Fitting model...
Traceback (most recent call last):
  File "keras/kerasBug.py", line 29, in <module>
    model.fit(Xt, Yt)
  File "/home/alex/Tests/annie/env/lib/python2.7/site-packages/keras/models.py", line 620, in fit
    sample_weight=sample_weight)
  File "/home/alex/Tests/annie/env/lib/python2.7/site-packages/keras/engine/training.py", line 1032, in fit
    batch_size=batch_size)
  File "/home/alex/Tests/annie/env/lib/python2.7/site-packages/keras/engine/training.py", line 963, in _standardize_user_data
    exception_prefix='model target')
  File "/home/alex/Tests/annie/env/lib/python2.7/site-packages/keras/engine/training.py", line 97, in standardize_input_data
    str(array.shape))
Exception: Error when checking model target: expected timedistributed_1 to have 3 dimensions, but got array with shape (100, 1)
(env)[alex@annie annie]$
```

Help? :)

**Comment by fchollet** [comment]
I find the error very readable; what is not clear to you? Error when checking model target (that's your Yt). Expected 3 dims, but found shape (100, 1). Fix your Yt array. The output of your model is 3D.

**Comment by alexmarkley** [comment]
Aha, this is definitely pilot error. I got a recommendation to use TimeDistributed(Dense()) for LSTM Regression modeling, without fully understanding what the TimeDistributed wrapper does. In the documentation it does mention 3D output, but since it's only one line I missed it.
