### ISSUE TITLE
LSTM text generation example broken?

### ISSUE THREAD

**Issue by gamboviol** [fchollet/keras#363]
I just cloned f817e2e71c8e78382b6e459b8183236af59e0a4c and see this error when running examples/lstm_text_generation.py:

    Iteration 1
    Epoch 0
    Traceback (most recent call last):
          File "lstm_text_generation.py", line 76, in <module>
            model.fit(X, y, batch_size=128, nb_epoch=1)
          File "build/bdist.macosx-10.10-intel/egg/keras/models.py", line 371, in fit
          File "build/bdist.macosx-10.10-intel/egg/keras/models.py", line 135, in _fit
          File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 588, in __call__
            self.fn.thunks[self.fn.position_of_error])
          File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 579, in __call__
    outputs = self.fn()
          File "/Library/Python/2.7/site-packages/theano/gof/op.py", line 632, in rval
            r = p(n, [x[0] for x in i], o)
          File "/Library/Python/2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 2223, in perform
            out[0] = x.reshape(tuple(shp))
    ValueError: size must remain unchanged, changed from 7552 to -59
    Apply node that caused the error: GpuReshape{2}(GpuElemwise{add,no_inplace}.0, MakeVector.0)
    Inputs shapes: [(128, 59), (2,)]
    Inputs strides: [(59, 1), (8,)]
    Inputs types: [CudaNdarrayType(float32, matrix), TensorType(int64, vector)]

If I revert to 1857a6af5ed6592552559b15c190708e912be139 it runs fine. Did something get broken in between?

**Comment by fchollet** [comment]
It works for me on both CPU and GPU. It's quite possible that we started relying on a more recent Theano feature since 1857a6a. Make sure your version of Theano is up to date.

**Comment by gamboviol** [comment]
Thanks, that fixes it, I was using 0.6. I actually see it starting to fail with 0.6 at 4c5f8e364c369ecda181dfe469500d05de81d1e1. Maybe worth specifying a version in setup.py?

Thanks for a fantastic library anyway :)
