### ISSUE TITLE
Bidirectional does not work with return_sequences=True and Masking

### ISSUE THREAD

**Issue by alex-j-j** [fchollet/keras#3676]
I use embeddings, a bi-directional LSTM and a final, time-distributed Dense. However, if I want to use masking, I get a shape error.

The following code gives an error:

```
import numpy as np
from keras.engine.topology import Input, merge, Merge
from keras.layers.embeddings import Embedding
from keras.layers.wrappers import TimeDistributed, Bidirectional
from keras.layers.recurrent import LSTM
from keras.layers.core import Dense, Masking
from keras.engine.training import Model
from numpy import dtype, int32

num_classes = 10
num_symbols = 10
datapoints = 100
seq_len = 10
x = np.random.randint(num_symbols, size=(datapoints, seq_len))
y = np.random.randint(num_classes, size=(datapoints, seq_len))
y_one_hot = np.zeros((datapoints, seq_len, num_classes))

for i in range(datapoints):
    for j in range(seq_len):
        y_one_hot[i][j][y[i][j]] = 1

embedding_size = 10
embedding_weights = np.zeros((num_symbols, embedding_size))

for i in range(num_symbols):
    embedding_weights[i] = np.random.rand(embedding_size)

input = Input(shape=(seq_len,), dtype="int32")
embedding = Embedding(num_symbols, embedding_size, input_length=seq_len)

embedded_input = embedding(input)

mask = Masking(mask_value=0)(embedded_input)

bidirect = Bidirectional(LSTM(100, return_sequences=True))(mask)

final = TimeDistributed(Dense(num_classes, activation="softmax"))(bidirect)

model = Model(input=[input], output=[final])

model.compile(loss='categorical_crossentropy', optimizer="rmsprop", metrics=['accuracy'])

model.fit(x, y_one_hot)
```

If one removes the mask, it compiles and runs without problems.

The error in the above case is:

```
ValueError: Shape (?, 10) must have rank 3
```

Whatever I do (e.g., reshaping the input, specifying input and output of each layer), it doesn't work. Is this a bug or am I doing something wrong?

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by farizrahman4u** [comment]
Paste the full error message.

**Comment by alex-j-j** [comment]
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 563, in merge_with
    self.assert_same_rank(other)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 609, in assert_same_rank
    "Shapes %s and %s must have the same rank" % (self, other))
ValueError: Shapes (?, 10) and (?, ?, ?) must have the same rank

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 639, in with_rank
    return self.merge_with(unknown_shape(ndims=rank))
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 570, in merge_with
    (self, other))
ValueError: Shapes (?, 10) and (?, ?, ?) are not compatible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexjudea/git/event/Argumentor/src/test.py", line 35, in <module>
    bidirect = Bidirectional(LSTM(100, return_sequences=True))(mask)
  File "/Users/alexjudea/Library/Python/3.5/lib/python/site-packages/keras/engine/topology.py", line 515, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/alexjudea/Library/Python/3.5/lib/python/site-packages/keras/engine/topology.py", line 573, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/alexjudea/Library/Python/3.5/lib/python/site-packages/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/alexjudea/Library/Python/3.5/lib/python/site-packages/keras/layers/wrappers.py", line 196, in call
    Y_rev = self.backward_layer.call(X, mask)
  File "/Users/alexjudea/Library/Python/3.5/lib/python/site-packages/keras/layers/recurrent.py", line 213, in call
    input_length=input_shape[1])
  File "/Users/alexjudea/Library/Python/3.5/lib/python/site-packages/keras/backend/tensorflow_backend.py", line 1139, in rnn
    mask = tf.reverse(mask, [True] + [False] * (ndim - 1))
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1815, in reverse
    name=name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2312, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1704, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 988, in _ReverseShape
    input_shape = input_shape.with_rank(dims_shape[0])
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 641, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (?, 10) must have rank 3
```

**Comment by farizrahman4u** [comment]
This has been fixed. Install latest version of Keras.

**Comment by RaffEdwardBAH** [comment]
@farizrahman4u is that commit #3662 ?

**Comment by alex-j-j** [comment]
It seems that I updated the wrong Python version with the newest code. It works, thanks.

**Comment by farizrahman4u** [comment]
@RaffEdwardBAH yes.
