### ISSUE TITLE
Odd Theano exception when adding TimeDistributed(Dense(x)) to Sequential model as Input

### ISSUE THREAD

**Issue by worosom** [fchollet/keras#3736]
Hi!

I get the following exception:

```
Exception: When specifying `unroll=True`, an `input_length` must be provided to `rnn`.
```

When I run the below code:

```
from keras.models import Sequential
from keras.layers import TimeDistributed, Dense
model = Sequential()
model.add(TimeDistributed(Dense(32),batch_input_shape=(10,10,1022)))
```

This issue occurs if I install Keras from this repository via

```
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
```

yet I get no error if I install Keras via

```
pip install keras
```

What happened in the code to make the error come up?

Here's what I see in the console:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras.models import Sequential
Using Theano backend.
Using gpu device 0: GeForce GTX 1070 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5005)
>>> from keras.layers import TimeDistributed, Dense
>>> model = Sequential()
>>> model.add(TimeDistributed(Dense(32),batch_input_shape=(10,10,1022)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 276, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 370, in create_input_layer
    self(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 122, in call
    unroll=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 744, in rnn
    raise Exception('When specifying `unroll=True`, an `input_length` '
Exception: When specifying `unroll=True`, an `input_length` must be provided to `rnn`.
```

**Comment by nouiz** [comment]
Just a note, this is not a Theano error, but an error raised by Keras itself.

Mostly, put unroll=False or specify input_length as the message tell.
