### ISSUE TITLE
Running Keras results in import error of backend

### ISSUE THREAD

**Issue by dmitrinesterenko** [fchollet/keras#3738]
``` sh
Traceback (most recent call last):
  File "random.py", line 2, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/site-packages/keras/backend/__init__.py", line 6, in <module>
    from .common import epsilon
  File "/usr/local/lib/python2.7/site-packages/keras/backend/common.py", line 1, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 21, in <module>
    from .utils import SkipTest
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/local/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/workdir/current/random.py", line 2, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 8, in <module>
    from . import backend as K
ImportError: cannot import name backend
```

To reproduce please clone the [repo with the docker files](https://github.com/dmitrinesterenko/keras_docker) that I had used to isolate my installation to just the required pieces.

Given a docker machine is present the steps to reproduce should be 

``` sh
./scripts/build.sh
./scripts/run.sh
```
## The docker images will be built with the latest versions of Theano and Keras so I must be missing something simple that someone with experience can point out to me so that I can learn.

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by cryptc** [comment]
I received this error after upgrading to TensorFlow 1.10.0.  To fix it, I deleted the TensorFlow directory and reinstalled.  There is apparently an issue with the TensorFlow upgrade process that can cause this.
