### ISSUE TITLE
Error when building example network 

### ISSUE THREAD

**Issue by kretes** [fchollet/keras#3795]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I was reproducing example code from https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html - using code from https://gist.github.com/fchollet/0830affa1f7f19fd47b06d4cf89ed44d

it works in 1.0.8 but doesn't work in latest revision.

I Prepared a dockerfile for 1.0.8: https://gist.github.com/kretes/566d9d725891be683f5362c03dee484f which when downloaded as Dockerfile-working and run with:

```docker build -t keras-bug:1.0.8 -f Dockerfile-working . && docker run keras-bug:1.0.8``` works ok

and alternative environment for latest git revision (fixed to the latest now (4fb3f1b3f384c3a05306b37ea9a736144ed6394a)): https://gist.github.com/kretes/7e4a0102fc64a3b6447f5ab44d7ab397 which when downloaded as Dockerfile-failing and run with: 
```docker build -t keras-bug:latest-git -f Dockerfile-failing . && docker run keras-bug:latest-git```
gives:
```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/opt/conda/lib/python3.5/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/opt/conda/lib/python3.5/site-packages/keras/layers/pooling.py", line 162, in call
    dim_ordering=self.dim_ordering)
  File "/opt/conda/lib/python3.5/site-packages/keras/layers/pooling.py", line 212, in _pooling_function
    border_mode, dim_ordering, pool_mode='max')
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1696, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 536, in max_pool
    name=name)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1038, in _max_pool
    data_format=data_format, name=name)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/common_shapes.py", line 505, in max_pool_shape
    padding)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/common_shapes.py", line 184, in get2d_conv_output_size
    (row_stride, col_stride), padding_type)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/ops/common_shapes.py", line 149, in get_conv_output_size
    "Filter: %r Input: %r" % (filter_size, input_size))
ValueError: Filter must not be larger than the input: Filter: (2, 2) Input: (1, 148)
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f40bc791780>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 171, in __del__
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 167, in close
TypeError: 'NoneType' object is not callable
```

**Comment by kretes** [comment]
I checked whether the problem persists in 1.1.0 and found out that the problem is only when backend is tensorflow - even with current tf version 0.10 and keras 1.1.0

**Comment by jtyberg** [comment]
I can confirm that the example works in 1.0.8, but fails with an exception in 1.1.0:

```ValueError: Filter must not be larger than the input:```

I'm at 

```
Keras==1.1.0
tensorflow==0.10.0
Theano==0.8.2
```

I believe the issue is the switch to Tensorflow as the default backend, and the `image_dim_ordering` now defaults to `tf`, but the example was written for a Theano backend where the `image_dim_ordering` is `th`.  So the shape of the input (and subsequent tensors) needs to change.

I'm really new to all this, but I was able to get the example to run by switching my  `image_dim_ordering` to `th` in `~/.keras/keras.json`.  I don't know if this is sacrilege, but I also don't know enough (yet) to switch the shapes of all the tensors in the example.

```
{
    "image_dim_ordering": "th",
    "backend": "tensorflow",
    "epsilon": 1e-07,
    "floatx": "float32"
}
```

**Comment by kretes** [comment]
Yes that's right - that's about different dimension ordering and migration from 1.0.8 to 1.1.0. closing
