### ISSUE TITLE
examples/imdb_cnn.py not working

### ISSUE THREAD

**Issue by nreimers** [fchollet/keras#3813]
Hi,
I'm running the examples/imdb_cnn.py script with current master branch of keras and 0.8.2. Theano version.

However, the code is not learning anything. The loss does not go down and the accuracy stays at 50%.

The other example, for example imdb_lstm.py or imdb_festtext.py work as expected and achieve around 90% accuracy. 

I suspect that something with the convolution or the max-over-time is broken in the imdb_cnn.py script.

Has anyone else the same problem?

**Comment by nreimers** [comment]
Nevermind, just cleaned all cache files and updated Theano once more and now it is running and it is learning as expected.

 Sorry for the spam.

**Comment by hkmztrk** [comment]
Hello,

I have the following error with the script, could you help me with that?

Thank you!

File "/usr/lib64/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 1287, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/keras/utils/data_utils.py", line 220, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/usr/lib64/python3.4/urllib/request.py", line 186, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "imdb_cnn.py", line 29, in <module>
    (x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
  File "/usr/lib64/python3.4/site-packages/keras/datasets/imdb.py", line 51, in load_data
    path = get_file(path, origin='https://s3.amazonaws.com/text-datasets/imdb.npz')
  File "/usr/lib64/python3.4/site-packages/keras/utils/data_utils.py", line 222, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://s3.amazonaws.com/text-datasets/imdb.npz: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
