### ISSUE TITLE
Dropout layer doesn't support Tensorflow workflow

### ISSUE THREAD

**Issue by FBMachine** [fchollet/keras#3823]
Following the workflow here:
https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html#using-keras-models-with-tensorflow

Using a layer with dropout throws an exception. It works if there is no dropout.

Edit: it has nothing to do with the Embedding layer. The problem is specifically with the dropout layer, and will also happen if you manually add a dropout layer to the model.

Minimal code to reproduce:

```
import tensorflow as tf
from keras import backend as K
from keras.models import Sequential
from keras.layers import Embedding

with tf.Graph().as_default():
    with tf.Session() as session:
        input_length = 140
        x = tf.placeholder(tf.int32, shape=(None, input_length))

        K.set_session(session)

        model = Sequential()
        model.add(Embedding(257, 300, input_length=input_length, dropout=0.2))
```

Stack trace:

```
$ KERAS_BACKEND=tensorflow python exception-repro.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "exception-repro.py", line 14, in <module>
    model.add(Embedding(257, 300, input_length=input_length, dropout=0.2))
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/keras/models.py", line 275, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/keras/engine/topology.py", line 367, in create_input_layer
    self(x)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/keras/engine/topology.py", line 511, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/keras/engine/topology.py", line 569, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/keras/layers/embeddings.py", line 134, in call
    W = K.in_train_phase(self.W * B, self.W)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1109, in in_train_phase
    lambda: alt)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1150, in cond
    res_t = context_t.BuildCondBranch(fn1)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1089, in BuildCondBranch
    real_v = _SwitchRefOrTensor(real_v, self._pred)[self._branch]
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 304, in _SwitchRefOrTensor
    return switch(data, pred, name=name)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 198, in switch
    with ops.op_scope([data, pred], name, "Switch") as name:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3692, in op_scope
    g = _get_graph_from_inputs(values)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3499, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/dgonzalez/tf_env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3444, in _assert_same_graph
    "%s must be from the same graph as %s." % (item, original_item))
ValueError: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("mul_1:0", shape=(257, 300), dtype=float32).
```

**Comment by SRTjiawei** [comment]
I got the same issue, seems it's because that we created multiple graphs, not a problem about the Dropout. I tried to add `with tf.Graph().as_default()`, but didn't solved it yet.

**Comment by philipperemy** [comment]
I have the same issue and nothing works. I'm working on a solution now.

**Comment by philipperemy** [comment]
`tf.nn.dropout` temporary solution is to use the dropout layer from TF.

**Comment by philipperemy** [comment]
The problem comes from the call to `K.in_train_phase` in the class `Dropout`. `_LEARNING_PHASE` was defined outside of the graph. So that's why we have this error.

**Comment by philipperemy** [comment]
@FBMachine 

This code works:

```
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

from keras import backend as K
from keras.layers import Dropout
from keras.layers import Highway, Dense
from keras.metrics import categorical_accuracy as accuracy
from keras.objectives import categorical_crossentropy

sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=False))
K.set_session(sess)

# this placeholder will contain our input digits, as flat vectors

for d in ['/gpu:0', '/gpu:1']:
    with tf.device(d):
        img = tf.placeholder(tf.float32, shape=(None, 784))
        x = Highway(activation='relu')(img)  # fully-connected layer with 128 units and ReLU activation
        x = Dropout(p=1)(x)
        x = Highway(activation='relu')(x)
        x = Dropout(p=0.2)(x)
        x = Highway(activation='relu')(x)
        x = Dropout(p=0.1)(x)
        x = Highway(activation='relu')(x)
        x = Dropout(p=0.05)(x)
        preds = Dense(10, activation='softmax')(x)  # output layer with 10 units and a softmax activation

labels = tf.placeholder(tf.float32, shape=(None, 10))
loss = tf.reduce_mean(categorical_crossentropy(labels, preds))
mnist_data = input_data.read_data_sets('MNIST_data', one_hot=True)

train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
batch = None

max_epochs = int(1e9)
with sess.as_default():
    for i in range(max_epochs):
        batch = mnist_data.train.next_batch(50)
        train_step.run(feed_dict={img: batch[0],
                                  labels: batch[1],
                                  K.learning_phase(): 1})
        if i % 10 == 0:
            acc_value = accuracy(labels, preds)
            with sess.as_default():
                acc_val = acc_value.eval(feed_dict={img: mnist_data.test.images,
                                                    labels: mnist_data.test.labels,
                                                    K.learning_phase(): 0})
                print('epoch = {0} val_acc = {1:.3f}'.format(i, acc_val))
```

**Comment by sonalgupta** [comment]
is there a solution for this? I don't want to use the default graph and want to do `with tf.Graph().as_default():`

**Comment by philipperemy** [comment]
@sonalgupta not from what I heard. The problem comes from the learning phase constant defined in the backend. Dropout uses this constant and try to evaluate it via a cond ops. I don't have much time to propose a fix now.

The only easy fix I see is to use

```
keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)
```
Instead of the object `Dropout` of Keras.

If you use only the tensorflow backend, you should be fine.

**Comment by farizrahman4u** [comment]
```python
K.set_learning_phase(1)
```

**Comment by philipperemy** [comment]
@farizrahman4u If you set the learning phase to 1, your model will use the dropout layers on the validation/test set.

**Comment by farizrahman4u** [comment]
Set it to 1 first; Train your model. Set it to 0; Create a new model with same config; Transfer weights from old model to new model.

**Comment by farizrahman4u** [comment]
You can also provide the K.learning_phase() place holder through the feed_dict argument as clearly mentioned in the blog; which would be more straight forward imo.
```python
train_step.run(feed_dict={x: batch[0], labels: batch[1], K.learning_phase(): 1})
```

**Comment by sonalgupta** [comment]
From what I have heard, this is fixed in the master.

**Comment by philipperemy** [comment]
@sonalgupta ok thanks for your feedback!

**Comment by burgalon** [comment]
@sonalgupta any idea about the specific commit?

**Comment by redst4r** [comment]
not sure if related, but I also had some trouble with Dropout and tensorflow.
Using this fixed it:
```python
import tensorflow as tf
tf.python.control_flow_ops = tf  # some hack to get tf running with Dropout
```
