### ISSUE TITLE
None type on input size does not to work on UpSampling2D

### ISSUE THREAD

**Issue by owang** [fchollet/keras#3965]
The code (tensorflow backend)

```
m = keras.models.Sequential()
m.add(keras.layers.convolutional.Convolution2D(1, 3, 3, border_mode='same', input_shape=(None, None,1)))
m.add(keras.layers.convolutional.UpSampling2D(size=(2, 2),dim_ordering='tf'))
```

The error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/owang/Library/Python/2.7/lib/python/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/owang/Library/Python/2.7/lib/python/site-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/owang/Library/Python/2.7/lib/python/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/owang/Library/Python/2.7/lib/python/site-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/owang/Library/Python/2.7/lib/python/site-packages/keras/layers/convolutional.py", line 1318, in call
    self.dim_ordering)
  File "/Users/owang/Library/Python/2.7/lib/python/site-packages/keras/backend/tensorflow_backend.py", line 756, in resize_images
    X.set_shape((None, original_shape[1] * height_factor, original_shape[2] * width_factor, None))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by owang** [comment]
Does no one else have this problem? It seems pretty deal-breaking for any fully convolutional autoencoder type network.

**Comment by uschmidt83** [comment]
I just encountered the same problem...

**Comment by uschmidt83** [comment]
I think the error message posted by @owang is fixed by replacing [tensorflow_backend.py#L787](https://github.com/fchollet/keras/blob/49386e8da49f0c63c467c28456c995ad24cc99fb/keras/backend/tensorflow_backend.py#L787) with
```python
X.set_shape((None, original_shape[1] * height_factor if original_shape[1] is not None else None, original_shape[2] * width_factor if original_shape[2] is not None else None, None))
```

However, there is an additional problem when calling `m.fit` later on:
```python
m = keras.models.Sequential()
m.add(keras.layers.convolutional.Convolution2D(1, 3, 3, border_mode='same', input_shape=(None, None,1)))
m.add(keras.layers.convolutional.UpSampling2D(size=(2, 2),dim_ordering='tf'))

m.compile(loss='mse', optimizer='adam')
m.fit(np.ones((1,10,10,1)),np.ones((1,20,20,1)))
```
Error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-38e637439d3c> in <module>()
      4 
      5 m.compile(loss='mse', optimizer='adam')
----> 6 m.fit(np.ones((1,10,10,1)),np.ones((1,20,20,1)))

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/keras/models.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, **kwargs)
    625                               shuffle=shuffle,
    626                               class_weight=class_weight,
--> 627                               sample_weight=sample_weight)
    628 
    629     def evaluate(self, x, y, batch_size=32, verbose=1,

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight)
   1095         else:
   1096             ins = x + y + sample_weights
-> 1097         self._make_train_function()
   1098         f = self.train_function
   1099 

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/keras/engine/training.pyc in _make_train_function(self)
    712             training_updates = self.optimizer.get_updates(self._collected_trainable_weights,
    713                                                           self.constraints,
--> 714                                                           self.total_loss)
    715             updates = self.updates + training_updates
    716 

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/keras/optimizers.pyc in get_updates(self, params, constraints, loss)
    380 
    381     def get_updates(self, params, constraints, loss):
--> 382         grads = self.get_gradients(loss, params)
    383         self.updates = [K.update_add(self.iterations, 1)]
    384 

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/keras/optimizers.pyc in get_gradients(self, loss, params)
     66 
     67     def get_gradients(self, loss, params):
---> 68         grads = K.gradients(loss, params)
     69         if hasattr(self, 'clipnorm') and self.clipnorm > 0:
     70             norm = K.sqrt(sum([K.sum(K.square(g)) for g in grads]))

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py in gradients(loss, variables)
   1075     with regard to `loss`.
   1076     '''
-> 1077     return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
   1078 
   1079 

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gradients.pyc in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method)
    467                 # If grad_fn was found, do not use SymbolicGradient even for
    468                 # functions.
--> 469                 in_grads = _AsList(grad_fn(op, *out_grads))
    470               else:
    471                 # For function call ops, we add a 'SymbolicGradient'

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/image_grad.pyc in _ResizeNearestNeighborGrad(op, grad)
     41       grad,
     42       op.inputs[0].get_shape()[1:3],
---> 43       align_corners=op.get_attr("align_corners"))
     44   # pylint: enable=protected-access
     45   return [grads, None]

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.pyc in _resize_nearest_neighbor_grad(grads, size, align_corners, name)
    816   result = _op_def_lib.apply_op("ResizeNearestNeighborGrad", grads=grads,
    817                                 size=size, align_corners=align_corners,
--> 818                                 name=name)
    819   return result
    820 

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.pyc in apply_op(self, op_type_name, name, **keywords)
    492             # What type does convert_to_tensor think it has?
    493             observed = ops.convert_to_tensor(values,
--> 494                                              as_ref=input_arg.is_ref).dtype.name
    495             prefix = ("Input '%s' of '%s' Op has type %s that does not match" %
    496                       (input_name, op_type_name, observed))

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    655 
    656         if ret is None:
--> 657           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    658 
    659         if ret is NotImplemented:

/home/uschmidt/sw/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in _tensor_shape_tensor_conversion_function(s, dtype, name, as_ref)
    196   if not s.is_fully_defined():
    197     raise ValueError(
--> 198         "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
    199   if dtype is not None:
    200     if dtype not in (dtypes.int32, dtypes.int64):

ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)
```

I think it is a TF bug, because it works without problems when I replace `tf.image.resize_nearest_neighbor` with `tf.image.resize_bilinear` in [tensorflow_backend.py#L786](https://github.com/fchollet/keras/blob/49386e8da49f0c63c467c28456c995ad24cc99fb/keras/backend/tensorflow_backend.py#L786)

Uwe

**Comment by uschmidt83** [comment]
I've submitted a pull request (https://github.com/tensorflow/tensorflow/pull/5497) for the tensorflow bug.
