### ISSUE TITLE
get error when Convert from CPU to GPU

### ISSUE THREAD

**Issue by wangye0523** [fchollet/keras#4017]
Hi, guys:
I am using keras, but when I was trying to change to GPU from CPU which CPU works well, the error shows.. Actually I definitely run the cuda example with instruction correctly. 
I followed the instruction to change the GPU conf:
openmp=False 
device = gpu   
floatX = float32  
allow_input_downcast=True  
[lib]
cnmem = 0.8 
[blas]
ldflags= -lopenblas
[nvcc]
fastmath = True  

from CPU:
[global]
openmp=True 
device = cpu 
floatX = float32  
allow_input_downcast=True  
[blas]
ldflags= -lopenblas 

ye@ye-desktop:~$ gedit ~/.theanorc 
ye@ye-desktop:~$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using Theano backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 61, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 42, in <module>
    from theano.configdefaults import config
  File "/usr/local/lib/python2.7/dist-packages/theano/configdefaults.py", line 16, in <module>
    from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 84, in <module>
    theano_cfg.read(config_files)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/ye/.theanorc, line: 1
'openmp=False \n'

According to the error, I pip installed ConfigParser, really appreciate your help.!

**Comment by nouiz** [comment]
In the config file for GPU, you are missing that at the top. You have it in
the CPU config file.

[global]

**Comment by wangye0523** [comment]
It works. Thanks so much!
