### ISSUE TITLE
Can't save model, both save_model function and ModelCheckpoint(save_best_only=True) when fine-tuning

### ISSUE THREAD

**Issue by barrykui** [fchollet/keras#4038]
error information when call save_model
```
Traceback (most recent call last):
  File "seqnet.py", line 468, in <module>
    main()
  File "seqnet.py", line 153, in main
    train_val_test()
  File "seqnet.py", line 455, in train_val_test
    train_model_runner(i)
  File "seqnet.py", line 342, in train_model_runner
    save_model(model, fname)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/models.py", line 56, in save_model
    model.save_weights_to_hdf5_group(model_weights_group)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/engine/topology.py", line 2458, in save_weights_to_hdf5_group
    g = f.create_group(layer.name)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py/h5g.c:2536)
ValueError: unable to create group (Symbol table: Unable to initialize object)
```
error information when call ModelCheckpoint(save_best_only=True)
```
Traceback (most recent call last):
  File "xnet.py", line 468, in <module>
    main()
  File "xnet.py", line 153, in main
    train_val_test()
  File "xnet.py", line 455, in train_val_test
    train_model_runner(i)
  File "xnet.py", line 339, in train_model_runner
    model = train_model(model,X_train,Y_train,X_val, Y_val,batch_size,opt.epoch, bestModelName+"."+str(n))
  File "xnet.py", line 256, in train_model
    X_val[:,:,:,4:Ndim] ], Y_val),shuffle=True,callbacks=[early_stopping, checkpointer])
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 620, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1119, in fit
    callback_metrics=callback_metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 857, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 42, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 298, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2423, in save
    save_model(self, filepath, overwrite)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 56, in save_model
    model.save_weights_to_hdf5_group(model_weights_group)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2458, in save_weights_to_hdf5_group
    g = f.create_group(layer.name)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py/h5g.c:2536)
ValueError: unable to create group (Symbol table: Unable to initialize object)
```

**Comment by barrykui** [comment]
1. pip install h5py --upgrade.
2. check the the layer name should not be the same.

**Comment by supernirmesh** [comment]
Did you get any solution ?
