### ISSUE TITLE
TensorBoard callback failing on_epoch_end(*)

### ISSUE THREAD

**Issue by mjdietzx** [fchollet/keras#4048]
`TypeError: 0.001 has type <class 'numpy.float32'>, but expected one of: (<class 'float'>, <class 'int'>, <class 'int'>)` raised here: https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L533

I fixed (atleast it's not failing.. haven't checked actual visualization yet) by changing L533 to `summary_value.simple_value = value.item()`.

I am running tensorflow 0.10 with GPU enabled on Ubuntu 14.04 and Python 3.4.

To reproduce just run any example with the default TensorBoard callback: `callbacks.TensorBoard(log_dir='./logs')`.

```
Traceback (most recent call last):
  File "src/models/keras_vgg16.py", line 147, in <module>
    main(False)
  File "src/models/keras_vgg16.py", line 128, in main
    cbks=cbks)
  File "/home/ubuntu/XXXXX/src/models/model_training_helpers.py", line 248, in fit_keras_model
    class_weight=class_weight)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1498, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 42, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 533, in on_epoch_end
    summary_value.simple_value = value
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 676, in setter
    field_setter(self, new_value)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 664, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/type_checkers.py", line 108, in CheckValue
    raise TypeError(message)
TypeError: 0.001 has type <class 'numpy.float32'>, but expected one of: (<class 'float'>, <class 'int'>, <class 'int'>)
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f8e26879860>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 522, in __del__
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 518, in close
  File "/usr/lib/python3.4/contextlib.py", line 126, in helper
TypeError: 'NoneType' object is not callable
```

**Comment by mjdietzx** [comment]
Also tested and failing with Python 3.5 on OS X when training with CPU (and most tensorflow 0.11.0rc).

Issue is when TensorBoard callback is called with other callbacks. While when

`cbks=[TensorBoard, EarlyStopping]` works, `cbks=[TensorBoard, ReduceLROnPlateau]` fails. Look like`ReduceLROnPlateau` is causing the problem, not sure if other callbacks cause the prob as well - i haven't tested that.
