### ISSUE TITLE
keras with tensorflow gpu raises an error

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#4057]
If i invoke command in python shell i am able to run it. 

output

> > > import keras
> > > Using TensorFlow backend.
> > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
> > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
> > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
> > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
> > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally

But when i try to run the entire program it raises the below error.

Using TensorFlow backend.
Traceback (most recent call last):
  File "lskeras3.py", line 6, in <module>
    from keras.preprocessing import sequence
  File "/usr/local/lib/python2.7/dist-packages/keras/**init**.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/**init**.py", line 64, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/**init**.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/**init**.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

**Comment by malaikannan** [comment]
Are you using sudo to run your code?? If so try it without sudo. Code that works in shell should work when you are executing entire code.
