### ISSUE TITLE
ValueError: Dimension 3 in Rebroadcast's input was supposed to be 1

### ISSUE THREAD

**Issue by xcmax** [fchollet/keras#4059]
Traceback (most recent call last):
File "F:/python/ObGraspDec/GraspRegression/GraspRegression.py", line 102, in 
model.fit(X, Y, batch_size=1, nb_epoch=1, verbose=1, shuffle=False)
File "D:\anaconda2\lib\site-packages\keras\engine\training.py", line 1106, in fit
callback_metrics=callback_metrics)
File "D:\anaconda2\lib\site-packages\keras\engine\training.py", line 824, in fit_loop
outs = f(ins_batch)
File "D:\anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 717, in __call_
return self.function(*inputs)
File "D:\anaconda2\lib\site-packages\theano-0.9.0.dev3-py2.7.egg\theano\compile\function_module.py", line 879, in call
storage_map=getattr(self.fn, 'storage_map', None))
File "D:\anaconda2\lib\site-packages\theano-0.9.0.dev3-py2.7.egg\theano\gof\link.py", line 325, in raise_with_op
reraise(exc_type, exc_value, exc_trace)
File "D:\anaconda2\lib\site-packages\theano-0.9.0.dev3-py2.7.egg\theano\compile\function_module.py", line 866, in call
self.fn() if output_subset is None else\
File "D:\anaconda2\lib\site-packages\theano-0.9.0.dev3-py2.7.egg\theano\gof\op.py", line 866, in rval
r = p(n, [x[0] for x in i], o)
File "D:\anaconda2\lib\site-packages\theano-0.9.0.dev3-py2.7.egg\theano\compile\ops.py", line 708, in perform
(axis, x.shape[axis]))
ValueError: Dimension 3 in Rebroadcast's input was supposed to be 1 (got 55 instead)
Apply node that caused the error: Rebroadcast{?,?,?,1}(GpuContiguous.0)
Toposort index: 135
Inputs types: [CudaNdarrayType(float32, (True, True, True, False))]
Inputs shapes: [(1, 1, 1, 55)]
Inputs strides: [(0, 0, 0, 1)]
Inputs values: ['not shown']
Inputs type_num: ['']
Outputs clients: [[GpuElemwise{true_div,no_inplace}(Rebroadcast{?,?,?,1}.0, GpuElemwise{Composite{sqrt((i0 + i1))},no_inplace}.0), GpuElemwise{true_di

# Code

model=AlexNet(weights_path='../weights/regression.h5')
Indice=range(0,885)
DataIndiceList = []
for i in range(0,885,10):
DataIndiceList.append(Indice[i:i + 10])
for e in range(50):
print("epoch %d" % e)
for IndiceList in DataIndiceList:
X, Y = DataUtils.LoadAugData(IndiceList[0], IndiceList[-1])
ShuffleList=range(0,len(Y))
random.shuffle(ShuffleList)
X = X[ShuffleList]
Y = Y[ShuffleList]/227.0
model.fit(X, Y, batch_size=1, nb_epoch=1, verbose=1, shuffle=False)

**Comment by xcmax** [comment]
When I change the theano version from 0.9 to 0.8, there is no error.　May be this is a bug in 0.9
