### ISSUE TITLE
Json Error in Keras

### ISSUE THREAD

**Issue by afzalal** [fchollet/keras#4153]
while importing keras ( from keras.models import Sequential)

the following error were raised
Traceback (most recent call last):
  File "/home/afzal/Deep cnn/cnn_deeplearningpgm/keras_cnn_new3.py", line 2, in <module>
    import keras
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/**init**.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/backend/**init**.py", line 29, in <module>
    _config = json.load(open(_config_path))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 5 column 25 (char 108)

I have installed theano

cud you help me to solve it

**Comment by ekolve** [comment]
I ran in to the same issue, it looks like there is a raise condition writing to the config file path and another process reading in the config file.

That change looks like it should fix it.
https://github.com/fchollet/keras/commit/a4d191d4f97a8100a561b87802fdd6ab5db0ed26

There is still the possibility that when the config file is first written another process reads the empty file before the config file is written and flushed.
