### ISSUE TITLE
ConvLSTM2D with Theano libgpuarray and cuDNN crashes

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#4305]
> KeyError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn}(Shape_i{1}.0, InplaceGpuDimShuffle{0,1,4,2,3}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, Shape_i{1}.0, InplaceGpuDimShuffle{3,2,0,1}.0, InplaceGpuDimShuffle{x,x,x,0}.0, InplaceGpuDimShuffle{3,2,0,1}.0, InplaceGpuDimShuffle{3,2,0,1}.0, InplaceGpuDimShuffle{x,x,x,0}.0, InplaceGpuDimShuffle{3,2,0,1}.0, InplaceGpuDimShuffle{3,2,0,1}.0, InplaceGpuDimShuffle{x,x,x,0}.0, InplaceGpuDimShuffle{3,2,0,1}.0, InplaceGpuDimShuffle{3,2,0,1}.0, InplaceGpuDimShuffle{x,x,x,0}.0, InplaceGpuDimShuffle{3,2,0,1}.0), '\n', 'The following error happened while compiling the node', GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'cudnn_handle')

I assume this is related to having convolution operations inside a scan. @jeammimi, @nouiz, @fchollet, what do you think? Can you get the `conv_lstm.py` example working with `THEANO_FLAGS=device=cuda` and cuDNN?

**Comment by nouiz** [comment]
Make sure to use Theano dev version. If you where using it, update it
again. I fixed a crash that could solve this problem recently.

If the problem persist, give the full error message.

**Comment by carlthome** [comment]
Problem persists with Theano's latest unfortunately (installed from GitHub master just now). Please try `python keras/examples/conv_lstm.py`, same for you?

`pip show theano`:
```sh
Name: Theano
Version: 0.9.0.dev4
Summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
Home-page: http://deeplearning.net/software/theano/
Author: LISA laboratory, University of Montreal
Author-email: theano-dev@googlegroups.com
License: BSD
Location: /home/carl/anaconda3/lib/python3.5/site-packages
Requires: numpy, scipy, six
```

`python conv_lstm.py`:
```sh
Using Theano backend.
Mapped name None to device cuda: TITAN X (Pascal)
Using cuDNN version 5105 on context None
Traceback (most recent call last):
  File "conv_lstm.py", line 104, in <module>
    nb_epoch=300, validation_split=0.05)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/keras/models.py", line 640, in fit
    sample_weight=sample_weight)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1084, in fit
    self._make_test_function()
  File "/home/carl/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 739, in _make_test_function
    **self._function_kwargs)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 821, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 807, in __init__
    **kwargs)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 1784, in orig_function
    defaults)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/vm.py", line 1057, in make_all
    impl=impl))
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/op.py", line 824, in make_c_thunk
    no_recycling=e_no_recycling)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/cc.py", line 563, in accept
    self.fetch_variables()
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/cc.py", line 589, in fetch_variables
    params = node.run_params()
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/graph.py", line 129, in run_params
    return self.op.get_params(self)
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gpuarray/dnn.py", line 215, in get_params
    ptr = get_prop(self.dnn_context(node), 'cudnn_handle').value
  File "/home/carl/anaconda3/lib/python3.5/site-packages/theano/gpuarray/type.py", line 114, in get_prop
    return _get_props(name)[k]
KeyError: ('The following error happened while compiling the node', GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'cudnn_handle')
```

**Comment by nouiz** [comment]
What Theano and Keras flag do you use?

**Comment by carlthome** [comment]
Pretty standard:

```sh
[global]
device = cuda
floatX = float32

[lib]
cnmem = 1
```

```sh
{
    "floatx": "float32",
    "backend": "theano",
    "image_dim_ordering": "th",
    "epsilon": 1e-07
}
```

Same error with `image_dim_ordering='tf'` as well.

**Comment by carlthome** [comment]
Related, I think.

```python
/home/carl/anaconda3/lib/python3.5/site-packages/keras/engine/training.py in fit_generator(self, generator, samples_per_epoch, nb_epoch, verbose, callbacks, validation_data, nb_val_samples, class_weight, max_q_size, nb_worker, pickle_safe)
   1362 
   1363         do_validation = bool(validation_data)
-> 1364         self._make_train_function()
   1365         if do_validation:
   1366             self._make_test_function()

/home/carl/anaconda3/lib/python3.5/site-packages/keras/engine/training.py in _make_train_function(self)
    722                                              [self.total_loss] + self.metrics_tensors,
    723                                              updates=updates,
--> 724                                              **self._function_kwargs)
    725 
    726     def _make_test_function(self):

/home/carl/anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py in function(inputs, outputs, updates, **kwargs)
    819                 msg = "Invalid argument '%s' passed to K.function" % key
    820                 raise ValueError(msg)
--> 821     return Function(inputs, outputs, updates=updates, **kwargs)
    822 
    823 

/home/carl/anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py in __init__(self, inputs, outputs, updates, **kwargs)
    805                                         allow_input_downcast=True,
    806                                         on_unused_input='ignore',
--> 807                                         **kwargs)
    808 
    809     def __call__(self, inputs):

/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    324                    on_unused_input=on_unused_input,
    325                    profile=profile,
--> 326                    output_keys=output_keys)
    327     # We need to add the flag check_aliased inputs if we have any mutable or
    328     # borrowed used defined inputs

/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    484                          accept_inplace=accept_inplace, name=name,
    485                          profile=profile, on_unused_input=on_unused_input,
--> 486                          output_keys=output_keys)
    487 
    488 

/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1782                    on_unused_input=on_unused_input,
   1783                    output_keys=output_keys).create(
-> 1784             defaults)
   1785 
   1786     t2 = time.time()

/home/carl/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py in create(self, input_storage, trustme, storage_map)
   1649             theano.config.traceback.limit = theano.config.traceback.compile_limit
   1650             _fn, _i, _o = self.linker.make_thunk(
-> 1651                 input_storage=input_storage_lists, storage_map=storage_map)
   1652         finally:
   1653             theano.config.traceback.limit = limit_orig

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/link.py in make_thunk(self, input_storage, output_storage, storage_map)
    697         return self.make_all(input_storage=input_storage,
    698                              output_storage=output_storage,
--> 699                              storage_map=storage_map)[:3]
    700 
    701     def make_all(self, input_storage, output_storage):

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/vm.py in make_all(self, profiler, input_storage, output_storage, storage_map)
   1055                                                  compute_map,
   1056                                                  no_recycling,
-> 1057                                                  impl=impl))
   1058                 linker_make_thunk_time[node] = time.time() - thunk_start
   1059                 if not hasattr(thunks[-1], 'lazy'):

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    922             try:
    923                 return self.make_c_thunk(node, storage_map, compute_map,
--> 924                                          no_recycling)
    925             except (NotImplementedError, utils.MethodNotDefined):
    926                 # We requested the c code, so don't catch the error.

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    822                           if old_o in no_recycling]
    823         cl = theano.gof.cc.CLinker().accept(e,
--> 824                                             no_recycling=e_no_recycling)
    825 
    826         _logger.debug('Trying CLinker.make_thunk')

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/cc.py in accept(self, fgraph, no_recycling, profile)
    561                 fgraph, no_recycling, profile)
    562         self.fgraph = fgraph
--> 563         self.fetch_variables()
    564         self.no_recycling = no_recycling
    565         return self

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/cc.py in fetch_variables(self)
    587         self.node_params = dict()
    588         for node in self.node_order:
--> 589             params = node.run_params()
    590             if params is not graph.NoParams:
    591                 # try to avoid creating more than one variable for the

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gof/graph.py in run_params(self)
    127         """
    128         if hasattr(self.op, 'get_params'):
--> 129             return self.op.get_params(self)
    130         return NoParams
    131 

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gpuarray/dnn.py in get_params(self, node)
    213         except KeyError:
    214             pass
--> 215         ptr = get_prop(self.dnn_context(node), 'cudnn_handle').value
    216         res = handle_type.make_value(ptr)
    217         set_prop(self.dnn_context(node), 'cudnn_handle_param', res)

/home/carl/anaconda3/lib/python3.5/site-packages/theano/gpuarray/type.py in get_prop(name, k)
    112 
    113 def get_prop(name, k):
--> 114     return _get_props(name)[k]
    115 
    116 

KeyError: ('The following error happened while compiling the node', GpuDnnConvGradW{algo='none', inplace=True}(GpuContiguous.0, GpuArrayConstant{[[[[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  ..., 
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]]


 [[[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  ..., 
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]]


 [[[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  ..., 
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]]


 ..., 
 [[[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  ..., 
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]]


 [[[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  ..., 
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]]


 [[[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  ..., 
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]]]}, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'cudnn_handle')
```

**Comment by carlthome** [comment]
Does anyone have any additional insight here?

**Comment by carlthome** [comment]
Related https://github.com/Theano/Theano/issues/5123

**Comment by carlthome** [comment]
Annoyingly, downgrading (e.g. `pip install git+git://github.com/theano/theano@1dabf8540db2f5eda4a80c2798848c12836642c1`) is the best fix I could come up with at the moment. :cry:

**Comment by abergeron** [comment]
I've tried to reproduce this, but I get a different error:
```
$ THEANO_FLAGS=floatX=float32,device=cuda0 python conv_lstm.py 
Using Theano backend.
Mapped name None to device cuda0: GeForce GTX 750 Ti
PCI Bus ID: 0000:07:00.0
Using cuDNN version 5105 on context None
/home/anakha/ext/keras/keras/layers/convolutional_recurrent.py:279: UserWarning: Be carefull if used with convolution3D layers:
th in convolution 3D corresponds to (samples, channels, conv_dim1, conv_dim2,conv_dim3)
while for this network it corresponds to: (samples, time, channels, rows, cols)
  warnings.warn('Be carefull if used with convolution3D layers:\n'
/home/anakha/ext/keras/keras/layers/convolutional_recurrent.py:279: UserWarning: Be carefull if used with convolution3D layers:
th in convolution 3D corresponds to (samples, channels, conv_dim1, conv_dim2,conv_dim3)
while for this network it corresponds to: (samples, time, channels, rows, cols)
  warnings.warn('Be carefull if used with convolution3D layers:\n'
Traceback (most recent call last):
  File "conv_lstm.py", line 104, in <module>
    nb_epoch=300, validation_split=0.05)
  File "/home/anakha/ext/keras/keras/models.py", line 642, in fit
    sample_weight=sample_weight)
  File "/home/anakha/ext/keras/keras/engine/training.py", line 1062, in fit
    batch_size=batch_size)
  File "/home/anakha/ext/keras/keras/engine/training.py", line 1000, in _standardize_user_data
    check_loss_and_target_compatibility(y, self.loss_functions, self.internal_output_shapes)
  File "/home/anakha/ext/keras/keras/engine/training.py", line 215, in check_loss_and_target_compatibility
    ' while using as loss `' + loss.__name__ + '`. '
Exception: A target array with shape (1000, 15, 40, 40, 1) was passed for an output of shape (None, None, 40, 40, 1) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output
```

**Comment by carlthome** [comment]
@kilotaras, https://github.com/fchollet/keras/commit/6b04add93209f557e265bbd04ab34d5491d463f0 probably introduced @abergeron's problem with examples/conv_lstm.py

Shouldn't the shape checking ignore `None`? `None` is used for allowing variable lengths during shape inference.

**Comment by kilotaras** [comment]
@carlthome sorry my bad, I was checking wrong parameter for None. Will prepare PR with fix (and test) in a couple of minutes.

**Comment by kilotaras** [comment]
The fix is in #4458

**Comment by abergeron** [comment]
I tried with the current master of Theano, libgpuarray and keras (with the fix in #4458 on top) and I don't get an error.

**Comment by carlthome** [comment]
Curious, I did a reinstall of Theano, Keras and libgpuarray from their respective master branches just now. All tests with `python -c "import pygpu; pygpu.test()"` passes but I still get the same error when running conv_lstm.py:

```py
KeyError: ('The following error happened while compiling the node', GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', 'cudnn_handle')
```

I think this might be related with that my particular graphics card is very recent. If I force cuDNN with THEANO_FLAGS, warnings and errors pop up:

```sh
RuntimeError: You enabled cuDNN, but we aren't able to use it: Can not compile with cuDNN. We got this error:
b"nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).\n/usr/bin/ld: /tmp/tmpxft_00007474_00000000-4_try_flags_4_lxnpcb.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC\n/usr/bin/ld: final link failed: Nonrepresentable section on output\ncollect2: error: ld returned 1 exit status\n"
```

**Comment by nouiz** [comment]
What is your GPU? Part of the error tell the opposite, that it is old.

What is your GPU and cuda version? Maybe you need a more recent cuda/driver
for your GPU.

**Comment by carlthome** [comment]
Solved!

I'm on Ubuntu 16.04. For CUDA 7.5, if you recall, the gcc version had to be no newer than 4.9, so many of us set update-alternatives to prefer that version. Now, with CUDA 8 [nvcc wants a newer gcc](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz3x7mwvZrG) so the solution was simply to configure update-alternatives accordingly.

One would also have to clear Theano's compile cache most likely (`theano-cache purge`).
