### ISSUE TITLE
Error when applying activity regularization on TimeDistributed(Dense(...))

### ISSUE THREAD

**Issue by vsmelov** [fchollet/keras#4394]
Hello
I have latest keras and tensorflow packages

```
Keras==1.1.1
tensorflow==0.11.0rc0
```

My code is:

```
inputs = Input(shape=(None, Nin))
encoded = TimeDistributed(
    Dense(n_features,
          activation='relu',
          activity_regularizer=activity_l1l2(0.01, -0.01)
     )
)(inputs)
```

But when I run it, i got error:

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 850M, pci bus id: 0000:0a:00.0)
Traceback (most recent call last):
  File "train_conv_autoencoder.py", line 27, in <module>
    autoencoder, encoder, decoder = get_conv_encoder()
  File "/neural-music/model/get_autoencoder.py", line 107, in get_conv_encoder
    )(encoded)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 100, in build
    super(TimeDistributed, self).build()
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 28, in build
    regularizer.set_layer(self)
  File "/usr/local/lib/python2.7/dist-packages/keras/regularizers.py", line 113, in set_layer
    raise Exception('Regularizers cannot be reused')
Exception: Regularizers cannot be reused
```

I tried to apply regularization on wrapper TimeDistributed
this way:

```
encoded = TimeDistributed(
        Dense(n_features),
        activity_regularizer=activity_l1l2(0.01, -0.01)
)(encoded)
```

but get error:

```
Traceback (most recent call last):
  File "train_conv_autoencoder.py", line 27, in <module>
    autoencoder, encoder, decoder = get_conv_encoder()
  File "/neural-music/model/get_autoencoder.py", line 107, in get_conv_encoder
    activity_regularizer=activity_l1l2(0.01, -0.01)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 91, in __init__
    super(TimeDistributed, self).__init__(layer, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 10, in __init__
    super(Wrapper, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 307, in __init__
    assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' + kwarg
AssertionError: Keyword argument not understood: activity_regularizer
```

How can I apply activity regularization on TimeDistributed(Dense(...))?

**Comment by vsmelov** [comment]
By the way, may be my question is related to this [https://github.com/MoyanZitto/keras-cn/issues/12](Issue)
But I dont understand this issue completely.

**Comment by vsmelov** [comment]
Why it does set_layer for Wrapped layer here [https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py#L26](line 26-28) while Dense layer already did it here [https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L714](line 714) ?

I commented line 26-28 in wrappers.py and it works fine
