### ISSUE TITLE
Simplest Xception model broken (TF, Windows 7, Python 3.5)

### ISSUE THREAD

**Issue by isaacgerg** [fchollet/keras#4478]
**Windows 7, Python 3.5, fresh github pull**

```
import keras.applications
from keras.layers import Input
model = keras.applications.xception.Xception(include_top=True, weights='imagenet', input_tensor=Input(shape=(299, 299, 3)))    
```
yields the following when I run in Wing IDE

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'DepthwiseConv2dNative' with these attrs. Registered devices: [CPU,GPU], Registered kernels:
<no registered kernels>
[[Node: separable_conv2d/depthwise = DepthwiseConv2dNative[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1]](Relu_1, block2_sepconv1_depthwise_kernel/read)]]
Caused by op 'separable_conv2d/depthwise'
```
and the following when i run at the python command line.

```
Traceback (most recent call last):
  File "c:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "c:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 999, in _run_fn
    self._extend_graph()
  File "c:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1048, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "c:\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "c:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'MatMul_1': Unknown input node 'Mean_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python35\lib\site-packages\keras\applications\xception.py", line 199, in Xception
    model.load_weights(weights_path)
  File "c:\Python35\lib\site-packages\keras\engine\topology.py", line 2500, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "c:\Python35\lib\site-packages\keras\engine\topology.py", line 2585, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "c:\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 995, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "c:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "c:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "c:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "c:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'MatMul_1': Unknown input node 'Mean_1'
```

Supplanting Xception with VGGnet, everything works fine.

`model = keras.applications.vgg16.VGG16(include_top=True, weights='imagenet', input_tensor=Input(shape=(224, 224, 3)))
`
No errors.

@nafizh ran on mac OS with keras 1.1.1 and python 2.7.12 and he had no error.

**Comment by mrry** [comment]
This is at least partly due to TensorFlow issue (https://github.com/tensorflow/tensorflow/issues/5818): the DepthwiseConv2DNative kernel isn't currently included in the TensorFlow build on Windows.

**Comment by isaacgerg** [comment]
this one should still work.  Its a graph connection issue.
https://github.com/fchollet/keras/issues/4477

**Comment by isaacgerg** [comment]
I should add that it seems prepending any amount of network in front of
that resnet50 example bombs.  For example, putting dropout before it.
