### ISSUE TITLE
ValueError in example code for Variational Autoencoder

### ISSUE THREAD

**Issue by sourabhd** [fchollet/keras#4508]
Keras version : 1.1.1 (latest)
Tensorflow version: 0.10.0
CUDA version: 7.5
CUDNN version: 5.0.5
Python version : 2.7

https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py#L47

On changing line 47:
  return xent_loss + kl_loss
to:
 return kl_loss

I see the following error

CUDA_VISIBLE_DEVICES=3 python variational_autoencoder.py
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "variational_autoencoder.py", line 65, in <module>
    validation_data=(x_test, x_test))
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1083, in fit
    self._make_train_function()
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/keras/engine/training.py", line 696, in _make_train_function
    self.total_loss)
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/keras/optimizers.py", line 213, in get_updates
    new_a = self.rho * a + (1. - self.rho) * K.square(g)
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 576, in square
    return tf.square(x)
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 345, in square
    return gen_math_ops.square(x, name=name)
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2228, in square
    result = _op_def_lib.apply_op("Square", x=x, name=name)
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 458, in apply_op
    as_ref=input_arg.is_ref).dtype.name
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 628, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/users/sourabh.d/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 346, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by sumethy** [comment]
Similar problem, I run the example code in variational_autoencoder.py without any modification and got the following error

/home/sumeth/miniconda3/envs/tf/lib/python3.5/site-packages/keras/engine/topology.py:1519: UserWarning: Model inputs must come from a Keras Input layer, they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "model_1" was not an Input tensor, it was generated by layer custom_variational_layer_1.
Note that input tensors are instantiated via `tensor = Input(shape)`.
The tensor that caused the issue was: input_1:0
  str(x.name))
variational_autoencoder.py:66: UserWarning: Output "custom_variational_layer_1" missing from loss dictionary. We assume this was done on purpose, and we will not be expecting any data to be passed to "custom_variational_layer_1" during training.
  vae.compile(optimizer='rmsprop', loss=None)
Traceback (most recent call last):
  File "variational_autoencoder.py", line 81, in <module>
    validation_data=(x_test, x_test))
  File "/home/sumeth/miniconda3/envs/tf/lib/python3.5/site-packages/keras/engine/training.py", line 1426, in fit
    batch_size=batch_size)
  File "/home/sumeth/miniconda3/envs/tf/lib/python3.5/site-packages/keras/engine/training.py", line 1300, in _standardize_user_data
    exception_prefix='model target')
  File "/home/sumeth/miniconda3/envs/tf/lib/python3.5/site-packages/keras/engine/training.py", line 100, in _standardize_input_data
    'Found: array with shape ' + str(data.shape))
ValueError: The model expects 0 input arrays, but only received one array. Found: array with shape (10000, 784)

Environment: keras 2.0.3, tf 1.0.1, Anaconda3, python 3.5

**Comment by ZhaohuiXue** [comment]
Similar problem.

**Comment by acorbe** [comment]
same here. Any improvement?

**Comment by augustkx** [comment]
Similar problems.
