### ISSUE TITLE
error on basic binary classification.

### ISSUE THREAD

**Issue by andrewcz** [fchollet/keras#4521]
hi all trying to run the following script and need some help :).

from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
import numpy
import pandas as pd
 
# Function to create model, required for KerasClassifier
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=8, init='uniform', activation='relu'))
	model.add(Dense(8, init='uniform', activation='relu'))
	model.add(Dense(1, init='uniform', activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

dataset = pd.read_csv("/home/andrewcz/Downloads/numerai_test/numerai/train.csv")
array= dataset.values

# split into input (X) and output (Y) variables
X = array[:,0:20]
Y = array[:,21]

# create model
model = KerasClassifier(build_fn=create_model, nb_epoch=150, batch_size=10, verbose=0)
# evaluate using 10-fold cross validation
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

this get the following

Using TensorFlow backend.
Traceback (most recent call last):
  File "test2.py", line 39, in <module>
    results = cross_val_score(model, X, Y, cv=kfold)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/model_selection/_validation.py", line 140, in cross_val_score
    for train, test in cv_iter)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/sklearn/model_selection/_validation.py", line 238, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/wrappers/scikit_learn.py", line 148, in fit
    history = self.model.fit(X, y, **fit_args)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/models.py", line 652, in fit
    sample_weight=sample_weight)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1038, in fit
    batch_size=batch_size)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/engine/training.py", line 963, in _standardize_user_data
    exception_prefix='model input')
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/engine/training.py", line 111, in standardize_input_data
    str(array.shape))
Exception: Error when checking model input: expected dense_input_1 to have shape (None, 8) but got array with shape (86687, 20)

**Comment by JimBiardCics** [comment]
The exception is correct. You gave it an (N,20) input shape, but your first Dense layer expects an (N,8) shape - the input_dim argument is 8. The two dimensionalities must match.
