### ISSUE TITLE
Compiling error using GPU

### ISSUE THREAD

**Issue by ruanxt** [fchollet/keras#4558]
When running the example from https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py

 in a system with GPU. It cannot be compiled. But when I run it in CPU mode, it works. The error info is

```
Problem occurred during compilation with the command line below:
/opt/gcc/4.9.2/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=15360 -mtune=generic -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/numpy/core/include -I/opt/python27/include/python2.7 -I/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof -L/opt/python27/lib -fvisibility=hidden -o /home/ruanxt/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-2.7.4-64/tmp0iOZzc/d16654b784f584f17fdc481825fd2cca.so /home/ruanxt/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-2.7.4-64/tmp0iOZzc/mod.cpp -lpython2.7
/tmp/ccZCQd93.s: Assembler messages:
/tmp/ccZCQd93.s:2977: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/ccZCQd93.s:2987: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rsi)'
/tmp/ccZCQd93.s:2989: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/ccZCQd93.s:2991: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rsi)'

Traceback (most recent call last):
  File "vae_keras_example.py", line 34, in <module>
    z = Lambda(sampling, output_shape=(latent_dim,))([z_mean, z_log_var])
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/keras/engine/topology.py", line 517, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/keras/engine/topology.py", line 571, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/keras/engine/topology.py", line 160, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/keras/layers/core.py", line 587, in call
    return self.function(x, **arguments)
  File "vae_keras_example.py", line 30, in sampling
    std=epsilon_std)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1733, in random_normal
    return rng.normal(size=shape, avg=mean, std=std, dtype=dtype)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 1544, in normal
    nstreams=nstreams)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 1354, in uniform
    rstates = self.get_substream_rstates(nstreams, dtype)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/configparser.py", line 115, in res
    return f(*args, **kwargs)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 1256, in get_substream_rstates
    multMatVect(rval[0], A1p72, M1, A2p72, M2)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 66, in multMatVect
    [A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym], o, profile=False)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/compile/function_module.py", line 1784, in orig_function
    defaults)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/vm.py", line 1059, in make_all
    impl=impl))
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/cc.py", line 1492, in compile_cmodule
    preargs=preargs)
  File "/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2323, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', "Compilation failed (return status=1): /tmp/ccZCQd93.s: Assembler messages:. /tmp/ccZCQd93.s:2977: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'. /tmp/ccZCQd93.s:2987: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rsi)'. /tmp/ccZCQd93.s:2989: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'. /tmp/ccZCQd93.s:2991: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rsi)'. ", '[DotModulo(A, s, m, A2, s2, m2)]')

```

Could anyone help? Thanks!

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [X ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by patyork** [comment]
This appears to be an issue with GCC or the Theano build, see [here](https://github.com/Theano/Theano/issues/3873#issuecomment-224918432).

Could you let us know if this is in fact on a Mac, and what GPU you are using?

**Comment by ruanxt** [comment]
I'm using CentOS 6.5 with gcc version 4.9. The gpu version is GeForce GTX 1080 

And this is the warning info before the error info:

```
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5105)
/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/tensor/basic.py:5759: UserWarning: Warning, Cannot compute test value: input 0 (input_1) of Op dot(input_1, HostFromGpu.0) missing default value
  return _dot(a, b)
/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/tensor/var.py:137: UserWarning: Warning, Cannot compute test value: input 0 (dot.0) of Op Elemwise{add,no_inplace}(dot.0, InplaceDimShuffle{x,0}.0) missing default value
  return theano.tensor.basic.add(self, other)
/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/tensor/var.py:38: UserWarning: Warning, Cannot compute test value: input 0 (Elemwise{add,no_inplace}.0) of Op Elemwise{abs_,no_inplace}(Elemwise{add,no_inplace}.0) missing default value
  return theano.tensor.basic.abs_(self)
/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/tensor/var.py:137: UserWarning: Warning, Cannot compute test value: input 0 (Elemwise{add,no_inplace}.0) of Op Elemwise{add,no_inplace}(Elemwise{add,no_inplace}.0, Elemwise{abs_,no_inplace}.0) missing default value
  return theano.tensor.basic.add(self, other)
/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/tensor/var.py:137: UserWarning: Warning, Cannot compute test value: input 1 (Elemwise{abs_,no_inplace}.0) of Op Elemwise{add,no_inplace}(Elemwise{add,no_inplace}.0, Elemwise{abs_,no_inplace}.0) missing default value
  return theano.tensor.basic.add(self, other)
/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/tensor/var.py:242: UserWarning: Warning, Cannot compute test value: input 1 (Elemwise{add,no_inplace}.0) of Op Elemwise{mul,no_inplace}(InplaceDimShuffle{x,x}.0, Elemwise{add,no_inplace}.0) missing default value
  return theano.tensor.basic.mul(other, self)
/home/ruanxt/tests/theano_env/lib/python2.7/site-packages/theano/tensor/basic.py:5759: UserWarning: Warning, Cannot compute test value: input 0 (Elemwise{mul,no_inplace}.0) of Op dot(Elemwise{mul,no_inplace}.0, HostFromGpu.0) missing default value
  return _dot(a, b)
```

**Comment by patyork** [comment]
Did you build theano and keras from source, or use a build for your distribution? From what I've seen, this is an issue when building Theano with an incorrect compiler.

**Comment by ruanxt** [comment]
I'm using virtualenv, and use pip to install both keras and theano. To submit the issue, I updated them to the newest version, but there is still the error.

**Comment by ruanxt** [comment]
I think the problem should be in the code. When I run this piece of code, it works well with GPU. 

```
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import load_model
from keras.callbacks import ModelCheckpoint
from keras.datasets import mnist
import numpy as np

image_dim = 784;
batch_size = 10;
input_img = Input(shape=(image_dim,))

encoded = Dense(256, activation='relu')(input_img)
encoded = Dense(64, activation='relu')(encoded)
encoded = Dense(16, activation='relu')(encoded)
encoded = Dense(4, activation='relu')(encoded)

#decoding
decoded = Dense(16, activation='relu')(encoded)
decoded = Dense(64, activation='relu')(decoded)
decoded = Dense(256, activation='relu')(decoded)
decoded = Dense(image_dim, activation='sigmoid')(decoded)

autoencoder = Model(input=input_img, output=decoded)

autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

'''
saves the model weights after each epoch if the validation loss decreased
'''
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = x_train.reshape((len(x_train), np.prod(x_train.shape[1:])))
x_test = x_test.reshape((len(x_test), np.prod(x_test.shape[1:])))


model_path = "weights.hdf5"
checkpointer = ModelCheckpoint(filepath=model_path, verbose=1)

autoencoder.fit(x_train, x_train,
        shuffle=True,
        nb_epoch=100,
        batch_size=batch_size,
        validation_data=(x_test, x_test),
        callbacks=[checkpointer])
```

**Comment by nouiz** [comment]
Make sure to use the dev version of Theano, not the last release.

We have work around gcc bug in Theano.

**Comment by ruanxt** [comment]
Actually I'm using the dev version of Theano.
