### ISSUE TITLE
Backwards LSTM + Embedding + Mask + Tensorflow backend produces "ValueError: Shape must be rank 2 but is rank 3 for 'Reverse' (op: 'Reverse') with input shapes:" 

### ISSUE THREAD

**Issue by stefanthaler** [fchollet/keras#4570]
When I create a model that contains an Embedding layer with masking and a backwards LSTM and using the Tensorflow backend, I get the following error: 

> ValueError: Shape must be rank 2 but is rank 3 for 'Reverse' (op: 'Reverse') with input shapes: [3,2,40], [2].

I've created a [gist](https://gist.github.com/stefanthaler/6120be321431cb8506429d4c635d530b) that reproduces the error. 

I suspect it has something to do with these two lines in the tensorflow_backend.py, where one time ndim-1 is used and the other time ndim-2 is used.   
https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L1248
https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L1273

The complete stacktrace is:

 > File "stateful_lstm_embedding_butg.py", line 18, in <module>
    model.add(LSTM(10,  batch_input_shape=(batch_size,time_steps,embedding_size), return_sequences=False, go_backwards=True))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 324, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 517, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 571, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 155, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 227, in call
    input_length=input_shape[1])
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1249, in rnn
    inputs = tf.reverse(inputs, [True] + [False] * (ndim - 2))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2513, in reverse
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 2 but is rank 3 for 'Reverse' (op: 'Reverse') with input shapes: [3,2,40], [2].

**Comment by fchollet** [comment]
Fixed, thank you for the report.

**Comment by dylanrandle** [comment]
Hi, When I create a network with Bidirectional LSTM I get a similar error: 

Traceback (most recent call last):
  File "char_level_amount.py", line 190, in <module>
    model.add(Bidirectional(LSTM(128, return_sequences = True), input_shape = (None, MAX_CHAR_STRING_LENGTH, len(chars))))
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 433, in add
    layer(x)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 585, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/wrappers.py", line 263, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/recurrent.py", line 288, in call
    initial_state = self.get_initial_state(inputs)
  File "/usr/local/lib/python3.4/dist-packages/keras/layers/recurrent.py", line 230, in get_initial_state
    initial_state = K.tile(initial_state, [1, self.units])  # (samples, output_dim)
  File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 1872, in tile
    return tf.tile(x, n)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3677, in tile
    name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 3 but is rank 2 for 'bidirectional_1/Tile' (op: 'Tile') with input shapes: [?,182,1], [2].

The error occurs in the first layer of the model. 

model = Sequential()
#model.add(BatchNormalization())
model.add(Bidirectional(LSTM(128, return_sequences = True), input_shape = (None, MAX_CHAR_STRING_LENGTH, len(chars))))
model.add(Bidirectional(LSTM(128, return_sequences = True)))
model.add(TimeDistributed(Dense(2)))
model.add(Activation('softmax'))
model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

**Comment by Helw150** [comment]
@dylanrandle Did you ever solve your bug? I have the same error and am attempting to debug.

**Comment by grafael** [comment]
@Helw150  @dylanrandle  I'm getting the same error.. Did you find the solution?

**Comment by gabrielepozzati** [comment]
@grafael @Helw150 @dylanrandle same issue here ... 

Traceback (most recent call last):
  File "/home/gabriele/Desktop/codes/rec_trainer.py", line 61, in <module>
    model = model1(int(ns.c), pos)
  File "/home/gabriele/Desktop/codes/rec_trainer.py", line 29, in model1
    merge_mode='concat'))   
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/models.py", line 492, in add
    output_tensor = layer(self.outputs[0])
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/layers/wrappers.py", line 315, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/layers/recurrent.py", line 2032, in call
    initial_state=initial_state)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/layers/recurrent.py", line 546, in call
    initial_state = self.get_initial_state(inputs)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/layers/recurrent.py", line 479, in get_initial_state
    for dim in self.cell.state_size]
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/layers/recurrent.py", line 479, in <listcomp>
    for dim in self.cell.state_size]
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2094, in tile
    return tf.tile(x, n)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5691, in tile
    "Tile", input=input, multiples=multiples, name=name)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/gabriele/miniconda3/envs/nnmanG/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 3 but is rank 2 for 'bidirectional_1/Tile' (op: 'Tile') with input shapes: [?,50,1], [2].

def model1(chain, pos):
    model = Sequential()
    model.add(Embedding(20, 50, embeddings_initializer='uniform', input_length=pos))
    model.add(Reshape((chain, 400, 50)))
    model.add(Bidirectional(LSTM(20, activation='relu', recurrent_activation='relu', 
                                 kernel_initializer='uniform', recurrent_initializer='uniform', 
                                 return_sequences=True), 
                            merge_mode='concat'))   
    model.add(TimeDistributed(Dense(1, kernel_initializer='Orthogonal', activation='linear')))
    model.compile(loss='mean_absolute_error', optimizer = 'adam')
    return model
