### ISSUE TITLE
Cannot load 1.1.1 model using 1.1.2

### ISSUE THREAD

**Issue by thefiddler** [fchollet/keras#4578]
I exported a model to .yml using keras 1.1.1. When I try to load it using 1.1.2, I get the following exception:
```
Traceback (most recent call last):
  File "~/test/network.py", line 32, in get_model
    model = model_from_yaml(loaded_model_yml)
  File "~/.virtualenvs/test/lib/python3.5/site-packages/keras/models.py", line 199, in model_from_yaml
    return layer_from_config(config, custom_objects=custom_objects)
  File "~/.virtualenvs/test/lib/python3.5/site-packages/keras/utils/layer_utils.py", line 34, in layer_from_config
    return layer_class.from_config(config['config'])
  File "~/.virtualenvs/test/lib/python3.5/site-packages/keras/engine/topology.py", line 2395, in from_config
    process_layer(layer_data)
  File "~/.virtualenvs/test/lib/python3.5/site-packages/keras/engine/topology.py", line 2373, in process_layer
    custom_objects=custom_objects)
  File "~/.virtualenvs/test/lib/python3.5/site-packages/keras/utils/layer_utils.py", line 34, in layer_from_config
    return layer_class.from_config(config['config'])
  File "~/.virtualenvs/test/lib/python3.5/site-packages/keras/engine/topology.py", line 1467, in from_config
    output_mask_type = config.pop('output_mask_type')
KeyError: 'output_mask_type'
```

This occurs on both the tensorflow and theano backends. The error appears to be caused by these lines, which don't exist in keras 1.1.1: [topology.py:1467](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1467-L1473)

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Dapid** [comment]
Does it happen with every model? If not, how is the model defined?

**Comment by fchollet** [comment]
This should be fixed now: https://github.com/fchollet/keras/commit/78988b5cd67d066bb4c9c6c29b636331e4f78c4d

Thanks for the report.
