### ISSUE TITLE
Import error with keras and theano

### ISSUE THREAD

**Issue by MrWanter** [fchollet/keras#4616]
My keras works fine with theano and GPU, but this morning, after I upgrade keras and theano with:
```
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
```
and run `import theano`, it first raise an error of:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 79, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 71, in <module>
    from theano.scan_module import scan_op
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 58, in <module>
    from six import iteritems, integer_types, raise_from
ImportError: cannot import name raise_from
```
then run `import theano` again, it raise the error of:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 79, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
ImportError: cannot import name tensor
```
run import keras, it first raise an error of:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 66, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 79, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 71, in <module>
    from theano.scan_module import scan_op
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 58, in <module>
    from six import iteritems, integer_types, raise_from
ImportError: cannot import name raise_from
```
then run `import keras` again, it raise the error of:
```
Using Theano backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 66, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 79, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
ImportError: cannot import name tensor
```
I'm really puzzled about this problem, had anyone encountered this problem before? thanks in advance!

**Comment by patyork** [comment]
Try running `from six import raise_from`. If you can't run that, then either upgrade six manually, or rerun your upgrades without the `--no-deps` flag.

**Comment by MrWanter** [comment]
Thank you, I tried `from six import raise_from`, the result is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name raise_from
```
then I upgrade six by `sudo pip install six --upgrade`, but it still cannot work, then I rerun:
```
pip install git+git://github.com/Theano/Theano.git --upgrade
pip install git+git://github.com/fchollet/keras.git --upgrade
```
after a bunch of installation, I tried `import theano` and `import keras`, it still raise the error information as before.

**Comment by MrWanter** [comment]
by the way, with the code:
```
pip install git+git://github.com/Theano/Theano.git --upgrade
pip install git+git://github.com/fchollet/keras.git --upgrade
```
it installs numpy, scipy ,six and theano again.

**Comment by charles96322** [comment]
Could you find an answer to your problem? I'm having the same issue...

**Comment by afshindn** [comment]
You need to update the six library manually. For some reason it won't work if you use pip install. 
Download the package from here: https://pypi.python.org/pypi/six#downloads
cd DownloadLoc/six-1.10.0
sudo python setup.py install

**Comment by vsmolyakov** [comment]
Upgrading the six library manually helped resolve the issue.

**Comment by hadasbgu** [comment]
I am also having the same issue, but can't understand how to manually install six,
It is already installed in my computer, but with different version: 1.5.2
what should I do?
