### ISSUE TITLE
examples/mnist_swwae.py crashes

### ISSUE THREAD

**Issue by ahundt** [fchollet/keras#4694]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano,... (I'm running on tensorflow)

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I successfully ran `python mnist_cnn.py` from 7e2e7a5e5a43443122df0b497f88dd77fd3bfc7c on my GTX1080 with a TensorFlow R0.12rc0 backend. I then ran `python mnist_swwae.py` and got the following failure:

```bash
~/src/keras/examples on master
± python mnist_swwae.py
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Traceback (most recent call last):
  File "mnist_swwae.py", line 136, in <module>
    y = MaxPooling2D(pool_size=(pool_sizes[i], pool_sizes[i]))(y_prepool)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/topology.py", line 517, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/topology.py", line 571, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/topology.py", line 155, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/layers/pooling.py", line 158, in call
    dim_ordering=self.dim_ordering)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/layers/pooling.py", line 207, in _pooling_function
    border_mode, dim_ordering, pool_mode='max')
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/backend/tensorflow_backend.py", line 1853, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1617, in max_pool
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1598, in _max_pool
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'MaxPool' (op: 'MaxPool') with input shapes: [?,1,32,8].
-> [1]
```

Help or feedback from anyone is welcome, @antonmbk you may be interested in this because you contributed the example. Thanks!

**Comment by fchollet** [comment]
I can confirm. @antonmbk, thoughts?

**Comment by fchollet** [comment]
This specific issue is due to the example being written under the assumption `image_dim_ordering="th"` (it should be made compatible with both modes). However, this is not the only issue with TF. There are further bugs.

**Comment by fchollet** [comment]
The other bug is that the model is taking the gradient of a gradient, which isn't supported for all ops in TF. In particular MaxPool.

**Comment by fchollet** [comment]
If this isn't easily fixable, then the example should include a check for the current backend and raise a helpful exception with TF. Also, start with `K.set_image_dim_ordering('th')`.

**Comment by ahundt** [comment]
@fchollet would a feature request issue in https://github.com/tensorflow/tensorflow for MaxPool gradient of a gradient make sense?

**Comment by fchollet** [comment]
@ahundt yes it would, you should post one.

For the time being, I have "fixed" the example by doing what I mentioned above.

**Comment by ahundt** [comment]
created https://github.com/tensorflow/tensorflow/issues/6294

**Comment by ahundt** [comment]
Looks like this is already in progress:
https://github.com/tensorflow/tensorflow/issues/6143

With a pull request in progress:
https://github.com/tensorflow/tensorflow/pull/6299

**Comment by antonmbk** [comment]
Just seeing this, thanks for bringing it up @ahundt.  I'm hoping the tf people fix this in that PR you mentioned.

**Comment by ahundt** [comment]
pull request update:
https://github.com/tensorflow/tensorflow/pull/6664

hopefully the relevant day is getting closer... should this perhaps be reopened since the real fix doesn't seem too far away?

**Comment by ahundt** [comment]
@antonmbk @fchollet tensorflow/tensorflow#6664 is merged to master so maxpool grad grad should work, can this be reopened? Will a tf version check be appropriate so the error message appears only when appropriate?
