### ISSUE TITLE
An error occured when run babi_memnn.py in theano backend, but in tensorflow backend it's ok

### ISSUE THREAD

**Issue by EncodeTS** [fchollet/keras#4714]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Here is the [code](https://github.com/fchollet/keras/blob/master/examples/babi_memnn.py).
In theano backend, when I run babi_memnn.py, it reminds me the follow error. However, when use tensorflow backend everything is ok.
```
Traceback (most recent call last):
  File "babi_memnn.py", line 210, in <module>
    validation_data=([inputs_test, queries_test, inputs_test], answers_test))
  File "/home/ts/anaconda3/lib/python3.5/site-packages/keras/models.py", line 664, in fit
    sample_weight=sample_weight)
  File "/home/ts/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1086, in fit
    self._make_train_function()
  File "/home/ts/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 705, in _make_train_function
    **self._function_kwargs)
  File "/home/ts/anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 884, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/ts/anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 870, in __init__
    **kwargs)
  File "/home/ts/anaconda3/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/ts/anaconda3/lib/python3.5/site-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/home/ts/anaconda3/lib/python3.5/site-packages/theano/compile/pfunc.py", line 188, in rebuild_collect_shared
    (store_into, update_d[store_into]))
ValueError: ('this shared variable already has an update expression', (embedding_2_W, GpuFromHost.0))

```

**Comment by fchollet** [comment]
This is now fixed.
