### ISSUE TITLE
Can't do 'load_model' on custom loss function which uses tensor from out of the loss function

### ISSUE THREAD

**Issue by calanchue** [fchollet/keras#4798]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
gist codes : https://gist.github.com/calanchue/424cb03d3f205817e282249b4f1f50c6
Keras + theano + window

It is somewhat related to capability of the keras, I'm posting here.

What i try to do is that load and save variational autoencoder which is presented at example of the keras. I made little change for sampling to save the sampling layer(wrote arguments field). but except that, All other model things are intact.

But it gives me weird theano error(posted below). It seems that it can't find input tensor when it recreate model from saved file. After little experiments, my guess is that this bug comes from that vae_loss function use outer tensor which is not provided as the function input.  it seems that Keras can't find those tensor after load it. Other custom loss functions which only use only input tensor works fine.

Are there any way to load those kind of loss function with Keras? 

Error message when the code try to load
```
load
Traceback (most recent call last):

File "<ipython-input-19-49e8c8795740>", line 109, in <module>
vae_loaded = load_model("test_vae", custom_objects={"vae_loss":vae_loss})

File "C:\Users\user\Anaconda2\lib\site-packages\keras\models.py", line 163, in load_model
model._make_train_function()

File "C:\Users\user\Anaconda2\lib\site-packages\keras\engine\training.py", line 723, in _make_train_function
**self._function_kwargs)

File "C:\Users\user\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 787, in function
return Function(inputs, outputs, updates=updates, **kwargs)

File "C:\Users\user\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 773, in __init__
**kwargs)

File "C:\Users\user\Anaconda2\lib\site-packages\theano\compile\function.py", line 322, in function
output_keys=output_keys)

File "C:\Users\user\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 480, in pfunc
output_keys=output_keys)

File "C:\Users\user\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1783, in orig_function
output_keys=output_keys).create(

File "C:\Users\user\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1435, in __init__
accept_inplace)

File "C:\Users\user\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 176, in std_fgraph
update_mapping=update_mapping)

File "C:\Users\user\Anaconda2\lib\site-packages\theano\gof\fg.py", line 181, in __init__
self.__import_r__(output, reason="init")

File "C:\Users\user\Anaconda2\lib\site-packages\theano\gof\fg.py", line 376, in __import_r__
self.__import__(variable.owner, reason=reason)

File "C:\Users\user\Anaconda2\lib\site-packages\theano\gof\fg.py", line 418, in __import__
variable=r)

MissingInputError: An input of the graph, used to compute dot(input_12, HostFromGpu.0), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.

Backtrace when the variable is created:
File "C:\Users\user\Anaconda2\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
File "C:\Users\user\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2705, in run_cell
interactivity=interactivity, compiler=compiler, result=result)
File "C:\Users\user\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2809, in run_ast_nodes
if self.run_code(code, result):
File "C:\Users\user\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2869, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-19-49e8c8795740>", line 23, in <module>
x = Input(batch_shape=(batch_size, original_dim))
File "C:\Users\user\Anaconda2\lib\site-packages\keras\engine\topology.py", line 1091, in Input
input_tensor=tensor)
File "C:\Users\user\Anaconda2\lib\site-packages\keras\engine\topology.py", line 1010, in __init__
name=self.name)
File "C:\Users\user\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 84, in placeholder
x = T.TensorType(dtype, broadcast)(name)
```

It seems that it can't calculate

**Comment by OOMMYY** [comment]
I got this error too.
I fix this error by add a Session for my tf:
import tensorflow as tf
with tf.Session:
      //you code

**Comment by OOMMYY** [comment]
https://www.tensorflow.org/api_docs/python/tf/Session

**Comment by FlatErik90** [comment]
I have the same problem of not being able to load the model produced by the variational autoencoder example. The only changes I did are regarding the input dimension and consequential parameter adjustments. 

The error I get is different, however, the problem seems to be connected to the vae_loss, too.

> I got this error too.
> I fix this error by add a Session for my tf:
> import tensorflow as tf
> with tf.Session:
> //you code

Adding a session for tf did not help.

This is what i get:
```
Traceback (most recent call last):
File "reconstruction.py", line 123, in runModel
    preTrainedAutoencoder = load_model(preTrainedAutoencoderPath)
File "/data/user/vae/virtenv-tensorflow/local/lib/python2.7/site-packages/keras/engine/saving.py", line 295, in load_model
    sample_weight_mode=sample_weight_mode)
File "/data/user/vae/virtenv-tensorflow/local/lib/python2.7/site-packages/keras/engine/training.py", line 333, in compile
    raise ValueError('The model cannot be compiled '
ValueError: The model cannot be compiled because it has no loss to optimize.
```

I tried to set the loss manually by passing custom_objects={"loss": None} along with the model path when loading the model but it didn't change the error (None because I only want to predict at this point).
