### ISSUE TITLE
pygpu.gpuarray.GpuArrayException on Theano OpenCL backend

### ISSUE THREAD

**Issue by egorzhdan** [fchollet/keras#4965]
I'm using latest versions of Keras & Theano on a MacBook Pro with discrete AMD graphics. It works fine on CPU, but I'm getting this error when I try to use OpenCL backend:
```
Traceback (most recent call last):
  File "/Users/egorzh/train.py", line 107, in <module>
    model.fit(x, y1, nb_epoch=50, validation_split=0.2)
  File "/usr/local/lib/python3.6/site-packages/keras/models.py", line 671, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1100, in fit
    self._make_test_function()
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 735, in _make_test_function
    **self._function_kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 967, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 953, in __init__
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/local/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python3.6/site-packages/theano/compile/function_module.py", line 1784, in orig_function
    defaults)
  File "/usr/local/lib/python3.6/site-packages/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python3.6/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python3.6/site-packages/theano/gof/vm.py", line 1059, in make_all
    impl=impl))
  File "/usr/local/lib/python3.6/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/usr/local/lib/python3.6/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python3.6/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python3.6/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python3.6/site-packages/theano/gof/cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python3.6/site-packages/theano/gof/cmodule.py", line 1118, in module_from_key
    src_code = lnk.get_src_code()
  File "/usr/local/lib/python3.6/site-packages/theano/gof/cc.py", line 1465, in get_src_code
    mod = self.get_dynamic_module()
  File "/usr/local/lib/python3.6/site-packages/theano/gof/cc.py", line 1509, in get_dynamic_module
    self.code_gen()
  File "/usr/local/lib/python3.6/site-packages/theano/gof/cc.py", line 782, in code_gen
    name))
  File "/usr/local/lib/python3.6/site-packages/theano/gpuarray/basic_ops.py", line 376, in c_support_code_apply
    bins = '\n'.join(self._generate_kernel_bin(k, ctx) for k in kernels)
  File "/usr/local/lib/python3.6/site-packages/theano/gpuarray/basic_ops.py", line 376, in <genexpr>
    bins = '\n'.join(self._generate_kernel_bin(k, ctx) for k in kernels)
  File "/usr/local/lib/python3.6/site-packages/theano/gpuarray/basic_ops.py", line 318, in _generate_kernel_bin
    **k._get_py_flags())
  File "pygpu/gpuarray.pyx", line 2185, in pygpu.gpuarray.GpuKernel.__cinit__ (pygpu/gpuarray.c:27154)
  File "pygpu/gpuarray.pyx", line 431, in pygpu.gpuarray.kernel_init (pygpu/gpuarray.c:7261)
pygpu.gpuarray.GpuArrayException
```
(the description of the exception is >30000 characters long so I removed it; let me know if it's useful)

The code:
```
model = Sequential()
model.add(Dense(256, input_shape=(128, 2400)))
model.add(Flatten())
model.add(Dense(256))
model.add(Dense(nb_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
```

**Comment by patyork** [comment]
You might read through [here](https://github.com/Theano/libgpuarray/issues/203).

Not many ops in Theano are implemented for the OpenCL backend at this point; I can't find a full list of what's available and what's not, but so far the consensus seems to be that OpenCL backend is not ready for use with Theano.
