### ISSUE TITLE
ImageDataGenerator.flow_from_directory() is outputting the wrong shape data

### ISSUE THREAD

**Issue by mikalyoung** [fchollet/keras#5034]
From the flow_from_directory tuple output of X_batch and Y_batch, the Y_batch is outputting as a shape that is not one-hot encoding.  The model.fit_generator seems to need one-hot encoding for the labels.  How do you make this in the correct, compatible shape?  This seems to be a bug.

```
datagen = kerasim.ImageDataGenerator(
		        width_shift_range=.1, height_shift_range=.1,  # randomly shift images vertically (fraction of total height)
		        shear_range=0, zoom_range=.15,
		        rescale=None, fill_mode='constant', cval=0.,
		        horizontal_flip=True, vertical_flip=True)

valdatagen = kerasim.ImageDataGenerator(
		        width_shift_range=.1, height_shift_range=.1,  # randomly shift images vertically (fraction of total height)
		        shear_range=0, zoom_range=.15,
		        rescale=None, fill_mode='constant', cval=0.,
		        horizontal_flip=True, vertical_flip=True)
			
train_generator = datagen.flow_from_directory('...', target_size=(256,256), batch_size=batch_size, class_mode='binary')
validation_generator = valdatagen.flow_from_directory('...', target_size=(256,256), batch_size=batch_size, class_mode='binary')
model.fit_generator(train_generator, samples_per_epoch=2*Nimages, nb_epoch=nb_epoch, 
				validation_data=validation_generator, callbacks=callbacks_list, nb_val_samples=100, verbose=1)

```

For my image folders, I have data/train/0, data/train/1, data/validation/0, data/validation/1.  

Error in shape:

```
Epoch 1/50000
Traceback (most recent call last):
  File "DR.py", line 286, in train
    validation_data=validation_generator, callbacks=callbacks_list, nb_val_samples=100, verbose=1)
  File "/home/sysop/anaconda2/envs/tf/lib/python2.7/site-packages/keras/models.py", line 935, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/sysop/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 1518, in fit_generator
    class_weight=class_weight)
  File "/home/sysop/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 1271, in train_on_batch
    check_batch_axis=True)
  File "/home/sysop/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 995, in _standardize_user_data
    exception_prefix='model target')
  File "/home/sysop/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 124, in standardize_input_data
    str(array.shape))
ValueError: Error when checking model target: expected predictions to have shape (None, 2) but got array with shape (64, 1)
Exception in thread Thread-2:

```

I am running the latest versions of keras and tensorflow as of today.

**Comment by hrask** [comment]
If you are using "loss='categorical_crossentropy'", try set it to  "loss='sparse_categorical_crossentropy'" when compile your model.
