### ISSUE TITLE
MultiLabel prediction for videos

### ISSUE THREAD

**Issue by indra215** [fchollet/keras#5101]
Hi,

I want to train a model which predicts multiple labels for a given video. I have 5000 classes in total. I extracted 20 frames from each video and computed a 512 dimensional feature embedding by passing each frame through a CNN. So my training data is of the form X_train = (no_videos, 20, 512). For a each video there can be multiple labels as targets, so I represent the target label as a 5000 dimensional vector of 1's and 0's,  where 1's for the classes for that video. So my target label vector is of the form Y_train=(no_videos, 5000). 

I trained a LSTM model on this data but unfortunately when I predict the labels on the training data, I'm getting same labels for all the videos in the training data. 
```

model = Sequential()
model.add(LSTM(256, input_shape=X_train.shape[1:], return_sequences=True))
model.add(LSTM(256))
model.add(Dropout(0.2))
model.add(Dense(no_classes, activation='sigmoid'))

sgd = SGD(lr=0.00001, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
print(model.summary())

model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=no_epoch)
```

Is it the right way to train the LSTM or is there anything wrong ?

Can anyone please help me how to solve this ?

Thanks in advance.

**Comment by mbollmann** [comment]
If you're predicting classes, you definitely want a softmax activation for the final Dense layer.

**Comment by yhenon** [comment]
The proper loss for this purpose is `binary_crossentropy`

**Comment by indra215** [comment]
Thank you for the suggestions.

@mbollmann I've changed the loss function to `sparse_categorical_crossentropy` but then I get this error saying

```
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
lstm_1 (LSTM)                    (None, 20, 400)       1460800     lstm_input_1[0][0]               
____________________________________________________________________________________________________
lstm_2 (LSTM)                    (None, 400)           1281600     lstm_1[0][0]                     
____________________________________________________________________________________________________
dropout_1 (Dropout)              (None, 400)           0           lstm_2[0][0]                     
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 5000)          2005000     dropout_1[0][0]                  
====================================================================================================
Total params: 4747400
____________________________________________________________________________________________________
None
Traceback (most recent call last):
  File "lstm_tag_video_1.py", line 38, in <module>
    model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=no_epoch)
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/models.py", line 627, in fit
    sample_weight=sample_weight)
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1052, in fit
    batch_size=batch_size)
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 983, in _standardize_user_data
    exception_prefix='model target')
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 111, in standardize_input_data
    str(array.shape))
Exception: Error when checking model target: expected dense_1 to have shape (None, 1) but got array with shape (9111, 5000)
```

@yhenon I've used `binary_crossentropy` loss but even then the problem persists. I'm getting the same labels even now.
