### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal, but are 3 and 2

### ISSUE THREAD

**Issue by monajalal** [fchollet/keras#5110]
Can you please guide how to fix this error?
```
mona@pascal:~/computer_vision/VPilot$ python drive.py model.h5 8000 320 160 
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:368: UserWarning: The `regularizers` property of layers/models is deprecated. Regularization losses are now managed via the `losses` layer/model property.
  warnings.warn('The `regularizers` property of '
Traceback (most recent call last):
  File "drive.py", line 61, in <module>
    model = aitorNet.getModel(weights_path=args.weights)
  File "/home/mona/computer_vision/VPilot/model.py", line 106, in getModel
    model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2701, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2787, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1544, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/mona/tensorflow/_python_build/tensorflow/python/ops/variables.py", line 505, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/mona/tensorflow/_python_build/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/home/mona/tensorflow/_python_build/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/mona/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 2390, in create_op
    set_shapes_for_outputs(ret)
  File "/home/mona/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 1785, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/mona/tensorflow/_python_build/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Dimension 1 in both shapes must be equal, but are 3 and 2
```

**Comment by parkerzf** [comment]
From the error log, I guess the weight file in weights_path is not compatible to the model in:

model = aitorNet.getModel(weights_path=args.weights)

**Comment by wkm** [comment]
You may need to add `data_format='channels_first'` when adding layers to your model. (I just went through this when upgrading to keras 2).

Eg, I now have:
```
    def ConvBlock(self, layers, filters):
        model = self.model
        for i in range(layers):
            model.add(Conv2D(filters, (3, 3), activation='relu', padding='same', data_format='channels_first'))
        model.add(MaxPooling2D((2, 2), strides=(2, 2), data_format='channels_first'))
```

**Comment by ZER-0-NE** [comment]
I am trying to finetune the top layers of [facenet](https://github.com/nyoki-mtl/keras-facenet) as described here [Building powerful image classification models using very little data](https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html)
I have the facenet_keras.h5 and facenet_keras_weights.h5 files in the github repo.

```
[base_model =  InceptionResNetV1(input_shape=(224, 224, 3),
                          classes=12,
                          dropout_keep_prob=0.8,
                          weights_path= weights_path)

    top_model = Sequential()
    top_model.add(Flatten(input_shape= (img_width, img_height, 3)))
    top_model.add(Dense(256, activation='relu'))
    top_model.add(Dropout(0.5))
    top_model.add(Dense(12, activation='sigmoid'))
    top_model.load_weights(top_model_weights_path)

    base_model.add(top_model)

    for layer in base_model.layers[:422]:
        layer.trainable = False]
```

I get this error because the weights do not match. How can I get past this?

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1566   try:
-> 1567     c_op = c_api.TF_FinishOperation(op_desc)
   1568   except errors.InvalidArgumentError as e:

InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 12 and 128. Shapes are [1792,12] and [1792,128]. for 'Assign_1460' (op: 'Assign') with input shapes: [1792,12], [1792,128].

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-13-1e88430b9e07> in <module>()
      3                       classes=12,
      4                       dropout_keep_prob=0.8,
----> 5                       weights_path= weights_path)
      6 
      7 # base_model = load_model(top_model_weights_path)

<ipython-input-10-8d164826b2b0> in InceptionResNetV1(input_shape, classes, dropout_keep_prob, weights_path)
    208     model = Model(inputs, x, name='inception_resnet_v1')
    209     if weights_path is not None:
--> 210         model.load_weights(weights_path)
    211 
    212     return model

/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
   2665             else:
   2666                 load_weights_from_hdf5_group(
-> 2667                     f, self.layers, reshape=reshape)
   2668 
   2669     def _updated_config(self):

/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py in load_weights_from_hdf5_group(f, layers, reshape)
   3391                              ' elements.')
   3392         weight_value_tuples += zip(symbolic_weights, weight_values)
-> 3393     K.batch_set_value(weight_value_tuples)
   3394 
   3395 

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in batch_set_value(tuples)
   2370                 assign_placeholder = tf.placeholder(tf_dtype,
   2371                                                     shape=value.shape)
-> 2372                 assign_op = x.assign(assign_placeholder)
   2373                 x._assign_placeholder = assign_placeholder
   2374                 x._assign_op = assign_op

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py in assign(self, value, use_locking)
    613       the assignment has completed.
    614     """
--> 615     return state_ops.assign(self._variable, value, use_locking=use_locking)
    616 
    617   def assign_add(self, delta, use_locking=False):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py in assign(ref, value, validate_shape, use_locking, name)
    281     return gen_state_ops.assign(
    282         ref, value, use_locking=use_locking, name=name,
--> 283         validate_shape=validate_shape)
    284   return ref.assign(value, name=name)
    285 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py in assign(ref, value, validate_shape, use_locking, name)
     58     _, _, _op = _op_def_lib._apply_op_helper(
     59         "Assign", ref=ref, value=value, validate_shape=validate_shape,
---> 60         use_locking=use_locking, name=name)
     61     _result = _op.outputs[:]
     62     _inputs_flat = _op.inputs

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    785         op = g.create_op(op_type_name, inputs, output_types, name=scope,
    786                          input_types=input_types, attrs=attr_protos,
--> 787                          op_def=op_def)
    788       return output_structure, op_def.is_stateful, op
    789 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
   3390           input_types=input_types,
   3391           original_op=self._default_original_op,
-> 3392           op_def=op_def)
   3393 
   3394       # Note: shapes are lazily computed with the C API enabled.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1732           op_def, inputs, node_def.attr)
   1733       self._c_op = _create_c_op(self._graph, node_def, grouped_inputs,
-> 1734                                 control_input_ops)
   1735     else:
   1736       self._c_op = None

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1568   except errors.InvalidArgumentError as e:
   1569     # Convert to ValueError for backwards compatibility.
-> 1570     raise ValueError(str(e))
   1571 
   1572   return c_op

ValueError: Dimension 1 in both shapes must be equal, but are 12 and 128. Shapes are [1792,12] and [1792,128]. for 'Assign_1460' (op: 'Assign') with input shapes: [1792,12], [1792,128].

```

**Comment by senthilv83** [comment]
File "C:\Program Files\Anaconda3\lib\site-packages\keras\models.py", line 706, in load_weights
    topology.load_weights_from_hdf5_group(f, layers)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py", line 2908, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 1992, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 522, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 1 in both shapes must be equal, but are 23 and 22 for 'Assign_2' (op: 'Assign') with input shapes: [256,23], [256,22].

**Comment by zhaoyucong** [comment]
@senthilv83 我也遇到了同样的错误 你的这个错误您解决了吗
