### ISSUE TITLE
LSTM fails to compile when output_dim = 1

### ISSUE THREAD

**Issue by MaigoAkisame** [fchollet/keras#5124]
The following code runs OK:
```
from keras.layers import *
from keras.models import *
import numpy

input = numpy.array([[[1]]], dtype = 'float32')
    # A dummy input: batch size is 1, only 1 time step, and 1 dimension

model = Sequential([LSTM(2, input_dim = 1)])
    # Define a model with a single LSTM layer with output_dim = 2
model.predict(input)
```
And produces something like:
```
array([[-0.13025887,  0.36489519]], dtype=float32)
```

But if the output_dim of the LSTM layer is changed to 1:
```
model = Sequential([LSTM(1, input_dim = 1)])
model.predict(input)
```
The code produces the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/keras/models.py", line 716, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 1216, in predict
    self._make_predict_function()
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 751, in _make_predict_function
    **kwargs)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 929, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 915, in __init__
    **kwargs)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 730, in make_thunk
    self.validate_inner_graph()
  File "/data/ASR1/yunwang/software/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 249, in validate_inner_graph
    (self.name, type_input, type_output))
TypeError: ('The following error happened while compiling the node', forall_inplace,gpu,scan_fn}(Elemwise{Composite{Switch(EQ(i0, i1), ((i2 * i3 * i0 * i4) // i0), i0)}}[(0, 0)].0, GpuSubtensor{int64:int64:int8}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, DeepCopyOp.0, Elemwise{Composite{Switch(EQ(i0, i1), ((i2 * i3 * i0 * i4) // i0), i0)}}[(0, 0)].0, lstm_26_U_o, lstm_26_U_f, lstm_26_U_i, lstm_26_U_c), '\n', "Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the same type but have type 'CudaNdarrayType(float32, col)' and 'CudaNdarrayType(float32, matrix)' respectively.")
```

I am using Keras 1.2.0, Theano 0.8.2, and Cuda 7.0.

I suspect that maybe somewhere in the code the output axis (with a length of 1) is squeezed away?

**Comment by patyork** [comment]
#3641

**Comment by patyork** [comment]
You could set `unroll=True` in the recurrent layer - that solves it for now. I've opened a PR that should fix it.

**Comment by MaigoAkisame** [comment]
Thank you!
