### ISSUE TITLE
keras 1.2.1: (Theano backend) nvcc compilation error 

### ISSUE THREAD

**Issue by ehosseiniasl** [fchollet/keras#5161]
I have theano=0.8.2 and keras=1.2.1. Trying to run code on gpu K520 and had the following nvcc compilation error. When I downgrade keras to 1.2.0 it was solved.

```python
/usr/bin/ld: cannot find -lcuda_ndarray
collect2: error: ld returned 1 exit status
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost(TensorConstant{(1, 1, 1, 1) of -2.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 5825, in constant_folding
    no_recycling=[])
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/nvcc_compiler.py", line 399, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -arch=sm_30 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -Xlinker -rpath,/usr/local/cuda/lib -Xlinker -rpath,/usr/local/cuda/lib64 -I/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -I/usr/local/cuda/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/theano/gof -I/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda -o /home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpdiOsYr/da6ac6908198a9d83223e8a2be6b76b9.so mod.cu -L/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/cuda_ndarray -L/usr/lib -lcudart -lcublas -lcuda_ndarray -lpython2.7', '[GpuFromHost(TensorConstant{(1, 1, 1, 1) of -2.0})]')
```

**Comment by bstriner** [comment]
Does it work with bleeding edge keras and theano? Both have constant bugfixes so I personally try to keep to the latest version.

Cheers

**Comment by sicklife** [comment]
met the same problem.
keras version: 1.2.2
theano version: 0.8.2 dev

**Comment by nouiz** [comment]
Use Theano dev version. If it was a problem in Theano, then it is probably
already fixed there. The dev version of Theano is pretty stable.
