### ISSUE TITLE
predict generator

### ISSUE THREAD

**Issue by Bhee** [fchollet/keras#5236]
How to use predict_generator in examples/image_ocr.py?

model.predict_generator (mg_gen.next_val(),10,10)
Is it correct way of calling predict_generator?

but I got the error as below

`out = model.predict_generator(img_gen.next_val(),10,10)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/engine/training.py", line 1634, in predict_generator
    outs = self.predict_on_batch(x)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/engine/training.py", line 1268, in predict_on_batch
    self.internal_input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/engine/training.py", line 70, in standardize_input_data
    'Found: ' + str(data)[:200] + '...')
Exception: Error when checking : data should be a Numpy array, or list/dict of Numpy arrays. Found: None...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/engine/training.py", line 425, in data_generator_task
    generator_output = next(generator)
  File "/home/alpha/keras-master/examples/image_ocr.py", line 340, in next_val
    ret = self.get_batch(self.cur_val_index, self.minibatch_size, train=False)
AttributeError: 'TextImageGenerator' object has no attribute 'cur_val_index'`

**Comment by dfroze** [comment]
Hy, 
I've run the code from git and got the same problem:
AttributeError: 'TextImageGenerator' object has no attribute 'cur_val_index'

I've checked and it passes through build_word_list first and I can see the data with pycharm debug, but the exception is still there.

Any ideas why this happens or how to fix it?

**Comment by dfroze** [comment]
Ok, I got bored waiting for an answer that was not replied since  Feb 1, 2017.
So, after a few hours of hell, I found that next_train is called before on_train_begin (thread race or something) and thus it messes everything up. 

The fix (for now):
 Just wait for a flag to be set after on_train_begin is called, such as:
   ```
 def next_train(self):
        while not self.train_started:
            time.sleep(1)
         ......
```

**Comment by dfroze** [comment]
P.S: similar for on_epoch_begin. For a pro solution, use mutex/lock
