### ISSUE TITLE
 pywrap_tensorflow.TF_GetCode(status)) tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape in shape_and_slice spec does not match the shape in the save file: [10,5], save file shape: [10,3]

### ISSUE THREAD

**Issue by phaniparsa** [fchollet/keras#5316]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by phaniparsa** [comment]
IRIS_TRAINING = "C:/Stocks/tensorflow/tf_trainData.csv"
IRIS_TEST = "C:/Stocks/tensorflow/tf_testData.csv"

# Load datasets.
training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
    filename=IRIS_TRAINING,
    target_dtype=np.int,
    features_dtype=np.float32)
test_set = tf.contrib.learn.datasets.base.load_csv_with_header(
    filename=IRIS_TEST,
    target_dtype=np.int,
    features_dtype=np.float32)

# Specify that all features have real-value data
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]

# Build 3 layer DNN with 10, 20, 10 units respectively.
classifier = tf.contrib.learn.DNNClassifier(feature_columns=feature_columns,
                                            hidden_units=[10, 20, 10],
                                            n_classes=5,
                                            model_dir="/tmp/iris_model")

# Fit model.
classifier.fit(x=training_set.data,
               y=training_set.target,
               steps=2000)

# Evaluate accuracy.
accuracy_score = classifier.evaluate(x=test_set.data,
                                     y=test_set.target)["accuracy"]
print('Accuracy: {0:f}'.format(accuracy_score))




Error message:
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'tf_random_seed': None, '_evaluation_master': '', '_master': '', '_is_chief': True, 'save_checkpoints_steps': None, 'save_summary_steps': 100, 'keep_checkpoint_every_n_hours': 10000, 'save_checkpoints_secs': 600, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000000A712A20>, '_task_type': None, 'keep_checkpoint_max': 5, '_task_id': 0, '_environment': 'local', '_num_ps_replicas': 0, 'tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
}
WARNING:tensorflow:From C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py:315 in fit.: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py:315 in fit.: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py:315 in fit.: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with batch_size is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
INFO:tensorflow:Summary name dnn/hiddenlayer_0:fraction_of_zero_values is illegal; using dnn/hiddenlayer_0_fraction_of_zero_values instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_0:activation is illegal; using dnn/hiddenlayer_0_activation instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_1:fraction_of_zero_values is illegal; using dnn/hiddenlayer_1_fraction_of_zero_values instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_1:activation is illegal; using dnn/hiddenlayer_1_activation instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_2:fraction_of_zero_values is illegal; using dnn/hiddenlayer_2_fraction_of_zero_values instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_2:activation is illegal; using dnn/hiddenlayer_2_activation instead.
INFO:tensorflow:Summary name dnn/logits:fraction_of_zero_values is illegal; using dnn/logits_fraction_of_zero_values instead.
INFO:tensorflow:Summary name dnn/logits:activation is illegal; using dnn/logits_activation instead.
INFO:tensorflow:Create CheckpointSaverHook.
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape in shape_and_slice spec does not match the shape in the save file: [10,5], save file shape: [10,3]
	 [[Node: save/RestoreV2_16 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_16/tensor_names, save/RestoreV2_16/shape_and_slices)]]

Caused by op 'save/RestoreV2_16', defined at:
  File "<stdin>", line 1, in <module>
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Stocks/tensorflow/stock_Classification.py", line 94, in <module>
    steps=2000)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py", line 315, in fit
    max_steps=max_steps)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 191, in new_func
    return func(*args, **kwargs)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 355, in fit
    max_steps=max_steps)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 733, in _train_model
    max_steps=max_steps)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\graph_actions.py", line 297, in _monitored_train
    hooks=all_hooks) as super_sess:
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 447, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 618, in __init__
    _WrappedSession.__init__(self, self._sess_creator.create_session())
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 505, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 333, in create_session
    self._scaffold.finalize()
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 163, in finalize
    self._saver.build()
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 620, in build
    restore_sequentially, reshape)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 404, in _AddShardedRestoreOps
    name="restore_shard"))
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Shape in shape_and_slice spec does not match the shape in the save file: [10,5], save file shape: [10,3]
	 [[Node: save/RestoreV2_16 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_16/tensor_names, save/RestoreV2_16/shape_and_slices)]]

>>>     target_list, options, run_metadata)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    feed_dict_string, options, run_metadata)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    run_metadata_ptr)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1388, in restore
    init_fn=self._scaffold.init_fn)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\session_manager.py", line 227, in prepare_session
    config=config)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\session_manager.py", line 173, in _restore_checkpoint
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 341, in create_session
    _WrappedSession.__init__(self, self._sess_creator.create_session())
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 505, in create_session
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 618, in __init__
    max_steps=max_steps)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\graph_actions.py", line 297, in _monitored_train
    hooks=all_hooks) as super_sess:
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 447, in __init__
    max_steps=max_steps)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 733, in _train_model
    return func(*args, **kwargs)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 355, in fit
    max_steps=max_steps)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 191, in new_func
    execfile(filename, namespace)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Stocks/tensorflow/stock_Classification.py", line 94, in <module>
    steps=2000)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py", line 315, in fit
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape in shape_and_slice spec does not match the shape in the save file: [10,5], save file shape: [10,3]
	 [[Node: save/RestoreV2_16 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_16/tensor_names, save/RestoreV2_16/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    status, run_metadata)
  File "C:\Users\useradmin\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
Traceback (most recent call last):
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "C:\Users\useradmin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
