### ISSUE TITLE
training process crashed on a GPU cluster

### ISSUE THREAD

**Issue by huaiyanggongzi** [fchollet/keras#5385]
Hi, I am running a segnet model with abouyt 8000 pairs of 256*256 image pairs. The training process crashed along with the following error message. What can be the underlying cause for this, and how to solve it. It seems to be a memory allocation problem. Thank you very much.

`I tensorflow/core/common_runtime/bfc_allocator.cc:694] Stats:                       
Limit:                   261488640                                                  
InUse:                   261488640                                                  
MaxInUse:                261488640                                                  
NumAllocs:                     378                                                  
MaxAllocSize:              9437184                                                  

W tensorflow/core/common_runtime/bfc_allocator.cc:270] ***************************************************************************************************x             
W tensorflow/core/common_runtime/bfc_allocator.cc:271] Ran out of memory trying to allocate 2.0KiB.  See logs for memory state.                                         
W tensorflow/core/framework/op_kernel.cc:890] Internal: Dst tensor is not initialized.                                                                                  
E tensorflow/core/common_runtime/executor.cc:332] Executor failed to create kernel. Internal: Dst tensor is not initialized.                                            
         [[Node: Variable_33/initial_value = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [512] values: 0 0 0...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]                                                                            
Traceback (most recent call last):                                                  
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 644, in _do_call                                              
    return fn(*args)                                                                
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 628, in _run_fn                                               
    session, None, feed_dict, fetch_list, target_list, None)                        
tensorflow.python.pywrap_tensorflow.StatusNotOK: Internal: Dst tensor is not initialized.                                                                               
         [[Node: Variable_33/initial_value = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [512] values: 0 0 0...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]                                                                            

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 219, in <module>
    train_and_predict()                 
  File "train.py", line 215, in train_and_predict
    model.fit(imgs_train, imgs_mask_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1,callbacks=[model_checkpoint])                                            
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/models.py", line 409, in fit                                                 
    sample_weight=sample_weight)                                                    
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 1037, in fit                                       
    self._make_train_function()                                                     
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 663, in _make_train_function                       
    training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)                                                                 
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/optimizers.py", line 130, in get_updates                                     
    self.weights = [K.variable(np.zeros(K.get_value(p).shape)) for p in params]     
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/optimizers.py", line 130, in <listcomp>                                      
    self.weights = [K.variable(np.zeros(K.get_value(p).shape)) for p in params]     
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/tensorflow_backend.py", line 78, in variable                         
    get_session().run(v.initializer)                                                
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 340, in run                                                   
    run_metadata_ptr)                                                               
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 564, in _run                                                  
    feed_dict_string, options, run_metadata)                                        
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 637, in _do_run                                               
    target_list, options, run_metadata)                                             
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 659, in _do_call                                              
    e.code)
tensorflow.python.framework.errors.InternalError: Dst tensor is not initialized.
         [[Node: Variable_33/initial_value = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [512] values: 0 0 0...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Caused by op 'Variable_33/initial_value', defined at:
  File "train.py", line 219, in <module>
    train_and_predict()
  File "train.py", line 215, in train_and_predict
    model.fit(imgs_train, imgs_mask_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1,callbacks=[model_checkpoint])
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/models.py", line 409, in fit
    sample_weight=sample_weight)
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 1037, in fit
    self._make_train_function()
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 663, in _make_train_function
    training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/optimizers.py", line 130, in get_updates
    self.weights = [K.variable(np.zeros(K.get_value(p).shape)) for p in params]
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/optimizers.py", line 130, in <listcomp>
    self.weights = [K.variable(np.zeros(K.get_value(p).shape)) for p in params]
  File "/development//gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/tensorflow_backend.py", line 75, in variable
    v = tf.Variable(np.asarray(value, dtype=dtype), name=name)
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/ops/variables.py", line 209, in __init__
    dtype=dtype)
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/ops/variables.py", line 283, in _init_from_args
    dtype=dtype)
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/ops/constant_op.py", line 166, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/development//gtfw/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
`

**Comment by patyork** [comment]
It ran out of memory trying to allocate a tensor. It then tried to use that tensor, which is of course undefined at that time.

**Comment by huaiyanggongzi** [comment]
Hi patyork, are there any ways to solve this kind of problem? Thanks.

**Comment by patyork** [comment]
Smaller model, smaller batch size, or a bigger GPU.

**Comment by wenouyang** [comment]
Hi patyork, why smaller batch size can solve this kind problem? I would like to understand the mechanism underlying it. Thanks.

**Comment by patyork** [comment]
The GPU only has a certain amount of memory. If it runs out of memory, you have to do something to make the data on the GPU of smaller size, thus: smaller model or smaller batch size.

Alternatively, you can get a GPU with more memory.
