### ISSUE TITLE
'Graph' object has no attribute 'layers'

### ISSUE THREAD

**Issue by rbharath** [fchollet/keras#539]
It looks like the fit method for keras.models.graph is not working for head. I ran the following simple test script (from the tutorial):

```
import numpy as np
from keras.models import Graph
from keras.layers.core import Dense

X_train = np.zeros((10, 32))
y_train = np.zeros((10,))
graph = Graph()
graph.add_input(name='input', ndim=2)
graph.add_node(Dense(32, 16), name='dense1', input='input')
graph.add_node(Dense(32, 4), name='dense2', input='input')
graph.add_node(Dense(16, 4), name='dense3', input='dense1')
graph.add_output(name='output1', input='dense2')
graph.add_output(name='output2', input='dense3')

graph.compile('rmsprop', {'output1':'mse', 'output2':'mse'})
history = graph.fit({'input':X_train, 'output1':y_train,
                     'output2':y2_train}, nb_epoch=10)
```

And I get output:

```
Traceback (most recent call last):
  File "test_keras.py", line 15, in <module>
    graph.compile('rmsprop', {'output1':'mse', 'output2':'mse'})
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 576, in compile
AttributeError: 'Graph' object has no attribute 'layers'
```

**Comment by rbharath** [comment]
As an update, this sample code worked for me shortly before, when I wasn't on head. It stopped working once I pulled head from git.

**Comment by fchollet** [comment]
Right, this is now fixed.
