### ISSUE TITLE
Should Keras depend on TensorFlow instead of Theano?

### ISSUE THREAD

**Issue by danieljl** [fchollet/keras#5467]
Considering that now the default backend of Keras is TensorFlow and not Theano anymore, should Keras depend on TensorFlow? Currently it depends only on Theano: https://github.com/fchollet/keras/blob/master/setup.py#L13.

Moreover, installing keras by `pip install keras` doesn't work because when TensorFlow is not installed, Keras doesn't failover to Theano.

```
 14:19:24  ~ 
$ virtualenv test-env
New python executable in /home/daniel/test-env/bin/python
Installing setuptools, pip, wheel...done.

 14:19:30  ~ 
$ source test-env/bin/activate

 14:19:35  ~  🐍 test-env 
$ pip install keras
Collecting keras
Collecting pyyaml (from keras)
Collecting theano (from keras)
Requirement already satisfied: six in ./test-env/lib/python2.7/site-packages (from keras)
Collecting numpy>=1.7.1 (from theano->keras)
  Using cached numpy-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy>=0.11 (from theano->keras)
  Using cached scipy-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: pyyaml, numpy, scipy, theano, keras
Successfully installed keras-1.2.2 numpy-1.12.0 pyyaml-3.12 scipy-0.18.1 theano-0.8.2

 14:20:04  ~  🐍 test-env 
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/test-env/local/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/daniel/test-env/local/lib/python2.7/site-packages/keras/backend/__init__.py", line 67, in <module>
    from .tensorflow_backend import *
  File "/home/daniel/test-env/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
>>> 
```

**Comment by SCP-173-cool** [comment]
you can switch the backend from Tensorflow to theano via editing `~/.keras.json`

**Comment by kirit93** [comment]
Change the file ~/.keras/keras.json to be as follows:
```
{
    "floatx": "float32",
    "backend": "theano",
    "epsilon": 1e-07,
    "image_dim_ordering": "th"
}
```
The default backend in the json file is tensorflow.

**Comment by danieljl** [comment]
@SCP-173-cool @kirit93 Thanks for the info! However, my point is to streamline new users installing Keras. So, they can just `pip install keras` and be ready to use it. What do you think?

**Comment by kirit93** [comment]
You mean keras should default to theano instead of tensorflow in the .json file? I agree that would be much better.

**Comment by SCP-173-cool** [comment]
@danieljl @kirit93 Ha! That is not important. All frameworks of Deep Learning will be recoded and packaged by **KERAS**

**Comment by danieljl** [comment]
Closed by https://github.com/fchollet/keras/commit/173a40ddc18b35ab803b017cf73c544af319c5d5
