### ISSUE TITLE
Error getting the output of an LSTM layer

### ISSUE THREAD

**Issue by freesunshine0316** [fchollet/keras#5602]
I try to get the output of an LSTM layer in the type of numpy.array with the following code
from keras import backend as K
xxx = nnlm.model.get_layer('lstm_2').output
xxx = K.eval(xxx, session=K.get_session())

and got the following error:
Traceback (most recent call last):
  File "make_training_insts.py", line 27, in <module>
    xxx = xxx.eval(session=K.get_session())
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 581, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3797, in _eval_using_default_sessio
n
    return session.run(tensors, feed_dict)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/software/python/2.7.12/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'keras_learning_phase' with dt
ype bool
	 [[Node: keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by unrealwill** [comment]
Hello,

I'm no tensorflow expert put your error seems that you are not feeding the keras_learning_phase.

Here is a blog which explain how to use it.
https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html

Relevant part to feed learning phase:
```
acc_value.eval(feed_dict={img: mnist_data.test.images,
                                    labels: mnist_data.test.labels,
                                    K.learning_phase(): 0})
```
