### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by lhyxcxy** [fchollet/keras#5814]
# i use keras-2.0.0 and tensorflow 0.12  ,then run stateful_lstm.py  ，
Traceback (most recent call last):
  File "/home/lhy/PycharmProjects/keras_e/stateful_lstm.py", line 55, in <module>
    stateful=True))
  File "/usr/lib64/python2.7/site-packages/keras/models.py", line 422, in add
    layer(x)
  File "/usr/lib64/python2.7/site-packages/keras/layers/recurrent.py", line 252, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 545, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/lib64/python2.7/site-packages/keras/layers/recurrent.py", line 290, in call
    preprocessed_input = self.preprocess_input(inputs, training=None)
  File "/usr/lib64/python2.7/site-packages/keras/layers/recurrent.py", line 1033, in preprocess_input
    return K.concatenate([x_i, x_f, x_c, x_o], axis=2)
  File "/usr/lib64/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1527, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by jmhessel** [comment]
I had this same error. Upgrading to tf 1.0 fixes it.

**Comment by roopalgarg** [comment]
thanks @jmhessel , updating tf version to 1.0 from 0.12 fixed it.
