### ISSUE TITLE
TypeError: <lambda>() missing 1 required positional argument: 'name'

### ISSUE THREAD

**Issue by yanadsl** [fchollet/keras#5889]
Hi, I'm trying to reproduce [DDPG-Keras-Torcs](https://github.com/yanpanlau/DDPG-Keras-Torcs), and here is my system
- OS: Ubuntu16.04
- Backend: TensorFlow
- Python3.5
- CUDA8.0 & cuDNN 5.1
- GTX1070

I made some [syntax change](https://github.com/yanadsl/DDPG-Keras-Torcs) to match new version of keras and python3
Here is my error log
```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Using TensorFlow backend.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.7845
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.69GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
Now we build the model
/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, kernel_initializer=<function ..., activation="tanh")`
  '` call to the Keras 2 API: ' + signature)
Traceback (most recent call last):
  File "ddpg.py", line 155, in <module>
    playGame()
  File "ddpg.py", line 45, in playGame
    actor = ActorNetwork(sess, state_dim, action_dim, BATCH_SIZE, TAU, LRA)
  File "/home/yanadsl/DDPG-Keras-Torcs/ActorNetwork.py", line 22, in __init__
    self.model , self.weights, self.state = self.create_actor_network(state_size, action_size)   
  File "/home/yanadsl/DDPG-Keras-Torcs/ActorNetwork.py", line 48, in create_actor_network
    Steering = Dense(1,activation='tanh',init=lambda shape, name: normal(shape, scale=1e-4, name=name))(h1)  
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 528, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 827, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 364, in add_weight
    weight = K.variable(initializer(shape), dtype=K.floatx(), name=name)
TypeError: <lambda>() missing 1 required positional argument: 'name'
```

I find it strange that  `argument: 'name'` should be already passed in `core.py`
I have tried to reinstall both TensorFlow and Keras but nothing help.
And there are another error but shows randomly(after the log above)
```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fab633d0cf8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 582, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'
```
Perhaps there are nothing to deal with keras?
Thanks for any help!

**Comment by yanadsl** [comment]
After using old version the problem solved, so nothing wrong with keras

**Comment by EvgheniiBeriozchin** [comment]
What is the old version you used?

**Comment by yanadsl** [comment]
Hi,
I think this [link](https://github.com/yanpanlau/DDPG-Keras-Torcs/issues/14) should help
I used `sudo pip2 install keras==1.1 tensorflow-gpu==0.12.0` to make code works
since TF changed a lot in those early version, i'm not sure if your problem will be solved by which specific version
However, if you are working on an old project, this would worth a try :)
