### ISSUE TITLE
Errors when using more than ONE workers using predict_generator()

### ISSUE THREAD

**Issue by pengpaiSH** [fchollet/keras#5919]
I find out that errors occurred when I want to use multiple workers using ```predict_generator()```. Note that in the training process, I could set multiple workers in ```fit_generator()```.

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:05:00.0)
Begin to predict for testing data ...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.2-py2.7.egg/keras/engine/training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
ValueError: generator already executing

Traceback (most recent call last):
  File "predict_qzone13.py", line 38, in <module>
    steps = validation_steps, verbose = 1, max_q_size=40, workers=4)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.2-py2.7.egg/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.2-py2.7.egg/keras/engine/training.py", line 2094, in predict_generator
    outs = self.predict_on_batch(x)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.2-py2.7.egg/keras/engine/training.py", line 1683, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.2-py2.7.egg/keras/backend/tensorflow_backend.py", line 2073, in __call__
    feed_dict=feed_dict)
  File "/d/home/popeyepeng/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/d/home/popeyepeng/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape () for Tensor u'input_1:0', which has shape '(?, 299, 299, 3)'
```

**Comment by dteoh** [comment]
Your generator needs to be thread-safe.

**Comment by pengpaiSH** [comment]
@dteoh Thanks for your feedback. Note that in the training process, I could set multiple workers in ```fit_generator()```. And would you say more words about the issue, please?

**Comment by dteoh** [comment]
See #1638

**Comment by pengpaiSH** [comment]
@dteoh Thank you !!!
