### ISSUE TITLE
LocallyConnected1D (only "valid" is supported) ?

### ISSUE THREAD

**Issue by jagiella** [fchollet/keras#5925]
The keras documentation states that the padding for **LocallyConnected1D** layers could be chosen to be either `'same'` or `'valid'`.
But when I chose `'same'`, I get the following error:
```python
Traceback (most recent call last):
  File "CNNSPM.py", line 133, in <module>
    LocallyConnected1D(40, 10, padding='same', activation='relu'),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/local.py", line 98, in __init__
    '(only "valid" is supported): ' + padding)
ValueError: Invalid border mode for LocallyConnected1D (only "valid" is supported): same
```

**Comment by joelthchao** [comment]
Hi, we currently NOT support `same` padding, but it may supports in the future. Contribution is welcome!
