### ISSUE TITLE
Running a model with Recurrent Layer inside TimeDistributed

### ISSUE THREAD

**Issue by siddheshk** [fchollet/keras#6028]
I have defined a simple model that processes an input sentence.
The model is defined below
```python
embedding_sentence = Embedding(len(W2V), img_w, input_length=img_h, weights=[W2V], trainable=True, mask_zero=True, name='embedding_1')
input_layer = Input(shape=(img_h,), dtype='int32', name='input_layer')
embedding_layer = embedding_sentence(input_layer)
bidirectional_gru_word = Bidirectional(GRU(img_w+2*img_d, return_sequences=True, activation=conv_non_linear, implementation=2), merge_mode='concat')(embedding_layer)
preprocess_sentence_model = Model(inputs=[input_layer], outputs=[bidirectional_gru_word])
```
This model is a part of a bigger model that accepts documents instead of sentences. So in order to run the above `preprocess_sentence_model` I use the TimeDistributed Wrapper.

```python
input_layer_bag = Input(shape=(max_sentences, img_h,), dtype='int32', name='input_layer_bag')
preprocess_sentence = TimeDistributed(preprocess_sentence_model)(input_layer_bag)
```
This was working fine on Keras before v2. Now I get the following error
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1569, in predict
    self._make_predict_function()
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1037, in _make_predict_function
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1132, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1118, in __init__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1807, in orig_function
    output_keys=output_keys).create(
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1446, in __init__
    accept_inplace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 174, in __init__
    self.__import_r__(output, reason="init")
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 345, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 390, in __import__
    raise MissingInputError(error_msg, variable=r)
theano.gof.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute Elemwise{neq,no_inplace}(/input_layer, InplaceDimShuffle{x,x}.0), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.
 
Backtrace when that variable is created:

  File "test.py", line 308, in <module>
    img_w=50)
  File "test.py", line 81, in cnn
    input_layer = Input(shape=(img_h,), dtype='int32', name='input_layer')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1388, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1299, in __init__
    name=self.name)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 184, in placeholder
    x = T.TensorType(dtype, broadcast)(name)
```
But when I remove the GRU from the `preprocess_sentence_model` it seems to work fine. Can someone please help me out?

Thanks.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by jpraymond** [comment]
Might be related to this: https://github.com/fchollet/keras/issues/6169. I would try updating from the master branch.
