### ISSUE TITLE
keras 2.0.2 breaks resnet on theano backend

### ISSUE THREAD

**Issue by oak-tree** [fchollet/keras#6029]
I tried to run the example from  https://keras.io/applications/#resnet50 (copy&paste)

This result with the following error :

```
    preds = model.predict(x)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/keras/engine/training.py", line 1572, in predict
    batch_size=batch_size, verbose=verbose)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/keras/engine/training.py", line 1202, in _predict_loop
    batch_outs = f(ins_batch)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1122, in __call__
    return self.function(*inputs)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/oak/venv2/local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: GpuDnnConv images and kernel must have the same stack size

Apply node that caused the error: GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='valid', subsample=(2, 2), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})
Toposort index: 1039
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x7fd6e7ed0190>, Scalar(float32), Scalar(float32)]
Inputs shapes: [(1, 3, 230, 230), (7, 7, 3, 64), (1, 7, 114, 84), 'No shapes', (), ()]
Inputs strides: [(0, 52900, 230, 1), (1344, 192, 64, 1), (0, 9576, 84, 1), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x7fd6eae6ce70>, 1.0, 0.0]
Inputs name: ('image', 'kernel', 'output', 'descriptor', 'alpha', 'beta')

Outputs clients: [[GpuElemwise{Add}[(0, 0)](GpuDnnConv{algo='small', inplace=True}.0, GpuDimShuffle{x,0,x,x}.0)]]
```

**Comment by oak-tree** [comment]
Any idea about this issue?

**Comment by fchollet** [comment]
> ValueError: GpuDnnConv images and kernel must have the same stack size

It looks like you are trying to run code written for `data_format='channels_last'` with `channels_fist` (or the other way around). Make sure your data matches the default data format from your Keras config file at `~/.keras/keras.json`.

**Comment by oak-tree** [comment]
Yes, but the upgraded resnet50 has weights for tensorflow only. For some reason it fails when converting to `theano` but does not succeed [https://github.com/fchollet/keras/blob/master/keras/applications/resnet50.py#L266](url)

**Comment by fchollet** [comment]
The error message you posted is not related to weight conversion. Weight conversion does not affect weight shapes, only weight contents.

**Comment by oak-tree** [comment]
So what can be the cause? 

I  reran it on fresh file.

## keras.json

`{
    "epsilon": 1e-07,
    "floatx": "float32",
    "image_data_format": "channels_first",
    "backend": "theano"
}`

## Example code

```
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

model = ResNet50(weights='imagenet')

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
```
print('Predicted:', decode_predictions(preds, top=3)[0])

## Error message

```
Using Theano backend.
Traceback (most recent call last):
  File "res50.py", line 14, in <module>
    preds = model.predict(x)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/Keras-2.0.1-py2.7.egg/keras/engine/training.py", line 1572, in predict
    batch_size=batch_size, verbose=verbose)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/Keras-2.0.1-py2.7.egg/keras/engine/training.py", line 1202, in _predict_loop
    batch_outs = f(ins_batch)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/Keras-2.0.1-py2.7.egg/keras/backend/theano_backend.py", line 1094, in __call__
    return self.function(*inputs)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/oak/venv2/local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM images and kernel must have the same stack size

Apply node that caused the error: CorrMM{valid, (2, 2), (1, 1)}(IncSubtensor{InplaceSet;::, ::, int64:int64:, int64:int64:}.0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 442
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(1, 3, 230, 230), (7, 7, 3, 64)]
Inputs strides: [(634800, 211600, 920, 4), (5376, 768, -256, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{add,no_inplace}(CorrMM{valid, (2, 2), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "res50.py", line 6, in <module>
    model = ResNet50(weights='imagenet')
  File "/home/oak/venv2/local/lib/python2.7/site-packages/Keras-2.0.1-py2.7.egg/keras/applications/resnet50.py", line 207, in ResNet50
    x = Conv2D(64, (7, 7), strides=(2, 2), name='conv1')(x)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/Keras-2.0.1-py2.7.egg/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/Keras-2.0.1-py2.7.egg/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/home/oak/venv2/local/lib/python2.7/site-packages/Keras-2.0.1-py2.7.egg/keras/backend/theano_backend.py", line 1726, in conv2d
    filter_dilation=dilation_rate)
```

**Comment by fchollet** [comment]
I can repro. The issue is not backend dependent. And not related to weight conversion. Unclear to me what the problem is (at first look).

**Comment by oak-tree** [comment]
Updated: Using `tensorflow` works with the above code. Note that also the sample code for VGG breaks on `theano`

**Comment by tati-** [comment]
I have exactly the same problem.
It seems that the kernel shape is 'channels_last', although debugging shows that image_dim_ordering='th'.

**Comment by tati-** [comment]
I replaced the weight loading part of the code with that of the previous version (so loading the `https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_th_dim_ordering_th_kernels.h5` or `https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_th_dim_ordering_th_kernels_notop.h5` files directly, instead of loading the `tf` versions and converting them), and it works for me.

**Comment by mynameisfiber** [comment]
One thing I noticed was that the new resnet/vgg16 weight files don't have the `keras_version` attribute set. When I manually change it to `d.attrs['keras_version'] = bytes('2', 'utf8')` and remove the md5 hash checking, things seem to work.

NOTE: the model _loads_ and is able to make predictions... I haven't tested that it is making the correct predictions :)

**Comment by mynameisfiber** [comment]
@fchollet Seems like my fix yields correct predictions.  I get:

```
Predicted: [('n03085013', 'computer_keyboard', 0.21159104), ('n03642806', 'laptop', 0.19715701), ('n02112137', 'chow', 0.17430468)]
```

![](http://www.rd.com/wp-content/uploads/sites/2/2016/04/01-cat-wants-to-tell-you-laptop.jpg)

as well as:

```
Predicted: [('n02123045', 'tabby', 0.64627695), ('n02123159', 'tiger_cat', 0.19134907), ('n02124075', 'Egyptian_cat', 0.15488885)]
```
![](http://www.bharatint.com/img/categories/our-cat-shop-image.png)
