### ISSUE TITLE
Error running imdb example 

### ISSUE THREAD

**Issue by vin101** [fchollet/keras#6174]
I get the following error when I am trying to run the imdb example. 

`Using TensorFlow backend.
Loading data...
Traceback (most recent call last):
  File "imdb.py", line 64, in <module>
    (x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
TypeError: load_data() got an unexpected keyword argument 'num_words'`

**Comment by fchollet** [comment]
Update Keras.

**Comment by vin101** [comment]
With the latest version of keras I cannot use the recurrentshop library, I get the following error on importing recurrentshop (trying to use https://github.com/farizrahman4u/seq2seq)

`>>> import recurrentshop
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 3, in <module>
ImportError: cannot import name initializations
`

**Comment by sunnysai12345** [comment]
Check my pull request on recurrentshop for modifications https://github.com/datalogai/recurrentshop/pull/33
