### ISSUE TITLE
Some errors when running lstm_text_generation example

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#6246]
I have upgraded the newest version, but now there are always some errors. It's so confusing.
```
Using gpu device 0: GeForce GTX 750 (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5005)
corpus length: 539291
total chars: 56
nb sequences: 179751
Vectorization...
Build model...

--------------------------------------------------
Iteration 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "E:/DL EX/K/keras-master-2017-4-7/examples/lstm_text_generation.py", line 78, in <module>
    epochs=1)
  File "C:\Anaconda2\lib\site-packages\keras\models.py", line 853, in fit
    initial_epoch=initial_epoch)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1458, in fit
    self._make_train_function()
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1008, in _make_train_function
    **self._function_kwargs)
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 1132, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 1118, in __init__
    **kwargs)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1808, in orig_function
    defaults)
  File "C:\Anaconda2\lib\site-packages\theano\compile\function_module.py", line 1674, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Anaconda2\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Anaconda2\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
    impl=impl))
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 935, in make_thunk
    no_recycling)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "C:\Anaconda2\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py", line 417, in compile_str
    return dlimport(lib_filename)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
RuntimeError: ('The following error happened while compiling the node', GpuDnnSoftmaxGrad{tensor_format='bc01', mode='instance', algo='accurate'}(GpuContiguous.0, GpuContiguous.0), '\n', 'could not create cuDNN handle: CUDNN_STATUS_NOT_INITIALIZED', "[GpuDnnSoftmaxGrad{tensor_format='bc01', mode='instance', algo='accurate'}(<CudaNdarrayType(float32, (False, True, False, True))>, <CudaNdarrayType(float32, (False, True, False, True))>)]")
```

**Comment by sallamander** [comment]
@Imorton-zd I'm able to run this with Keras 2.0.2 and tensorflow 1.0.1. It looks like there might be a problem with your GPU configuration. Were you able to confirm that the GPU is set up correctly and verify that the CUDA libraries are loaded correctly? Typically when I see errors like this, it's because one of the CUDA libraries can't be found. 

Successfully loaded CUDA libraries typically look like this for me: 

<img width="639" alt="screen shot 2017-04-15 at 6 27 36 am" src="https://cloud.githubusercontent.com/assets/12429170/25063975/4dc107e4-21a5-11e7-8aaa-eed90f447aca.png">

whereas usually when I run into the kinds of errors your seeing, I see something that failed in those lines.
