### ISSUE TITLE
Cant use count_mode='steps' in ProgbarLogger

### ISSUE THREAD

**Issue by yanchao727** [fchollet/keras#6438]
```
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test),
          callbacks=[ProgbarLogger(count_mode='steps')])
```

```
Traceback (most recent call last):
  File "mnist_cnn.py", line 69, in <module>
    callbacks=[ProgbarLogger(count_mode='steps')])
  File "/home/yanchao/.virtualenvs/py3env/lib/python3.4/site-packages/keras/models.py", line 856, in fit
    initial_epoch=initial_epoch)
  File "/home/yanchao/.virtualenvs/py3env/lib/python3.4/site-packages/keras/engine/training.py", line 1493, in fit
    initial_epoch=initial_epoch)
  File "/home/yanchao/.virtualenvs/py3env/lib/python3.4/site-packages/keras/engine/training.py", line 1123, in _fit_loop
    callbacks.on_epoch_begin(epoch)
  File "/home/yanchao/.virtualenvs/py3env/lib/python3.4/site-packages/keras/callbacks.py", line 62, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "/home/yanchao/.virtualenvs/py3env/lib/python3.4/site-packages/keras/callbacks.py", line 258, in on_epoch_begin
    target = self.params['steps']
KeyError: 'steps'

```

**Comment by zhouhoo** [comment]
So do I, but  doc  in keras homepage  has mentioned this argument.
