### ISSUE TITLE
Error when saving weights

### ISSUE THREAD

**Issue by insomnia250** [fchollet/keras#6465]
When i use 'model.save_weights()' to save weights of a model containing a 'Bidirectional' LSTM layer, an error occurred .But when saving weights of a model containing no 'Bidirectional' layer, for example, common LSTM , weights are successfully saved. Why is that and how can I save model weights containing a 'Bidirectional LSTM' layer? Can anyone please help me?

the error occurred like this:
Traceback (most recent call last):
  File "J:\ZCT\stupoet\poet4\poet4_bidirec.py", line 213, in <module>
    model.save_weights('cycle{0}/my_model_weights.h5'.format(cycle))    
  File "F:\P\python2.7\lib\site-packages\keras\engine\topology.py", line 2460, in save_weights
    save_weights_to_hdf5_group(f, self.layers)
  File "F:\P\python2.7\lib\site-packages\keras\engine\topology.py", line 2721, in save_weights_to_hdf5_group
    dtype=val.dtype)
  File "F:\P\python2.7\lib\site-packages\h5py\_hl\group.py", line 111, in create_dataset
    self[name] = dset
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.7.0\h5py\_objects.c:2853)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.7.0\h5py\_objects.c:2811)
  File "F:\P\python2.7\lib\site-packages\h5py\_hl\group.py", line 276, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.7.0\h5py\_objects.c:2853)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.7.0\h5py\_objects.c:2811)
  File "h5py\h5o.pyx", line 202, in h5py.h5o.link (D:\Build\h5py\h5py-2.7.0\h5py\h5o.c:3908)
RuntimeError: Unable to create link (Name already exists)

**Comment by alugupta** [comment]
I am experiencing this as well. Were you able to figure out what the issue is?

**Comment by insomnia250** [comment]
I haven't figure out what's wrong with the method 'model.save_weights()' when using Bidirectional layers. But I am now using cPickle saving weights instead.
Specifically, use  'weights = model.get_weights()' to get a numpy ndarray of the model, and 'cPickle.dump()' to save 'weights' as a pkl file. When loading weights, using cPickle.load() load from the file and 'model.set_weights()' to prepare your model.

**Comment by mthmn20** [comment]
I was having a similar problem but it went away when I installed keras directly from github, pip install --upgrade git+git://github.com/fchollet/keras.git
