### ISSUE TITLE
keras:ImportError: libcufft.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sunpeng1996** [fchollet/keras#6519]
/usr/bin/python2.7 /home/sunpeng/Downloads/code/internet_example.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/sunpeng/Downloads/code/internet_example.py", line 9, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 4, in <module>
    from . import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 73, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcufft.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1

I see the libcufft.so.8.0 in my "/usr/local/cuda-8.0/lib64",but why occur this error?

**Comment by YungQuant** [comment]
I'm having the exact same issue trying to get keras to use my gpu's.

**Comment by second-technologies** [comment]
Had the same problem!

the package libcufft8.0 is probably missing on your system and can be resolved by installing that package.

`
apt install libcufft8.0
`

Tested on Ubuntu 17.04.

**Comment by YungQuant** [comment]
On Ubuntu 16.04:
Duncan-Y700:~$ apt install libcufft8.0
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
Duncan-Y700:~$ sudo apt install libcufft8.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcufft8.0
E: Couldn't find any package by glob 'libcufft8.0'
E: Couldn't find any package by regex 'libcufft8.0'
