### ISSUE TITLE
NPZ object has no attribute 'zip'" 

### ISSUE THREAD

**Issue by dycasxe101** [fchollet/keras#6526]
hello there, i have some problem, and i 'did not know how to solve it,please help me. i have no idea

> Error

Exception AttributeError: "'NpzFile' object has no attribute 'zip'" in <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x000000000DDBBB70>> ignored
Traceback (most recent call last):

  File "<ipython-input-5-66dbbe6f0198>", line 1, in <module>
    (x_train, y_train), (x_test, y_test) = mnist.load_data()

  File "C:\Users\dycAS\Anaconda2\lib\site-packages\keras\datasets\mnist.py", line 16, in load_data
    f = np.load(path)

  File "C:\Users\dycAS\Anaconda2\lib\site-packages\numpy\lib\npyio.py", line 399, in load
    pickle_kwargs=pickle_kwargs)

  File "C:\Users\dycAS\Anaconda2\lib\site-packages\numpy\lib\npyio.py", line 162, in __init__
    _zip = zipfile_factory(fid)

  File "C:\Users\dycAS\Anaconda2\lib\site-packages\numpy\lib\npyio.py", line 92, in zipfile_factory
    return zipfile.ZipFile(*args, **kwargs)

  File "C:\Users\dycAS\Anaconda2\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()

  File "C:\Users\dycAS\Anaconda2\lib\zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"

BadZipfile: File is not a zip file

>

**Comment by showforj** [comment]
I meet the same problem, have you solved it?

**Comment by awenhu** [comment]
any solution?

**Comment by dycasxe101** [comment]
i have solved it. just delete your dataset in root folder, and run again
2017-06-01 14:57 GMT+07:00 awenhu <notifications@github.com>:

**Comment by dycasxe101** [comment]
Alhamdulillah, done and solved. 

just remove your database downloaded at ur root folder. and run again. make sure ur connection, because this problem caused by the database you downloaded is failed

**Comment by showforj** [comment]
thank you very much! Solved!

**Comment by HoleungLiu** [comment]
Solved!  thank you ,dycasxe101

**Comment by Kidron-Hou** [comment]
excellent！

**Comment by taimurIslam** [comment]
can you plz help me, where  is the root folder here ??

**Comment by shinseitaro** [comment]
`rm ~/.keras/datasets/*
`

**Comment by npatel51** [comment]
In my case, I downloaded datasets manually: [https://s3.amazonaws.com/img-datasets/mnist.npz]  and modified the `mnist.py` file located under `\keras\datasets\`  basically change the path to `path = 'N:\Deep_Learning\envs\py_36\Lib\site-packages\keras\datasets\mnist.npz';` and it works obviously. However, for different datasets, you may want to save a copy `mnist.py` so you can revert the code.
