### ISSUE TITLE
Cannot save model!

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#6630]
Traceback (most recent call last):
  File "W:/Nutstore_Lab/5-13/Code/ReducingDimensions_CAE.py", line 47, in <module>
    autoencoder.save(filepath=r"W:/tmp/autoencoder5-13/model_ae16.h5")
  File "S:\Python35\lib\site-packages\keras\engine\topology.py", line 2472, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "S:\Python35\lib\site-packages\keras\models.py", line 97, in save_model
    f = h5py.File(filepath, 'w')
  File "S:\Python35\lib\site-packages\h5py\_hl\files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "S:\Python35\lib\site-packages\h5py\_hl\files.py", line 107, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.7.0\h5py\_objects.c:2853)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.7.0\h5py\_objects.c:2811)
  File "h5py\h5f.pyx", line 98, in h5py.h5f.create (D:\Build\h5py\h5py-2.7.0\h5py\h5f.c:2297)
OSError: Unable to create file (Unable to open file: name = 'w:/tmp/autoencoder5-13/model_ae16.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 302)

**Comment by taehoonlee** [comment]
Does there exist a folder named `autoencoder5-13`?

**Comment by Amirtha1189** [comment]
I got the same error message as above when i set the backprop_modifier as 'guided' for visulaising saliency. Please let me know what is the reason for this error

**Comment by taehoonlee** [comment]
Your error seems to be clear: `OSError: Unable to create file`. You have to create the folder `w:/tmp/autoencoder5-13/`.

**Comment by Ahmad5112** [comment]
> w:/tmp/autoencoder5-13/

Can you please explain how to create folder?

**Comment by JanderHungrige** [comment]
Either maually create that folder or with :
```
import os
path = "w:/tmp/autoencoder5-13/"
os.mkdir(path)
```

**Comment by Sivaaaa** [comment]
OSError: Unable to create file (unable to open file: name = 'stage1_gen.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

**Comment by Sivaaaa** [comment]
i am getting this error what i do
**Traceback (most recent call last):
  File "C:\stage_1_gan.py", line 453, in <module>
    stage1_gen.save_weights("stage1_gen.h5")
  File "C:\Users\HP\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1414, in save_weights
    with h5py.File(filepath, 'w') as f:
  File "C:\Users\HP\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\HP\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'stage1_gen.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)**
