### ISSUE TITLE
can't load model that includes a lambda layer that calls a tensorflow method

### ISSUE THREAD

**Issue by ophiry** [fchollet/keras#6633]
using tensorflow 1.1 with tensorflow.contrib.keras

I've seen some related questions and solutions, but they don't appear to be relevant for this case

```
import tensorflow

input_layer = tensorflow.contrib.keras.layers.Input(shape=(1,), name='input', dtype='string')
initializer = tensorflow.contrib.lookup.KeyValueTensorInitializer(['a', 'b', 'c'], [1,2,3])
lut = tensorflow.contrib.lookup.HashTable(initializer, 0)
tensorflow.contrib.keras.backend.get_session().run(lut.init)
lut_layer = tensorflow.contrib.keras.layers.Lambda(lut.lookup)(input_layer)

model = tensorflow.contrib.keras.models.Model(inputs=[input_layer], outputs=[lut_layer])
x = [['a'],['X'],['b']]
print(model.predict(x))

model.save('/tmp/lut.hdf5')

loaded_model = tensorflow.contrib.keras.models.load_model('/tmp/lut.hdf5')
print (loaded_model.predict(x))

```

output:
```
2017-05-15 10:21:04.430222: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-15 10:21:04.430235: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-05-15 10:21:04.430238: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-15 10:21:04.430243: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
[[ 1.]
 [ 0.]
 [ 2.]]
Traceback (most recent call last):
  File "/Users/ophir/dev/ophir/tf_keras_string_input.py", line 16, in <module>
    loaded_model = tensorflow.contrib.keras.models.load_model('/tmp/lut.hdf5')
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/models.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/models.py", line 327, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/utils/generic_utils.py", line 159, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/engine/topology.py", line 2392, in from_config
    process_layer(layer_data)
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/engine/topology.py", line 2360, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/utils/generic_utils.py", line 159, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/layers/core.py", line 635, in from_config
    printable_module_name='function in Lambda layer')
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    fn = module_objects.get(function_name)
AttributeError: 'NoneType' object has no attribute 'get'

Process finished with exit code 1

```

**Comment by ophiry** [comment]
Found workaround - use a custom layer

**Comment by viksit** [comment]
@ophiry would you provide an example of how you built this custom layer?

also, when exporting the model - does your vocabulary/mapping also get exported into the model? or do you have to store it separately somewhere?

**Comment by dustinbigham** [comment]
@ophiry could you share how to do this in a custom layer that fixes this problem?

**Comment by dustinbigham** [comment]
Thank you! This works fine for training but later I try to save the model with tf.contrib.saved_model.save_keras_model the K.get_session() call causes:
`ValueError: Cannot use the given session to execute operation: the operation's graph is different from the session's graph.`
