### ISSUE TITLE
pygpu.gpuarray.GpuArrayException with new backend

### ISSUE THREAD

**Issue by jagiella** [fchollet/keras#6650]
Using the dev/github versions Keras/Theano with the new libgpuarray backend the following error occures:
```python
Using Theano backend.
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
In file included from /tmp/try_flags_AZWvm4.c:4:0:
/usr/include/cudnn.h:63:26: fatal error: driver_types.h: No such file or directory
compilation terminated.

Mapped name None to device cuda: GeForce GTX 1070 (0000:01:00.0)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_1 (Conv2D)            (None, 4, 190, 290)       488       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 4, 95, 145)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 55100)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               7052928   
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 387       
=================================================================
Total params: 7,053,803
Trainable params: 7,053,803
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
Traceback (most recent call last):
  File "newBackend.py", line 15, in <module>
    model.fit( x, y)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 868, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1503, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1155, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1196, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9990)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7083)
pygpu.gpuarray.GpuArrayException: 
Apply node that caused the error: GpuContiguous(GpuSubtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 35
Inputs types: [GpuArrayType<None>(float32, 4D)]
Inputs shapes: [(4, 1, 11, 11)]
Inputs strides: [(4, 9223372036854775807, -176, -16)]
Inputs values: ['not shown']
Outputs clients: [[GpuCorrMM{valid, (1, 1), (1, 1)}(GpuContiguous.0, GpuContiguous.0)]]
``` 

A minimal example already reproducing the error is
```python
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
import numpy as np
x = np.random.random( size=(100, 1, 200, 300)).astype('float32')
y = np.random.random( size=(100, 3)).astype('float32')
model = Sequential([
	Conv2D( 4, (11,11), activation='relu', padding='valid', input_shape=x.shape[1:]),
	MaxPooling2D( (2,2)),
	Flatten(),
	Dense(128, activation='relu'),
	Dense(y.shape[1], activation='softmax')
])
print( model.summary())
model.compile( loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])
model.fit( x, y)
```

**Comment by ozancaglayan** [comment]
You need to set CPLUS_INCLUDE_PATH environment variable for new backend. See this:
https://github.com/Theano/Theano/issues/5463#issuecomment-280625719

**Comment by gokceneraslan** [comment]
Are the cudnn header error in the beginning and the last gpuarray exception somehow related?

**Comment by ozancaglayan** [comment]
sorry I thought that the problem was there. Anyways, I can not reproduce the error with gpuarray backend. Make sure you use a recent enough version of gpuarray as there were some important bugfixes.

**Comment by jagiella** [comment]
#5945 of Theano/Theano

**Comment by jagiella** [comment]
The error is related to the dev-version of numpy==1.13. With the current version of numpy==1.12 the new backend is working.
