### ISSUE TITLE
Embeddings's weights doesn't look well with other languages

### ISSUE THREAD

**Issue by amatosc** [fchollet/keras#6791]
Hello there! 
I'm trying to reproduce this [example of embedding](https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py)

but using data for doing it in Spanish, so I have got a dataset of tweets in Spanish and Word2vec model in Spanish as well. I just replace the necessary code to it works. And I got the next error:

```
Traceback (most recent call last):
  File "/Users/alex/classifier/app.py", line 147, in <module>
    model.fit(x_train, y_train, batch_size=128, epochs=2, validation_data=(x_test, y_test))
  File "/Users/alex/classifier/lib/python2.7/site-packages/keras/engine/training.py", line 1498, in fit
    initial_epoch=initial_epoch)
  File "/Users/alex/classifier/lib/python2.7/site-packages/keras/engine/training.py", line 1152, in _fit_loop
    outs = f(ins_batch)
  File "/Users/alex/classifier/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2229, in __call__
    feed_dict=feed_dict)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[18,135] = 621 is not in [0, 621)
	 [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_1/embeddings/read, _recv_input_1_0)]]

Caused by op u'embedding_1/Gather', defined at:
  File "/Users/alex/classifier/app.py", line 129, in <module>
    embedded_sequences = embedding_layer(sequence_input)
  File "/Users/alex/classifier/lib/python2.7/site-packages/keras/engine/topology.py", line 585, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/alex/classifier/lib/python2.7/site-packages/keras/layers/embeddings.py", line 120, in call
    out = K.gather(self.embeddings, inputs)
  File "/Users/alex/classifier/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1072, in gather
    return tf.gather(reference, indices)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1207, in gather
    validate_indices=validate_indices, name=name)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/alex/classifier/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[18,135] = 621 is not in [0, 621)
	 [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_1/embeddings/read, _recv_input_1_0)]]

```

Summary:
```

> _________________________________________________________________
> Layer (type)                 Output Shape              Param #   
> =================================================================
> input_1 (InputLayer)         (None, 140)               0         
> _________________________________________________________________
> embedding_1 (Embedding)      (None, 140, 300)          186300    
> _________________________________________________________________
> conv1d_1 (Conv1D)            (None, 139, 128)          76928     
> _________________________________________________________________
> max_pooling1d_1 (MaxPooling1 (None, 69, 128)           0         
> _________________________________________________________________
> conv1d_2 (Conv1D)            (None, 68, 128)           32896     
> _________________________________________________________________
> max_pooling1d_2 (MaxPooling1 (None, 34, 128)           0         
> _________________________________________________________________
> conv1d_3 (Conv1D)            (None, 33, 128)           32896     
> _________________________________________________________________
> max_pooling1d_3 (MaxPooling1 (None, 2, 128)            0         
> _________________________________________________________________
> flatten_1 (Flatten)          (None, 256)               0         
> _________________________________________________________________
> dense_1 (Dense)              (None, 128)               32896     
> _________________________________________________________________
> dense_2 (Dense)              (None, 4)                 516       
> =================================================================
> Total params: 362,432
> Trainable params: 176,132
> Non-trainable params: 186,300
> _________________________________________________________________
> Train on 50 samples, validate on 13 samples
> Epoch 1/2
>

```
 
Note that the original example was good for me, so may it be something related with the language? 

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). [Link](https://gist.github.com/amatosc/bfe1a83ea5d25839d15217da98301c35)

--------------------------------------------
* Mac OS
* Running on CPU
* Backend: tensorflow
--------------------------------------------
pip:
```
numpy==1.12.1
scipy==0.19.0
tensorflow==1.1.0
nltk==3.2.4
lxml==3.7.3
keras==2.0.4
gensim==2.1.0
pandas==0.20.1
scikit-learn==0.18.1
scipy==0.19.0
pip-upgrader==1.4.0
```

**Comment by ebubekirbbr** [comment]
I have installed latest version of tensorflow and same error is occured.

Layer (type)                 Output Shape              Param #   
=================================================================
embedding_1 (Embedding)      (None, 1000, 300)         29841300  
_________________________________________________________________
lstm_1 (LSTM)                (None, 1000, 128)         219648    
_________________________________________________________________
lstm_2 (LSTM)                (None, 1000, 64)          49408     
_________________________________________________________________
lstm_3 (LSTM)                (None, 1000, 96)          61824     
_________________________________________________________________
lstm_4 (LSTM)                (None, 1000, 128)         115200    
_________________________________________________________________
lstm_5 (LSTM)                (None, 32)                20608     
_________________________________________________________________
dense_1 (Dense)              (None, 256)               8448      
_________________________________________________________________
dense_2 (Dense)              (None, 23)                5911      
=================================================================
Total params: 30,322,347
Trainable params: 481,047
Non-trainable params: 29,841,300
_________________________________________________________________
None
Train on 83444 samples, validate on 20862 samples
Epoch 1/11
 2528/83444 [..............................] - ETA: 3:57:04 - loss: 2.5453 - acc: 0.2124Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[16,999] = 99471 is not in [0, 99471)
         [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dl.py", line 173, in <module>
    main()
  File "dl.py", line 169, in main
    vc.dl_algorithm(x_train, y_train, x_test, y_test)
  File "dl.py", line 147, in dl_algorithm
    validation_data=(x_test, y_test))
  File "/usr/lib64/python3.6/site-packages/keras/models.py", line 965, in fit
    validation_steps=validation_steps)
  File "/usr/lib64/python3.6/site-packages/keras/engine/training.py", line 1669, in fit
    validation_steps=validation_steps)
  File "/usr/lib64/python3.6/site-packages/keras/engine/training.py", line 1206, in _fit_loop
    outs = f(ins_batch)
  File "/usr/lib64/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[16,999] = 99471 is not in [0, 99471)
         [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]
