### ISSUE TITLE
Model deserialization failure with shared inputs layers

### ISSUE THREAD

**Issue by wpm** [fchollet/keras#6827]
**_(See the comments below for a simpler repro case.)_**

A model with shared inputs, LSTM, and Lambda layers fails to deserialize. A minimal repro case is here.

```python
from keras.engine import Input, Model
from keras.layers import Lambda, concatenate, Dense, LSTM
from keras.models import save_model, load_model

input_shape = (20, 300)

input_1 = Input(input_shape)
input_2 = Input(input_shape)

lstm = LSTM(32)
e1 = lstm(input_1)
e2 = lstm(input_2)

negative_e1 = Lambda(lambda x: -x)(e1)
hidden = concatenate([e1, e2, negative_e1])

logistic_regression = Dense(1, activation="sigmoid")(hidden)
model = Model(inputs=[input_1, input_2], outputs=logistic_regression)
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
print("Original model %s" % model)

name = "model.hd5"
save_model(model, name)

restored_model = load_model(name)
print("Restored model %s" % restored_model)
```

(This model is a simplification of a strategy used for textual semantic equivalence detection. The actual strategy takes the square of `e2 - e1` which exhibits the same problem.)

The `restore_model` fails with the exception `ValueError: Missing layer: input_2`.

This is as simple as I have been able to make the repro case.
Changing the model in the following ways makes the bug go away:
- Not using multiple inputs
- Not putting the inputs through a shared LSTM. (It works if you either omit the LSTM or use a separate LSTM for each input.)
- Not using a Lambda layer. (It works if you omit the Lambda layer, or replace it with a non-lambda function, e.g. `keras.layers.add([e1, e2])`)

This looks similar to #4160, but doesn't have the nested layers that issue has, so I'm not sure if it's the same bug.

This is the full stack trace.

```python
Traceback (most recent call last):
  File "/Users/billmcn/src/keras_serialization_bug/keras_serialization_bug.py", line 28, in <module>
    restored_model = load_model(name)
  File "/Users/billmcn/anaconda/envs/keras-serialization-bug/lib/python3.5/site-packages/keras/models.py", line 232, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/billmcn/anaconda/envs/keras-serialization-bug/lib/python3.5/site-packages/keras/models.py", line 293, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/billmcn/anaconda/envs/keras-serialization-bug/lib/python3.5/site-packages/keras/layers/__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "/Users/billmcn/anaconda/envs/keras-serialization-bug/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/billmcn/anaconda/envs/keras-serialization-bug/lib/python3.5/site-packages/keras/engine/topology.py", line 2374, in from_config
    process_layer(layer_data)
  File "/Users/billmcn/anaconda/envs/keras-serialization-bug/lib/python3.5/site-packages/keras/engine/topology.py", line 2361, in process_layer
    raise ValueError('Missing layer: ' + inbound_layer_name)
ValueError: Missing layer: input_2
```

_Keras version 2.0.4 with TensorFlow backend, Python 3.5.3_

## Checklist

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by wpm** [comment]
`config['layers']` is a list of the various layers in this object. It appears that the code assumes it is sorted in topological order, but something about the way this particular model is built causes it to be out of order. In particular, the `LSTM` layer comes in the list before the second `Input` causing the error I see here.

It looks like the topology for the graph is created in the constructor for `Container` in `topology.py`.

**Comment by wpm** [comment]
I think this is more serious than #4160. That bug has a cyclic structure in the graph, and Keras assumes DAGs. However, the graph I'm creating in this bug is acyclic.

**Comment by wpm** [comment]
Here's a simpler repro case.

```python
import os
import shutil
import tempfile

from keras.engine import Model, Input
from keras.layers import concatenate, Dense, Lambda
from keras.models import load_model

input_1 = Input((32,), name="Input-1")
input_2 = Input((32,), name="Input-2")
shared_dense = Dense(64, name="Shared")
r1 = shared_dense(input_1)
r2 = shared_dense(input_2)
negative_r2 = Lambda(lambda x: -x, name="Negation")(r2)
output = concatenate([r1, negative_r2], name="Output")

model = Model([input_1, input_2], output)
model.summary()

directory = tempfile.mkdtemp()
filename = os.path.join(directory, "model.hd5")
model.save(filename)
try:
    deserialized_model = load_model(filename)
    print("Deserialized model %s" % deserialized_model)
finally:
    shutil.rmtree(directory)
```

The model summary looks like this

```
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
Input-2 (InputLayer)             (None, 32)            0                                            
____________________________________________________________________________________________________
Shared (Dense)                   (None, 64)            2112                                         
____________________________________________________________________________________________________
Input-1 (InputLayer)             (None, 32)            0                                            
____________________________________________________________________________________________________
Negation (Lambda)                (None, 64)            0                                            
____________________________________________________________________________________________________
Output (Concatenate)             (None, 128)           0                                            
====================================================================================================
Total params: 2,112.0
Trainable params: 2,112.0
Non-trainable params: 0.0
____________________________________________________________________________________________________
```

Note that `Input-1` comes after `Shared`. 
`Input-2` is at depth 3 while `Input-1` and `Dense` are both at depth 2.

```python
>>> model.layers_by_depth[3]
[<keras.engine.topology.InputLayer object at 0x104c035f8>]
>>> model.layers_by_depth[2]
[<keras.layers.core.Dense object at 0x1087d3048>, <keras.engine.topology.InputLayer object at 0x104bb5c88>]
```

Having the layers out of topological order like this causes `load_model` to fail.

**Comment by wpm** [comment]
In `Container.__init__` in `topology.py:1668` the model builds its `layers` list from the `layers_by_depth` dictionary.

```
        # Set self.layers and self.layers_by_depth.
        layers = []
        for depth in depth_keys:
            layers_for_depth = layers_by_depth[depth]
            # Container.layers needs to have a deterministic order:
            # here we order them by traversal order.
            layers_for_depth.sort(key=lambda x: layer_indices[x])
            for layer in layers_for_depth:
                layers.append(layer)
```

Maybe the fix is to change the sense of the traversal order sorting

```
layers_for_depth.sort(key=lambda x: -layer_indices[x])
```

since layers closer to the input will be traversed last.

**Comment by wpm** [comment]
This is a duplicate of #6668. I verified that that change fixes this issue.
