### ISSUE TITLE
GpuArrayException: Error loading library: 0

### ISSUE THREAD

**Issue by dycasxe101** [fchollet/keras#6948]
Like my issue before, i'am still trying to configure theano, keras, cuda and cudnn.

i have error like this 

> >>> import theano
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\dycAS\Anaconda2\envs\theanoxe\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\Users\dycAS\Anaconda2\envs\theanoxe\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\Users\dycAS\Anaconda2\envs\theanoxe\lib\site-packages\theano\gpuarray\__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
GpuArrayException: Error loading library: 0

there's any solution to my problem, honestly, iam newbie in theano, please help me, i wanna give up

**Comment by vladimircape** [comment]
it's theano issue not keras

**Comment by dycasxe101** [comment]
ohhh sorry, but thanks for respon, every problem solve clearly with some tutorials.

**Comment by dycasxe101** [comment]
ohhh sorry, but thanks for respon, every problem solve clearly with some tutorials.
