### ISSUE TITLE
ConvLSTM2D: return_sequences=False returns a 5D tensor (should return 4D)

### ISSUE THREAD

**Issue by rawmean** [fchollet/keras#7044]
According to `ConvLSTM2D` documentation, when `return_sequences=False`, the `ConvLSTM2D` is supposed to only return the last element of the sequence.  Specifically:

```
     # Output shape
        - if `return_sequences`
             - if data_format='channels_first'
                5D tensor with shape:
                `(samples, time, filters, output_row, output_col)`
             - if data_format='channels_last'
                5D tensor with shape:
                `(samples, time, output_row, output_col, filters)`
        - else
            - if data_format ='channels_first'
                4D tensor with shape:
                `(samples, filters, output_row, output_col)`
            - if data_format='channels_last'
                4D tensor with shape:
                `(samples, output_row, output_col, filters)`
            where o_row and o_col depend on the shape of the filter and
            the padding
```

But setting `return_sequences=False` seem to have no effect and the layer continues to return a 5-d tensor.

Is this a bug?  Is there a workaround?

Here is my code:

```
def create_model(input_shape):

    num_filters = 15
    model = Sequential()
    model.add(ConvLSTM2D(filters=num_filters, kernel_size=(3, 3),
                         # input_shape=(None, 40, 40, 1),
                         input_shape=input_shape,
                         padding='same', return_sequences=True))
    model.add(BatchNormalization())

    model.add(ConvLSTM2D(filters=num_filters/2, kernel_size=(3, 3),
                         padding='same', return_sequences=True))
    model.add(BatchNormalization())

    model.add(ConvLSTM2D(filters=num_filters, kernel_size=(3, 3),
                         padding='same', return_sequences=False))
    model.add(BatchNormalization())

    model.add(Conv2D(filters=1, kernel_size=(3, 3),
                     activation='sigmoid',
                     padding='same', data_format='channels_last'))

    opt = optimizers.Adam(lr=1e-4)
    model.compile(loss='mae', optimizer=opt, metrics=[metrics.mae])

    return model
```

**Comment by fchollet** [comment]
As far as I can tell, `ConvLSTM2D` with `return_sequences=False` returns a 4D tensor (this is unit-tested). If you find an example where that is not the case, that is bug. In that case, please post a code example that other people can run to verify the bug.

**Comment by rawmean** [comment]
Thanks for the response.  I've modified your conv_lstm.py in Keras/examples slightly by setting `return_sequences` to `False` and replacing `Conv3D` with `Conv2D`.  Here is the self-contained gist:
https://gist.github.com/rawmean/254a65a236fc7dbcaa5ba11d0f2cb09f

This generates the following Value error:

```
Traceback (most recent call last):
  File "/home/me/Keras_examples/conv_lstm.py", line 108, in <module>
    epochs=300, validation_split=0.05)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 870, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1439, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1319, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 127, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected conv2d_1 to have 4 dimensions, but got array with shape (1000, 15, 40, 40, 1)
```

**Comment by fchollet** [comment]
Can't reproduce, in this script, the output of the last `ConvLSTM2D` is a 4D tensor with shape `(None, 40, 40, 40)`.

> _standardize_input_data

It sounds like the problem is with the data that you are passing as input.

**Comment by rawmean** [comment]
Thanks.  You are correct.  I should have changed the output dimension to 4D (remove the time dimension).

**Comment by sunmonk** [comment]
hey.
seq.add(ConvLSTM2D(filters=40, kernel_size=(3, 3),
                   padding='same', data_format='channels_last', return_sequences=False))

filters should not be 40   but 3!

seq.add(ConvLSTM2D(filters=3, kernel_size=(3, 3),
                   padding='same', data_format='channels_last', return_sequences=False))
