### ISSUE TITLE
DImensions error in running image_ocr.py

### ISSUE THREAD

**Issue by cliff007** [fchollet/keras#7105]
C:\Anaconda3\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 36966 --file E:/cliff/Programmer-related/GPU_related/keras学习/keras2.05_examples/image_ocr.py
warning: Debugger speedups using cython not found. Run '"C:\Anaconda3\python.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\setup_cython.py" build_ext --inplace' to build.
pydev debugger: process 95728 is connecting

Connected to pydev debugger (build 171.4424.42)
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 32 and 28 for 'dense2/add' (op: 'Add') with input shapes: [?,32,28], [1,28,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/cliff/Programmer-related/GPU_related/keras学习/keras2.05_examples/image_ocr.py", line 501, in <module>
    train(run_name, 0, 20, 128)
  File "E:/cliff/Programmer-related/GPU_related/keras学习/keras2.05_examples/image_ocr.py", line 464, in train
    name='dense2')(concatenate([gru_2, gru_2b]))
  File "C:\Anaconda3\lib\site-packages\keras\engine\topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Anaconda3\lib\site-packages\keras\layers\core.py", line 845, in call
    output = K.bias_add(output, self.bias)
  File "C:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 3389, in bias_add
    x += reshape(bias, (1, bias_shape[0], 1))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 67, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 32 and 28 for 'dense2/add' (op: 'Add') with input shapes: [?,32,28], [1,28,1].

---------------
##### As I can not pip install editdistance, I used python-Levenshtein  instead
    import Levenshtein  
##### and use Levenshtein.disntance() to replace editdistance.eval()
but i don't think this will cause the error above

**Comment by cliff007** [comment]
got the reason! That is a stupid mistake! No need to claim!

**Comment by shirayu** [comment]
@cliff007 How did you solve this problem? I got the same error.

**Comment by shirayu** [comment]
Found the reason. 

```
"backend": "tensorflow",
"image_data_format": "channels_first"
```

in ``~/.keras/keras.json`` causes this.

```
"backend": "tensorflow",
"image_data_format": "channels_last"
```

works well.
