### ISSUE TITLE
AssertionError: AbstractConv3d_gradWeights Theano optimization failed

### ISSUE THREAD

**Issue by sodaGH** [fchollet/keras#7143]
I'm using keras, with theano as the backend. Now i am facing this problem as followed. I  use GPU and cudnn ( versions of 5110 and 5005 both have been tried, but with the same problem). I really don't know what to do next. Do thx for your help!
```

ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv3d_gradWeights{convdim=3, border_mode='valid', subsample=(1, 1, 1), filter_flip=True, imshp=(None, 64, 10, 8, 8), kshp=(64, 64, 3, 3, 3), filter_dilation=(1, 1, 1)}(GpuElemwise{switch,no_inplace}.0, GpuElemwise{switch,no_inplace}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1335, in transform
    new_repl = opt.transform(node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 2833, in local_abstractconv_gw_cudnn
    return local_abstractconv3d_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 2803, in local_abstractconv3d_cudnn_graph
    conv_mode=conv_mode)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 1185, in dnn_gradweight3d
    subsample, conv_mode, precision)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 1176, in dnn_gradweight
    return gpu_dnn_conv_gradW()(img, topgrad, out, desc)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 774, in make_node
    "3d convolutions", (self.algo,))
ValueError: ("convolution algo %s can't be used for 3d convolutions", ('deterministic',))

ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv3d_gradWeights{convdim=3, border_mode='valid', subsample=(1, 1, 1), filter_flip=True, imshp=(None, 64, 8, 6, 6), kshp=(64, 64, 3, 3, 3), filter_dilation=(1, 1, 1)}(GpuElemwise{switch,no_inplace}.0, GpuElemwise{switch,no_inplace}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1335, in transform
    new_repl = opt.transform(node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 2833, in local_abstractconv_gw_cudnn
    return local_abstractconv3d_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 2803, in local_abstractconv3d_cudnn_graph
    conv_mode=conv_mode)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 1185, in dnn_gradweight3d
    subsample, conv_mode, precision)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 1176, in dnn_gradweight
    return gpu_dnn_conv_gradW()(img, topgrad, out, desc)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 774, in make_node
    "3d convolutions", (self.algo,))
ValueError: ("convolution algo %s can't be used for 3d convolutions", ('deterministic',))

ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_abstractconv_gw_cudnn,local_abstractconv_gi_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweights_gemm,local_abstractconv3d_gradweights_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)
ERROR (theano.gof.opt): node: AbstractConv3d_gradWeights{convdim=3, border_mode='valid', subsample=(1, 1, 1), filter_flip=True, imshp=(None, 64, 8, 6, 6), kshp=(64, 64, 3, 3, 3), filter_dilation=(1, 1, 1)}(GpuElemwise{switch,no_inplace}.0, GpuElemwise{switch,no_inplace}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1335, in transform
    new_repl = opt.transform(node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 2833, in local_abstractconv_gw_cudnn
    return local_abstractconv3d_cudnn_graph(node.op, ctx, node.inputs, node.outputs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 2803, in local_abstractconv3d_cudnn_graph
    conv_mode=conv_mode)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 1185, in dnn_gradweight3d
    subsample, conv_mode, precision)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 1176, in dnn_gradweight
    return gpu_dnn_conv_gradW()(img, topgrad, out, desc)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 774, in make_node
    "3d convolutions", (self.algo,))
ValueError: ("convolution algo %s can't be used for 3d convolutions", ('deterministic',))

ERROR (theano.gof.opt): Optimization failure due to: local_abstractconv_check
ERROR (theano.gof.opt): node: AbstractConv3d_gradWeights{convdim=3, border_mode='valid', subsample=(1, 1, 1), filter_flip=True, imshp=(None, 64, 8, 6, 6), kshp=(64, 64, 3, 3, 3), filter_dilation=(1, 1, 1)}(GpuElemwise{switch,no_inplace}.0, GpuElemwise{switch,no_inplace}.0, MakeVector{dtype='int64'}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/tensor/nnet/opt.py", line 615, in local_abstractconv_check
    node.op.__class__.__name__)
AssertionError: AbstractConv3d_gradWeights Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

Traceback (most recent call last):
  File "/media/root/sdb1/BrainImg/newFTR_CNN%MLP_fusion_0625/save_ftr_size97_0626_vgg.py", line 1382, in <module>
    callbacks=[csv_logger, reduce_lr, checkpointer, early_stopping])
  File "/home/soda/anaconda2/lib/python2.7/site-packages/Keras-2.0.4-py2.7.egg/keras/engine/training.py", line 1484, in fit
    self._make_train_function()
  File "/home/soda/anaconda2/lib/python2.7/site-packages/Keras-2.0.4-py2.7.egg/keras/engine/training.py", line 1020, in _make_train_function
    **self._function_kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/Keras-2.0.4-py2.7.egg/keras/backend/theano_backend.py", line 1170, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/Keras-2.0.4-py2.7.egg/keras/backend/theano_backend.py", line 1155, in __init__
    **kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1794, in orig_function
    output_keys=output_keys).create(
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1474, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 2095, in apply
    nb += self.process_node(fgraph, node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1987, in process_node
    lopt, node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1881, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/home/soda/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1867, in warn
    raise exc
AssertionError: AbstractConv3d_gradWeights Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

```

**Comment by crjxixixi** [comment]
hi,I have the same problem as you , i want to know that have you solved this problem?
