### ISSUE TITLE
Invalid Regularizer (l1, and l2) when loading a model

### ISSUE THREAD

**Issue by vcovo** [fchollet/keras#7171]
For the following script: 
-------------------------------------------------------------------------------------------------------------------------
import numpy as np
np.random.seed(9)
from keras.models import Sequential, load_model

train_set = np.loadtxt("data_SS/60+/learning/train_ronmon601.csv", delimiter=",")
test_set = np.loadtxt("data_SS/60+/learning/test_ronmon601.csv", delimiter=",")
X_train = train_set[:, 0:9]
y_train = train_set[:, 10]
X_test = test_set[:, 0:9]
y_test = test_set[:, 10]

model = load_model("best_individual_MON_l1.h5")

model.fit(X_train, y_train, nb_epoch=2400, batch_size=300)  # , verbose=0)
predictions = model.predict(X_test).flatten()

I get the following error: 
-------------------------------------------------------------------------------------------------------------------------
Using Theano backend.
Traceback (most recent call last):
  File "/home/vince/code/KAUST/CCRC-NN/Abdul/SuperScripts/load_model_test.py", line 23, in <module>
    model = load_model("best_individual_MON_l1.h5", custom_objects={'l1': l1, 'l2': l2})
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/models.py", line 128, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/models.py", line 177, in model_from_config
    return layer_from_config(config, custom_objects=custom_objects)
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/models.py", line 1030, in from_config
    layer = get_or_create_layer(first_layer)
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/models.py", line 1014, in get_or_create_layer
    layer = layer_from_config(layer_data)
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/engine/topology.py", line 929, in from_config
    return cls(**config)
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/layers/core.py", line 673, in __init__
    self.W_regularizer = regularizers.get(W_regularizer)
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/regularizers.py", line 162, in get
    instantiate=True, kwargs=kwargs)
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 30, in get_from_module
    str(identifier))
Exception: Invalid regularizer: {'l1': 0.35913780331611633, 'l2': 0.0}
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6ee95edf28>
Traceback (most recent call last):
  File "/home/vince/anaconda3/envs/NN/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

Process finished with exit code 1

I have tried a few different things:
- Importing l1 and l2 in to the above script
- Importing and passing as cutom_objects like so:  model = load_model("best_individual_MON_l1.h5", custom_objects={'l1': l1, 'l2': l2})

Note: when running the original script that created the model I had imported l1 as l1_reg (as l1 was conflicting with a already existent variable). I have also tried importing l1 as l1_reg and passing that as a custom function. 

Regardless, the error remains. After looking through the only issues that come up with the exception's key words I have not found a solution. What is surprising to me is: l1 is not a custom function, so I don't see why there should be an issue (a similar model that uses dropout loaded fine), and l2 wasn't used at all in this model, so I don't understand why it is mentioned. 

Retraining the model will be quite a pain. Any advice is appreciated. I am using Keras 1.1.1 (As that is what the model was trained on) Switching to the latest didn't change anything (it just worded the error a little differently).

**Comment by srijandas07** [comment]
Did you find any solution?
