### ISSUE TITLE
error when compiling a "de-serialized" CNN 

### ISSUE THREAD

**Issue by mmmikael** [fchollet/keras#722]
This can be reproduced by serializing and de-serializing the model at the end of the example ```mnist_cnn.py``` with the code:
```python
from keras.models import model_from_json
open('test.json', 'w').write(model.to_json())
model = model_from_json(open('test.json').read())
model.compile(loss='categorical_crossentropy', optimizer='adadelta')
```
The same code runs fine for ```mnist_mlp.py```.

The error traceback is quite long as it repeats several time the same section (first block):
```
...

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7f19792319d0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1834, in apply
    self.local_optimizers_map.get(node.op, [])):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 677, in __hash__
    return hash((type(self), self._props()))
TypeError: unhashable type: 'list'

Traceback (most recent call last):
  File "mnist_cnn.py", line 76, in <module>
    model.compile(loss='categorical_crossentropy', optimizer='adadelta')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 400, in compile
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 259, in make_thunk
    compute_map, no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 739, in make_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1073, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1015, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1045, in module_from_key
    module = self._get_from_key(key)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 942, in _get_from_key
    if key in self.entry_from_key:
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 677, in __hash__
    return hash((type(self), self._props()))
TypeError: ('The following error happened while compiling the node', GpuDnnConvDesc{border_mode=u'full', subsample=[1, 1], conv_mode='conv'}(Shape.0, Shape.0), '\n', "unhashable type: 'list'")

```

**Comment by fchollet** [comment]
I believe the issue is that the `subsample` argument expects a tuple and not a list. Python tuples are stored as lists in JSON.

This would be somewhat complex to fix at the deserialization step (we would need some flag to trigger a conversion from list to tuple -- but what flag?). The simplest way to fix might be in the convolution layers.

**Comment by mmmikael** [comment]
#739 fixes this issue.

Note that other layers have a similar problem like [Permute](https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L364).
