### ISSUE TITLE
model.get_config() throws ValueError: Improper config format...

### ISSUE THREAD

**Issue by 9thDimension** [fchollet/keras#7232]
I'm trying to follow the steps to export a keras model as a core tensorflow model, as outlined here https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html#exporting-a-model-with-tensorflow-serving.

First I tried exporting the `Resnet50` from `keras.applications`, which failed on the step `config = old_model.get_config()`. This also failed when using the `VGG16` as the `old_model`. Finally, I tried exporting a very simple feed foward MLP with 1 hidden layer, and got the same error:

```
Traceback (most recent call last):
  File "/home/hal9000/tf_serving_experiments/sndbx.py", line 44, in <module>
    new_model = model_from_config(config)
  File "/home/hal9000/keras2env/local/lib/python2.7/site-packages/keras/models.py", line 304, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/hal9000/keras2env/local/lib/python2.7/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/home/hal9000/keras2env/local/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 122, in deserialize_keras_object
raise ValueError('Improper config format: ' + str(config))
ValueError: Improper config format: {'layers': [{'class_name': 'InputLayer', 'config': {'dtype': 'float32', 'batch_input_shape': (None, 2), 'name': 'input_1', 'sparse': False}, 'inbound_nodes': [], 'name': 'input_1'}, {'class_name': 'Dense', 'config': {'kernel_initializer': {'class_name': 'VarianceScaling', 'config': {'distribution': 'uniform', 'scale': 1.0, 'seed': None, 'mode': 'fan_avg'}}, 'name': 'dense_1', 'kernel_constraint': None, 'bias_regularizer': None, 'bias_constraint': None, 'activation': 'relu', 'trainable': True, 'kernel_regularizer': None, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'units': 3, 'use_bias': True, 'activity_regularizer': None}, 'inbound_nodes': [[['input_1', 0, 0, {}]]], 'name': 'dense_1'}, {'class_name': 'Dense', 'config': {'kernel_initializer': {'class_name': 'VarianceScaling', 'config': {'distribution': 'uniform', 'scale': 1.0, 'seed': None, 'mode': 'fan_avg'}}, 'name': 'dense_2', 'kernel_constraint': None, 'bias_regularizer': None, 'bias_constraint': None, 'activation': 'softmax', 'trainable': True, 'kernel_regularizer': None, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'units': 2, 'use_bias': True, 'activity_regularizer': None}, 'inbound_nodes': [[['dense_1', 0, 0, {}]]], 'name': 'dense_2'}], 'input_layers': [['input_1', 0, 0]], 'output_layers': [['dense_2', 0, 0]], 'name': 'model_1'}

Process finished with exit code 1
```

I have a repeatable example you can try in this following gist:
https://gist.github.com/9thDimension/e1cdb2cd11f11309bfaf297b276f7456

**Comment by TiRune** [comment]
Also interested in this 👍

**Comment by joshuafishman** [comment]
Try using `keras.models.Model.from_config()` (for a functional model)? That worked for me.
