### ISSUE TITLE
Deep Dream Example not working on CNTK Backend?

### ISSUE THREAD

**Issue by gaara100** [fchollet/keras#7253]
Hi,
So I just setup keras with the new CNTK backend. It seems to work much better in all my uses so far, but...

The deep dream example doesn't work for me. 

It's running on GPU with tensorflow backend perfectly fine, but when I try to use CNTK, it spits out this:

Using CNTK backend
Selected GPU[0] GeForce GTX 1070 as the process wide default device.
Model loaded.
Traceback (most recent call last):
  File "deep_dream.py", line 89, in <module>
    scaling = K.prod(K.cast(K.shape(x), 'float32'))
  File "C:\Users\Jesse\Anaconda3\envs\tensorflow_gpu\lib\site-packages\keras\backend\cntk_backend.py", line 570, in prod
    axis = _normalize_axis(axis, x)
  File "C:\Users\Jesse\Anaconda3\envs\tensorflow_gpu\lib\site-packages\keras\backend\cntk_backend.py", line 650, in _normalize_axis
    shape = int_shape(x)
  File "C:\Users\Jesse\Anaconda3\envs\tensorflow_gpu\lib\site-packages\keras\backend\cntk_backend.py", line 286, in int_shape
    shape = x.shape
AttributeError: 'list' object has no attribute 'shape'

Keep in mind that my CNTK install has been tested and works fine, as does my Tensorflow-gpu install, in all other instances I've tried so far.
Thoughts? 

I am new, so I may be doing something wrong.

**Comment by souptc** [comment]
Yes, the deep dream example is not working with cntk backend right now. There are some other issues but the most important issue is that CNTK does not support gradients as symbolic op, so the "K.gradients" is not worked as keras expected. We are working on this in CNTK, but I don't have a ETA for it now.
