### ISSUE TITLE
TensorBoard callback not working with write_grads=True

### ISSUE THREAD

**Issue by javiercorrea** [fchollet/keras#7259]
If I use the TensorBoard callback with `write_grads=True ` the following snipet fails:

```
from keras.models import Sequential
from keras.layers import Input, Dense, add 
from keras.callbacks import TensorBoard
import numpy as np

model = Sequential()
model.add(Dense(16, input_shape=(32,)))
model.add(Dense(64, name='dense_o'))

model.compile(optimizer='sgd', loss='mean_squared_error')

batch_size = 100 
x_train = np.random.randn(batch_size, 32) 
y_train = np.random.randn(batch_size, 64) 

x_val = np.random.randn(batch_size, 32) 
y_val = np.random.randn(batch_size, 64) 
model.fit(x=x_train, y=y_train,
          validation_data=[x_val, y_val],
          callbacks=[TensorBoard(histogram_freq=5, write_grads=True)], epochs=100)
```

with:
```
Using TensorFlow backend.
Train on 100 samples, validate on 100 samples
Epoch 1/100
 32/100 [========>.....................] - ETA: 0s - loss: 1.6144Traceback (most recent call last):
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1136, in _do_call
    return fn(*args)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1118, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32] vs. [100]
	 [[Node: gradients_1/mul_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@mul"], _device="/job:localhost/replica:0/task:0/cpu:0"](gradients_1/mul_grad/Shape, gradients_1/mul_grad/Shape_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp.py", line 20, in <module>
    callbacks=[TensorBoard(histogram_freq=5, write_grads=True)], epochs=100) #
  File "/home/javier/.local/lib/python3.5/site-packages/keras/models.py", line 870, in fit
    initial_epoch=initial_epoch)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1507, in fit
    initial_epoch=initial_epoch)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1176, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/callbacks.py", line 771, in on_epoch_end
    result = self.sess.run([self.merged], feed_dict=feed_dict)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 786, in run
    run_metadata_ptr)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 994, in _run
    feed_dict_string, options, run_metadata)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1129, in _do_run
    target_list, options, run_metadata)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1149, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32] vs. [100]
	 [[Node: gradients_1/mul_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@mul"], _device="/job:localhost/replica:0/task:0/cpu:0"](gradients_1/mul_grad/Shape, gradients_1/mul_grad/Shape_1)]]

Caused by op 'gradients_1/mul_grad/BroadcastGradientArgs', defined at:
  File "tmp.py", line 20, in <module>
    callbacks=[TensorBoard(histogram_freq=5, write_grads=True)], epochs=100) #
  File "/home/javier/.local/lib/python3.5/site-packages/keras/models.py", line 870, in fit
    initial_epoch=initial_epoch)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1507, in fit
    initial_epoch=initial_epoch)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1117, in _fit_loop
    callbacks.set_model(callback_model)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/callbacks.py", line 52, in set_model
    callback.set_model(model)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/callbacks.py", line 661, in set_model
    weight)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/optimizers.py", line 71, in get_gradients
    grads = K.gradients(loss, params)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2307, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 562, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 368, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 562, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_grad.py", line 653, in _MulGrad
    rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 411, in _broadcast_gradient_args
    name=name)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

...which was originally created as op 'mul', defined at:
  File "tmp.py", line 10, in <module>
    model.compile(optimizer='sgd', loss='mean_squared_error')
  File "/home/javier/.local/lib/python3.5/site-packages/keras/models.py", line 788, in compile
    **kwargs)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/engine/training.py", line 911, in compile
    sample_weight, mask)
  File "/home/javier/.local/lib/python3.5/site-packages/keras/engine/training.py", line 453, in weighted
    score_array *= weights
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 821, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1044, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1434, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/javier/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [32] vs. [100]
	 [[Node: gradients_1/mul_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@mul"], _device="/job:localhost/replica:0/task:0/cpu:0"](gradients_1/mul_grad/Shape, gradients_1/mul_grad/Shape_1)]]
```

**Comment by JiangLing-han** [comment]
At the latest version of tensorflow[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/python/keras/callbacks.py], you can use write_grads.

**Comment by JiangLing-han** [comment]
At the [latest version](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/python/keras/callbacks.py) of tensorflow, you can use write_grads.

**Comment by javiercorrea** [comment]
Tensorboard tests are failing on my computer with HEAD Keras and Tensorflow 1.2.1

**Comment by javiercorrea** [comment]
Really sorry, but I found the issue. It was a change I made.
