### ISSUE TITLE
TypeError: <lambda>() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by jlfu** [fchollet/keras#7280]
I try to merge two tensor with mode which i define by lambda. 
Here is the code:
**f_merge_st = merge([f_merge, st_repeat], mode=lambda x,y: np.vstack((x,y)) )**
But i get the issue:
Traceback (most recent call last):
  File "coAtt_IMG_gate.py", line 210, in <module>
    # f_merge_st = merge([f_merge, st_repeat], mode=lambda x,y: np.vstack((x,y)) )
  File "/home/jlfu/coattentionNER/env15/lib/python2.7/site-packages/keras/engine/topology.py", line 1536, in merge
    name=name)
  File "/home/jlfu/coattentionNER/env15/lib/python2.7/site-packages/keras/engine/topology.py", line 1172, in __init__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/home/jlfu/coattentionNER/env15/lib/python2.7/site-packages/keras/engine/topology.py", line 571, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/jlfu/coattentionNER/env15/lib/python2.7/site-packages/keras/engine/topology.py", line 160, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/home/jlfu/coattentionNER/env15/lib/python2.7/site-packages/keras/engine/topology.py", line 1249, in call
    return self.mode(inputs, **arguments)
**TypeError: <lambda>() takes exactly 2 arguments (1 given)**

And i try to instead () by [] in merge layer, 
**f_merge_st = merge((f_merge, st_repeat), mode=lambda x,y: np.vstack((x,y)) )**
but it still get this issue: **TypeError: <lambda>() takes exactly 2 arguments (1 given)**

And i try to use keras Lambda layer,
**lambda_m = Lambda(lambda x,y: np.vstack((x,y)) )(f_merge, st_repeat)**
the issue still there.  **TypeError: <lambda>() takes exactly 2 arguments (1 given)**

Can anyone help me?

**Comment by td2014** [comment]
@jlfu .  Where is the documentation for this merge function that you are using?  Is this something you created or are you using a standard library?  Thanks.
