### ISSUE TITLE
Encounter "ValueError: None values not supported" when using custom loss function

### ISSUE THREAD

**Issue by yushuinanrong** [fchollet/keras#7567]
Hi,

I'm trying to apply a custom loss to my discriminative network. The loss is quite simply, just the standard deviation of the probabilities for each class. I don't need the ground truth label for this task.
Here is my code snippet:
def StdLoss(y_true, y_pred):
    label = K.cast(K.argmax(y_pred, axis= 1), dtype='float32')
    return K.std(label, axis = 0, keepdims=True)
However, I have a error message that says"ValueError: None values not supported"
I googled and seems it is a tensorflow problem. Anyway, I hope someone could enlighten me how to overcome this issue.
The complete error message is attached below.
Thanks!

Traceback (most recent call last):
  File "Fine_tune_representation_learn.py", line 197, in <module>
    shuffle=True, callbacks = callbacks)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1457, in fit
    self._make_train_function()
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1001, in _make_train_function
    self.total_loss)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/optimizers.py", line 398, in get_updates
    m_t = (self.beta_1 * m) + (1. - self.beta_1) * g
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 793, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")

**Comment by fgvenegas** [comment]
How did you solve this ?

**Comment by yushuinanrong** [comment]
It was caused by a stupid typo in my code. Nothing related to keras.

**Comment by MarcoForte** [comment]
Just want to say that this error can occur if your loss function accidentally doesn't use the input in it's calculation.

**Comment by marcossilva** [comment]
Would like to add that this might be caused by the use of non-differentiable loss functions bad designed. I used K.abs on my loss function and couldn't understand why it was giving me this error.
