### ISSUE TITLE
Multi-label classifier using Graph model

### ISSUE THREAD

**Issue by hemanth2090** [fchollet/keras#759]
Hi,

  I am trying to implement a multi-label classifier in keras. Here is the code I am using.

Input is 128x128 RGB image (similar to Cifar10 data) and label file is a one-hot vector with 14 classes. ([0 0 0 0 0 0 1 0 0 0 0 0 0 0])

```
# Define the input file (X_train) and labels file (Y_train) 
X_train = np.zeros((num_of_samples,channels,input_image_rows,input_image_columns), dtype=np.int32)
Y_train = np.zeros((num_of_samples,num_of_classes), dtype=np.int32)

X_train.shape = (152, 3, 128, 128)
Y_train.shape = (152, 14)


# Graph Model
model =  Graph()


# Load the input
model.add_input(name='input_data', ndim=4)

# Convolution Neural Network architecture 

model.add_node(Convolution2D(16, 3, 5, 5, activation='relu', border_mode='full', name='conv', input='input_data'))
model.add_node(MaxPooling2D(poolsize=(2,2)), name='pool', input='conv')

...........................
..........................
..........................



model.add_node(Dense(13*13*32, 1024,init='uniform'), name='flatten', input='final_pool_layer')
model.add_node(Dense(1024, 512,init='uniform', activation='softmax'),name='dense1', input='flatten')
model.add_node(Dense(512, nb_classes,init='uniform', activation='softmax'),name='dense2',input='dense1')

model.add_output(name='output1', input='dense2')

model.compile('sgd', {'output1':'categorical_crossentropy'})
history = model.fit({'input_data':X_train, 'output1':Y_train}, nb_epoch=10)


#############################################################

```

When I compile the code, it is running fine. When I am training (model.fit), I am getting the following error.

```

Error:

Epoch 0
Traceback (most recent call last):
  File "train-data.py", line 158, in <module>
    history = model.fit({'cards_input':X_train, 'output1':Y_train}, nb_epoch=10)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 678, in fit
    shuffle=shuffle, metrics=metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 211, in _fit
    outs = f(*ins_batch)
  File "/home/hemanth2090/Desktop/theano/Theano/theano/compile/function_module.py", line 779, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/hemanth2090/Desktop/theano/Theano/theano/tensor/type.py", line 177, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/usr/local/lib/python2.7/dist-packages/keras/models.py:616"  at index 1(0-based)', 'Wrong number of dimensions: expected 4, got 2 with shape (128, 14).')

```

I dont know why I am getting this error. I think the error states that there is a dimensionality mis-match between the input and label file. Input is 4D array while label is 2D array. Can someone please help me?

**Comment by fchollet** [comment]
The first thing you should try is upgrade Keras. 

Then, please provide a reproducible example of the issue (a paste-able code snippet) and I will look into it.

**Comment by hemanth2090** [comment]
Hey I made a mistake in the flatten layer and the input to the first dense layer. I had to do a manual hack. I will close this issue now.

**Comment by alyato** [comment]
@hemanth2090, Do you solve your problem? how do you do multi-label using graph model?
I think the one-hot vector also is used to multi-classes and multi-label is [0 0 1 0 0 1 0 0 0 0 0 0 0].
