### ISSUE TITLE
Getting learning_phase at the activation functions level

### ISSUE THREAD

**Issue by jmlipman** [fchollet/keras#7615]
I modified the ReLU activation function to print the value of the learning phase, expecting that during the training (fit) and testing (evaluate, predict) it will be different. In fact, according to the documentation, the value during the training should be 1 whereas during the testing 0 is expected.

`def relu(x, alpha=0., max_value=None):
    print(K.learning_phase())
    return K.relu(x, alpha=alpha, max_value=max_value)
`
During the training I get:
Tensor("activation_1/keras_learning_phase:0", dtype=bool)
and during testing I don't get anything at all.

How does it make sense?
JM.

**Comment by mahnerak** [comment]
That's because the `relu` function is called once, when defining the graph. You can see the same behaviour if you put the same `print(K.learning_phase())` inside call function of any layer.

Here, in Keras (in TensorFlow and Theano too) you first define a graph and then you run it. It's not always possible to debug by printing the value **(the values are symbolic!)**.

Anyways, you can use `K.learning_phase()` as a condition. Simple `if` condition will not work.
You shoud use `K.in_train_phase(a, b)`. It will return tensor which equals `a` if model is in training phase, and `b` if it's not. An example of usage you can find at Dropout implementation (https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L103).

**Comment by jmlipman** [comment]
I tried to use that function on an activation function but I get the following error when I'm training the data:

You must feed a value for placeholder tensor 'dense_1/keras_learning_phase' with dtype bool

I thought that Keras automatically knows whether I'm training or testing the data implicitly. Where do I have to specify the value of learning_phase then?

**Comment by jmlipman** [comment]
I realized that I have to write K.set_learning_phase(0) (or 1) before the creating the model. This makes no sense to me because I thought it can automatically see whether it's being training or testing. Furthermore, setting the learning phase as 0 or 1 will only have effect once and the next time I will use the model, the activation function will still consider the same learning_phase value.

What I'm trying to figure out is how can I recreate different behaviors at the activation function level using the learning_phase but I was not successful.

**Comment by mahnerak** [comment]
No, it's very bad idea setting learning_phase manually.
Example of making custom activation function using `learning_phase`:
```python
import numpy as np

import keras
from keras import backend as K
from keras.models import Model
from keras.layers import Input, Dense
from keras.activations import softmax

def custom_activation(x):
    activation = x + K.in_train_phase(0.0, 1000.0)
    activation._uses_learning_phase = True # very important
    return activation

x = Input(shape=(784,))
h = Dense(units=100, activation='tanh') (x)
y = Dense(units=10, activation=custom_activation) (h)

model = Model(inputs=x, outputs=y)
model.compile(optimizer='SGD', loss='mean_absolute_error')

X = np.random.uniform(low=0, high=1, size=(10000, 784))
Y = np.random.uniform(low=0, high=1, size=(10000, 10))

model.fit(X, Y, epochs=10)

print(model.evaluate(X, Y))
```

You will get loss ~0.25 during training, but ~1000 during test (evaluation) phase.

**Comment by jmlipman** [comment]
Thanks!

activation._uses_learning_phase was the key ;)

**Comment by zhhongzhi** [comment]
@mahnerak   
thanks for the demo code. I have problem running the model, the error codes are as follows,
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/mydata/wp/SimpleQAMine/fullSimpleQA/relation_reranking/learn_get_intern_valuse.py", line 60, in <module>
    y = Dense(units=10, activation='custom_activation') (h)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/layers/core.py", line 808, in __init__
    self.activation = activations.get(activation)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/activations.py", line 79, in get
    return deserialize(identifier)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/activations.py", line 71, in deserialize
    printable_module_name='activation function')
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/utils/generic_utils.py", line 157, in deserialize_keras_object
    ':' + function_name)
ValueError: ('Unknown activation function', ':custom_activation')
```
environment 
` Keras (2.0.2)
tensorflow-gpu (1.1.0)
`
Do you have any idea to fix it?  Thanks!

**Comment by mahnerak** [comment]
@zhhongzhi In your code (file `learn_get_intern_valuse.py` line 60) you provided activation function with quotes:
```python
y = Dense(units=10, activation='custom_activation') (h)
```
however, in my code I provide function:
```python
y = Dense(units=10, activation=custom_activation) (h)
```

**Comment by zhhongzhi** [comment]
@mahnerak Thanks! I noticed that I have wrongly edited it. And the original error reported is:
`Using TensorFlow backend.
Traceback (most recent call last):
  File "/mydata/wp/SimpleQAMine/fullSimpleQA/relation_reranking/learn_get_intern_valuse.py", line 60, in <module>
    y = Dense(units=10, activation=custom_activation) (h)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/layers/core.py", line 845, in call
    output = self.activation(output)
  File "/mydata/wp/SimpleQAMine/fullSimpleQA/relation_reranking/learn_get_intern_valuse.py", line 54, in custom_activation
    activation = x + K.in_train_phase(0.0, 1000.0)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/backend/tensorflow_backend.py", line 2451, in in_train_phase
    x = switch(training, x, alt)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/Keras-2.0.2-py2.7.egg/keras/backend/tensorflow_backend.py", line 2410, in switch
    else_expression_fn)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1741, in cond
    orig_res, res_t = context_t.BuildCondBranch(fn1)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1668, in BuildCondBranch
    real_v = self._ProcessOutputTensor(v)
  File "/home/hongzhi/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1626, in _ProcessOutputTensor
    if val.name not in self._values:
AttributeError: 'float' object has no attribute 'name'`

Thank you for your attention.
