### ISSUE TITLE
how to use concat with merge

### ISSUE THREAD

**Issue by collawolley** [fchollet/keras#7638]
I was trying to upgrade my past codes after some months, I can see that many things have changed.
How can I use merge in concat mode as shown below with the new keras version. Thanks
merged = merge([x1, x2], mode='concat')

**Comment by Danielhiversen** [comment]
```
from keras.layers import concatenate
 concatenate([x1, x2], axis=-1)
```

**Comment by collawolley** [comment]
Thanks Daniel.
However, it does not seem to work. see here the error:
from keras.layers import concatenate

merged = concatenate([x1,x2], axis=-1)
Traceback (most recent call last):

  File "<ipython-input-19-30772e57cb8d>", line 1, in <module>
    merged = concatenate([x1,x2], axis=-1)

  File "/home/ade/.local/lib/python2.7/site-packages/keras/layers/merge.py", line 508, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)

  File "/home/ade/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)

  File "/home/ade/.local/lib/python2.7/site-packages/keras/layers/merge.py", line 283, in call
    return K.concatenate(inputs, axis=self.axis)

  File "/home/ade/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1723, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)

  File "/home/ade/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(

  File "/home/ade/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "/home/ade/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "/home/ade/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))

  File "/home/ade/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)

  File "/home/ade/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by collawolley** [comment]
Can anybody please help with this? How do I replicate the old merge layer with concat in the new keras!!

import keras
from keras.layers import concatenate

input1 = keras.layers.Input(shape=(16,))
x1 = keras.layers.Dense(8, activation='relu')(input1)
input2 = keras.layers.Input(shape=(32,))
x2 = keras.layers.Dense(8, activation='relu')(input2)

merge = concatenate([x1, x2], axis=-1)


Error: TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by Danielhiversen** [comment]
The code you posted works fine here.
It seems that you are using Keras 2.0.4, so you can try to upgrade to 2.0.6

**Comment by collawolley** [comment]
Thanks @Danielhiversen . I have verified that I have keras 2.0.6 and I still get errors compiling the code. please see the attached snapshot of my console. I would appreciate any help, thanks.
![screenshot from 2017-08-14 14-44-01](https://user-images.githubusercontent.com/15602821/29272274-9ba938fa-80ff-11e7-8344-ee2c19f9bd5b.png)
![screenshot from 2017-08-14 14-45-21](https://user-images.githubusercontent.com/15602821/29272277-9fa25f18-80ff-11e7-92c5-99eb2aafc9fd.png)
![screenshot from 2017-08-14 14-44-56](https://user-images.githubusercontent.com/15602821/29272278-9fbbea96-80ff-11e7-8436-9a77b7e212b8.png)

**Comment by keunwoochoi** [comment]
With tensorflow 1.2.1 and keras 2.0.6, the code works on my mac. What's the backend and its version?

**Comment by collawolley** [comment]
Hi @keunwoochoi and thanks for the response.

I am using keras 2.0.6, you can see the screenshot up there confirming that. The backend is tensorflow.
I am using tensorflow version = 0.12.1

Thanks. I will appreciate your help.

**Comment by collawolley** [comment]
@Danielhiversen @keunwoochoi   Thanks. found out it's my obsolete tensorflow version that's causing it. Now closing this.

**Comment by kalyanghosh** [comment]
This is basically a compatibility issue among Keras & Tensorflow. 
The following steps would resolve the issue.
Uninstall keras & tensorflow
1. sudo pip uninstall keras
2. sudo pip uninstall tensorflow
Then, reinstall both of them with the specified version
1. sudo pip install keras==2.0.6
2. sudo pip install tensorflow==1.2.1
