### ISSUE TITLE
load_model: ValueError('Missing layer: ' + inbound_layer_name)

### ISSUE THREAD

**Issue by Dobiasd** [fchollet/keras#7682]
I accidentally managed to create a model that can be saved but not loaded.

Here is a minimal example to reproduce the problem:

```python
from keras.models import Model, load_model
from keras.layers import Input, Dense, concatenate

input_shape = (16, 9, 3)
input_layer = Input(shape=input_shape)

dense_A = Dense(3, name='dense_A')
dense_B = Dense(3, name='dense_B')
dense_C = Dense(3, name='dense_C')

x1 = dense_B(dense_A(input_layer))
x2 = dense_A(dense_C(input_layer))
x = concatenate([x1, x2])

model = Model(inputs=input_layer, outputs=x)

model.save('model.h5')
model = load_model('model.h5')
```

Output:

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = load_model('model.h5')
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2450, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2437, in process_layer
    raise ValueError('Missing layer: ' + inbound_layer_name)
ValueError: Missing layer: dense_C
```

The model itself does not make a lot of sence of course, but as far as I understand, everything that can be serialized should also be deserializable. Is this a bug?

Keras version: 2.0.6
Python version: 3.5.2
Tensorflow version: 1.2.1

**Comment by viig99** [comment]
I am facing the same issue, model not getting loaded after getting saved

**Comment by nicolewhite** [comment]
This was actually fixed in https://github.com/fchollet/keras/commit/395a2edfd7741b5cdce7997bf8d4018d0e4b10d9 but introduced a new bug with your same example.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-5faf1f8b72be> in <module>()
     16 
     17 model.save('model.h5')
---> 18 model = load_model('model.h5')

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/models.py in load_model(filepath, custom_objects, compile)
    233             raise ValueError('No model found in config file.')
    234         model_config = json.loads(model_config.decode('utf-8'))
--> 235         model = model_from_config(model_config, custom_objects=custom_objects)
    236 
    237         # set weights

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/models.py in model_from_config(config, custom_objects)
    307                         'Maybe you meant to use '
    308                         '`Sequential.from_config(config)`?')
--> 309     return layer_module.deserialize(config, custom_objects=custom_objects)
    310 
    311 

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/layers/__init__.py in deserialize(config, custom_objects)
     52                                     module_objects=globs,
     53                                     custom_objects=custom_objects,
---> 54                                     printable_module_name='layer')

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    137                 return cls.from_config(config['config'],
    138                                        custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 139                                                            list(custom_objects.items())))
    140             with CustomObjectScope(custom_objects):
    141                 return cls.from_config(config['config'])

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/engine/topology.py in from_config(cls, config, custom_objects)
   2466                 if layer in unprocessed_nodes:
   2467                     for node_data in unprocessed_nodes.pop(layer):
-> 2468                         process_node(layer, node_data)
   2469 
   2470         name = config.get('name')

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/engine/topology.py in process_node(layer, node_data)
   2423             if input_tensors:
   2424                 if len(input_tensors) == 1:
-> 2425                     layer(input_tensors[0], **kwargs)
   2426                 else:
   2427                     layer(input_tensors, **kwargs)

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    558                                          '`layer.build(batch_input_shape)`')
    559                 if len(input_shapes) == 1:
--> 560                     self.build(input_shapes[0])
    561                 else:
    562                     self.build(input_shapes)

~/.virtualenvs/keras-dev-py3/lib/python3.5/site-packages/Keras-2.0.6-py3.5.egg/keras/layers/merge.py in build(self, input_shape)
    311         # Used purely for shape validation.
    312         if not isinstance(input_shape, list):
--> 313             raise ValueError('`Concatenate` layer should be called '
    314                              'on a list of inputs')
    315         if all([shape is None for shape in input_shape]):

ValueError: `Concatenate` layer should be called on a list of inputs
```
