### ISSUE TITLE
Fresh install, First run, Docs first example = fail

### ISSUE THREAD

**Issue by chrisdlangton** [fchollet/keras#7714]
Installed per below output and followed the docs getting started first example here;
https://keras.io/getting-started/functional-api-guide/#first-example-a-densely-connected-network

```
~/keras$ git clone https://github.com/fchollet/keras/ && cd keras
~/keras$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to Keras.egg-info/requires.txt
writing Keras.egg-info/PKG-INFO
writing top-level names to Keras.egg-info/top_level.txt
writing dependency_links to Keras.egg-info/dependency_links.txt
reading manifest file 'Keras.egg-info/SOURCES.txt'
writing manifest file 'Keras.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/activations.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/metrics.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/sequence.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/__init__.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/image.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/text.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
creating build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/visualize_util.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/layer_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/generic_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/io_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/np_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/__init__.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/test_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/data_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/constraints.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/objectives.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/__init__.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/wrappers
copying build/lib.linux-x86_64-2.7/keras/wrappers/scikit_learn.py -> build/bdist.linux-x86_64/egg/keras/wrappers
copying build/lib.linux-x86_64-2.7/keras/wrappers/__init__.py -> build/bdist.linux-x86_64/egg/keras/wrappers
creating build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/inception_v3.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/xception.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/imagenet_utils.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/__init__.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/music_tagger_crnn.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/audio_conv_utils.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/resnet50.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/vgg16.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/vgg19.py -> build/bdist.linux-x86_64/egg/keras/applications
creating build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/__init__.py -> build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/tensorflow_backend.py -> build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/mxnet_backend.py -> build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/theano_backend.py -> build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/common.py -> build/bdist.linux-x86_64/egg/keras/backend
creating build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/cifar10.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/cifar100.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/__init__.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/reuters.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/mnist.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/cifar.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/imdb.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/callbacks.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/optimizers.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/local.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/noise.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/advanced_activations.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/__init__.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/wrappers.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/embeddings.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/convolutional_recurrent.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/core.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/normalization.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/pooling.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/convolutional.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/recurrent.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/regularizers.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/engine
copying build/lib.linux-x86_64-2.7/keras/engine/__init__.py -> build/bdist.linux-x86_64/egg/keras/engine
copying build/lib.linux-x86_64-2.7/keras/engine/topology.py -> build/bdist.linux-x86_64/egg/keras/engine
copying build/lib.linux-x86_64-2.7/keras/engine/training.py -> build/bdist.linux-x86_64/egg/keras/engine
copying build/lib.linux-x86_64-2.7/keras/initializations.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/models.py -> build/bdist.linux-x86_64/egg/keras
byte-compiling build/bdist.linux-x86_64/egg/keras/activations.py to activations.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/metrics.py to metrics.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/sequence.py to sequence.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/image.py to image.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/text.py to text.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/visualize_util.py to visualize_util.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/layer_utils.py to layer_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py to generic_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/io_utils.py to io_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/np_utils.py to np_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/test_utils.py to test_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/data_utils.py to data_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/constraints.py to constraints.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/objectives.py to objectives.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/wrappers/scikit_learn.py to scikit_learn.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/wrappers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/inception_v3.py to inception_v3.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/xception.py to xception.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/imagenet_utils.py to imagenet_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/music_tagger_crnn.py to music_tagger_crnn.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/audio_conv_utils.py to audio_conv_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/resnet50.py to resnet50.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/vgg16.py to vgg16.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/vgg19.py to vgg19.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py to tensorflow_backend.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/mxnet_backend.py to mxnet_backend.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py to theano_backend.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/common.py to common.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/cifar10.py to cifar10.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/cifar100.py to cifar100.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/reuters.py to reuters.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/mnist.py to mnist.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/cifar.py to cifar.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/imdb.py to imdb.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/callbacks.py to callbacks.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/optimizers.py to optimizers.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/local.py to local.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/noise.py to noise.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/advanced_activations.py to advanced_activations.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/wrappers.py to wrappers.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/embeddings.py to embeddings.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/convolutional_recurrent.py to convolutional_recurrent.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/core.py to core.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/normalization.py to normalization.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/pooling.py to pooling.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/convolutional.py to convolutional.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/recurrent.py to recurrent.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/regularizers.py to regularizers.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/engine/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/engine/topology.py to topology.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/engine/training.py to training.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/initializations.py to initializations.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/models.py to models.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
keras.backend.theano_backend: module MAY be using inspect.stack
creating 'dist/Keras-1.2.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Keras-1.2.2-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/Keras-1.2.2-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/Keras-1.2.2-py2.7.egg
Extracting Keras-1.2.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Keras 1.2.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/Keras-1.2.2-py2.7.egg
Processing dependencies for Keras==1.2.2
Searching for scipy>=0.14
Best match: scipy 0.19.1
Adding scipy 0.19.1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for numpy==1.13.1
Best match: numpy 1.13.1
Adding numpy 1.13.1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for Keras==1.2.2
~/keras$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow
>>> 
KeyboardInterrupt
~/keras$ sudo pip install tensorflow
Collecting tensorflow
  Downloading tensorflow-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl (43.1MB)
    100% |████████████████████████████████| 43.1MB 17kB/s 
Collecting backports.weakref>=1.0rc1 (from tensorflow)
  Downloading backports.weakref-1.0rc1-py2-none-any.whl
Requirement already satisfied: wheel in /usr/lib/python2.7/dist-packages (from tensorflow)
Collecting protobuf>=3.3.0 (from tensorflow)
  Downloading protobuf-3.4.0-cp27-cp27mu-manylinux1_x86_64.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 119kB/s 
Collecting mock>=2.0.0 (from tensorflow)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 2.3MB/s 
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow)
Collecting tensorflow-tensorboard<0.2.0,>=0.1.0 (from tensorflow)
  Downloading tensorflow_tensorboard-0.1.4-py2-none-any.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 324kB/s 
Requirement already satisfied: six>=1.10.0 in /home/chris/.local/lib/python2.7/site-packages (from tensorflow)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf>=3.3.0->tensorflow)
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow)
  Downloading pbr-3.1.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 2.0MB/s 
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow)
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow)
  Downloading bleach-1.5.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow)
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow)
  Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 1.4MB/s 
Installing collected packages: backports.weakref, protobuf, funcsigs, pbr, mock, markdown, html5lib, bleach, werkzeug, tensorflow-tensorboard, tensorflow
  Found existing installation: html5lib 0.999999999
    Uninstalling html5lib-0.999999999:
      Successfully uninstalled html5lib-0.999999999
Successfully installed backports.weakref-1.0rc1 bleach-1.5.0 funcsigs-1.0.2 html5lib-0.9999999 markdown-2.6.9 mock-2.0.0 pbr-3.1.1 protobuf-3.4.0 tensorflow-1.3.0 tensorflow-tensorboard-0.1.4 werkzeug-0.12.2
~/keras$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> node1 = tf.constant(0.1)
>>> node2 = tf.constant(0.2)
>>> sess = tf.Session()
>>> node3 = node1 + node2
>>> sess.run(node3)
0.30000001
>>> from keras.layers import Input, Dense
Using MXNet backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "keras/__init__.py", line 2, in <module>
    from . import backend
  File "keras/backend/__init__.py", line 70, in <module>
    from .mxnet_backend import *
  File "keras/backend/mxnet_backend.py", line 2, in <module>
    import mxnet as mx
ImportError: No module named mxnet
>>> 
KeyboardInterrupt
~/keras$ sudo pip install mxnet
Collecting mxnet
  Downloading mxnet-0.11.0-py2.py3-none-manylinux1_x86_64.whl (11.4MB)
    100% |████████████████████████████████| 11.4MB 64kB/s 
Collecting graphviz (from mxnet)
  Downloading graphviz-0.8-py2.py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from mxnet)
Installing collected packages: graphviz, mxnet
Successfully installed graphviz-0.8 mxnet-0.11.0
~/keras$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras.layers import Input, Dense
Using MXNet backend.
>>> from keras.models import Model
>>> inputs = Input(shape=(784,))
>>> x = Dense(64, activation='relu')(inputs)
>>> x = Dense(64, activation='relu')(x)
>>> predictions = Dense(10, activation='softmax')(x)
>>> model = Model(inputs=inputs, outputs=predictions)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'outputs'

~/keras$ pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
Collecting git+git://github.com/fchollet/keras.git
  Cloning git://github.com/fchollet/keras.git to /tmp/pip-Gl6xOb-build
Installing collected packages: Keras
  Found existing installation: Keras 1.2.2
    Uninstalling Keras-1.2.2:
      Successfully uninstalled Keras-1.2.2
  Running setup.py install for Keras ... done
Successfully installed Keras-2.0.7
~/keras$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras.layers import Input, Dense
Using MXNet backend.
>>> from keras.models import Model
>>> inputs = Input(shape=(784,))
>>> x = Dense(64, activation='relu')(inputs)
>>> x = Dense(64, activation='relu')(x)
>>> predictions = Dense(10, activation='softmax')(x)
>>> model = Model(inputs=inputs, outputs=predictions)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'outputs'
```
As you can see I did the following;

- cloned keras, ran setup
- tried to test tensorflow, errored
- installed tensorflow
- tested tensorflow, works
- tried to follow the keras example from the docs, saw a dependency `mxnet` was missing
- installed mxnet
- tried the same keras example, saw error about `outputs` arg missing
- made sure i was running latest keras, followed the provided command (listed here when i opened the issue) to update keras.
- tried again the same example after the update, still fails

As you can see, this is VERY far from usable. Either the docs are out of date or there is just simply a bug in the latest stable keras.. i honestly have no idea where to go from here.

**Comment by chrisdlangton** [comment]
using virtual env solved this issue
