### ISSUE TITLE
Load a model with a self define metric 

### ISSUE THREAD

**Issue by jasonfan1997** [fchollet/keras#7982]
I google it and saw a lot of people have the same error. However their solution do not work for me. 
First it hava a error like this
Traceback (most recent call last):
  File "feature_extraction_and_predict.py", line 219, in <module>
    main()
  File "feature_extraction_and_predict.py", line 142, in main
    top_model = keras.models.load_model(top_model_path)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\models.py", line 270, in load_model
    sample_weight_mode=sample_weight_mode)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\models.py", line 784, in compile
    **kwargs)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\engine\training.py", line 924, in compile
    handle_metrics(output_metrics)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\engine\training.py", line 914, in handle_metrics
    metric_fn = metrics_module.get(metric)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\metrics.py", line 67, in get
    return deserialize(identifier)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\metrics.py", line 61, in deserialize
    printable_module_name='metric function')
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 159, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown metric function:top_3_categorical_accuracy

When I use
top_model = keras.models.load_model(top_model_path,custom_objects={'accuracy',top_3_categorical_accuracy})

Then it have a error like
Traceback (most recent call last):
  File "feature_extraction_and_predict.py", line 220, in <module>
    main()
  File "feature_extraction_and_predict.py", line 143, in main
    top_model = keras.models.load_model(top_model_path,custom_objects={'accuracy',top_3_categorical_accuracy})
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\models.py", line 239, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\models.py", line 313, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "C:\Users\user98\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
AttributeError: 'set' object has no attribute 'items'

Can someone kindly tell me what is the problem

**Comment by eram1205** [comment]
Same problem! @jasonfan1997 Did you solve it?

**Comment by jasonfan1997** [comment]
You can google custom_objects try to add a one. It work for me
