### ISSUE TITLE
cifar10 CNN example doesn't work.

### ISSUE THREAD

**Issue by oshams** [fchollet/keras#807]
[I apologize if this is somehow an installation version mismatched (I believe I have the last version).]

I get an error:

AttributeError: 'module' object has no attribute 'relu'

Full error output:
Traceback (most recent call last):
  File "cifar10_cnn.py", line 72, in <module>
    model.compile(loss='categorical_crossentropy', optimizer=sgd)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 353, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 52, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 410, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 584, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 383, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 410, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 584, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 490, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 383, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 345, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 410, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 238, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 410, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 238, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 383, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 345, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 410, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 238, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 89, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 411, in get_output
  File "build/bdist.linux-x86_64/egg/keras/activations.py", line 20, in relu
AttributeError: 'module' object has no attribute 'relu'

**Comment by Smerity** [comment]
Whilst you might have the latest version of Keras, can I check what version of Theano do you have installed? Keras recently updated their `relu` to use the Theano implementation (https://github.com/fchollet/keras/pull/732) and Travis failed as it was using an older version of Theano. I could imagine you're experiencing the same issue.

**Comment by jellylidong** [comment]
I got error information like
TypeError: __init__() got an unexpected keyword argument 'input_length'
But I have installed the latest version from the zip file here. Any solutions?

**Comment by yueranyuan** [comment]
@jellylidong I had a similar problem w/ my installed version of Theano. I would recommend installing Theano from github to avoid any version related issues:

pip uninstall theano
pip install git+git://github.com/Theano/Theano.git@master

**Comment by oshams** [comment]
Thanks everyone :+1: .  Now I get this error:

Traceback (most recent call last):
  File "cifar10_cnn.py", line 103, in <module>
    datagen.fit(X_train)
  File "build/bdist.linux-x86_64/egg/keras/preprocessing/image.py", line 239, in fit
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

Tried looking at it and it all involves numpy, but my numpy is up to date. I suppose I could bite the 30 minute bullet and uninstall numpy and install from master..

Thoughts?

**Comment by oshams** [comment]
Recent binding in cifar10_cnn.py has fixed this issue.

**Comment by MinhazPalasara** [comment]
For the record. It is due to short hand operator.
Lets say X is unit8 and Y is float in numpy. If you use short hand operator, X -= Y, this raises the TypeError. If you use X = X - Y, it takes care of the type casting.

**Comment by dnffkf369** [comment]
@yueranyuan Thanks you very much!!!
You solved my problem :)
