### ISSUE TITLE
Using Masking without embeddings and the new API

### ISSUE THREAD

**Issue by sergeyf** [fchollet/keras#816]
Below is my sequence to sequence model (thanks to various folks throughout the forum for helping me assemble this with all of your informative posts). I have 1 dimensional time series, and they are no longer than length 50. 

```
input_dim = 1
seqlen = 50
hidden_size = 16
print('Build model...')
model = Sequential()
model.add(LSTM(input_dim=input_dim, output_dim=hidden_size, return_sequences=False))
model.add(Dense(hidden_size))
model.add(Activation('relu'))
model.add(RepeatVector(seqlen))
model.add(LSTM(hidden_size, return_sequences=True))
model.add(TimeDistributedDense(output_dim=input_dim, activation="linear"))

optimizer = rmsprop(lr=0.01, clipnorm=10)
model.compile(optimizer=optimizer, loss='mse')
```

This compiles and trains well. The time-series are reproduced very well.

However, I would like to also have masking in the input for the purpose of filling in the inputs. So now I'd like to add a Masking layer, like so:

```
print('Build model...')
hidden_size = 16
model = Sequential()
model.add(Masking(mask_value=0))
model.add(LSTM(input_dim=input_dim, output_dim=hidden_size, return_sequences=False))
model.add(Dense(hidden_size))
model.add(Activation('relu'))
model.add(RepeatVector(seqlen))
model.add(LSTM(hidden_size, return_sequences=True))
model.add(TimeDistributedDense(output_dim=input_dim, activation="linear"))

optimizer = rmsprop(lr=0.01, clipnorm=10)
model.compile(optimizer=optimizer, loss='mse')
```

And this provides the traceback:

```
Build model...
Traceback (most recent call last):

  File "<ipython-input-9-c9d8834ae358>", line 5, in <module>
    model.add(LSTM(input_dim=input_dim, output_dim=hidden_size, return_sequences=False))

  File "build\bdist.win-amd64\egg\keras\layers\containers.py", line 37, in add
    self.layers[-1].set_previous(self.layers[-2])

  File "build\bdist.win-amd64\egg\keras\layers\core.py", line 32, in set_previous
    assert self.input_ndim == len(layer.output_shape), "Incompatible shapes: layer expected input with ndim=" +\

  File "build\bdist.win-amd64\egg\keras\layers\core.py", line 82, in output_shape
    return self.input_shape

  File "build\bdist.win-amd64\egg\keras\layers\core.py", line 65, in input_shape
    raise Exception('Layer is not connected. Did you forget to set "input_shape"?')

Exception: Layer is not connected. Did you forget to set "input_shape"
```

Any ideas on how to add Masking to the model? Thanks very much.

**Comment by sergeyf** [comment]
I am currently trying this:

```
model = Sequential()
M = Masking(mask_value=0)
M._input_shape = X.shape
model.add(M)
model.add(LSTM(input_dim=input_dim, output_dim=hidden_size, return_sequences=False))
...
```

But this seems like a clumsy solution. Does Masking need an input_dim parameter?

**Comment by fchollet** [comment]
You simply do:

```python
model = Sequential()
model.add(Masking(mask_value=0, input_shape=(input_dim,)))
```

All layers support the `input_shape` keyword argument.

**Comment by sergeyf** [comment]
Ah, thanks for that.

**Comment by sergeyf** [comment]
Trying that, I get the following error:

```
Traceback (most recent call last):

  File "<ipython-input-51-d176d93c0584>", line 3, in <module>
    model.add(LSTM(input_dim=input_dim, output_dim=hidden_size, return_sequences=False))

  File "build\bdist.win-amd64\egg\keras\layers\containers.py", line 37, in add
    self.layers[-1].set_previous(self.layers[-2])

  File "build\bdist.win-amd64\egg\keras\layers\core.py", line 33, in set_previous
    str(self.input_ndim) + " but previous layer has output_shape " + str(layer.output_shape)

AssertionError: Incompatible shapes: layer expected input with ndim=3 but previous layer has output_shape (None, 1)
```

**Comment by kotrfa** [comment]
I am getting same error with this model:
```
model = Sequential()  
model.add(LSTM(in_out_neurons, hidden_neurons, return_sequences=False))  
model.add(Dense(hidden_neurons, in_out_neurons))  
model.add(Activation("linear"))  
model.compile(loss="mean_squared_error", optimizer="rmsprop")  
```
and the error traceback:

```
Traceback (most recent call last):
  File "keras_vectors.py", line 45, in <module>
    model.add(Dense(hidden_neurons, in_out_neurons))  
  File "/home/dan/prac/.virtualenvs/kerastwo/lib/python3.5/site-packages/keras/layers/containers.py", line 37, in add
    self.layers[-1].set_previous(self.layers[-2])
  File "/home/dan/prac/.virtualenvs/kerastwo/lib/python3.5/site-packages/keras/layers/core.py", line 32, in set_previous
    assert self.input_ndim == len(layer.output_shape), "Incompatible shapes: layer expected input with ndim=" +\
  File "/home/dan/prac/.virtualenvs/kerastwo/lib/python3.5/site-packages/keras/layers/recurrent.py", line 41, in output_shape
    input_shape = self.input_shape
  File "/home/dan/prac/.virtualenvs/kerastwo/lib/python3.5/site-packages/keras/layers/core.py", line 65, in input_shape
    raise Exception('Layer is not connected. Did you forget to set "input_shape"?')
Exception: Layer is not connected. Did you forget to set "input_shape"?

```

adding `input_shape` like this:
```
model.add(Dense(hidden_neurons, in_out_neurons, input_shape=(2,)))
```
doesn't help.

**Comment by holderm** [comment]
any updates on this?

**Comment by kotrfa** [comment]
It's for some reason closed - can you open it again since it seems there are more of us?

**Comment by Cospel** [comment]
Older version of keras support this with no problem, but with new version through pip install keras i get same error for LSTM:

Exception: Layer is not connected. Did you forget to set "input_shape"?

**Comment by holderm** [comment]
Can anyone provice me quick fix how to install the last version with the old API on 
a) a "clean" system
b) downgrade from the latest Keras version
That would be great!

I will follow this issue with the new API but I need this particular function for my application, so I'll go with the old API in the meantime.

**Comment by kotrfa** [comment]
I guess it shouldn't be discussed here...

But as far as I understand all you need is new `virtualenv` with `pip` and install keras using `pip install keras==0.1` (or whatever version you want). How to do it depends on your system. These keywords should be enough for finding guides and tutorials for your case.

On Linux with Python 3.3+ it's supereasy:
```
$ virtualenv3 myvenv
$ pip install keras==0.1.0
```

**Comment by nicolas-ivanov** [comment]
For those people who run into
```
Exception: Layer is not connected. Did you forget to set "input_shape"?
```
please notice that in the recent version of keras some interfaces were changed. Before:
```python
LSTM(input_dimention, output_dimension, return_sequences=False)
```
After:
```python
LSTM(output_dimension, return_sequences=False, input_shape=(num_of_vectors, vect_dimension))
```

And for the Dense layer, before:
```python
Dense(input_dimention, output_dimension)
```
After:
```python
Dense(output_dim)
```

See usage example [here](https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py).

**Comment by shwetgarg** [comment]
I am sorry for the trivial question.

I read "http://keras.io/layers/core/" and "code comments" of masking layer. But I am unable to understand the purpose of Masking layer, especially in context of RNN. Also what exactly get_output_mask(train=None) method does in Layer class.

**Comment by facadev** [comment]
@nicolas-ivanov The example helps a lot. They should definitely update the doc. :)

**Comment by kevinmartinmauro** [comment]
also getting this error
