### ISSUE TITLE
Changing the training loop causes the model to fail while saving

### ISSUE THREAD

**Issue by kuba-chledowski** [fchollet/keras#8604]
Hi!

I am trying to reproduce [esim](https://arxiv.org/abs/1609.06038), state of the art method in Natural Language Inference. After first epoch, I get the following error: 
  
    Traceback (most recent call last):
      File "src/scripts/train_model.py", line 69, in <module>                                                                                         
        plugins=[MetaSaver(), AutomaticNamer(namer="timestamp_namer")])                                                                               
      File "/home/kchledowski/subspace-word-embeddings/src/vegab.py", line 403, in main                                                               
        call_training_func)()                                                                                                                         
      File "/home/kchledowski/subspace-word-embeddings/src/vegab.py", line 265, in func_wrapper                                                       
        func(*args, **kwargs)                                                                                                                         
      File "/home/kchledowski/subspace-word-embeddings/src/vegab.py", line 388, in call_training_func                                                 
        func(config, args.save_path, **training_func_kwargs)                                                                                          
      File "src/scripts/train_model.py", line 56, in train_model                                                                                      
        n_epochs=config["n_epochs"], batch_size=config["batch_size"])                                                                                 
      File "/home/kchledowski/subspace-word-embeddings/src/training_loop.py", line 125, in baseline_training_loop                                     
        callbacks=callbacks)                                                                                                                          
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper                      
        return func(*args, **kwargs)                                                                                                                  
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/site-packages/keras/engine/training.py", line 2082, in fit_generator                
        callbacks.on_epoch_end(epoch, epoch_logs)                                                                                                     
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end                         
        callback.on_epoch_end(epoch, logs)                                                                                                            
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/site-packages/keras/callbacks.py", line 428, in on_epoch_end                        
        self.model.save(filepath, overwrite=True)                                                                                                     
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/site-packages/keras/engine/topology.py", line 2553, in save                         
        save_model(self, filepath, overwrite, include_optimizer)                                                                                      
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/site-packages/keras/models.py", line 107, in save_model                             
        'config': model.get_config()                                                                                                                  
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/site-packages/keras/engine/topology.py", line 2394, in get_config                   
        return copy.deepcopy(config)                                                                                                                  
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 150, in deepcopy                                                     
        y = copier(x, memo)   
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                               
        y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 150, in deepcopy                                                     
        y = copier(x, memo)                                                                                                                           
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 220, in _deepcopy_tuple                                              
        y = [deepcopy(a, memo) for a in x]                                                                                                            
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 220, in <listcomp>                                                   
        y = [deepcopy(a, memo) for a in x]                                                                                                            
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 150, in deepcopy                                                     
        y = copier(x, memo)                                                                                                                           
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 220, in _deepcopy_tuple                                              
        y = [deepcopy(a, memo) for a in x]                                                                                                            
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 220, in <listcomp>                                                   
        y = [deepcopy(a, memo) for a in x]                                                                                                            
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 180, in deepcopy                                                     
        y = _reconstruct(x, memo, *rv)                                                                                                                
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 280, in _reconstruct                                                 
        state = deepcopy(state, memo)                                                                                                                 
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 150, in deepcopy                                                     
        y = copier(x, memo)                                                                                                                           
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                               
        y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 180, in deepcopy                                                     
        y = _reconstruct(x, memo, *rv)                                                                                                                
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 280, in _reconstruct                                                 
        state = deepcopy(state, memo)                                                                                                                 
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 150, in deepcopy                                                     
        y = copier(x, memo)                                                                                                                           
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                               
        y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 180, in deepcopy                                                     
        y = _reconstruct(x, memo, *rv)                                                                                                                
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 280, in _reconstruct                                                 
        state = deepcopy(state, memo)                                                                                                                 
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 150, in deepcopy                                                     
        y = copier(x, memo)                                                                                                                           
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                               
        y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                
      File "/home/kchledowski/anaconda2/envs/tf3gpu/lib/python3.6/copy.py", line 169, in deepcopy                                                     
        rv = reductor(4)                                                                                                                              
    TypeError: can't pickle _thread.lock objects 

Which may look like problem with saving in my model. However, when I use simpler neural network architecture, such as [bilstm](https://arxiv.org/abs/1508.01991), everything works correctly and I can proceed to the next epoch.

Any ideas, what might be the cause? 

- [+] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [+] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

**Comment by julienr** [comment]
Can you share your code or a minimal reproducible example ? It's hard to tell without the code, but it looks like it's trying to save a `threading.Lock` object which is obviously not a good idea.
Do you use multithreading in some custom layer / loss / anything you pass to keras ?

**Comment by kuba-chledowski** [comment]
Hi, thank you for answering. This is the part of the training loop that makes the problem (I apologize for not giving enough details, I am quite new to programming, I really do not know how to look for the multithreading, do you have any suggestions?):

    premise = Input(shape=(None,), dtype='int32')
    hypothesis = Input(shape=(None,), dtype='int32')

    bilstm_encoder = Bidirectional(LSTM(units=config["embedding"]["dim"], return_sequences=True))
    translate = TimeDistributed(Dense(config["embedding"]["dim"],
                                      kernel_regularizer=l2(1e-5),
                                      bias_regularizer=l2(1e-5),
                                      activation='relu'),
                                name='translate')

    prem = bilstm_encoder(embed(premise))
    hypo = bilstm_encoder(embed(hypothesis))

    embed_p = Dropout(config["dropout"])(prem)
    embed_h = Dropout(config["dropout"])(hypo)

    #  Score each words and calc score matrix Eph.
    F_p, F_h = embed_p, embed_h
    Eph = Dot(axes=(2, 2))([F_h, F_p])  # [batch_size, Hsize, Psize]
    Eh = Lambda(lambda x: softmax(x))(Eph)  # [batch_size, Hsize, Psize]
    Ep = Permute((2, 1))(Eph)  # [batch_size, Psize, Hsize)
    Ep = Lambda(lambda x: softmax(x))(Ep)  # [batch_size, Psize, Hsize]

    #  Normalize score matrix, bilstm_encoder premesis and get alignment
    PremAlign = Dot((2, 1))([Ep, embed_h])  # [-1, Psize, dim]
    HypoAlign = Dot((2, 1))([Eh, embed_p])  # [-1, Hsize, dim]
    mm_1 = Multiply()([embed_p, PremAlign])
    mm_2 = Multiply()([embed_h, HypoAlign])
    sb_1 = Lambda(lambda x: tf.subtract(x, PremAlign))(embed_p)
    sb_2 = Lambda(lambda x: tf.subtract(x, HypoAlign))(embed_h)

    PremAlign = Concatenate()([embed_p, PremAlign, sb_1, mm_1, ])  # [batch_size, Psize, 2*unit]
    HypoAlign = Concatenate()([embed_h, HypoAlign, sb_2, mm_2])  # [batch_size, Hsize, 2*unit]
    PremAlign = Dropout(config["dropout"])(PremAlign)
    HypoAlign = Dropout(config["dropout"])(HypoAlign)

    PremAlign = translate(PremAlign)
    HypoAlign = translate(HypoAlign)

    #  Final biLST < bilstm_encoder + Softmax Classifier
    Decoder = Bidirectional(LSTM(units=300, return_sequences=True),
                            name='finaldecoder')  # [-1,2*units]
    final_p = Dropout(config["dropout"])(Decoder(PremAlign))
    final_h = Dropout(config["dropout"])(Decoder(HypoAlign))

    AveragePooling = Lambda(lambda x: K.mean(x, axis=1))  # outs [-1, dim]
    MaxPooling = Lambda(lambda x: K.max(x, axis=1))  # outs [-1, dim]
    avg_p = AveragePooling(final_p)
    avg_h = AveragePooling(final_h)
    max_p = MaxPooling(final_p)
    max_h = MaxPooling(final_h)
    Final = Concatenate()([avg_p, max_p, avg_h, max_h])
    Final = Dropout(config["dropout"])(Final)
    Final = Dense(300,
                  kernel_regularizer=l2(1e-5),
                  bias_regularizer=l2(1e-5),
                  name='dense300_' + config["dataset"]["name"],
                  activation='tanh')(Final)
    Final = Dropout(config["dropout"] / 2)(Final)
    Final = Dense(3,
                  activation='softmax',
                  name='judge300_' + config["dataset"]["name"])(Final)
    model = Model(inputs=[premise, hypothesis], outputs=Final)

**Comment by kuba-chledowski** [comment]
I have found out, by commenting line by line, that these lines cause the saving error.

    sb_1 = Lambda(lambda x: tf.subtract(x, PremAlign))(embed_p)
    sb_2 = Lambda(lambda x: tf.subtract(x, HypoAlign))(embed_h)

Do you have any idea why?

**Comment by kuba-chledowski** [comment]
I have resolved the problem by changing the lambda into keras.layers.Subtract.
