### ISSUE TITLE
weird memory error

### ISSUE THREAD

**Issue by valexandersaulys** [fchollet/keras#895]
So I'm not sure why this is coming up. I included the snippet of code and the error message. This seems to be stemming from NumPy, what I'm really confused on is why. When I run it, I often dip way into my memory before the error comes up. I feel like I'm missing something obvious. 

Thanks in Advance!

Error Message:
```
Using gpu device 0: GeForce GTX 980 (CNMeM is disabled)
Traceback (most recent call last):
  File "prototype_two.py", line 65, in <module>
    model.add(Dense(2048));
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 37, in add
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 37, in set_previous
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 557, in build
  File "build/bdist.linux-x86_64/egg/keras/initializations.py", line 43, in glorot_uniform
  File "build/bdist.linux-x86_64/egg/keras/initializations.py", line 16, in uniform
  File "build/bdist.linux-x86_64/egg/keras/utils/theano_utils.py", line 12, in sharedX
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError
```

Snippet of Code Below:
```
model = Sequential()
# C1
model.add(Convolution2D(nb_filter=96,    # number of kernels
                        nb_row=11,       # number of rows in the kernel
                        nb_col=11,       # number of columns in the row
                        border_mode="full",
                        input_shape=(3,X1,X2)
                    ));     
model.add(LeakyReLU(alpha=LEAKY_RELU));

# Flatten
model.add(Flatten());

# D1
model.add(Dense(2048));
model.add(LeakyReLU(alpha=LEAKY_RELU));
# D2
model.add(Dense(1024));
model.add(LeakyReLU(alpha=LEAKY_RELU));

# O
model.add(Dense(NUM_CLASSES,activation='softmax'));
```

**Comment by fchollet** [comment]
Your GPU is out of memory. You can either reduce your batch size or reduce the size of your network.
