### ISSUE TITLE
Autoencoder issue with layer

### ISSUE THREAD

**Issue by Cospel** [fchollet/keras#899]
Hello, I install new version of keras library. Unfortunately it breaks some of my older scripts/models.

For example my autoencoder network:
```
encoder = containers.Sequential([Dense(400, 800, activation='tanh')])
decoder = containers.Sequential([Dense(800, 400, activation='tanh')])
ae = Sequential()
ae.add(AutoEncoder(encoder=encoder, decoder=decoder, output_reconstruction=False))
ae.compile(loss='mean_squared_error', optimizer='rmsprop')
ae.fit(X, X, verbose=1, nb_epoch = 100)
```

Throws exception:
Traceback (most recent call last):
  File "nn_ae2.py", line 27, in <module>
    ae.compile(loss='mean_squared_error', optimizer='rmsprop')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 355, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 86, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 792, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 86, in get_input
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 107, in get_input
Exception: Layer is not connected                and is not an input layer.

Can you help me?
I have installed newest version of keras and theano(directly from github).

**Comment by EderSantana** [comment]
Now we are doing automatic shape inference. Please see the examples folder and docs for details. Now, your model should be something like

```python
encoder = containers.Sequential([Dense(800, activation='tanh', input_dim=400)]) # first input dim is now a named argument
decoder = containers.Sequential([Dense(400, activation='tanh')]) # second input dim and later are inferred
ae = Sequential()
ae.add(AutoEncoder(encoder=encoder, decoder=decoder, output_reconstruction=False))
ae.compile(loss='mean_squared_error', optimizer='rmsprop')
ae.fit(X, X, verbose=1, nb_epoch = 100)
```

**Comment by Cospel** [comment]
Thanks for fast reply. Automatic shape inference looks good :).

But with your code i get:
Traceback (most recent call last):
  File "nn_ae2.py", line 27, in <module>
    ae.compile(loss='mean_squared_error', optimizer='rmsprop')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 358, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 74, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 816, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 74, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 614, in get_output
AttributeError: 'Dense' object has no attribute 'W'

**Comment by Cospel** [comment]
Ok so this works for me only if i specify also the input_dim to decoder.
So the correct code is for me:

```
encoder = containers.Sequential([Dense(800, activation='tanh', input_dim=400)]) # first input dim is now a named argument
decoder = containers.Sequential([Dense(400, activation='tanh', input_dim=800)]) # second input dim and later are inferred
ae = Sequential()
ae.add(AutoEncoder(encoder=encoder, decoder=decoder, output_reconstruction=False))
ae.compile(loss='mean_squared_error', optimizer='rmsprop')
ae.fit(X, X, verbose=1, nb_epoch = 100)
```

Probably the inference currently doesn't work for containers.

**Comment by fchollet** [comment]
> Probably the inference currently doesn't work for containers?

No, it doesn't as of now. Maybe in the future...
