### ISSUE TITLE
keras 2.0  can not use relu activation

### ISSUE THREAD

**Issue by peterGuang** [fchollet/keras#908]
Traceback (most recent call last):
  File "exp1_v2.py", line 324, in <module>
    testCNN(totalsize=1000,winsize=2,drop_rate=0.1,tempsize=8,epoch=1000,f1=Fals
e)
  File "exp1_v2.py", line 121, in testCNN
    model = buildCNN(tempsize,winsize,drop_rate)
  File "exp1_v2.py", line 117, in buildCNN
    model.compile(loss='mean_squared_error', optimizer=sgd)
  File "E:\Anaconda\lib\site-packages\keras\models.py", line 353, in compile
    self.y_train = self.get_output(train=True)
  File "E:\Anaconda\lib\site-packages\keras\layers\containers.py", line 52, in g
et_output
    return self.layers[-1].get_output(train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 410, in get_ou
tput
    X = self.get_input(train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 89, in get_inp
ut
    return self.previous.get_output(train=train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 584, in get_ou
tput
    X = self.get_input(train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 89, in get_inp
ut
    return self.previous.get_output(train=train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 490, in get_ou
tput
    X = self.get_input(train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 89, in get_inp
ut
    return self.previous.get_output(train=train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 383, in get_ou
tput
    X = self.get_input(train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 89, in get_inp
ut
    return self.previous.get_output(train=train)
  File "E:\Anaconda\lib\site-packages\keras\layers\core.py", line 411, in get_ou
tput
    return self.activation(X)
  File "E:\Anaconda\lib\site-packages\keras\activations.py", line 20, in relu
    return T.nnet.relu(x)
AttributeError: 'module' object has no attribute 'relu'

**Comment by peterGuang** [comment]
It's theano,
I cloned the source of theano from the github, installed it.
then, problem solved
