### ISSUE TITLE
Convolutional Layers seem to be broken

### ISSUE THREAD

**Issue by claymcleod** [fchollet/keras#937]
I tried running both the "VGG-like convnet" in the documentation and "mnist_cnn.py" in the examples folder. Both fail with this error:

```
$ python mnist_cnn.py
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Traceback (most recent call last):
  File "mnist_cnn.py", line 69, in <module>
    model.compile(loss='categorical_crossentropy', optimizer='adadelta')
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 358, in compile
    self.y_train = self.get_output(train=True)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/containers.py", line 74, in get_output
    return self.layers[-1].get_output(train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 480, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 654, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 455, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 480, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 654, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 560, in get_output
    X = self.get_input(train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 102, in get_input
    return self.previous.get_output(train=train)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 459, in get_output
    X *= self.srng.binomial(X.shape, p=retain_prob, dtype=theano.config.floatX) / retain_prob
  File "/usr/local/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 1289, in binomial
    x = self.uniform(size=size, nstreams=nstreams)
  File "/usr/local/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 1270, in uniform
    size=size, nstreams=orig_nstreams)
  File "/usr/local/lib/python2.7/site-packages/theano/sandbox/rng_mrg.py", line 331, in new
    return op(rstate, cast(v_size, 'int32'))
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/basic.py", line 1178, in cast
    return _cast_mapping[dtype](x)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 527, in __call__
    raise ValueError('Cannot compute test value: input %i (%s) of Op %s missing default value' % (i, ins, node))
ValueError: Cannot compute test value: input 0 (Shape.0) of Op Elemwise{Cast{int32}}(Shape.0) missing default value
```

I'm using the latest Theano and Keras releases. I would try to fix the error, but I'm fairly new to Theano at this point.

**Comment by fchollet** [comment]
Is this on GPU?

Can anyone repro this?

**Comment by claymcleod** [comment]
This is not on a GPU, just a CPU.

**Comment by fchollet** [comment]
Can't repro, the mnist_cnn and cifar10_cnn work for me on CPU with bleeding
edge Keras and Theano.

**Comment by Chasego** [comment]
Maybe this link will help: https://github.com/Theano/Theano/issues/1439

**Comment by claymcleod** [comment]
Can confirm that this fixed my issue.
