### ISSUE TITLE
What is the correct way to run convolutional tests?

### ISSUE THREAD

**Issue by rdipietro** [fchollet/keras#969]
If I run test_convolutional.py, I get two errors, one from test_convolution_1d and one from test_convolution_2d, both with similar outputs:

```
Traceback (most recent call last):                                                                                                 
  File "test_convolutional.py", line 87, in test_convolution_2d                                                                    
    out = layer.get_output(train).eval()                                                                                           
  File "/home-4/rdipiet2@jhu.edu/vc/keras/keras/layers/convolutional.py", line 252, in get_output                                  
    subsample=self.subsample)                                                                                                      
  File "/cm/shared/apps/anaconda/2.7.10/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 704, in dnn_conv             
    img = gpu_contiguous(img)                                                                                                      
  File "/cm/shared/apps/anaconda/2.7.10/lib/python2.7/site-packages/theano/gof/op.py", line 507, in __call__                       
    node = self.make_node(*inputs, **kwargs)                                                                                       
  File "/cm/shared/apps/anaconda/2.7.10/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 3511, in make_node     
    input = as_cuda_ndarray_variable(input)                                                                                        
  File "/cm/shared/apps/anaconda/2.7.10/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 41, in as_cuda_ndarray_
variable                                                                                                                           
    return gpu_from_host(tensor_x)                                                                                                 
  File "/cm/shared/apps/anaconda/2.7.10/lib/python2.7/site-packages/theano/gof/op.py", line 507, in __call__                       
    node = self.make_node(*inputs, **kwargs)                                                                                       
  File "/cm/shared/apps/anaconda/2.7.10/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 133, in make_node      
    dtype=x.dtype)()])                                                                                                             
  File "/cm/shared/apps/anaconda/2.7.10/lib/python2.7/site-packages/theano/sandbox/cuda/type.py", line 69, in __init__             
    (self.__class__.__name__, dtype, name))                                                                                        
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None 
```                 

I can reproduce this on two different machines which have different graphics cards and different versions of the CUDA toolkit. Meanwhile I have .theanorc set up correctly, and have also tried upgrading to the bleeding-edge version of Theano (based on suggestions elsewhere). Neither has fixed the problem.

Are these tests passing for others?

Thanks!

**Comment by rdipietro** [comment]
See https://github.com/fchollet/keras/issues/984.
